### ISSUE TITLE
Lazy loading components without Route

### ISSUE THREAD

**Issue by fourctv** [mgechev/angular-seed#1358]
**This is not a real seed issue**, but more of a help question.

I was using `DynamicComponentLoader` to lazy load components into my app, without ng2 Route. Then at some RC, when `DynamicComponentLoader` got deprecated I updated the code to use `ComponentResolver`.
That has been deprecated since RC5, and I've been searching for a way to do what I need, now with 2.0.0. (current docs have no coverage on this topic)

I presumed I'd need to use NgModules for the dynamically loaded components and I found `SystemJsNgModuleLoader`, which works fine. I loads the module and its components, as I can see on the browser's network tab.

But I am struggling to find the next steps to get the loaded module activated/injected, and the main component in that module as well.

`SystemJsNgModuleLoader` loads the module and gives me its `NgModuleFactory` and I can then use `factory.create()` to get me a `NgModuleRef`. Do I need to do anything else to get the loaded ngModule up and active?

How do I inject the module's main component?
I tried to use `System.import(comp)` (which is what I was using before), and that too works fine and gives me what I believed is a `provider`, but I could not find a way to inject that into my app.

Of course, this being brand new functionality, there is only old stuff on google/stackoverflow/etc.

I'll keep on digging and will post a solution I hope.
But if you can chime in and give me some pointers, that would be a great help.

thanks anyway,
julio

ps: sorry to use this venue to ask for help, but I could not find a better place or a better community to talk to

**Comment by OogieBoogieInJSON** [comment]
This is how you implement dynamically loaded components. It's updated: https://github.com/laco0416/angular2-component-outlet

Not even that hard.

**Comment by i7326** [comment]
use ComponentFactoryResolver instead ComponentResolver.. u may reference http://stackoverflow.com/questions/39580484/typescript-error-ts2339-on-componentref to load components dynamicaly ...  this works with latest version

**Comment by fourctv** [comment]
@i7326 yes, you do have to use ComponentFactoryResolver to inject components dynamically. But that is not sufficient if the component is loaded dynamically in runtime. The Component type is not known ahead of time.

@OogieBoogieInJSON pointer does solve the problem. You have to use `Compiler. compileModuleAndAllComponentsAsync()` to compile a dynamically loaded ngModule and get access to its component factories. In my case I use `SystemJsNgModuleLoader.load()` to load modules, and embedded components, on the fly. The missing step was the compiler.

Here is what I am using in case this helps someone else, and it works like a charm:

```
    constructor(
                private viewref: ViewContainerRef , 
               private resolver: ComponentFactoryResolver,
               private loader:SystemJsNgModuleLoader,
                private compiler:Compiler)  {}

   openWebApp(menu) {
                this.loader.load(menu.modulePath)  // load the module and its components
                .then ((modFac) => {
                    // the missing step, need to use Compiler to resolve the module's embedded components
                    this.compiler.compileModuleAndAllComponentsAsync<any>(modFac.moduleType)
                        .then((factory) => {
                            let cmpFactory: any;
                            // now look for the module's main component so we can instantiate it
                            for (let i = factory.componentFactories.length - 1; i >= 0; i--) {
                                if (factory.componentFactories[i].componentType.name === menu.componentName) {
                                    cmpFactory = factory.componentFactories[i];
                                }
                            }
                            return cmpFactory;
                            })
                        .then(cmpFactory => { 
                            // need to instantiate the Module so we can use it as the provider for the new component
                            let modRef = modFac.create(this.viewref.parentInjector);
                            let compRef = this.viewRef.createComponent(cmpFactory,0,modRef);
                            // done, now Module and main Component are known to NG2
                            ........
                        });
   }
```

thanks a lot for the help

**Comment by OogieBoogieInJSON** [comment]
Actually much better with this code snippet commented.

**Comment by mgechev** [comment]
This looks pretty nice. What's your current setup? Do you have separate bundles for the individual modules that you want to load lazily or you load each individual component on demand?

**Comment by vijosoco** [comment]
@fourctv  -- I would be interested to understand more.  Can you elaborate on **menu.modulepath** referenced in your code above. What does that look like. I currently use lazy loading feature to dynamically create routes and execute them.  However, in the angular2-seed production build that ability is lost.  I can no longer use the dynamic route that i generate.  

I have been doing the following: 

Build an array of lazy routes, like this example:
`{path: 'application', loadChildren: './app/core/application/application.module#ApplicationModule'}
`
Then I use resetConfig to define those routes:
`let routerConfig = this.router.config;
routerConfig.unshift(<Route>dynRoutesArray);
this.router.resetConfig(routerConfig);`

This works perfectly well in DEV build but fails in PROD build as a result of bundling, minification (I believe).   Ultimately I need to be able to dynamically load and execute routes.  Looking for the best way to do this in PROD and DEV.

**Comment by fourctv** [comment]
@mgechev the idea is to have one bundle per module, so all its components get loaded, when the module loads. At this point I see no reason (yet?) to lazy load components individually.

Still in the todo list is a way to optimize bundles to avoid reloading components that are shared among modules. Of course some of the shared components that are part of the main 'framework' get loaded with index, but there are always other components that end up being used by multiple components on large app. And I'll have to address that at some point.

Any ideas are welcome.

**Comment by fourctv** [comment]
@vijosoco -- as I mentioned above, in my case I am not using routing at all, or better, I do  not use angular routes, I do it my own way. 

FYI, `menu` entries look something like:
```
        {
            modulePath: 'app/components/userRating/',
            moduleFile: 'userRatingModule.js',
            moduleName: 'UserRatingModule',
            componentName: 'UserRating',
            roles: ['Viewer', 'Admin'],
            hideMenu: false,
            title: 'User Rating'
        },
```

**Comment by mgechev** [comment]
@fourctv yes, I agree that it's the optimal case.

**Comment by ruffiem** [comment]
This is just a suggestion at this point but did you try to achieve the same behavior with webpack instead of systemJS ? I believe you can create a Webpack bundle per module then load your bundles on demand. It would theoretically also work using ng2 route.

**Comment by mgechev** [comment]
Closing this issue. We can keep the discussion [here](https://github.com/mgechev/angular-seed/issues/864).

**Comment by gomesNazareth** [comment]
This works
{
    path: 'account',
    loadChildren:'./app/account/account.module#AccountModule'
   }

**Comment by gomesNazareth** [comment]
lazyloading fails in production

**Comment by mgechev** [comment]
@gomesNazareth in production you have to provide separate bundles. You can configure them and create them by using SystemJS builder. At this point I haven't spend much time researching how this can be implemented in the seed. I only did some basic testing in the ["lazy" branch](https://github.com/mgechev/angular-seed/tree/lazy) of the seed. The production build there doesn't work yet but it's in the right direction. Let me know how your experiment goes.

**Comment by TheDonDope** [comment]
@gomesNazareth have a look here: https://youtu.be/QLns6s02O48?t=6m27s

**Comment by gomesNazareth** [comment]
Thanks mgechev and TheDonDope for the help . I used the seed from the lazy branch .After some modifications to the seed.config and the routes lazy loading is working  now for production.

**Comment by mgechev** [comment]
Yes, I fixed the production build today. AoT still doesn't work, unfortunately.

**Comment by gomesNazareth** [comment]
@mgechev I having an issues with the directory and file paths in production for windows machine. The production builds but the file path for main.js is wrong in app.js . Below is the screen shot . Can you help me with this ? 
![image](https://cloud.githubusercontent.com/assets/18714183/19849287/c57214b6-9f6b-11e6-8d84-f32f4b9d748b.png)

**Comment by urantiana** [comment]
Same error here (systemjs unexpected token <)

**Comment by mgechev** [comment]
Try the "lazy" branch. It implements lazy loading and supports AoT.

**Comment by urantiana** [comment]
I'm already using the lazy loading branch. It doesn't work either.

**Comment by mgechev** [comment]
With custom setup or a clean clone? It shows a very basic implementation of lazy-loading behavior so for your custom setup it most likely will not work. I am using it for a big project where the module bundling strategy is much more complicated and covers much more cover cases compared to what we have in the `lazy` branch here.

**Comment by urantiana** [comment]
No, I have built a clean clone from the lazy branch.

**Comment by gomesNazareth** [comment]
I have used the lazy loading  seed for  my project.It worked fine. you need  to specify the modules in the seed.config so that production build can find them. And check your  imports in alll  your components. I had an issue  with rxjs imports. how ever  there is still a path issue on windows  os

**Comment by charitharumapperuma** [comment]
Hi, is there a way to do this using Webpack? 
I'm using,
```
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

@angular/*: 2.4.3
@angular/router: 3.4.3
```

And if I use above code block in a Webpack project, following error is shown in compile time,
```
Argument of type 'NgModuleRef<any>' is not assignable to parameter of type 'Injector'.
  Property 'get' is missing in type 'NgModuleRef<any>'.
```
and when I try to load a module manually following error comes up in browser,
```
EXCEPTION: Uncaught (in promise): Error: Cannot find module 'app/+profile/summary/summary.module'.
Error: Cannot find module 'app/+profile/summary/summary.module'.
```

**Comment by ruffiem** [comment]
@charitharumapperuma I recommend you take a look at this : https://github.com/meligy/routing-angular-cli

**Comment by charitharumapperuma** [comment]
@ruffiem I took a look at the project you suggested. Seems like it is similar to router based lazy loading. In my case I need a mechanism to load modules on demand within the same route.

**Comment by klesky** [comment]
any progress on this? i'm having the same error as  @gomesNazareth

**Comment by HMubaireek** [comment]
@fourctv This  method worked. But let's say you've dynamically loaded a module that has two components, how to navigate from component 1 to component 2 ?

Please look here for more details:
https://stackoverflow.com/questions/47868321/routing-between-components-inside-a-dynamically-loaded-module

**Comment by raujonas** [comment]
@fourctv @vijosoco I am currently facing the same issue with the path to my dynamic module, but I am getting "Error: Uncaught (in promise): Error: Cannot find module '././external/external.module#ExternalModule'." So my question is, am I missing another step? Can this work at all with .ts files or do I have to bundle the module somehow before? 

Thank you for your help!
