### ISSUE TITLE
Native i18n is not generating <trans-unit> as expected

### ISSUE THREAD

**Issue by DarienChoo** [mgechev/angular-seed#1440]
**Steps to reproduce and a minimal demo of the problem**
Following this cookbook (https://angular.io/docs/ts/latest/cookbook/i18n.html#!#ng-xi18n), I'm trying to generate the .xlf file.

- Include 'i18n' in desired template html (e.g. app.component.html)

- Open a terminal window at the root of the application project and enter the ng-xi18n command:
**npm run i18n**

**Current behavior**
A .xlf file is generated but the <body> of the file is missing <trans-unit>:
![my-output](https://cloud.githubusercontent.com/assets/5697198/19183670/012c7e74-8cac-11e6-8d2a-7ecf8f94c8cb.jpg)

**Expected/desired behavior**
A .xlf file generated with <trans-unit> tag and related information extract from template html
![expected](https://cloud.githubusercontent.com/assets/5697198/19183714/32cf8cbe-8cac-11e6-9002-3148ef99b3a2.jpg)

**Comment by ruffiem** [comment]
@DarienChoo you should not be using i18n native until it's correctly implemented in the seed. At this time, I got it working without problem at JIT but AoT requires more work.

**Comment by DarienChoo** [comment]
@ruffiem, I tried to remove src from exclude in tsconfig.json but it triggered another issue. 
"Error: can't find symbol Host exported from module "../node_modules/@angular/core/src/di/metadata.d.ts" "

Could you be kind enough to tell me how you made it work? TQ.

**Comment by ruffiem** [comment]
#### WARNING : This command will compile your typescript files and generate javascript, javascript maps and json metadatas in your components which is boring to remove...

First make a backup of your `tsconfig.json` file. To create `messages.xlf`, add the entry point of your app in your `tsconfig.json` - also exlude the `tools` directory. 

```
{
  "compilerOptions": { ... },
  "files": [
    "src/client/app/main.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "src",
    "tools", <<<
    "typings/index.d.ts",
    "typings/modules"
  ],
  "compileOnSave": false
}
```

Then run the ng-xi18n command.

**Comment by DarienChoo** [comment]
@ruffiem , thank you so much! I can create a proper `messages.xlf` now. Appreciate your recommendation too!

**Comment by ruffiem** [comment]
Anytime, Darien. Maybe we could close this.

**Comment by dileepkeeppalli** [comment]
I am getting an error when excecuting the command in terminal

```
C02PH6QYG3QD:logger dileep$ ./node_modules/.bin/ng-xi18n  --i18nFormat=xmb
TypeError: compiler.HtmlParser is not a function
    at extract (/GE/Test_Angular2/logger/node_modules/@angular/compiler-cli/src/extract_i18n.js:12:50)
    at Object.main (/GE/Test_Angular2/logger/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/GE/Test_Angular2/logger/node_modules/@angular/compiler-cli/src/extract_i18n.js:153:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
Extraction failed
```
