### ISSUE TITLE
Supports multiple Angular applications with shared codebase in a single instance of the seed

### ISSUE THREAD

**Issue by JanickRoss** [mgechev/angular-seed#1441]
Is it possible to make a short example on a wiki page for this feature ?

**Comment by jwuliger** [comment]
Yes please! I am trying to find the best practices to do this myself. Adding 2 NG2 apps using this seed. Thanks!

**Comment by mgechev** [comment]
I'll write the wiki today. Once [this PR lands](https://github.com/mgechev/angular-seed/pull/1455) in master we'll have both - AoT enabled and standard production builds working for multiple apps with shared codebase!

**Comment by mgechev** [comment]
Here's the wiki page https://github.com/mgechev/angular-seed/wiki/Multiple-Applications.

**Comment by jwuliger** [comment]
Awesomeness!

**Comment by JanickRoss** [comment]
thanks for the wiki page ;)
