### ISSUE TITLE
[Discuss] Sass improvement

### ISSUE THREAD

**Issue by lifaon74** [mgechev/angular-seed#1452]
Hi, I'm opening this not to report an issue but to discuss about sass performance.

The problems : 
- last changes (https://github.com/mgechev/angular-seed/commit/20d8d5cbc1f3cc3608de095e951d18f213f9ce64), create sometime problems with sass with import (some files doesn't change but imports yes, problem : they are not re-processed !).
- The scss files are not cached => with medium projects (+30 components -> +30 scss files in app/) it takes about 30s to compute all of them, too long for proper dev.
- Finally, some scss files only contain variables, mixins, etc... and should not be processed, or even added to the main.css when build.prod.

I have done some personnal improvement to the build.html_css task, and share here ideas (maybe not the best, that's what I created a talk). File available [here](http://www.filedropper.com/buildhtmlcss). I'll do a PR if validated.

So first of all : 

1) I created a new folder called scss at the root of `app/APP_NAME`, this folder contains all my "external scss", and none of these files should be compiled.

Into the `css/` folder, I just put one file `main.scss` containing `@import '../scss/main';` This file will import all needed scss files and will be compiled. => This ensure a single entry point, and avoid compiling useless scss files (ex: variables, other projects styles, etc...).

I have also created into project.config.ts a new variable : `SCSS_SRC = `${this.APP_SRC}/scss`;`

2) Into build.html_css

New variable `const useCache = true;` (should go to project.config) to enable/disabled chache.

3 paths : 

``` ts
const appSCSSFiles  = join(Config.APP_SRC, '**', '*.scss'); // all app scss files
const SCSSFiles     = join(Config.SCSS_SRC, '**', '*.scss'); // all "external" scss files that should not be processed
const mainSCSSFiles = join(Config.CSS_SRC, '**', '*.scss'); // entry scss files
```

Then into `processComponentScss()`I used a combinaison of gulp_cache, gulp_progeny, and gulp_filter

``` ts
return gulp.src([
      appSCSSFiles, // all my app scss files
      SCSSFiles // all my "external" scss files
    ])
    .pipe(useCache ? plugins.cached('process-component-scss') : plugins.util.noop()) // check cached files
    .pipe(useCache ? plugins.progeny() : plugins.util.noop()) // check imports
// personal code
    .pipe(debug({title: 'app css before filter'}))
    .pipe(filter([appSCSSFiles, '!' + SCSSFiles])) // remove all "external" scss files that should no be compiled
    .pipe(debug({title: 'app css after filter'}))
// end personal code
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass(Config.getPluginConfig('gulp-sass')).on('error', plugins.sass.logError))
    .pipe(plugins.postcss(processors))
    .on('error', reportPostCssError)
    .pipe(plugins.sourcemaps.write(isProd ? '.' : ''))
    .pipe(gulp.dest(isProd ? Config.TMP_DIR : Config.APP_DEST));
```

And did the same for `getExternalScssStream()`

Not a lot of changes but great compilation time improvement.

If more ideas, comment here.

**Comment by mgechev** [comment]
I'm not a Sass user so I haven't noticed all these problems. Thanks for the proposal!

I like the suggestions, it'll be even better if we're able to reduce the number of configuration properties that you introduce, since we already have plenty of them. Do you think we can drop `useCache` (if we have caching in all cases we don't loose anything, except some memory, right?) and move `SCSS_SRC` to `pluginConfig`?

**Comment by lifaon74** [comment]
Yes, `useCache` can be removed. I just used it as a security. By the way, I disabled the `shallRun`of the `CssTask` which return true for sass files, but with caching maybe this class will ne be uselfull anymore ?

**Comment by lifaon74** [comment]
So I created a fork here: https://github.com/lifaon74/angular-seed

I changes client css files by scss files to provide examples.

**Comment by mgechev** [comment]
Great, thanks for the effort! I will take a look at it later today/tomorrow after I fix the P1 issue in the tracker.

**Comment by RoxKilly** [comment]
@lifaon74 your modification is useful.  With the current repo, I can't see a clean way to exclude `scss` files that I don't want compiled and bundled.  With your mod, I would just put those files in the abstract styes folder: `Config.SCSS_SRC`

Thank you.

**Comment by lifaon74** [comment]
Doc available here https://github.com/lifaon74/angular-seed/wiki/Sass

@mgechev tell me when you'll merge and I'll duplicate the wiki page into your git.

**Comment by caleuanhopkins** [comment]
+1 :+1: @lifaon74 need to get your sass wiki docs into this projects wiki, will probably help many others like me trying to get sass working

**Comment by lifaon74** [comment]
New pull request => https://github.com/mgechev/angular-seed/pull/1568
