### ISSUE TITLE
Sass files are not being processed

### ISSUE THREAD

**Issue by ospaarmann** [mgechev/angular-seed#1454]
I have the issue that the .scss in the component folders files are not being processed. The main.scss is being processed without an issue, but all the files inside the component subfolders are just ignored. They are referenced in the styleUrls metadata though:
```

// file: /my_app/src/client/app/+home/home.component.ts

import { Component } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'trope-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
export class HomeComponent {
  constructor() {}
}
```

The ENABLE_SCSS option is permanently turned on, like though (`/tools/config/seed.config.ts`):

`ENABLE_SCSS = argv['scss'] || true;`

Any idea what is going on?

**Comment by sangecz** [comment]
scss is not enabled by default, the line `ENABLE_SCSS = argv['scss'] || true;` should be `ENABLE_SCSS = argv['scss'] || false;` and it means that it is enabled if scss arg is present else disabled

you can either opt it on by e.g.
`npm run -- --scss `
or set it to default in `/tools/config/project.config.ts` in constructor: `this.ENABLE_SCSS = true;`

**Comment by ospaarmann** [comment]
Thanks for your reply but I don't see the difference. I just set the default on a higher level. 

Anyway, when I set it to default in `/tools/config/project.config.ts` in the constructor: `this.ENABLE_SCSS = true;` or start the server with `npm start -- --scss` (you had a typo there) I still have the same problem. 

Still only `.scss` files in `/src/client/css` are being processed. There is also this line in `seed.config.ts`: 

```
/**
* The folder of the applications css files.
* @type {string}
*/
CSS_SRC = `${this.APP_SRC}/css`;
```

So maybe angular-seed was changed and now only processes files in this folder. But that wouldn't make too much sense since angular 2 encourages writing css files for components (using `styleUrls`).

**Comment by mgechev** [comment]
@ospaarmann I cannot reproduce your issue. My `AboutComponent` is using `about.component.scss`. Once I run the application with:

```shell
npm start -- --scss
```

Everything works as expected. Make sure you have correct configuration of the seed and you haven't overridden any essential tasks.
