### ISSUE TITLE
External js files are not working inside angular 2 components

### ISSUE THREAD

**Issue by Mahfuz2811** [mgechev/angular-seed#1458]
I'm working with altair admin template. Trying to convert it into an angular2 spa.
Everything is working fine except external js. Javascripts are not working properly. But the css files are working. Material components and modals other javascript functionality nothing is working inside angular component file.
[Stackoverflow Problem Link](http://stackoverflow.com/questions/39974914/external-js-files-are-not-working-inside-angular-2-components)

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
