### ISSUE TITLE
Add external dependency not working

### ISSUE THREAD

**Issue by CuriousLayman** [mgechev/angular-seed#1459]
Steps to reproduce:
Follow instructions at https://github.com/mgechev/angular-seed/wiki/Add-external-dependency. Then run build.prod from the gulp file.

In the latest version of seed you'll now have to chase all the dependencies of the external dependency and add package configuration for all dependencies otherwise you'll receive the error below in the build.bundles.app step. In prior versions just adding package information for angular2-jwt would work. Now you'll have to add package info for js-base64, then buffer (which should be global for node?), etc.

[07:42:38] Starting 'build.bundles.app'...
[07:42:41] 'build.bundles.app' errored after 2.64 s
[07:42:41] Error on fetch for js-base64.js at file:///D:/Work/Projects/angular2seed/node_modules/js-base64.js
	Loading angular2-jwt/angular2-jwt.js
	Loading dist\tmp\app\home/home.module.js
	Loading dist\tmp\app\app.module.js
	Loading dist\tmp\app\main.js
	Error: ENOENT: no such file or directory, open 'D:\Work\Projects\angular2seed\node_modules\js-base64.js'
    at Error (native)
[07:42:41] 'build.prod' errored after 15 s
[07:42:41] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for js-base64.js at file:///D:/Work/Projects/angular2seed/node_modules/js-base64.js
	Loading angular2-jwt/angular2-jwt.js
	Loading dist\tmp\app\home/home.module.js
	Loading dist\tmp\app\app.module.js
	Loading dist\tmp\app\main.js
	ENOENT: no such file or directory, open 'D:\Work\Projects\angular2seed\node_modules\js-base64.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'D:\Work\Projects\angular2seed\node_modules\js-base64.js'
Stack:
Error on fetch for js-base64.js at file:///D:/Work/Projects/angular2seed/node_modules/js-base64.js
	Loading angular2-jwt/angular2-jwt.js
	Loading dist\tmp\app\home/home.module.js
	Loading dist\tmp\app\app.module.js
	Loading dist\tmp\app\main.js
	Error: ENOENT: no such file or directory, open 'D:\Work\Projects\angular2seed\node_modules\js-base64.js'
    at Error (native)
Process terminated with code 1.

**Comment by CuriousLayman** [comment]
This actually appears to be a problem with the package angular2-jwt itself.

**Comment by TheDonDope** [comment]
Hi @CuriousLayman,

do you absolutely need to use the package `angular2-jwt`? The implementation amount is not that much, have a look here: https://github.com/TheDonDope/crudular/commit/cb720805b182865ba7d0accb949206e77a80aacd
