### ISSUE TITLE
Minification at dev mode

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular-seed#1460]
In older versions dev mode worked with minifaction, but now every fina js is loades on a separated request. Would be nice if this feature work again.
Thank you

**Comment by mgechev** [comment]
We have never had minification in dev, neither bundling. We are still loading third-party dependencies, such as Angular, Rxjs and others, with a single request using their bundle.

Probably in future we'll introduce something like SystemJS HMR or Angular hot loading.

**Comment by gustavolira** [comment]
@mgechev Sorry, I was talking about this #400

**Comment by mgechev** [comment]
No problem. This issue should be addressed with final, let me know if you still see all your `@angular/*` files loaded separately.

**Comment by gustavolira** [comment]
Sorry I did not understand. 
About final you mean angular 2 final version?
I'm using the last version of angular-seed master branch

**Comment by mgechev** [comment]
Yes, currently we load the Angular bundles so #400 is addressed by the current version of the seed.

<img width="1058" alt="screen shot 2016-10-11 at 10 48 15" src="https://cloud.githubusercontent.com/assets/455023/19281687/3e356a50-8fa0-11e6-9f73-8a584995956f.png">


We have never loaded the files from `src/client/app` as a single bundle. Currently the application that I'm working on has a couple of hundreds of files which slows the refresh and I know what you are talking about. At some point we'll think about an optimization which will make the dev process faster.

**Comment by gustavolira** [comment]
Hi @mgechev it's exactly what you said, thank you for your support!

**Comment by gustavolira** [comment]
Hi @mgechev I just checked, it's only libs from node modules and my own files

**Comment by mgechev** [comment]
It'll be best if we bundle all the app files and produce a single file. It will be loaded together with libraries and everything will be much faster. In the past I've used [this](https://www.npmjs.com/package/browserify-incremental). I haven't researched for anything SystemJS-related.
