### ISSUE TITLE
Include intl polyfill

### ISSUE THREAD

**Issue by Zasuk** [mgechev/angular-seed#1464]
Hi, 
This polyfill is used in some date pipes...i think we should include it by default in the project (or at least leave it commented).

The polyfill can be found here: https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by mgechev** [comment]
Would you open a PR with this? I think, adding the polyfil to npm dependencies and to seed.config.ts in NPM_DEPENDENCIES is what we need here.

**Comment by Zasuk** [comment]
Yeah i can but it will take some time because i'm really busy at moment and i'm on holidays in next weeks. I'll send a PR asap, ok?

**Comment by ruffiem** [comment]
Do you want to include all of them ?

**Comment by mgechev** [comment]
Maybe we should just include this list of polyfils in the readme.
