### ISSUE TITLE
Curious about using ts-helpers to reduce code bloat and help fine tune code coverage, etc.

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular-seed#1467]
Emit helpers is on by default throughout the seed, which ends up leaving a lot of code bloat in development. This is outside the realm of AoT.

> This can be a problem when dealing with code coverage or payload size of you library/app.

Curious any thoughts around using https://github.com/ngParty/ts-helpers to allow setting `"noEmitHelpers": true` in the `tsconfig` to help solve this?

**Comment by NathanWalker** [comment]
May need this to implement here: https://github.com/ngParty/ts-helpers/issues/2

**Comment by NathanWalker** [comment]
Actually the above shouldn't be a blocker; it is used here already: https://github.com/AngularClass/angular2-webpack-starter/search?utf8=%E2%9C%93&q=ts-helpers

**Comment by mgechev** [comment]
Sounds good to me. It should not be hard to integrate with the seed (configuration change + additional line in `NPM_DEPENDENCIES`).

I can take it tomorrow/during the weekend, if anyone can take it before that it'll be awesome.

**Comment by Hotell** [comment]
Just a heads up 
https://github.com/ngParty/ts-helpers#note-starting-typescript-21-this-package-wont-be-needed-anymore

**Comment by mgechev** [comment]
Thanks for the feedback.

**Comment by NathanWalker** [comment]
Very nice, that will be a welcome addition in 2.1 👍
