### ISSUE TITLE
Add example for Routing CanActivate 

### ISSUE THREAD

**Issue by KANekT** [mgechev/angular-seed#1471]
Add example for Routing CanActivate

**Comment by TheDonDope** [comment]
The seed is not aimed to be a full angular feature demo, so i'd rather suggest adding a wiki example.

However, if you can also take a look here: https://github.com/TheDonDope/crudular/commit/cb720805b182865ba7d0accb949206e77a80aacd more specifically https://github.com/TheDonDope/crudular/blob/cb720805b182865ba7d0accb949206e77a80aacd/src/app/shared/authentication/authentication.guard.ts and https://github.com/TheDonDope/crudular/blob/cb720805b182865ba7d0accb949206e77a80aacd/src/app/home/home.routing.ts
