### ISSUE TITLE
Add external JS library

### ISSUE THREAD

**Issue by kiuka** [mgechev/angular-seed#1473]
Hey guys,

I tried to add an external library to angular2-seed, but I couldn't make it work.

The desired library is https://github.com/callmecavs/jump.js

I followed the Wiki, therefore I added the following lines:

project.config.ts
`
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'jump.js/dist/jump.min.js', inject: 'libs'},
`

`  SYSTEM_BUILDER_CONFIG: any = {
...
    packages: {
...
      'jump.js': {
        main: 'dist/jump.min.js',
        defaultExtension: 'js'
      }
    }
  };`

After that, I tried to import the library, but it still undefined:

`import jump from 'jump.js';`

Could someone please tells me that what is the proper way to add an external JS library?

Thanks in advance!

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
