### ISSUE TITLE
SystemJS packageConfigPaths causing issues

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#1475]
I've got an app based on the seed which completes the prod build fine on my local machine. However, if I set it up to build on our Jenkins server, I get an error about not being able to locate a `package.json` for one of my dependencies (NGRX in this case).

I was baffled, since it builds fine locally. I searched around on Google and found this similar issue over at the angular-seed-advanced repo: https://github.com/NathanWalker/angular-seed-advanced/issues/48

The fix he applied was to [delete the entire SystemJS `packageConfigPaths` key](https://github.com/NathanWalker/angular-seed-advanced/commit/959ea8f43c42081452b67f088eeff1c15bb625b8).

I figured it was worth a try, and it solved the Jenkins build problem, while still building fine locally as well.

I'm not exactly sure why this worked, since SystemJS offers virtually no documentation on `packageConfigPaths` at all. Maybe the issue I ran into is related to the environment somehow (Linux vs. Windows), or possibly even something related to the order in which the `packageConfigPaths` are evaluated?

Anyway, I wanted to raise the issue here. Is the `packageConfigPaths` in the seed config actually necessary? Because deleting it seems to have solved the problem without affecting anything else.

**Comment by mgechev** [comment]
The purpose of `packageConfigPaths` is to point to directories where SystemJS can get more metadata regarding the packages (i.e. main file for instance). It is a redundant property sometimes and instead you can use `paths`. This brings simplification of the configuration so I don't mind dropping the `packageConfigPaths`. Would you mind opening a PR with this change?

**Comment by brian428** [comment]
Will do!

**Comment by Skielex** [comment]
This change broke my app, since a bunch of dependencies such as lodash and breeze-client are now being referenced with a wrong path.

For instance
`import * as _ from 'lodash';`
results in
`http://localhost:5555/node_modules/lodash.js`
which is obviously wrong.

I can fix the issue by re-adding the removed code into my `project.config.ts`:
```
    this.SYSTEM_CONFIG_DEV.packageConfigPaths = [
      `/node_modules/*/package.json`,
      `/node_modules/**/package.json`,
      `/node_modules/@angular/*/package.json`
    ];
```

My question is, if this is the correct way to solve my problem? It is definitely a lot simpler than adding a path to `SYSTEM_CONFIG_DEV` for every dependency.

**Comment by 1thrasher** [comment]
@mgechev I just updated my app to the lastest seed, and the removal of the packageConfigPaths causes a 404 error for a couple of files (rxjs and moment.js in my case). Re-adding these lines fixes the problem.

Is there a workaround for this?

**Comment by mgechev** [comment]
You can override the system configuration in your `project.config.ts` file for now:

```ts
constructor() {
  // ...
  this.SYSTEM_DEV_CONFIG.packageConfigPaths = [		
     `/node_modules/*/package.json`,		
     `/node_modules/**/package.json`,		
     `/node_modules/@angular/*/package.json`		
   ];
  // ...
}
```

**Comment by brian428** [comment]
Or (and correct me if I'm wrong, Minko), you can map them via `paths`, right?

As I understand it, the problem with `packageConfigPaths` (other than it seeming to be [totally undocumented](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md)), is that it assumes that **all** dependent node modules are packaged/distributed in the same way. Meaning `packageConfigPaths` can break things **even if** you explicitly add your own path mapping.

As a result, I still think this should stay out of the default seed config. Folks can add it back in their project config if they really want to. But given that the SystemJS config docs don't even mention `packageConfigPaths`, it looks like the "right" way to do this is really to add path mappings, rather than relying on `packageConfigPaths`.

**Comment by pratheekhegde** [comment]
@brian428 Fortunately, this was the only way by which I got @ngrx working.

```
    // @ngrx/core
    additionalPackages.push({
      name:'@ngrx/core',
      path:'node_modules/@ngrx/core/bundles',
      packageMeta:{
        main: 'core.umd.js',
        defaultExtension: 'js',
      }
    });
```

In `project.config.ts` I  added additionalPackages for `@ngrx/store , @ngrx/effects, @ngrx/router-store` and `@ngrx/store-devtools` finally the magic line `delete this.SYSTEM_BUILDER_CONFIG['packageConfigPaths']; ` got it working on both local and prod

Thanks a lot.
