### ISSUE TITLE
The package @angular/common@2.0.2 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by albertosetim** [mgechev/angular-seed#1480]
Good mornnig,  I make a fresh clone  and i have the following problem:

The package @angular/common@2.0.2 does not satisfy its siblings' peerDependencies requirements!
![image](https://cloud.githubusercontent.com/assets/17254772/19384844/6c0e0b34-9203-11e6-9734-37f2156f35f4.png)

![image](https://cloud.githubusercontent.com/assets/17254772/19384798/1780effa-9203-11e6-99c0-886bbc235176.png)

step 1 :
git clone --depth 1 https://github.com/mgechev/angular2-seed.git
step 2:
npm install

**Comment by RoxKilly** [comment]
@albertosetim Looks like the problem I faced recently.  I would do the following:

1. delete the project
2. [upgrade node/npm](https://nodejs.org/en/download/) to the latest (`node 6.8`)
3. clone
4. install

**Comment by albertosetim** [comment]
nice error gones ;)
