### ISSUE TITLE
Wiki instruction on SASS support does not work

### ISSUE THREAD

**Issue by RoxKilly** [mgechev/angular-seed#1481]
The Wiki on [enabling SASS support](https://github.com/mgechev/angular-seed/wiki/Enabling-SASS-support) states:

> For a permanent enablement, set the `ENABLE_SCSS` config value to true in either `seed.config.ts` or `project.config.ts`

Took me a while to figure this out, but the two options are not equivalent. If I set the flag in `project.config.ts` (where we're supposed to make edits), it is not properly picked up by the `build.html_css` task (in `dev` environment).

Specifically, the function [`getInjectableStyleExtension()`](https://github.com/mgechev/angular-seed/blob/master/tools/config/seed.config.ts#L318) will return `css` even if `ENABLE_SCSS` is set to true in `project.config.ts`.  As a result, my main stylesheet -- `/src/client/css/main.scss` -- is never picked up by the `build.html_css` task.  Instead, a non-existent `main.css` is sought.

Setting the `ENABLE_SCSS` flag in `seed.config.ts` works, but there is a stern warning at the top of that file:

> /************************* DO NOT CHANGE ************************
 * DO NOT make any changes in this file because ...

**Comment by RoxKilly** [comment]
A quick fix, for those who -- like me -- do not want to edit `seed.config.ts` is to explicitly list your `main.scss` as an asset in [`project.config.ts`](https://github.com/mgechev/angular-seed/blob/master/tools/config/project.config.ts#L28):
```
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      { src: `${this.CSS_SRC}/main.scss`, inject: true, vendor: false },
    ];
```
Don't know whether that covers me fully, but fixes the immediate problem of task `build.html_css` ignoring the `ENABLE_SCSS` flag when in `dev` environment

**Comment by RoxKilly** [comment]
ignore. My mistake

**Comment by martingula** [comment]
What was your mistake?

**Comment by RoxKilly** [comment]
@martingula Setting `ENABLE_SCSS` flag in `project.config.ts` does not properly change the behavior of `build.html_css` as I pointed out. 

I said "*my mistake*" because my conclusion (that `main.scss` is not picked up) is incorrect.  In fact, when the flag is set from `project.config.ts`, all `*.scss` files in the CSS folders are compiled.  So even though `main.scss` is not detected properly (the task looks for `main.css`), the file still gets compiled.
