### ISSUE TITLE
i18n not generates Id in <trans-unit>

### ISSUE THREAD

**Issue by TsarS** [mgechev/angular-seed#1484]
Hello,  i am trying to "Enabling Angular i18n native", but `npm run i18n`  generates a file 

    `<?xml version="1.0" encoding="UTF-8" ?>
       <xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
           <file source-language="en" datatype="plaintext" original="ng2.template">
              <body>
              </body>
            </file>
         </xliff>`
 
  Without any id in `<trans-unit>` section

**Comment by mgechev** [comment]
Did you take a look at the last 8 section? https://github.com/mgechev/angular-seed/wiki/Enabling-Angular-i18n-native

Most likely this is the problem in your case - you don't have a file which references to your application so `ng-xi18n` can't reach out your app.

**Comment by TsarS** [comment]
Wow i'm sorry. Yes, it works with with app.through.ts. Sorry

**Comment by mgechev** [comment]
No problems. It'll get simpler with the next version we introduce :-);
