### ISSUE TITLE
not letting me to add ngModel in toolbar component

### ISSUE THREAD

**Issue by svennela** [mgechev/angular-seed#1485]
**Steps to reproduce and a minimal demo of the problem**
  <input  [(ngModel)]="searchTerm" class="form-control">

_What steps should we try in your demo to see the problem?_

you can use ngModel in the tool bard or nav bar.

**Current behavior**

Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("<h1>Angular 2 Seed</h1>
<input  [ERROR ->][(ngModel)]="searchTerm"

**Expected/desired behavior**
it should let me use ngmodel in toolbar component.
**Other information**

**Comment by mgechev** [comment]
You need `FormsModule`.

**Comment by svennela** [comment]
where do i add? I mean which file. I have added in shared.module.ts
