### ISSUE TITLE
Forerunnerdb typings

### ISSUE THREAD

**Issue by StefanKoenen** [mgechev/angular-seed#1486]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

1. Install forerunnerdb: `npm install forerunnerdb --save`

_What steps should we try in your demo to see the problem?_

Use the forerunnerdb typings in your project

**Current behavior**
The forerunnerdb typings (located in forerunnerdb/typescript/types.d.ts) are not working in sublime

**Expected/desired behavior**
Autocompletion from the typings 😄 

**Other information**
There is no tutorial / info about including typings of other libraries.

**Comment by mgechev** [comment]
If there are no typings distributed with `forerunnerdb`, and also there are no such available in `@types/forerunnerdb` you should create them yourself. You can place them in `tools/manual_typings/project`.
