### ISSUE TITLE
Using the seed to build libraries

### ISSUE THREAD

**Issue by vlio20** [mgechev/angular-seed#1487]
Hi,  
Is it possible to use this seed to make libraries? 
Things that this are special to libraries:  
1. Multiple css files - for theming.
2. bundled and unbundled generated files (in dist).
3. Easy way to import generated files. 

For example - the angular-cli doesn't generates (builds) files that are feet to use as a library - the files that it generates are good to be used as an app.

**Comment by mgechev** [comment]
The seed is extensible so you can add tasks which do everything that you need. Easy to import files is a requirements which entirely depends on the library developer - all you need there is a `package.json` file with set `main` property. You may also need to drop some of the `package.json` fields such as `private`, `devDependencies`, etc.
