### ISSUE TITLE
Uncaught (in promise): TypeError: System.import is not a function

### ISSUE THREAD

**Issue by chaplin** [mgechev/angular-seed#1490]
After running `npm run serve.prod` and Browser complaining 
"Uncaught (in promise): TypeError: System.import is not a function"
<img width="771" alt="2016-10-17 05 17 12 pm" src="https://cloud.githubusercontent.com/assets/628456/19432161/df4011b0-948d-11e6-87cf-740c42367540.png">

**Comment by RoxKilly** [comment]
@chaplin The build tools for production are setup to bundle the app in a way that does removes the need for `System` module loader. Did you modify `/tools/config/seed.config.ts` or anything in `tools/task/seed/` directly?

**Comment by chaplin** [comment]
@RoxKilly thank for your quick reply
No I did't modify anything in `/tools/config/seed.config.ts` and `tools/task/seed`.

**Comment by chaplin** [comment]
But I do modify tslint.json according issues #12120

**Comment by RoxKilly** [comment]
If in `/tools/config/seed.config.ts`, you replace the line:
```
    { src: 'systemjs/dist/system.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
```
With
```
    { src: 'systemjs/dist/system.src.js', inject: 'shims'},
```
Does the error still occur?

Secondly, did you edit `index.html`, in particular the block of code around `System.import`? If so, how?

**Comment by chaplin** [comment]
the `System.import is not a function` error is disappear but got another one
<img width="859" alt="2016-10-17 05 59 41 pm" src="https://cloud.githubusercontent.com/assets/628456/19433506/99911fb4-9493-11e6-8d45-c78f6cb16bb3.png">

**Comment by RoxKilly** [comment]
Does the app work when you use `serve.dev` task?

**Comment by mgechev** [comment]
This issue is caused by misconfiguration. The production build does not use SystemJS but instead bundles tp cjs modules.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by gomesNazareth** [comment]
I am having the same issue with prod .Has anyone found a fix ?

**Comment by gomesNazareth** [comment]
This happens when i try to lazy load the modules

**Comment by gomesNazareth** [comment]
export const routes: Routes = [
  ...HomeRoutes,
  ...AboutRoutes,
  {
    path: '',
    loadChildren:'./app/account/account.module#AccountModule'
  },
];

**Comment by RoxKilly** [comment]
@gomesNazareth I don't know how to use this seed to deploy lazy loaded modules. I don't think it's supported

**Comment by TheDonDope** [comment]
Have a look here, this is not a seed issue, but rather how to use the angular router: https://youtu.be/QLns6s02O48?t=6m27s

**Comment by ruffiem** [comment]
@TheDonDope what systemjs has to do with the router ?

**Comment by ruffiem** [comment]
Great...
![screen shot 2016-11-03 at 19 09 54](https://cloud.githubusercontent.com/assets/1785492/19979017/3454cb1e-a1f9-11e6-8f45-e9b35cdeec92.png)

**Comment by mgechev** [comment]
In the lazy branch we have experiments with bundling for lazy loading. The production works, I need to spend some more time making it work with AoT enabled.

**Comment by ruffiem** [comment]
@mgechev thanks, I will check it 👍

**Comment by gomesNazareth** [comment]
lazy loading prod build  work well on mac and linux . but  on windows  it fails .. file paths  are not correct. .

**Comment by ZuSe** [comment]
I run into the same problem as @chaplin  (using the lazy branch)
For some reason it does not resolve the lazy loaded files with the proper extension:

EXCEPTION: Uncaught (in promise): Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/app/components/content/dashboard/dashboard.module
	Error loading http://localhost:5555/app/components/content/dashboard/dashboard.module

Any ideas?
