### ISSUE TITLE
[Question] loading config file at runtime and AOT

### ISSUE THREAD

**Issue by Crazyht** [mgechev/angular-seed#1493]
Hi, 

I try to load angular config (API Url and SSO Url) dynamically from server with something like : 

export const Config: EnvConfig = require('/config');

It's work perfectly in dev mode, but compilation in production AOT mode crash when try to find /config :( 

How I can explain to AOT compiler don't impact this require ?

**Comment by mgechev** [comment]
Using require you are not requiring the config file at runtime but instead it gets part of the application bundle.

You can load the configuration by making an http request and populating the config object on successful response.

Good luck.

**Comment by Crazyht** [comment]
Finally I found this crappy workaround : 
Just add <script src="/config"></script> where my server generate javascript with config affected to window.AppSettings and configure DI with 

export const Config: EnvConfig = (<any>window).AppSettings; 

I m not sure is good way, but it's work
