### ISSUE TITLE
inlineNg2Template follows commented out code, and throws errors

### ISSUE THREAD

**Issue by syrys** [mgechev/angular-seed#1494]
So, hypothetically, lets say you have a new component called demo, and it looks a little like this:

````
import {Component} from '@angular/core';
@Component({
  moduleId: module.id,
  selector: 'my-demo',
  // templateUrl: 'demo.component.html',
  template: `
    <h1>Demo Component</h1>
`,
  // styleUrls: ['demo.component.css']
})
export class DemoComponent {
}
````

As you can tell, the `styleUrls` and `templateUrl` sections are commented out. But if you run the gulp task `build.prod` it fails at the sub task `build.js.prod`. Reason for the failure is that it cannot find the file `dist/tmp/..../demo/demo.component.html` (and if that line is removed, then `dist/tmp/..../demo/demo.component.css`). This means, obviously, even though these lines are commented out in your code, `inlineNg2Template` plugin still tries to follow that link and crashes and dies when it fails to do so.

Error looks a like this:
````
Error: ENOENT: no such file or directory, open '__DIST_TMP_APP_DIR__\demo\demo.component.html'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at getFileData (__PROJECT_DIR__\node_modules\gulp-inline-ng2-template\parser.js:281:17)
    at __PROJECT_DIR__\node_modules\gulp-inline-ng2-template\parser.js:245:22
    at __PROJECT_DIR__\node_modules\async\dist\async.js:3671:13
    at replenish (__PROJECT_DIR__\node_modules\async\dist\async.js:884:21)
    at __PROJECT_DIR__\node_modules\async\dist\async.js:888:13
    at eachOfLimit (__PROJECT_DIR__\node_modules\async\dist\async.js:915:26)
    at __PROJECT_DIR__\node_modules\async\dist\async.js:920:20
````

Is there a sensible solution for this? I mean, sure i can remove the commented out lines, but what if i want to have it exactly like that (for future developers of my codebase to know that you can link to a file that way incase they wernt fully familiar with angular2).

**Comment by mgechev** [comment]
You can try the AoT enabled production build (`npm run build.prod.exp`) which doesn't use `inlineNg2Template`. I'd recommend you to open an issue [here](https://github.com/ludohenin/gulp-inline-ng2-template/issues) if such issue doesn't already exist and continue the discussion with @ludohenin.
