### ISSUE TITLE
npm run build.prod octal literals are not allowed in strict mode 

### ISSUE THREAD

**Issue by kjwm** [mgechev/angular-seed#1497]
I am always getting this error whenever i try to run build.prod. I will appreciate any help.

**Comment by mgechev** [comment]
It'd be helpful if you provide more information and a minimum demo that can help us reproduce your problem. Without knowing your node, npm, OS versions we can't do much. 

Judging by the title of the issue I'd recommend you to take a look [here](https://stackoverflow.com/questions/23609042/how-to-avoid-octal-literals-are-not-allowed-in-strict-mode-with-createwritestr).
