### ISSUE TITLE
Cannot find module '.tmp/Rx.min.js' 

### ISSUE THREAD

**Issue by JonCatmull** [mgechev/angular-seed#1501]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

Created new repo using following steps:

```
git clone --depth 1 https://github.com/mgechev/angular-seed.git
cd angular-seed
sudo npm install
npm start

```

**Current behavior**

Errors on npm start

```
Error in plugin 'run-sequence(build.html_css)'                                                            
Message:                                                                                                             
    Cannot find module '.tmp/Rx.min.js'                                                                              
Details:                                                                                                             
    code: MODULE_NOT_FOUND                                                                                           
Stack:                                                                                                               
Error: Cannot find module '.tmp/Rx.min.js'                                                                           
    at Function.Module._resolveFilename (module.js:339:15)
```

**Expected/desired behavior**

Start app and livereload page

**Other information**

I have made and run a project before on a older version of the seed back when it was on angular-rc6.

I'm on a mac running macOS Sierra

node v 6.9.0
npm v 3.10.8

**Comment by JonCatmull** [comment]
[npm-debug.log.txt](https://github.com/mgechev/angular-seed/files/536940/npm-debug.log.txt)

**Comment by mgechev** [comment]
Would you run `./node_modules/.bin/gulp build.bundle.rxjs` and run `npm start` again?

**Comment by JonCatmull** [comment]
Thankyou that has fixed it, out of interest why did this happen? Is it a bug or something I did?

**Comment by mgechev** [comment]
On any reason the `postinstall` hook didn't execute properly.

**Comment by zeeshanjan82** [comment]
@mgechev I faced the same issue, thanks for the fix.

**Comment by amalshehu** [comment]
I too faced the same issue after adding a dependency.Thanks @mgechev

**Comment by MilosStanic** [comment]
Using the seed on Windows Subsystem for Linux. 
I ran first npm install, then yarn install which did not complete. 
Maybe that's how I got this error. But Minko's fix fixed it.

**Comment by nvsky** [comment]
sudo gulp build.bundle.rxjs

**Comment by saikiranmandhala** [comment]
@mgechev Faced the same issue, thanks for the fix. 
npm postinstall should also fix the issue just in case of multiple packages failures of post script.
