### ISSUE TITLE
Prod build doesn't work with external libraries

### ISSUE THREAD

**Issue by martingula** [mgechev/angular-seed#1502]
**Steps to reproduce and a minimal demo of the problem**

This code is based on this approach 
https://github.com/danielcrisp/angular2-seed

1. install and save ng2-bootstrap inside angular-seed.

2. I have this inside project.config.ts file to include ng2-bootstrap for dev and production build.

Line 47:

this.SYSTEM_CONFIG_DEV.paths['ng2-bootstrap'] = 'node_modules/ng2-bootstrap/ng2-bootstrap.js';
this.SYSTEM_BUILDER_CONFIG.packages['ng2-bootstrap'] = {
      main: 'ng2-bootstrap.js',
      defaultExtension: 'js'
};

When I ran npm run build.prod SYSTEM_BUILDER_CONFIG.packages collection doesn't have 
ng2-bootstrap info.

It works if I put it inside seed.config.ts file but I don't want to use seed.config.
Can you guide me what am I missing? 

Why is packages object not extended inside SYSTEM_BUILDER_CONFIG with ng2-bootstrap object?
Thanks.

**Comment by eppsilon** [comment]
Do you have the latest version of the seed? There were some changes that were rolled back today that might've caused this. (See https://github.com/mgechev/angular-seed/pull/1495.)

**Comment by martingula** [comment]
After some investigation - this was the cause of it and rollback fixed it. Thanks.
https://github.com/mgechev/angular-seed/commit/0c972d671c4337d361f56fa3684dac4601aaedbf#diff-3d695f3c2a28f15f1129d3a122b806d5
