### ISSUE TITLE
tslint errors in ci builds but not prod builds

### ISSUE THREAD

**Issue by njs50** [mgechev/angular-seed#1505]
is this desirable? shouldn't it also throw an error in a prod build? seems weird that a build which runs fine locally would fail in CI.

**Comment by mgechev** [comment]
Yes, this is intentional in order to force common style in PRs.

**Comment by njs50** [comment]
shouldn't it be possible to test your code before making a PR? why not also throw on a prod build?

**Comment by mgechev** [comment]
It's easier to merge PRs when the CI build fails, on the other hand linting errors are not critical for the production build.

**Comment by njs50** [comment]
In many cases the CI server is making the production build, so failing it there is failing the prod build. 

In some places PRs might not be built or validation might be done locally prior to hitting CI. errors that only happen in a build pipeline away from the developers really aren't ideal.

Currently i want to setup a pre push git hook to validate a branch before I create a PR. having to override the tsslint task to do that isn't ideal. Perhaps it should be a config option to throw on lint errors, then at least we could override it without having to change the task.
