### ISSUE TITLE
Changes made in css/scss files don't reflect in the watch mode

### ISSUE THREAD

**Issue by TianCNCA** [mgechev/angular-seed#1506]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
Turn on the scss support,
Run npm start
Modify some css/scss code
_What steps should we try in your demo to see the problem?_

**Current behavior**
Log shows it has detected changes in the css file and a rebuild/reload has been triggered, however in the browser the old css code are still used.

**Expected/desired behavior**
Changes made to css files should be reflected on the fly.

**Other information**

**Comment by mgechev** [comment]
Just tried it and it works for me. You can verify if the changes are triggered if you add a `console.log(files);` statement in `tools/utils/seed/code_change_tools.ts` just above `browserSync.reload(files);`. If you see logs like:

```
[ '/Users/mgechev/Projects/angular-seed/src/client/app/home/home.component.css' ]
```

Everything should be fine.

**Comment by mgechev** [comment]
@TianCNCA actually there was an issue. Would you try cloning master and try again?

**Comment by TianCNCA** [comment]
Sure thing @mgechev , I'll post my result later on

**Comment by TianCNCA** [comment]
@mgechev I confirm it's working now. Thanks!
