### ISSUE TITLE
What happened to css-lint?

### ISSUE THREAD

**Issue by danielcrisp** [mgechev/angular-seed#1509]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
```
**Current behavior**

Previously the seed included a `css-lint` task but I notice it was removed in this commit:
https://github.com/mgechev/angular-seed/commit/d829ef8e6f2bb461930c32d851da2a0715b68af9

It is still mentioned as a feature in the main README.md. Is this a mistake? Or was it intentionally removed and not replaced?

The reason I noticed is that I am having some problems with the task in an older version of the seed.

**Comment by danielcrisp** [comment]
Ok, found this: https://github.com/mgechev/angular-seed/pull/1478#issue-182980788

So it was dropped because of limited usage, rather than problems

**Comment by sullyme** [comment]
Why `css-lint` was removed?

How to lint css now?
