### ISSUE TITLE
font-awesome icons not showing up - Prod build 

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1510]
Hello,

I am having issues with font-awesome icons in Prod build, it works fine in Dev..

I have followed the instructions given in wiki

https://github.com/mgechev/angular-seed/wiki/Add-external-fonts..

I have sync'd up angular-seed on Oct 3rd..

here is my code

project.config.ts

```ts
FONTS_DEST = `${this.APP_DEST}/fonts`;

FONTS_SRC = [
      `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/fonts/**`,
       'node_modules/font-awesome/fonts/**'
]
```

build.fonts.ts

```ts
import * as gulp from 'gulp';
import Config from '../../config';

export = () => {
    return gulp.src(Config.FONTS_SRC)
        .pipe(gulp.dest(Config.FONTS_DEST));
};
```

gulpfile.ts

```ts
// --------------
// Build prod.
gulp.task('build.prod', (done: any) =>
  runSequence('clean.prod',
//            'tslint',
//            'css-lint'
              'build.assets.prod',
              'build.fonts',
              'build.html_css',
              'copy.prod',
              'build.js.prod',
              'build.bundles',
              'build.bundles.app',
              'minify.bundles',
              'build.index.prod',
              done));
```

Thanks
SK

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)```

**Current behavior**
I see square boxes in place of font-awesome icons
<!-- Describe how the bug manifests. -->

**Expected behavior**
Display font-awesome icons
<!-- Describe what the behavior would be without the bug. -->

**Minimal reproduction of the problem with instructions**
follow wiki instructions https://github.com/mgechev/angular-seed/wiki/Add-external-fonts 
to add font-awesome icons and run the production build
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem.
-->

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->

**Please tell us about your environment:**
I am testing on Window 10, Chrome, Angular 2.0 Final, angular-seed
<!-- Operating system, IDE, package manager, HTTP server, ... -->

* **Angular Seed Version:** 2.0.X 
Sync'd up on Oct 3 2016
<!-- Check which is the hash of the last commit from angular-seed that you have locally -->

* **Node:** `node --version` = 4.6.1

**Comment by mgechev** [comment]
In general your setup looks good to me. Would you verify that the files are copied to `dist/prod/fonts`?

**Comment by skolli853780** [comment]
Thank you for the quick response

I see 6 different types of fontawesome files under dist/prod/fonts..

**Comment by mgechev** [comment]
How are you referencing them in the CSS files? Probably you need to adjust to the directory where the files are supposed to be located based on the path in the CSS files.

**Comment by skolli853780** [comment]
I have added font-awesome.min.css file to project config NPM dependencies

 // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
        {src: 'primeui/primeui-ng-all.min.css', inject: true},
      {src: 'primeui/primeui-ng-all.min.js', inject: 'libs'},
      {src: 'font-awesome/css/font-awesome.min.css', inject: true},
      { src: 'primeng/resources/primeng.min.css', inject: true },

font-awesome.min.css (injected into main.css) calls font files 

@font-face{font-family:FontAwesome;src:url(../fonts/fontawesome-webfont.eot?v=4.6.3);src:url(../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3) format('embedded-opentype'),url(../fonts/fontawesome-webfont.woff2?v=4.6.3) format('woff2'),url(../fonts/fontawesome-webfont.woff?v=4.6.3) format('woff'),url(../fonts/fontawesome-webfont.ttf?v=4.6.3) format('truetype'),url(../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular)

I call the font-awesome icon directly in html 

  <i class="fa fa-facebook"></i>

It works perfectly fine with dev build.. issue is with Prod build

Thanks
SK

**Comment by skolli853780** [comment]
In one of the issues, you mentioned that we can disable bundling ..

https://github.com/mgechev/angular-seed/issues/1373

Can you please let me know what I should do to disable bundling? I think the issue I am facing is something to do with bundling (which is done only in Prod build) as it works perfectly fine with Dev build.. also we are using Ultima (PrimeNG theme) along with Font-awesome.. so when we are bundling different themes, something is getting overwritten during bundling process.. I maybe wrong though.. just a thought..

Thanks
Som

**Comment by mgechev** [comment]
Most likely the problem comes from the location strategy that you're using. If you're with `PathLocationStrategy` (which is the default one) and you're in `/foo/bar` then `../fonts` will point to `/foo/fonts` instead of `/fonts`.

You can switch to `HashLocationStrategy` or better use absolute path for the font url. This doesn't seem like an issue related to the seed but most likely to the setup that you're using. Anyway, lets keep it open until you are able to solve it.

I will also not recommend disabling bundling for production because it'll introduce a lot of requests.

**Comment by skolli853780** [comment]
I tried using both the location strategies Path and Hash .. no luck.. I will try absolute path for the font url

**Comment by omerfarukyilmaz** [comment]
@skolli853780 I am using font-awesome with PrimeNG as well in one of my projects and everything works well, both in dev and prod.

The difference is, I am using the free bootstrap theme.

      { src: 'font-awesome/css/font-awesome.min.css', inject: true },
      { src: 'primeng/resources/themes/bootstrap/theme.css', inject: true },
      { src: 'primeng/resources/primeng.min.css', inject: true },

I don't know how the (paid?) Ultima theme works but maybe primeng/resources/themes/bootstrap/theme.css has something to do with it.

For your code, try including font-awesome first before Ultima. Just a guess, it may work.

	FONTS_SRC = [
		'node_modules/font-awesome/fonts/**',
		`${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/fonts/**`
	]

Hope I can help.

And btw, as far as I know, you no longer need primeui (the js nor css) as a dependency if you are using the latest few versions of primeng. Only primeng with font-awesome should be enough.

**Comment by skolli853780** [comment]
@mgechev @omerfarukyilmaz  - Thank you for your insights.. For some reason I could not get Fontawesome working with Prod build, as an alternative I tried Ion Icons (https://github.com/driftyco/ionicons) and it is working well .. I am closing this thread.

Thank you
SK

**Comment by trytechstuff** [comment]
@mgechev @omerfarukyilmaz Just import into your styles and the after it will work for prod too.
@import url("https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css");**
