### ISSUE TITLE
[refactor] copy.prod task has redundancies with unintended side-effects

### ISSUE THREAD

**Issue by RoxKilly** [mgechev/angular-seed#1513]
[x] bug report

`tools/tasks/seed/copy.prod.ts` has a couple of redundancies:

[Line 12](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/copy.prod.ts#L12) copies all `html` files from `src/client/` to `dist/tmp`. Notice that whenever `copy.prod` is used -- in `build.prod` and `build.prod.exp` -- it is preceded by task `build.html_css`.

`build.html_css` already copies `html` files [in the same way](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/build.html_css.ts#L39).  The unintended consequence is that if `build.html_css` or any other task between that and `copy.prod` modifies the files in `dist/tmp`, the modified files will just be overwritten by `copy.prod`

My use case: I have a customized `build.html_css` that minifies the template files as they are copied.  Unfortunately, the minified files are overwritten by `copy.prod`, so later when the templates get inlined, the original templates -- not the minified ones -- are processed.

[Line 15](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/copy.prod.ts#L15) is redundant because the line immediately above it does the same thing and more: unless I'm mistaken, the glob `**/*.json` is a superset of `*.json`

**Comment by mgechev** [comment]
@RoxKilly makes sense. I think we can drop `**/*.html`, `**/*.css`, `*.json`. Do you want to open a PR or I can change it myself.
