### ISSUE TITLE
problem with codelyzer in @angular 2.1.1 (tslint errors)

### ISSUE THREAD

**Issue by stefanos-** [mgechev/angular-seed#1514]
tslint errors in npm run build.prod || tslint task enabled. The problem comes from codelyzer (const _ = compiler.__compiler_private__; --> templateParser.ts). There is a reference to a private method of @angular/compiler that may has changed in new version of angular (2.1.1).

**Comment by mgechev** [comment]
Thanks for reporting this issue. I will try to resolve it by the beginning of the next week.

**Comment by mgechev** [comment]
It's addressed by this PR https://github.com/mgechev/codelyzer/pull/124. I will push it to npm once the PR has been approved and merged. Again, thanks for reporting the problem!

**Comment by felipequiroz** [comment]
tslint errors in npm run build.prod. The problem comes from codelyzer (templateParser.ts):

var TemplateParser = _.TemplateParser;

TypeError: Cannot read property 'TemplateParser' of undefined

**Comment by mgechev** [comment]
This is fixed in the latest version of codelyzer, remove the `node_modules/codelyzer` directory and run `npm i` again.

**Comment by felipequiroz** [comment]
@mgechev, the problem occured in the last release v2.0.1, but when I cloned the repository the problem didn't appear. Thanks for your answer!
