### ISSUE TITLE
Production build TSError when encountering ${{myVar}} in html template

### ISSUE THREAD

**Issue by 1thrasher** [mgechev/angular-seed#1515]
[x] bug report

**Current behavior**
`npm run build.prod` fails when it encounters a `${{myVar}}` in the html template (but works if there is a space between the $ and {{, like `$ {{myVar}}`).

**Expected behavior**
There should not be a typescript error.

**Minimal reproduction of the problem with instructions**
`git clone https://github.com/mgechev/angular-seed.git`
Add `testNumber: number = 15.167;` to `home.component.ts`
Add `<p>${{testNumber | number:'1.2-2'}}</p>` to `home.component.html`
Run `npm run build.prod` and watch it fail with:
```
Starting 'build.js.prod'...
dist/tmp/app/home/home.component.ts(10,363): error TS1005: ':' expected.
dist/tmp/app/home/home.component.ts(10,365): error TS2304: Cannot find name 'number'.
dist/tmp/app/home/home.component.ts(10,371): error TS1005: ',' expected.
dist/tmp/app/home/home.component.ts(10,379): error TS1005: ':' expected.
[08:42:43] TypeScript: 3 syntax errors
[08:42:43] TypeScript: 1 semantic error
[08:42:43] TypeScript: emit succeeded (with errors)
```
Now add a space between the `$` and the `{{` in `home.component.html` and run `npm run build.prod`. Success!

* **Node:** `node --version` = v4.4.7

**Comment by mgechev** [comment]
This is an [know issue](https://github.com/mgechev/angular-seed/issues/1479) in `gulp-inline-ng2-templates`. You can try using `npm run build.prod.exp` which doesn't inline the templates as HTML but uses AoT instead.

**Comment by 1thrasher** [comment]
Thanks! (And sorry, I must have just missed the prior issue.)

**Comment by mgechev** [comment]
No worries, I hope AoT helps. Let me know if you hit any issues there.
