### ISSUE TITLE
Help with adding dependencies (eg. ng2-bootstrap)

### ISSUE THREAD

**Issue by syrys** [mgechev/angular-seed#1517]
Hi,

Im attempting to add some external dependencies to this project (eg. `ng2-bootstrap`: http://valor-software.com/ng2-bootstrap), and failing a bit. I spent a bit of time browsing through the wiki page and the other projects, but i seem to be hitting walls (other example projects/forks are very outdated, and maybe the wiki might also be im not sure?).

So, injecting a simple js/css file is easy. You simply add the following to your project.config file:
````
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'bootstrap/dist/css/bootstrap.min.css', inject: true},
    ];
````

But my main problem is, libraries/dependencies which also have other modules within it. For example `ng2-bootstrap`. This has modules that does different things. And you might want to use only some of them and not all of them (so, there is no point importing every module which will increase the filesize).

Can someone give me an example/instructions if not too much trouble? Following the wiki page didnt work for me at all. I will continue to try few more things in the meantime :)

**Comment by RoxKilly** [comment]
I would try the following, in `tools/config/project.config.ts`:

```
this.addPackageBundles({
  name:'ng2-bootstrap/ng2-bootstrap',
  path:'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.umd.js',
  packageMeta:{
    main: 'bundles/ng2-bootstrap.umd.js',
    defaultExtension: 'js'
  }
});
```
You can then import as you would any other `Angular` class
```
import { AccordionModule } from 'ng2-bootstrap/ng2-bootstrap';
```

**Comment by syrys** [comment]
@RoxKilly 
Just tried that, but when i run `npm start` i get the following error (on my chrome console):
````
http://localhost:5555/node_modules/moment.js:  Failed to load resource: the server responded with a status of 404 (Not Found)

localhost/:55: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/moment.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ localhost/:55
````

Also, wouldnt that code you suggested would import the entire bundle file `ng2-bootstrap.umd.js` which includes ALL the modules rather than the individual modules that are required within the project? I dont really mind so long as i can get it working, but ideally, it would be better if only the required modules can be imported (so you save a little bit of space on the build and the resulting webapp loads a tiny bit faster).

**Comment by RoxKilly** [comment]
Sounds like you'll also need to install and link to `Moment.js`

**Installing**
```
npm install --save-dev moment
```
**Linking** in `tools/config/project.config.ts`
```
this.addPackageBundles({
  name:'moment',
  path:'node_modules/moment/moment.js',
  packageMeta:{
    main: 'moment.js'  // also try index.js
    defaultExtension: 'js'
  }
});
```

As far as the bundling is concerned, I would try using `index.js` instead of `bundles/ng2-bootstrap.umd.js` or `moment.js` (see the `packageMeta` in both of my posts).  

I don't know whether using the `umd` means that all components of the library are included even if you only used a few.

**Comment by syrys** [comment]
@RoxKilly thanks a lot, that helped me. I didnt end up using that lib, but i got the gist of it :D 

On slightly similar note, im now having another similar issue. I want to use a JS file that was written outside of angular 2 (lets just say it has some global helper functions, or something similar to jQuery). I would like to somehow attach this js file to the page, and make use of the available functions (globally available?) within my angular 2 app. Can this be done easily?

Sake of argument, lets say the js file looks like this
````
// Location: /src/client/assets/cool.js
alert('this is cool'); //this should trigger immediately
function myCoolFunc(){ alert('this is a cool function'); } //this triggers when called
````

I tried adding the following to `project.config` file:
````
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      {src: `${this.APP_SRC}/assets/cool.js`, inject: true, vendor: false}
    ];
````
After that, if i run a `build.dev` or `npm start`, i see the resulting index.html file has a script tag that corresponds to the `cool.js` and its linked correctly to the file. However, if i open up the console on the page (after running `npm start`), the function `myCoolFunc` is not defined, and the first alert does not trigger.

Its a bit strange to me, the JS file is 'attached' but the code isnt being executed. Does this have something to do with how system js work (im not very familiar with it)?

Cheers.

**Comment by syrys** [comment]
Ah, never mind, i take my last post back. i did something wrong on my end. :D
