### ISSUE TITLE
Upgraded Node.js to 6.9.1 - npm start throwing error

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1518]
Hello,

npm start works fine with Node.js 4.6.1, I just upgraded to 6.9.1 and I am getting an error

(node:6200) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined

[10:40:05] Starting 'serve.dev'...
[10:40:05] Starting 'build.dev'...
[10:40:05] Starting 'build.assets.dev'...
[10:40:06] Finished 'build.assets.dev' after 1.03 s
[10:40:06] Starting 'build.fonts'...
[10:40:06] Finished 'build.fonts' after 293 ms
[10:40:06] Starting 'build.html_css'...
[10:40:12] Finished 'build.html_css' after 5.17 s
[10:40:12] Starting 'build.js.dev'...
[10:40:18] Finished 'build.js.dev' after 6.78 s
[10:40:18] Starting 'build.index.dev'...
[10:40:19] gulp-inject 2 files into index.html.
[10:40:19] gulp-inject 3 files into index.html.
(node:2288) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined

npm run serve.prod works fine..

I have sync'd up Angular-seed on Oct 3rd

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)```

**Current behavior**
<!-- Describe how the bug manifests. -->
Upgraded Node.js to 6.9.1 and npm to 3.10.8
**Expected behavior**
<!-- Describe what the behavior would be without the bug. -->
npm start should build the dev scripts and launch the application
**Minimal reproduction of the problem with instructions**
Upgrade Node.js to 6.9.1 and 3.10.8 and test npm start
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem.
-->

**What is the motivation / use case for changing the behavior?**
I was using Node 4.6.1, wanted to upgrade to latest version to use latest features
<!-- Describe the motivation or the concrete use case -->

**Please tell us about your environment:**
Windows 10, Chrome, Node.js 6.9.1 , npm 3.10.8
<!-- Operating system, IDE, package manager, HTTP server, ... -->

* **Angular Seed Version:** 2.0.X - 2.0.0
<!-- Check which is the hash of the last commit from angular-seed that you have locally -->

* **Node:** `node --version` = 6.9.1

**Comment by mgechev** [comment]
The current master works for me with node 6.9.1.

**Comment by mgechev** [comment]
@skolli853780 the problem doesn't come from the node version. You need to take a look which promise is being rejected due to invocation of the `replace` method of identifier which has value `undefined`.
