### ISSUE TITLE
System.registerDynamic is not a function

### ISSUE THREAD

**Issue by albertosetim** [mgechev/angular-seed#1524]
hey there, i have a problem using  npm run serve.prod.. always  in the browser console is a error:
**System.registerDynamic is not a function**
![image](https://cloud.githubusercontent.com/assets/17254772/19630821/1a46d752-998a-11e6-949c-57d376b58bfb.png)

**Comment by mgechev** [comment]
I cannot reproduce the issue. Most likely you've introduced a dependencies which uses system module format. Since we want to reduce the bundle size in the production build we don't have systemjs there.

**Comment by Christian-Yang** [comment]
@albertosetim     
How is the final solution?

I also have the same problem here
