### ISSUE TITLE
use Config.APP_BASE so that it's configurable

### ISSUE THREAD

**Issue by henryoh007** [mgechev/angular-seed#1526]
I am a bit new and want to add another item to the router. U are presently have routing to the Home and About menu item and pages. I would like to add a new page on the seed. It is a bit ambiguous in how that is accomplished  I need to configure ...the APP_BASE for the routing ?? 
Please point me to anywhere that has a good tutorial on this tool that you are using for the routing configuration.  Please any links to how this is accomplished and or advise. Please let me know. 

Thanks a ton

**Comment by mgechev** [comment]
Take a look at this article http://thelillysblog.com/2016/10/08/registration-form-with-angular-seed/. Good luck!
