### ISSUE TITLE
Recommend removing clean.ts in favor of del plugin

### ISSUE THREAD

**Issue by dlabaj** [mgechev/angular-seed#1527]
[ X] feature request

**Current behavior**
Currently there is a clean.ts script that is being maintained by the angular-seed project.  Recommending that we may want to remove it and use del npm plugin instead to cut down on maintenance going forward.

**Expected behavior**
Recommend updating the seed project to use del npm package below:

del npm plugin - https://www.npmjs.com/package/del
del files and folders example - https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

**Comment by mgechev** [comment]
We were using del in the past but it doesn't provide big enough abstraction on top of rimraf in order to switch to it and introduce additional dependency (it relays on rimraf).
