### ISSUE TITLE
LESS Support

### ISSUE THREAD

**Issue by oferze** [mgechev/angular-seed#1528]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
No support for LESS

**Expected behavior**
Support for LESS

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
There already is support for SASS; LESS is another popular one and I'm suggesting adding support for it too. [There is an old rejected PR](https://github.com/mgechev/angular-seed/pull/104) that introduced this; the reason for rejection at the time was not willing to be opinionated about technologies to be used. But SASS is one of them, so I believe a revisit would be worthwhile. Happy to implement it myself once I get the green light that such support for LESS will be merged to master eventually.

**Please tell us about your environment:**
N/A

* **Angular Seed Version:** 2.0.1

* **Node:** `node --version` = N/A

**Comment by mgechev** [comment]
This is outside the scope of thr seed project, even Sass wasn't planned initially but there was huge demand for it.

Since angular-seed is quite extensible, you can add Less support yourseld inside tools/tasks/project.
