### ISSUE TITLE
Minification in angular2-seed

### ISSUE THREAD

**Issue by harishrohokale** [mgechev/angular-seed#1529]
Hi All,

I am using angular2-seed from last 6 months. I just wanted to know the task for minification like scss, css, ts, etc. 

Can someone help on this?

**Comment by RoxKilly** [comment]
If you use one of the production builds, such as `build.prod`, `serve.prod` or `build.prod.exp`, your styles will be minified as part of the `build.html_css` task [as seen here](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/build.html_css.ts#L65)

**Comment by TheDonDope** [comment]
Thanks @RoxKilly
