### ISSUE TITLE
External css files are not getting bundled into main.css - Prod build - latest angular-seed

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1532]
Hello,

I am trying to get the latest angular-seed code (last sync up was on Oct 3rd)..  for some reason, external scripts are not getting bundled into main.css file with Prod build. It was working fine before 

Has anyone tried to integrate external scripts with the latest angular-seed code?

**I'm submitting a ...**  (check one with "x")

```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I am using external css files - PrimeNG and Ultima, these files are not getting bundled into main.css with the latest Angular seed code

**Expected behavior**
External scripts are bundled into main.css

**Minimal reproduction of the problem with instructions**
Using the latest angular-seed , add external scripts and see if it is getting bundled into prod build main.css

**What is the motivation / use case for changing the behavior?**
Getting the latest angular-seed code

**Please tell us about your environment:**
Chrome, Windows 10, 

- **Angular Seed Version:** 2.0.X 
  2.1.0
  
  
- **Node:** `node --version` = 6.9.1

**Comment by mgechev** [comment]
Would you share the content of your `project.config.ts` file? You need to declare the external CSS files there. In case you're using third-party components, their CSS should be automatically bundled if they have proper script references to it.

**Comment by skolli853780** [comment]
Please find the project.config.ts code below..

This was working before with the code I sync'd beginning of this month, I am having issues with latest seed code

import { join } from 'path';

import { SeedConfig } from './seed.config';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

    FONTS_DEST = `${this.APP_DEST}/fonts`;

    FONTS_SRC = [
      `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/fonts/**`,
      `${this.APP_SRC}/libs/ionicons-2.0.1/**`
    ];

  constructor() {
    super();
    this.APP_TITLE = '';

      this.SYSTEM_CONFIG_DEV.paths['primeng'] =
      `${this.APP_BASE}node_modules/primeng/primeng`;

      this.SYSTEM_BUILDER_CONFIG.packages['primeng'] = {
          main: 'primeng.js',
          defaultExtension : 'js'
      };

    /* Enable typeless compiler runs (faster) between typed compiler runs. */
    // this.TYPED_COMPILE_INTERVAL = 5;

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
        {src: 'primeui/primeui-ng-all.min.css', inject: true},
      {src: 'primeui/primeui-ng-all.min.js', inject: 'libs'},
      { src: 'primeng/resources/primeng.min.css', inject: true }


      // inject into css section

  ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      {src: `${this.APP_SRC}/assets/js/charts.min.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/assets/js/moment.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/assets/js/fullcalendar.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/assets/js/quill.min.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/assets/js/jquery.deps.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/assets/css/main.css`, inject: true, vendor: false},

      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/layout.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/nanoscroller.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/ripple.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/swipe.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/theme/theme-indigo.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/css/layout-indigo.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/css/animate.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ionicons-2.0.1/ionicons.min.css`, inject: true, vendor: false},


// {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
    ];

    /* Add to or override NPM module configurations: */
    // this.mergeObject(this.PLUGIN_CONFIGS['browser-sync'], { ghostMode: false });
  }

}

**Comment by skolli853780** [comment]
Did you get a  chance to reproduce this issue?

**Comment by skolli853780** [comment]
As soon as I revert back the build.html_css changes , css files are getting bundled

**Comment by mgechev** [comment]
What changes did you do there?

**Comment by skolli853780** [comment]
I have reverted back build.html_css changes to Sep10 commit..

https://github.com/mgechev/angular-seed/blob/791b8103f500c18da3eea7c48ee0ebf7be5d501c/tools/tasks/seed/build.html_css.ts

**Comment by skolli853780** [comment]
Yesterday Valentin fixed external css function.. I will try it again..

https://github.com/mgechev/angular-seed/commit/e877f6c482ec0b68ef5076b174d2cfbe669f9cc6

if you look at the fix, getexternalcss was processing scss files, that has been fixed.. hopefully it will work for me now.. I will keep you posted

**Comment by skolli853780** [comment]
Thanks to Valentin.. external css is getting injected now.. but couple of things I have noticed

1) main.css is not a minified version.. looks like a regular css file
2) build.fonts is removed (not sure why) in the latest prod build section of gulpfile.ts - because of which external fonts are not getting copied to dist/prod folder.. I have fixed it in my local version.. now external fonts are getting copied in my local version

Thanks
SK
