### ISSUE TITLE
Injecting `MdDialog` at app module level results in error: `No component factory found for MdDialogContainer`

### ISSUE THREAD

**Issue by sidewaiise** [mgechev/angular-seed#1535]
**I'm submitting a 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When trying to inject MdDialog at app.module level, we get an error that prevents the app from running:

`all:60 Error: Error: Unexpected value 'MdDialog' imported by the module 'AppModule'(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"`

**Expected behavior**
The dialog should work.

**Minimal reproduction of the problem with instructions**
if you have an angular 2 app structure with app.module, inject MdDialog into the app module as an import. Then implement MdDialog as shown in the example repository: https://github.com/angular/material2/tree/master/src/demo-app/dialog

**What is the motivation / use case for changing the behavior?**

For the module to behave as the docs/examples show it should

**Please tell us about your environment:**

Mac OSX, VSCode, npm, gulp

* **Angular Seed Version:** 2.0.X

2.0.1

* **Node:** `node --version` = 6.0.0

**Comment by mgechev** [comment]
Would you upload the code that doesn't work on GitHub so I can take a look at it? This error [is quite common](https://www.google.com/search?q=Unexpected+value+%27+imported+by+the+module&oq=Unexpected+value+%27+imported+by+the+module&aqs=chrome..69i57.3325j0j1&sourceid=chrome&ie=UTF-8&safe=high) so it's very likely to not be a problem related to the seed.
