### ISSUE TITLE
Why aren't the tests picking up errors that are introduced by the latest @angular/*?

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular-seed#1538]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Clone repo and run `npm run build.prod`

**Expected behavior**

The project Would build Just fine
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Vscode

* **Angular Seed Version:** 2.0.X

* **Node:** `node --version` =

**Comment by mgechev** [comment]
What errors should the build pick?

**Comment by sfabriece** [comment]
What I mean is that because angular 2.1.1 was causing errors, at least from what I gathered.  Shouldn't these have been picked up by the builds. Unless the dependencies were cached meaning that the version on angular was the previous one, which worked just fine.  Sorry for the long explanation.

**Comment by mgechev** [comment]
The errors with the AoT compiler are fixed now so the problems are no longer reproducible :-).

**Comment by sfabriece** [comment]
I was thinking that this would be a preventive measure to catch regressions in the future.

**Comment by mgechev** [comment]
A good way to prevent them is to change Angular's version to a specific version (i.e. 2.1.1 instead of ~2.1.1) and on each release run a set of tests. This seems to work so I'll consider it for future versions.
