### ISSUE TITLE
Strict CSP (Content-Security-Policy)

### ISSUE THREAD

**Issue by TomJahncke** [mgechev/angular-seed#1539]
Is it possible to use strict CSP with angular 2?  To turn on CSP (for experimentation) in the seed application I added the following line to the head of the index.html:

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'">
```

**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Add 

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'">
```

to the index.html in the head section and the application errors out loading in the browser.  Initially due to unsafe-inline, I believe if I address those errors I will then get some unsafe-eval errors.  

**Expected behavior**
Support strict CSP with the seed project.  (Maybe just add information to the Wiki on how to do this.)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Add <meta http-equiv="Content-Security-Policy" content="default-src 'self'"> to the head of the index.html

**Please tell us about your environment:**
Windows 7, Webstore (2.2.4), npm / systemJs, tomcat (through Spring Boot)
- **Angular Seed Version:** 2.0.X
  Current (from 10/19/2016)
- **Node:** `node --version` =
  4.5.0

**Comment by mgechev** [comment]
Hey @TomJahncke. The seed supports strict CSP apps thanks to the AoT support. In development you don't have to enable it, since you don't have to use strict CSP but if you're planning to work on a Chrome extension, for instance, you can use `npm run build.prod.exp` in order to get your source precompiled, this way Angular won't have to access `eval()`.

**Comment by ComFreek** [comment]
[index.html @ line 30](https://github.com/mgechev/angular-seed/blob/cb0ef80427b787064720335b5e13bf8bef75f4a4/src/client/index.html#L30) contains an inline script (`function module() {}`). Where would be the best alternative place for this?

**Comment by whobeika** [comment]
Why don’t you put that in an external JS file instead of inlining it...
