### ISSUE TITLE
Angular routing doesn't work when URL is directly visited with appbase defined

### ISSUE THREAD

**Issue by alan12111** [mgechev/angular-seed#1540]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Entering Url of page will not render unless clicked on a link with app base path defined
**Expected behavior**

Page must render regardless of url or clicking
**Minimal reproduction of the problem with instructions**
create an app base defined on run time
then go to the about
message:
Cannot GET /customPath/about

**What is the motivation / use case for changing the behavior?**

To have the basic functionality working with a base path defined
**Please tell us about your environment:**

Mac, Chrome
- **Angular Seed Version:**
  
  2.1.0
- **Node:** `node --version` =
  6.9.0

**Comment by TheDonDope** [comment]
How do you serve your application? With a seed provided task, or do you deploy, say your `/dist/prod` build to a nginx webserver or something? If the lather is the case: you need to configure your webserver accordingly, it is not a seed issue.
