### ISSUE TITLE
Unable to include Bootstrap SASS ( scss files) with Angular Seed project

### ISSUE THREAD

**Issue by hbweb** [mgechev/angular-seed#1542]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Hello. I was just wonder if anyone come across the same issue. I was not be able to use Boostrap Sass into this project atm.

**Expected behavior**
It should works with sass library

**Minimal reproduction of the problem with instructions**
1. Install bootstrap sass package via npm `npm install bootstrap-sass --save`
2. Change project.config.ts as below to include bootstrap scss file
```
import { join } from 'path';

import { SeedConfig } from './seed.config';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    this.APP_TITLE = 'Home Office';

    // SCSS supported
    this.ENABLE_SCSS = true;

    /* Enable typeless compiler runs (faster) between typed compiler runs. */
    // this.TYPED_COMPILE_INTERVAL = 5;

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'lodash/lodash.min.js', inject: 'libs'},
      {src: 'bootstrap-sass/assets/stylesheets/_bootstrap.scss', inject : true}
  
    ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false}
      // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
    ];

    /* Add to or override NPM module configurations: */
    // this.mergeObject(this.PLUGIN_CONFIGS['browser-sync'], { ghostMode: false });
    
  }

}
```

Please note that lodash module loads fine.. it only breaks when we add the .scss bit.

3.  Run `npm start`

4. Error message

```
(node:5272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined
```

**What is the motivation / use case for changing the behavior?**
none

**Please tell us about your environment:**
NPM (3.10.8) , Windows 10 (win32, x64), Node (v6.9.1)

* **Angular Seed Version:** 2.0.X

* **Node:** `node --version` = 0.0.0 (Clone Angular Seed version on October 25th 2016 )

Many thanks

**Comment by admosity** [comment]
This is the injection configuration which is the wrong place to put that. 

You have to go into your sass file where you would like to include bootstrap. I'm assuming you want to include it on the app level, so if this is a fresh seed, you would put it in:

`src/client/css/main.scss`

and have an import statement like so:

```scss
@import "bootstrap-sass/assets/stylesheets/bootstrap";
```

Alternatively, you can modify your project settings to add bootstrap-sass to your gulp-sass includePaths:

`node_modules/bootstrap-sass/assets/stylesheets`

for a cleaner import format.

**Comment by mgechev** [comment]
@admosity thanks for the response!

**Comment by hbweb** [comment]
Thank you guys.
