### ISSUE TITLE
PROD mode is not working with SCSS Enabled

### ISSUE THREAD

**Issue by harishrohokale** [mgechev/angular-seed#1546]
Hi All,

I have enabled prod mode and also enabled scss. SCSS works fine if i build in dev mode. But in prod mode it is not able to find css or scss file for each component which is declared in stylesUrl.
Below is the console error : 
zone.js?1477508260765:355 Unhandled Promise rejection: Failed to load http://localhost:3000/app/login/login.component.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load http://localhost:3000/app/login/login.component.css undefined

I have renamed my file extensions with scss to enable sass. 

Can someone please help me on this? I tried the same with angular-seed the same is facing over there too.

**Comment by mgechev** [comment]
Would you upload a minimal demo in order to be able to debug & fix it as quickly as possible?

**Comment by harishrohokale** [comment]
I have made changes in below files : 

1. Seed.config.ts for ENABLE_SCSS = argv['scss'] || true;
2. build.html_css.ts for const isProd = Config.ENV === 'dev';
3. renamed all css files for each component to scss

[test.zip](https://github.com/mgechev/angular-seed/files/555642/test.zip)

Below is the screenshot of error : 
![screen shot 2016-10-27 at 5 09 42 pm](https://cloud.githubusercontent.com/assets/6389000/19765930/b8b24148-9c68-11e6-8e59-281c35e32480.png)

Hope this is enough information to help you to debug.

**Comment by harishrohokale** [comment]
Waiting for your response.

**Comment by mgechev** [comment]
For me it works ok, only `main.css` is not being injected, on any reason.

**Comment by mgechev** [comment]
Actually there's nothing to push to a separate branch - just rename all the `*.css` files to `*.scss` and run `npm run build.prod -- --scss`.

**Comment by harishrohokale** [comment]
Working for PROD. Thanks.
One question can we use the same behaviour in Dev mode? If yes then how?

**Comment by AdrianAgui** [comment]
I have the same problem (compile in dev is fine but build fails in prod), in my case the error is the next:

![image](https://user-images.githubusercontent.com/18145972/27628651-0326eac0-5bf0-11e7-98de-f8ef97d1deb2.png)

I realized the @media from sass files cause this error and i dont know how can i fix it, can anyone help me? @mgechev 

Thanks.
