### ISSUE TITLE
unable to import/use jQuery

### ISSUE THREAD

**Issue by syrys** [mgechev/angular-seed#1547]
Yes, yes, i know, we shouldn't be using jquery. But i have a specific need to use it. 

Im unable to build production version if i use jquery within my app. `npm start` works just fine, but `npm run build.prod` crashes and dies.

Lets say for sake of simplification, i want to `console.log` the `body` or add a class name to the `body` tag. Here are the steps i took:

1) `npm install jquery --save`
2) edit `project.config.ts` and add the following:
````
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'}
    ];
````
3) edit your desired component, implement `OnInit` (import it), and add a `ngOnInit` function.

4) within the `ngOnInit`, add the following line: `console.log($('body'));` Note: im NOT importing anything.

5) Run `npm start`, and all works as expected, and console has the correct log.

6) Run `npm run build.prod`, and it will crash with the error: `__COMPONENT_PATH__\home.component.ts(21,17): error TS2304: Cannot find name '$'.`

7) try adding `import * as $ from "jquery";` to the top of the page (from step 4), and run `npm run build.prod` again, and you will see the output: `__COMPONENT_PATH__\home.component.ts(2,20): error TS2307: Cannot find module 'jquery'.`

What am i doing wrong here? Is there a way to tell typescript to ignore these errors? Because im assuming it will work just fine so long as typescript actually compiles the rest of the code.

Any thoughts?

**Comment by syrys** [comment]
Please note, the steps i have taken are exactly what was explained here: https://github.com/mgechev/angular-seed/wiki/Add-external-scripts-and-styles

However, the wiki doesnt go into detail regurding how to make use of the imported libraries (specially if they arnt written in typescript).

There are couple of scenarios of libraries i can think of, would be ideal if someone can add or clarify some info on how to use them.

1. Libraries with global Objects. Like jQuery (or lodash etc...), they add a global window object that you can access from anywhere.
2. Libraries that add global functions. I dont know if they exists nowdays, but what if a simple JS file/library exists that makes available some helper functions that you can call globally. Or prototypes to existing objects.
3. Plugins/addons to other libraries. Great example would be jQuery Plugins. and they enable things like: `$('#my-element').doSomethingCool()`;

**Comment by mgechev** [comment]
You should get familiar with how [TypeScript ambient type definitions work](https://www.typescriptlang.org/docs/tutorial.html).

**Comment by amitgaikwad712** [comment]
@syrys you should go with only one step then it will work jquery for you.
Add following line before @Component decorator : 
let $ : any
