### ISSUE TITLE
Missing module - AppModuleNgFactory - Or not longer necessary

### ISSUE THREAD

**Issue by martingula** [mgechev/angular-seed#1557]
Issue in "main-prod.ts"

import { AppModuleNgFactory } from './app.module.ngfactory';

app.module.ngfactory.ts file doesn't exist.

What am I missing?

**Comment by mgechev** [comment]
Yes, it doesn't. It's used after AoT. You can read more about it [here](http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/).

**Comment by martingula** [comment]
Thank you great article, really appreciate it.
