### ISSUE TITLE
feature request: serve.prod.exp

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular-seed#1559]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

we can't serve the AOT version of the app

**What is the motivation / use case for changing the behavior?**

making sure everything works before pushing to production

**Please tell us about your environment:**

* **Angular Seed Version:** 2.1.X

latest version of seed: ce1f9f8
* **Node:** `node --version` = 7.0.0

**Comment by mgechev** [comment]
Makes sense. The feature will require adding a task to gulpfile.ts, quite similar to serve.prod, and alias in package.json. Would you want to open a PR with the feature?

**Comment by sfabriece** [comment]
I'll give it a go.
