### ISSUE TITLE
npm error while trying to install ionic cordova .. help please!!

### ISSUE THREAD

**Issue by AyaMaher7** [mgechev/angular-seed#1562]
c:\>npm install -g ionic cordova
C:\Users\Aya\AppData\Roaming\npm
`-- ionic@2.1.4

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Aya\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\Aya\AppData\Roaming\npm\node_modules\.staging\abbrev-bbc7a320
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Aya\AppData\Roaming\npm\node_modules\.staging\abbrev-bbc7a320' -> 'C:\Users\Aya\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Aya\AppData\Roaming\npm\node_modules\.staging\abbrev-bbc7a320' -> 'C:\Users\Aya\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\npm-debug.log

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
