### ISSUE TITLE
PrimeNG production build with primeng.js not working - Wiki

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1563]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Production build - I need to add PrimeUI js file instead of Primeng to make it work.. I am getting an error "Ultima is not defined" when I inject PrimeNG/PrimeNG.js.. something is not correct when it is bundling using Production build

**Expected behavior**
Latest PrimeNG does not depend on PrimeUI js file.. so it should work with Primeng js file

**Minimal reproduction of the problem with instructions**
   // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      { src: 'primeng/resources/primeng.min.css', inject: true },
      {src: 'primeui/primeui-ng-all.min.js', inject: true}

      // inject into css section

  ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      {src: `${this.APP_SRC}/assets/css/main.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/layout.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/nanoscroller.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/ripple.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/js/swipe.js`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/theme/theme-purple-cyan.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/css/layout-purple-cyan.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ultima-ng-1.0.2/layout/css/animate.css`, inject: true, vendor: false},
      {src: `${this.APP_SRC}/libs/ionicons-2.0.1/css/ionicons.min.css`, inject: true, vendor: false},

Instead of PrimeUI js file, If I give primeng js file, it works in Dev build but not in Production build

**What is the motivation / use case for changing the behavior?**
Use Primeng/Primeng js file instead of PrimeUI js file as Primeng does not depend on PrimeUI anymore 

**Please tell us about your environment:**

Chrome, NodeJS, Ultima, PrimeNG

* **Angular Seed Version:** 2.0.X

* **Node:** `node --version` = 7.0

**Comment by skolli853780** [comment]
Followed Wiki https://github.com/mgechev/angular-seed/wiki/Add-PrimeNG

**Comment by skolli853780** [comment]
I would like to use Primeng.js

// Add NPM third-party libraries to be injected/bundled.
this.NPM_DEPENDENCIES = [
...this.NPM_DEPENDENCIES,
// {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
// {src: 'lodash/lodash.min.js', inject: 'libs'},
{ src: 'primeng/resources/primeng.min.css', inject: true },
{src: 'primeng/primeng.js', inject: true}

  // inject into css section
];

PrimeNG.js has export statements for the components that are in another folder.. so I think there is an issue with Production build when PrimeNG.js is injected

**Comment by mgechev** [comment]
Just like in `SYSTEM_CONFIG_DEV` you need to add reference to primeng in `SYSTEM_BUILDER_CONFIG`.

Take a look at the [config file and the inline docs](https://github.com/mgechev/angular-seed/blob/master/tools/config/seed.config.ts#L388-L450).

**Comment by skolli853780** [comment]
Project.config.ts     

this.SYSTEM_CONFIG_DEV.paths['primeng'] =
      `${this.APP_BASE}node_modules/primeng/primeng`;

      this.SYSTEM_BUILDER_CONFIG.packages['primeng'] = {
          main: 'primeng.js',
          defaultExtension : 'js'
      };

**Comment by skolli853780** [comment]
I have tried different things..
this is the only thing that is working..
not sure why it is not working with primeng/primeng.js 

  // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      { src: 'primeng/resources/primeng.min.css', inject: true },
      {src: 'primeui/primeui-ng-all.min.js', inject: true}

      // inject into css section

  ];

**Comment by mgechev** [comment]
Ok, I'm reopening the issue and will give it a try in the next days.

**Comment by skolli853780** [comment]
Thank you..

**Comment by omerfarukyilmaz** [comment]
May I ask, why do you need `primeui-ng-all.min.js` or `primeng.js`?

I am asking because I too use PrimeNG in one of our projects and have had no problems in dev or production build. `primeui` was removed from dependencies a while ago and `primeng.js` is not needed in `NPM_DEPENDENCIES `

You can check out the [PrimeNG Setup](http://www.primefaces.org/primeng/#/setup) link for the official documentation (included systemjs setup).

### Alternative

I personally (different from the official PrimeNG documentation) have no changes in `SYSTEM_CONFIG_DEV` nor `SYSTEM_BUILDER_CONFIG`. I simple use it injecting only the css as so

    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      { src: 'font-awesome/css/font-awesome.min.css', inject: true },
      { src: 'primeng/resources/themes/bootstrap/theme.css', inject: true },
      { src: 'primeng/resources/primeng.min.css', inject: true },
      { src: 'jquery/dist/jquery.min.js', inject: 'libs' },
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

and it works, both for build.dev and build.prod. Again, I do not change anything for `SYSTEM_CONFIG_DEV` nor `SYSTEM_BUILDER_CONFIG` whether for `paths` or `packages`.

**Comment by skolli853780** [comment]
If I don't give js file reference I get an error..In addition to PrimeNG, we are using Ultima theme that has .js files.. I think javascript of Ultima theme looks for PrimeNG/PrimeUI js file

layout.js?1478009993283:371 Uncaught ReferenceError: $ is not defined(…)
nanoscroller.js:12 Uncaught ReferenceError: jQuery is not defined(…)
ripple.js:1 Uncaught ReferenceError: $ is not defined(…)
swipe.js:14 Uncaught ReferenceError: jQuery is not defined(…)

**Comment by skolli853780** [comment]
Cagatay from PrimeTek confirmed that PrimeNG does not need PrimeUI but the Ultima theme we are using depends on jquery.. so I need to give Primeui-all-ng.min.js
