### ISSUE TITLE
Running Chrome debugger in VSCode

### ISSUE THREAD

**Issue by variuse** [mgechev/angular-seed#1564]
I was trying to get Chrome debugger in VSCode running with angular-seed and there's seem to be a problem with paths when generating sourcemaps. Using a sourceMapPathOverrides works fine, but it could also be fixed in build.js.dev

See here for a solution: https://github.com/Microsoft/vscode-chrome-debug/issues/272

**Comment by mgechev** [comment]
Thanks for the issue and pointing out the solution. I'll push the `sourceMapPathOverrides` to master by the end of the day.

**Comment by savcha** [comment]
Removing .vscode from gitignore is going to make it difficult to merge because everyone's configuration is different. 

Would it be better to put this as a sample configuration perhaps somewhere in the tools dir?
