### ISSUE TITLE
SBE/BDD Testing

### ISSUE THREAD

**Issue by pete2014** [mgechev/angular-seed#1565]
**I'm submitting a ...**  
```
[x] feature request
```

**Current behavior**
Project only has unit testing.

**Expected behavior**
Would like to see cucumber based SBE testing using feature files, etc.

**What is the motivation / use case for changing the behavior?**
Would like to use this seed in a calculation heavy project which will require SBE type testing

**Please tell us about your environment:**
Windows, VisualStudio 2015

* **Angular Seed Version:** 2.0.X
dcedc18bbccaf73266deaba080956ef111e9f158

* **Node:** 
`node --version` = 7.0.0

**Comment by mgechev** [comment]
Hey @pete2014, thanks for giving the seed a try! BDD is already possible with jasmine. SBE is another great feature that has plenty of use cases in development. Although it's a nice feature, I'd prefer to keep it out of the seed for now. We want to satisfy the requirements of most developers and in the same time keep the seed as minimalistic as possible.

As part of your `tools/tasks/project` directory you can introduce another task which invokes cucumber and implements your SBE features. This way you'll be able to easier update your seed by using `git pull upstream master` without introducing merge conflicts, and we will be able to keep the seed as minimalistic as possible.

**Comment by mpetkov** [comment]
@pete2014 - Were you able to integrate cucumber into the seed?  I was wondering if there is an example somwehere on github that uses it with this seed.

**Comment by mpetkov** [comment]
@pete2014 and @mgechev - After spending some more time on this it looks like for some reason the app doesn't start up when using cucumber but it does when using it with jasmine/protractor as is.   The only way I could get it to work is to run **serve.e2e** before I execute the tests like it says in the instructions.  However this will not allow the project to be tested with continous integration.  What am I missing here?
