### ISSUE TITLE
Angular Universal support

### ISSUE THREAD

**Issue by koodikindral** [mgechev/angular-seed#1566]
Are there any plans of introducing Angular Universal into this project? 
From SEO perspective, it would be great as most of the crawlers cannot index the sites, which have been created with Angular.

**Comment by webia1** [comment]
Most of the crawlers can index almost everything in angular2 apps but I've nothing against server side rendering, solely for performance reasons,..  Therefore +1

**Comment by mgechev** [comment]
Universal requires introducing a BE infrastructure (not only the dev servers we have) and brings another set of problems which require implementation, maintenance and documentation.

I'd prefer to keep the project as minimalistic as possible and do not introduce Universal at this point.

Any Angular application developed with the seed, or not, can be easily deployed to a server with Universal installed. The only change required will be another main file with slightly different bootstrap processes.

**Comment by patrickmichalina** [comment]
@koodikindral been working on a universal starter project, hope it helps!

https://github.com/patrickmichalina/fusebox-angular-universal-starter
