### ISSUE TITLE
ENV property deprecation warnings

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#1567]
Using the latest seed, I'm seeing numerous warnings like this:
`Warning: the "ENV" property is deprecated. Use "BUILD_TYPE" instead.`

I've done a global search through everything under /tasks and all I can find is:
```
Search "ENV" (5 hits in 4 files)
  tools\config\seed.config.ts (2 hits)
	Line 65:   get ENV() {
	Line 66:     util.log(util.colors.yellow('Warning: the "ENV" property is deprecated. Use "BUILD_TYPE" instead.'));
  tools\env\dev.ts (1 hit)
	Line 4:   ENV: 'DEV'
  tools\env\prod.ts (1 hit)
	Line 4:   ENV: 'PROD'
  tools\utils\seed\template_locals.ts (1 hit)
	Line 38:     ENV_CONFIG: JSON.stringify(Object.assign(baseConfig, config))
```

So basically I can't tell what is trying to use `Config.ENV` and generating these warnings. Obviously, I can omit the warnings by just commenting out the log message, but I didn't really want to do that without understanding what's trying to use `ENV` in the first place. It _seems_ like nothing is using it, so the fact that the warnings are still appearing is making me think I'm missing something.

**Comment by brian428** [comment]
To add: just to see what happens, I commented out the `get ENV()` method in `seed.config.ts`, and everything still seems to compile and run correctly. Which seems to make this even more baffling.

**Comment by webia1** [comment]
https://github.com/mgechev/angular-seed/pull/1519

**Comment by mgechev** [comment]
The lodash templetes are accessing ENV which causes the warnig. The ENV property together with the deprecation warning will go away in the next few days.
