### ISSUE TITLE
Automatic messages filling with i18n does not work

### ISSUE THREAD

**Issue by stojancveticanin** [mgechev/angular-seed#1573]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I am trying to set up i18n in my angular2 project. I set up everything as you describe but automatic `messages.xlf` generation returns me file without any "key". I even tried to clone your project but it is the same. I am running command `npm run i18n` to generate the `messages.xlf` file.

**Expected behavior**
On running command `npm run i18n` file `messages.xlf` should be generated with all "keys" that are marked with `i18n` tag in application.

**Please tell us about your environment:**
Windows 10, JetBrains WebStrom 2016.2.4

* **Angular Seed Version:** 2.0.1

* **Node:** `node --version` = 7.0.0

**Comment by fleske** [comment]
Same problem here, I used the guide for i18n from the wiki.
When I remove "src" from excluded in tsconfig.json it is being generated...but that is not a solution for the problem...

**Comment by ruffiem** [comment]
@stojancveticanin did you create the app.through.ts file to allow ng-xi18n to find your app entry point ? Information is standing at [Wiki page, step 8](https://github.com/mgechev/angular-seed/wiki/Enabling-Angular-i18n-native).

**Comment by stojancveticanin** [comment]
@ruffiem It works!!! Thank you very much! I don't know how I missed that step, maybe because it is after issues...

**Comment by ruffiem** [comment]
@stojancveticanin true, fixed in the wiki too. Thanks for pointing this 👍

**Comment by mgechev** [comment]
@ruffiem thanks for keeping it up to date!
