### ISSUE TITLE
Change Prod build base href

### ISSUE THREAD

**Issue by mikemichaelis** [mgechev/angular-seed#1575]
I would like to move my PROD build to a site with a base href of "PROD/".  I'm attempting to use the --base parameter on the gulp build.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting

**Current behavior**
update package.json w/ 
"build.prod": "gulp build.prod --color --env-config prod --config-env prod --build-type prod --base PROD/",

npm run build.prod

index.html base href properly set to "PROD/" but all references link references also prefixed with PROD/ producing get requests of:

PROD/PROD/main.css

**Comment by mgechev** [comment]
Use `npm run build.prod -- --base /PROD/` and it'll work for everything except `assets/data.json`.

**Comment by mikemichaelis** [comment]
Awesome, worked great!  I appreciate all the good hard work on this seed!

**Comment by bonaparte89** [comment]
I'm running into this issue as well... I'm able to start the application with npm start -- --config-env test, but now i of course want to build the application with this config as well... as soon as i do so i get some errors... I'm not sure what exactly I'm doing wrong here... changed my package.json build.prod to
"build.prod": "gulp build.prod --color --config-env prod --config-env test --config-env stage",

any ideas on this one? 
I run npm run build.prod -- --config-env stage
typeerror: path must be a string. received ['prod', 'test', 'stage, 'stage']

thanks
