### ISSUE TITLE
Multi-app production build error with shared files

### ISSUE THREAD

**Issue by 1thrasher** [mgechev/angular-seed#1579]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support reques
```

**Current behavior**
There are production build errors when attempting to utilize a shared multi-app:
```
[09:59:37] 'build.bundles.app' errored after 1.15 s
[09:59:37] Error on fetch for dist/tmp/app/shared/shared.module.js at file:///Users/me/home/github/angular-seed/node_modules/dist/tmp/app/shared/shared.module.js
	Loading dist/tmp/multiapp/app.module.js
	Loading dist/tmp/multiapp/main.js
	Error: ENOENT: no such file or directory, open '/Users/me/home/github/angular-seed/node_modules/dist/tmp/app/shared/shared.module.js'
    at Error (native)
```

**Expected behavior**
It should build without error.

**Minimal reproduction of the problem with instructions**
Create a multi-app that shares the `/src/client/app/shared` folder:
- `git clone --depth 1 https://github.com/mgechev/angular-seed.git`
- `cd angular-seed`
- `npm install`
- `cp -R src/client/app src/client/multiapp`
- `rm -rf src/client/multiapp/shared`
- Update line 11 of `src/client/multiapp/app.module.ts` to: 
```import { SharedModule } from '../app/shared/shared.module';```
- Update line 2 of `src/client/multiapp/app.component.ts` to:
```import { Config } from '../app/shared/index';```
- Update line 2 of `src/client/multiapp/home/home.component.ts` to:
```import { NameListService } from '../../app/shared/index';```
- Update lines 3 and 5 of `src/client/multiapp/home/home.component.ts` to:
```
import { SharedModule } from '../../app/shared/shared.module';
import { NameListService } from '../../app/shared/name-list/index';
```
- `npm start -- --app multiapp` (app runs correctly)
- `npm run build.prod -- --app multiapp` or `npm run build.prod.exp -- --app multiapp` (results in above error)

**What is the motivation / use case for changing the behavior?**
Utilize production builds for shared multi-apps.

**Please tell us about your environment:**
OSX, npm v3.10.8

* **Angular Seed Version:** `cd77885`
* **Node:** `node --version` = v6.9.1

**Comment by mgechev** [comment]
This issue is related to misconfigured `SYSTEM_BUILDER_CONFIG` but I'll take a look at it a bit later and tell you what changes you should make.

**Comment by markoddi01** [comment]
I'm having trouble doing a build to the prod file as well.

Do you have the same issue?

I recently cloned this seed app and here are the steps I did to recreate the bug.

**Steps**:
- I navigated to the dist/prod folder in git bash.
- Then I did npm run serve.prod and I got the below error.
- I havent touched the gulp file.
- When I do npm run start it works fine.
- But I need to do a prod build to go live

![gitbasherror](https://cloud.githubusercontent.com/assets/2556223/19949625/a95d0282-a14a-11e6-851f-d41a48f5956a.png)

Thank you in advanced

**Comment by mgechev** [comment]
Add this line to your `project.config.ts`:

```ts
this.SYSTEM_BUILDER_CONFIG.paths['dist/tmp/app/shared/*'] = 'dist/tmp/app/shared/*';
```
