### ISSUE TITLE
Issue when building to prod for live release

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1580]
Hi,

I recently cloned this app on the weekend and  I'm having trouble doing a build to the prod file.

Info 

- I navigate to dist/prod file and do npm run serve.prod
- I can build to dev fine and the app all works fine when serving to dev.
- I haven't touched the gulp file.
- I'm using node version 4.4.5.
- I'm using Angular 2 and Typescript.
- I haven't changed any of the tech.
- I'm using git bash and sublime IDE.

**Steps:**

- I navigate to dist/prod file
- I then run : npm run serve.prod
- Then I got this error below in the screen shot:

![gitbasherror](https://cloud.githubusercontent.com/assets/2556223/19950032/0d21438a-a14d-11e6-9a7e-eb2e14f24a23.png)

I'm looking to go live this weekend and wanted to push to my staging website a few times with a production build before then.

I'm not sure if I need to update the libraries or if theres a bug with gulp.
Do you have this same issue or anyone thats download this app.

I look forward to your responses.

Thank you in advance!

**Comment by mgechev** [comment]
You should run `npm run serve.prod` in the root of the project, not in `dist/prod`. An alternative of this is to:

```
npm install -g http-server
npm run build.prod
cd dist/prod
http-server .
```

**Comment by markoddi01** [comment]
Which folder do I run it from? /src?

**Comment by markoddi01** [comment]
I've tried running npm run serve.prod from /src and from /angular2-seed and it starts to build prod folder and then half way through stops and I get the same error

**Comment by mgechev** [comment]
```
git clone https://github.com/mgechev/angular-seed
cd angular-seed
npm i
npm run serve.prod
```

**Comment by markoddi01** [comment]
I have my own app build inside this structure

**Comment by mgechev** [comment]
This means you're not using angular-seed to build your app? In such case this doesn't seem like an issue related to this project.

**Comment by markoddi01** [comment]
I am using it

**Comment by markoddi01** [comment]
I've just added more website routes

**Comment by mgechev** [comment]
In such case:

> You should run npm run serve.prod in the root of the project...

Good luck!

**Comment by markoddi01** [comment]
when you mean root, which folder?
