### ISSUE TITLE
How can I update the type definitions in the app to accept Firebase type?

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1588]
How can I update the type definitions in the app to accept Firebase type?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by samuelfernandez** [comment]
I've updated the wiki at https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularFire2

**Comment by mgechev** [comment]
@samuelfernandez thanks for updating it out!
