### ISSUE TITLE
I have a few typescript errors, how can I turn typescript checker off when doing a build.prod?

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1589]
I have a few typescript errors, how can I turn typescript checker off when doing a build.prod?

**Comment by mgechev** [comment]
This is considered bad practice but you can take a look at [`--isolatedModules`](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by markoddi01** [comment]
I found out why the build.prod didn't work, its because I have typescript errors.
I will fix these eventually but is there an easy way e.g. in gulp to ignore typescript checking/linter on build.prod?

**Comment by markoddi01** [comment]
Thank you. "isolatedModules": true, worked. Yeah this will only be temporay
