### ISSUE TITLE
I'm having trouble added angular-google-maps to the project

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1590]
I'm in the file named: seed.config.js line: 370.

I'm trying to add "angular-google-maps" which is a node module.

I'm having trouble getting it working when I do a "serve.prod".

How would you go about adding angular-google-maps so that its included in the build?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by markoddi01** [comment]
Thanks. I've posted a comment in the room

**Comment by markoddi01** [comment]
No ones really responding in the room :(

**Comment by mgechev** [comment]
I'd recommend you to take a look at the docs instead. We're using SystemJS so this is a good start.
