### ISSUE TITLE
npm run build.prod failed

### ISSUE THREAD

**Issue by kahanu** [mgechev/angular-seed#1591]
Dev works fine, but I just tried building for production, and I got this error:

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
    1 verbose cli   'C:\\Users\\King\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'run',
    1 verbose cli   'build.prod' ]
    2 info using npm@3.9.2
    3 info using node@v4.4.5
    4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
    5 info lifecycle angular2-seed@0.0.0~prebuild.prod: angular2-seed@0.0.0
    6 silly lifecycle angular2-seed@0.0.0~prebuild.prod: no script for prebuild.prod, continuing
    7 info lifecycle angular2-seed@0.0.0~build.prod: angular2-seed@0.0.0
    8 verbose lifecycle angular2-seed@0.0.0~build.prod: unsafe-perm in lifecycle true
    9 verbose lifecycle angular2-seed@0.0.0~build.prod: PATH: C:\Users\King\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Websites\MEAN\brightonhallschool\schoolsite\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\PROGRA~1\CONDUS~1\DISKEE~1\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Git\cmd;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\King\AppData\Roaming\npm
    10 verbose lifecycle angular2-seed@0.0.0~build.prod: CWD: C:\Websites\MEAN\brightonhallschool\schoolsite
    11 silly lifecycle angular2-seed@0.0.0~build.prod: Args: [ '/d /s /c', 'gulp build.prod --color --config-env prod' ]
    12 silly lifecycle angular2-seed@0.0.0~build.prod: Returned: code: 1  signal: null
    13 info lifecycle angular2-seed@0.0.0~build.prod: Failed to exec build.prod script
    14 verbose stack Error: angular2-seed@0.0.0 build.prod: `gulp build.prod --color --config-env prod`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (C:\Users\King\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at EventEmitter.emit (events.js:172:7)
    14 verbose stack     at ChildProcess.<anonymous> (C:\Users\King\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at ChildProcess.emit (events.js:172:7)
    14 verbose stack     at maybeClose (internal/child_process.js:827:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    15 verbose pkgid angular2-seed@0.0.0
    16 verbose cwd C:\Websites\MEAN\brightonhallschool\schoolsite
    17 error Windows_NT 6.3.9600
    18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\King\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
    19 error node v4.4.5
    20 error npm  v3.9.2
    21 error code ELIFECYCLE
    22 error angular2-seed@0.0.0 build.prod: `gulp build.prod --color --config-env prod`
    22 error Exit status 1
    23 error Failed at the angular2-seed@0.0.0 build.prod script 'gulp build.prod --color --config-env prod'.
    23 error Make sure you have the latest version of node.js and npm installed.
    23 error If you do, this is most likely a problem with the angular2-seed package,
    23 error not with npm itself.
    23 error Tell the author that this fails on your system:
    23 error     gulp build.prod --color --config-env prod
    23 error You can get information on how to open an issue for this project with:
    23 error     npm bugs angular2-seed
    23 error Or if that isn't available, you can get their info via:
    23 error     npm owner ls angular2-seed
    23 error There is likely additional logging output above.
    24 verbose exit [ 1, true ]

I'm using Visual Studio Code and I'm getting a lot of [stylelint] messages.  I can't tell what they are referring to: 

    4:26473 ?  Expected single space before "}" of a single-line block (block-closing-brace-space-before) [stylelint]
    4:26475 ?  Expected newline after "}" (block-closing-brace-newline-after) [stylelint]
    4:26488 ?  Expected double colon pseudo-element notation (selector-pseudo-element-colon-notation) [stylelint]
    4:26494 ?  Expected single space before "{" (block-opening-brace-space-before) [stylelint]
    4:26496 ?  Expected single space after "{" of a single-line block (block-opening-brace-space-after) [stylelint]
    4:26504 ?  Expected single space after ":" with a single-line declaration (declaration-colon-space-after) [stylel
    4:26510 ?  Expected a trailing semicolon (declaration-block-trailing-semicolon) [stylelint]
    4:26510 ?  Expected single space before "}" of a single-line block (block-closing-brace-space-before) [stylelint]

I looked through all my code and it's formatted correctly.  Will style lint warning block a production build?

Any help in figuring out why my production build is failing, is appreciated.

BTW, I'm on a Windows 8.1 Pro machine.

**Comment by mgechev** [comment]
The problem is not in tslint, it's not in angular-seed neither. You can take a look [here](https://github.com/angular/angular-seed/issues/199) where someone has reported similar problem in [angular/angular-seed](https://github.com/angular/angular-seed).

**Comment by kahanu** [comment]
@mgechev your first link goes to an issue with "npm start".  My issue is with "npm run build.prod".  And I don't know if they are the same, but my warnings were for stylelint, not tslint.

BTW, I just cloned your seed project, and for the first time, it doesn't run using "npm start".  This is the debug log info:

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
    1 verbose cli   'C:\\Users\\King\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'start' ]
    2 info using npm@3.9.2
    3 info using node@v4.4.5
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info lifecycle angular-seed@0.0.0~prestart: angular-seed@0.0.0
    6 silly lifecycle angular-seed@0.0.0~prestart: no script for prestart, continuing
    7 info lifecycle angular-seed@0.0.0~start: angular-seed@0.0.0
    8 verbose lifecycle angular-seed@0.0.0~start: unsafe-perm in lifecycle true
    9 verbose lifecycle angular-seed@0.0.0~start: PATH: C:\Users\King\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\MEAN-Apps\angular-seed\node_modules\.bin;C:\Program Files\nodejs;C:\Users\King\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\King\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\PROGRA~1\CONDUS~1\DISKEE~1;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Git\cmd;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\dotnet;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\King\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
    10 verbose lifecycle angular-seed@0.0.0~start: CWD: C:\MEAN-Apps\angular-seed
    11 silly lifecycle angular-seed@0.0.0~start: Args: [ '/d /s /c', 'gulp serve.dev --color' ]
    12 silly lifecycle angular-seed@0.0.0~start: Returned: code: 1  signal: null
    13 info lifecycle angular-seed@0.0.0~start: Failed to exec start script
    14 verbose stack Error: angular-seed@0.0.0 start: `gulp serve.dev --color`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (C:\Users\King\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at EventEmitter.emit (events.js:172:7)
    14 verbose stack     at ChildProcess.<anonymous> (C:\Users\King\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at ChildProcess.emit (events.js:172:7)
    14 verbose stack     at maybeClose (internal/child_process.js:827:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    15 verbose pkgid angular-seed@0.0.0
    16 verbose cwd C:\MEAN-Apps\angular-seed
    17 error Windows_NT 6.3.9600
    18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\King\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
    19 error node v4.4.5
    20 error npm  v3.9.2
    21 error code ELIFECYCLE
    22 error angular-seed@0.0.0 start: `gulp serve.dev --color`
    22 error Exit status 1
    23 error Failed at the angular-seed@0.0.0 start script 'gulp serve.dev --color'.
    23 error Make sure you have the latest version of node.js and npm installed.
    23 error If you do, this is most likely a problem with the angular-seed package,
    23 error not with npm itself.
    23 error Tell the author that this fails on your system:
    23 error     gulp serve.dev --color
    23 error You can get information on how to open an issue for this project with:
    23 error     npm bugs angular-seed
    23 error Or if that isn't available, you can get their info via:
    23 error     npm owner ls angular-seed
    23 error There is likely additional logging output above.
    24 verbose exit [ 1, true ]
    
Any ideas?  My project works fine in dev mode.  I just can't build for production.

**Comment by mgechev** [comment]
Try the latest version of the project and this warning will be gone (although it won't bring any problems):

```
$ git clone --depth 1 https://github.com/mgechev/angular-seed.git
$ cd angular-seed

# install the project's dependencies
$ npm install
```

**Comment by kahanu** [comment]
I'll try it.  Also I looked at the error messages I'm getting in the console window, and I see two messages: 

    Octal literals are not allowed in strict mode

What does this mean?

**Comment by kahanu** [comment]
Ok, I fixed it.

I had:

    footer ul.navigation > li + li::before {
        padding: 0 5px;
        color: #ccc;
        content: "\00a0";
    }

... and I had to escape the content hex value to this:

    footer ul.navigation > li + li::before {
        padding: 0 5px;
        color: #ccc;
        content: "\\00a0";
    }

Sheesh.
