### ISSUE TITLE
Bug: Backslash in referenced styleUrls file cuts off the following style rules

### ISSUE THREAD

**Issue by jverhoelen** [mgechev/angular-seed#1595]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When using `styleUrls` in a @Component, inside the referenced file there are no CSS occurrences like `content: "\f002"` possible. The backslash "\" seems to be a problem. It results in all other following styles/lines in the stylesheet to be truncated in *production builds*. This problem does not occur in development mode/builds.

**Expected behavior**
The backslash enclosed by "" or '' should not result in the following CSS instructions to be ignored. It is e.g. needed to reference a character from the chosen font-family, e.g. when working with an icon font.

**Minimal reproduction of the problem with instructions**
In a component, use a stylesheet referenced by `styleUrls` and insert a CSS style like the following:

```
.something:hover:before {
    content: "\f002";
    font-family: "FontAwesome";
}
```

Add some more styles behind it. Serve a production build and check if the styles after the "bad one" are recognised.

**What is the motivation / use case for changing the behavior?**
To enable the full use of CSS vocabulary.

**Please tell us about your environment:**
Mac OSX 10.11.6, IntelliJ IDEA, npm

* **Angular Seed Version:** `2732677418abf538a269491e7731a8e161c308f4`

* **Node:** `node --version` = v5.8.0

**Comment by mgechev** [comment]
I cannot reproduce the issue with the current master. Would you try updating your seed version and run `npm run build.prod` again?

```
git remote add upstream https://github.com/mgechev/angular-seed
git pull upstream master
# Hopefully you won't have a lot of merge conflicts and all your custom tasks
# and configuration are in `tools/*/project`.
npm i # or yarn install
npm run build.prod
```
