### ISSUE TITLE
Sourcemap of bundle on prod build

### ISSUE THREAD

**Issue by Doehl** [mgechev/angular-seed#1597]
[x ] feature request

**Current behavior**
No sourcemap is being generated on prod build.

**Expected behavior**
Generate a sourcemap file of the bundle.
Does not have to be enabled by default, if it can be enabled through a configuration file.

**Bulids that will be effected**
- build.prod
- build.prod.ext

**Pros**
- Will enable us to use a tool like the [source-map-explorer](https://github.com/danvk/source-map-explorer).
- Better debugging of production builds.

**Comment by mgechev** [comment]
Yes, `source-map-explorer` is awesome and I'm using it on a daily basis.

We're intentionally not providing sourcemaps as part of the production bundle - we want to reduce the bundle size/number of requests. You can easily introduce sourcemaps by overriding (redefining it in `tools/tasks/project`) your `build.bundles.app.ts` or `build.bundles.app.exp.ts` and also preventing the code from minification, i.e. overriding `minify.bundles.ts` (I believe uglifyjs will strip the comments by default).

Good luck! Let me know how it goes.
