### ISSUE TITLE
Error: Unexpected value 'MockBackend' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by ganesansays** [mgechev/angular-seed#1598]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Importing MockBackend into AppModule raises "Error: Unexpected value 'MockBackend' imported by the module 'AppModule'" in the browser.

![image](https://cloud.githubusercontent.com/assets/7574782/20007773/d1a13734-a2c3-11e6-9fc3-c07eec8e58b0.png)

**Expected behavior**
Expectation is to get the page without any error and should be able to use MockBackend.

**Minimal reproduction of the problem with instructions**

Clone the repo and add the portion of code highlighted in **BOLD** in src/client/app/app.module.ts 
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HttpModule } from '@angular/http';
**import { MockBackend } from '@angular/http/testing';**
import { AppComponent } from './app.component';
import { routes } from './app.routes';

import { AboutModule } from './about/about.module';
import { HomeModule } from './home/home.module';
import { SharedModule } from './shared/shared.module';

@NgModule({
  imports: [BrowserModule, HttpModule, **MockBackend**, RouterModule.forRoot(routes), AboutModule, HomeModule, SharedModule.forRoot()],
  declarations: [AppComponent],
  providers: [{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  }],
  bootstrap: [AppComponent]

})
export class AppModule { }

**What is the motivation / use case for changing the behavior?**

I am trying to mock the backend, not only for unit and e2e testing, but to develop the application using the stubs. I am unable to inject mock backend.

**Please tell us about your environment:**

OS: Windows 7
IDE: Visual Studio Code
PM: npm
HTTP Server: node

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = v4.4.2

**Comment by mgechev** [comment]
We're already using `MockBackend` in the sample `home.component.spec.ts`. Would you take a look at the file and compare with your configuration?

**Comment by ganesansays** [comment]
Great ... Following the one is home.component.specs.ts seems to be working. Thanks much @mgechev
