### ISSUE TITLE
Not finding external dependencies

### ISSUE THREAD

**Issue by snowburnt** [mgechev/angular-seed#1599]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I'm trying to use angular2-modal with angular-seed. 

I followed the instructions on the wiki:

"npm install angular2-modal --save"

And then referenced it in app.module.ts and in my app. 

when I do npm start, I get an error in the console:
'Error loading http://localhost:5555/node_modules/angular2-modal.js as "angular2-modal" from http://localhost:5555/app/app.module.js Report this error at https://github.com/mgechev/angular2-seed/issues'

I also tried the additional steps of adding these:
   this.SYSTEM_CONFIG_DEV.paths['angular2-modal']=`${this.APP_BASE}node_modules/angular2-modal`;

    this.SYSTEM_BUILDER_CONFIG.packages['angular2-modal']={
      main: 'bundles/angular2-modal.umd.js',
      defaultExtension: 'js'
    }
to project.config.ts but I get the same error
**Expected behavior**

It should pull in the modal package and allow the functionality in dev.
**Minimal reproduction of the problem with instructions**

The steps I took are outlined in the faulty behavior section.
**What is the motivation / use case for changing the behavior?**

This will enable users to use external packages with angular-seed, or at least get provide clarity on how it will happen.
**Please tell us about your environment:**

Windows 8.1, Visual Studio Code, npm, npm.

* **Angular Seed Version:** `aaaaf75`

not sure where to find this...just downloaded it last week.
* **Node:** `node --version` =
6.3.0

**Comment by markoddi** [comment]
I'm having the same issue but with angular2-google-maps

**Comment by snowburnt** [comment]
My workaround was to download the source and wire it into the client folder and let seed take care of it...far from ideal, however.

**Comment by skolli853780** [comment]
for some reason it is not picking up from system_builder_config or system_config_dev for external scripts.. I had to add it to NPM dependencies

  // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      { src: 'primeng/resources/primeng.min.css', inject: true },
      {src: 'primeui/primeui-ng-all.min.js', inject: true}

      // inject into css section

  ];

or you could download it and put it under client folder

**Comment by mgechev** [comment]
**project.config.ts**

```ts
import { join } from 'path';

import { SeedConfig } from './seed.config';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    // this.APP_TITLE = 'Put name of your app here';

    /* Enable typeless compiler runs (faster) between typed compiler runs. */
    // this.TYPED_COMPILE_INTERVAL = 5;

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false}
      // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
    ];

    this.addPackageBundles({
      name: 'angular2-modal',
      path: 'node_modules/angular2-modal/bundles/angular2-modal.umd.js'
    });

    /* Add to or override NPM module configurations: */
    // this.mergeObject(this.PLUGIN_CONFIGS['browser-sync'], { ghostMode: false });
  }

}
```

With the only change:

```ts
    this.addPackageBundles({
      name: 'angular2-modal',
      path: 'node_modules/angular2-modal/bundles/angular2-modal.umd.js'
    });
```

**Comment by snowburnt** [comment]
@mgechev, That change had no effect in my environment.

**Comment by mgechev** [comment]
What version of the seed are you using? What's the hash of the last commit?

**Comment by TingtingGu** [comment]
Is the problem solved? I run into the same issue with ngx-datatable(https://github.com/swimlane/ngx-datatable). When I import this library into angular-tours-of-hero, it works fine.

**Comment by jigarpt** [comment]
Anyone able to address this issue? I am using ngx-datatable with angular-seed. when I do a prod build I get following error only on linux machine. 

It tries to look "@swimlane/package.json" instead of "@swimlane/ngx-datatable/package.json"; not sure why?

```
Error: Error on dependency parsing for dist/tmp/app/shared/shared.module.js at file:///app/dist/tmp/app/shared/shared.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        (SystemJS) ENOENT: no such file or directory, open '/app/node_modules/@swimlane/package.json'
        Error: ENOENT: no such file or directory, open '/app/node_modules/@swimlane/package.json'
            at Error (native)
        Error loading /app/node_modules/@swimlane/package.json
            at Error (native)
            at Error (native)
```

**Comment by jigarpt** [comment]
I could address these issue with following setup:

1. project.config.ts -> added following configuration for additionalPackages.
```
 {
      name: '@swimlane/ngx-datatable',
      path: 'node_modules/@swimlane/ngx-datatable/release/index.js'
    }
```
2. seed.config.ts -> SYSTEM_BUILDER_CONFIG -> packageConfigPaths:
`join('node_modules', '@swimlane', '*', 'package.json')`

**Comment by edefkiko** [comment]
project.config.ts add 2 statements it worked for me.

{
        name: '@swimlane/ngx-charts',
        path: 'node_modules/@swimlane/ngx-charts/release/index.min.js',
      },
      {
        name: '@swimlane/ngx-charts/*',  //prod
        path: 'node_modules/@swimlane/ngx-charts/release/index.min.js',
      },
