### ISSUE TITLE
Feature: Serve prod build via Nginx Docker container

### ISSUE THREAD

**Issue by TheDonDope** [mgechev/angular-seed#1602]
Hey guys,

in another project of mine i extended the docker production build to serve the files in an nginx container, see here: https://github.com/TheDonDope/crudular#dockerization

In this issue i only want to gather opinions if this enhancement might also be interesting for the seed.

Thank you @sclausen for providing the `nginx.conf` here https://github.com/mgechev/angular-seed/pull/1522#issuecomment-255969000

//cc @mgechev @sclausen

**Comment by mgechev** [comment]
I don't mind having it as part of the sees but this mean that we have to maintain the feature in future. Let's keep it out of the project for now, until we get featured requests for it.

**Comment by TheDonDope** [comment]
Alright, i'll push an PR tomorrow :)

**Comment by NicolasTr** [comment]
I'm also using nginx to serve the static files but I'm considering dropping it in this particular case in favour of https://universal.angular.io

Have a look at the [get started guide](https://universal.angular.io/quickstart/).

In my opinion, the setup should look like this:
```
              +---------------------------------------+
              |           Reverse proxy               |
              |      (nginx/haproxy/traefik/...)      |
              |   Handles ssl, security headers, ...  |
              +---------------------------------------+
                               |
                               |
                               |
              +------------------------------------+
              |                                    |
              |                                    |
              |                                    |
+-----(frontend container)----+            (other containers)
+             |               +
+         Universal           +
+             |               +
+       Static files          +
+-----------------------------+
```

Arguably, universal should not even be in the same container as the static files. But in this case, providing server-side rendering to every user of this repository might make it worth.

**Comment by TheDonDope** [comment]
Hi @NicolasTr 
Thank you for the input about `angular/universal`. Feel free to go ahead and issue a PR if you are willing :)
