### ISSUE TITLE
SASS wiki clarifciation

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular-seed#1604]
Can the SASS wiki be updated to show what needs to be done to include the individual component scss files?  I am not sure if I need to use styleUrls or just import the scss file in the main one.
https://github.com/mgechev/angular-seed/wiki/Working-with-SASS

**Comment by hank-ehly** [comment]
@mpetkov 

I took the liberty of adding an example to [the Wiki](https://github.com/mgechev/angular-seed/wiki/Working-with-SASS).

**Comment by mpetkov** [comment]
Thank you! Just wanted to make sure I was doing it the recommended way.

**Comment by mgechev** [comment]
@hank-ehly, thanks for the update!
