### ISSUE TITLE
Problem installing external dependency angular2-highcharts

### ISSUE THREAD

**Issue by macdasi** [mgechev/angular-seed#1611]
I run npm install angular2-highcharts
And added this lines into "project.config.ts"
`this.SYSTEM_CONFIG_DEV.paths['angular2-highcharts'] =
        '${this.APP_BASE}node_modules/angular2-highcharts/index';`

`this.SYSTEM_BUILDER_CONFIG.packages['angular2-highcharts'] = {
      main: 'index.js',
      defaultExtension : 'js'
    }`

I get error 

> Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:50 (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/angular2-highcharts.js

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

Most likely you want something like:

```ts
this.addPackageBundles({
  name: 'angular2-modal',
  path: 'PATH_TO_THE_HIGHCHARTS_BUDNLE'
});
```

**Comment by aquile** [comment]
@macdasi hi! How did you solve this problem?

**Comment by davewragg** [comment]
@aquile this worked for me in project.config:
```
let additionalPackages: ExtendPackages[] = [
      {
        name: 'angular2-highcharts',
        path: 'node_modules/angular2-highcharts',
        packageMeta: {
          main: 'index.js',
          defaultExtension: 'js'
        }
      },
      {
        name: 'highcharts',
        path: 'node_modules/highcharts',
        packageMeta: {
          main: 'highcharts.js',
          defaultExtension: 'js'
        }
      }
```
