### ISSUE TITLE
Problem using dollar sign with property biding

### ISSUE THREAD

**Issue by netstart** [mgechev/angular-seed#1612]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
Using dollar sign in the last charactere with property biding has problem in build.prod
run my branch using

npm run build.prod to see the problem
https://github.com/netstart/angular-seed/tree/dollar_sign

running serve.dev does not occur this problem

```
<!--  with problem -->
<dollar-sign [dollarSign]="'R$'"></dollar-sign>

<!--  without problem
<dollar-sign [dollarSign]="'R$ '"></dollar-sign>
-->

<!-- without problem
<dollar-sign [dollarSign]="'R$R'"></dollar-sign>
-->

<!-- without problem
<dollar-sign [dollarSign]="'$R'"></dollar-sign>
-->

<!-- without problem
<dollar-sign [dollarSign]="'&#36;'"></dollar-sign>
-->
```

**Comment by mgechev** [comment]
Yes, this is [a known issue](https://github.com/mgechev/angular-seed/issues/1479) in `build.prod` because of the plugin we use for [inlining templates](https://github.com/ludohenin/gulp-inline-ng2-template).

The current workaround is to use AOT enabled build.

**Comment by netstart** [comment]
Why not upgrade version of the gulp-inline-ng2-template?

**Comment by netstart** [comment]
Sorry, but it´s not same problem, and update version of the gulp-inline-ng2-template not resolve
