### ISSUE TITLE
Add external downloaded jquery file to seed project 

### ISSUE THREAD

**Issue by amitgaikwad712** [mgechev/angular-seed#1617]
Hi I am using your seed for our project. I have implemented the Graphical interaction using Highchart in your seed. Its run fine till rc4 version of your seed then I have just migrated to stable version then also it is working on development mode when I have trying to deploy on the server then it showing that external downloaded files with following error: `` 
![screenshot from 2016-11-09 20 04 46](https://cloud.githubusercontent.com/assets/16113461/20141786/e9104e8a-a6b7-11e6-92a2-faa0ad09610b.png)
and I have added that all five files into index.html

``` <title><%= APP_TITLE %></title>
  <script src="app/qeasily/jqueries/jquery.min.js"></script>

  <script src="app/qeasily/jqueries/jquery.countdown360.js"></script>

  <script src="app/qeasily/jqueries/highcharts.js"></script>

  <script src="app/qeasily/jqueries/jquery.raty.js"></script>

  <script src="app/qeasily/jqueries/draggable-points.js"></script>

  <meta name="description" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  
```
**********************************************************************************************************
and below screenshot of index.html file

![screenshot from 2016-11-09 20 13 09](https://cloud.githubusercontent.com/assets/16113461/20142011/02250b12-a6b9-11e6-9a41-c74c5a595afe.png)

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
