### ISSUE TITLE
Can we co-exist with angular-cli project ? 

### ISSUE THREAD

**Issue by ishara** [mgechev/angular-seed#1618]
Can we run angular-cli project with angular-seed ? any plan or not possible

**Comment by mgechev** [comment]
We're using different build system. Probably it might be possible to reuse the scaffolding and code generation features of the CLI at some point, if we work on such integration, but we need to consider if it's worth it.

Do you mean anything specific? What is your use case?

**Comment by mgechev** [comment]
@ishara, if you have any ideas please message me [at gitter](https://gitter.im/mgechev/), or continue the discussion here.
