### ISSUE TITLE
Prod build can not find ng-bootstrap after updating to additionalPackages (Linux)

### ISSUE THREAD

**Issue by ZuSe** [mgechev/angular-seed#1619]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
The Prod build fails because it cannot find the bundles file specified in project.conf.ts
However it works on my windows machine (same node version).

```
[14:37:13] 'build.prod' errored after 53 s
[14:37:13] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for @ng-bootstrap/ng-bootstrap at file:///node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js
        Loading dist/tmp/app/components/app.internal.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        ENOENT: no such file or directory, open '/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js'
Stack:
Error on fetch for @ng-bootstrap/ng-bootstrap at file:///node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js
        Loading dist/tmp/app/components/app.internal.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js'
    at Error (native)
```

**Expected behavior**
The prod build should work as it does for me under Windows

**Minimal reproduction of the problem with instructions**
Add 
    additionalPackages.push({
      name: '@ng-bootstrap/ng-bootstrap',
      path: `${this.NPM_BASE}@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js`,
      packageMeta: {
        main: 'ng-bootstrap.js',
        defaultExtension: 'js'
      }
    });

to project.conf.ts on a Linux machine.

**What is the motivation / use case for changing the behavior?**
Support prod build on linux (needed for most build servers)

**Please tell us about your environment:**
Ubuntu 16.04 LTS
Node: 6.6.9
TS: 2.0.2

**Comment by mgechev** [comment]
Would you share the implementation of "addPackageBundles"? Recently there was a change in it which might has not affected your seed version.

**Comment by ZuSe** [comment]
@mgechev 
Thanks for your help.
There it is:

```
addPackageBundles(pack: ExtendPackages) {

    if (pack.path) {
      this.SYSTEM_CONFIG_DEV.paths[pack.name] = pack.path;
      this.SYSTEM_BUILDER_CONFIG.paths[pack.name] = pack.path;
    }

    if (pack.packageMeta) {
      this.SYSTEM_CONFIG_DEV.packages[pack.name] = pack.packageMeta;
      this.SYSTEM_BUILDER_CONFIG.packages[pack.name] = pack.packageMeta;
    }
  }

  addPackagesBundles(packs: ExtendPackages[]) {

    packs.forEach((pack: ExtendPackages) => {
      this.addPackageBundles(pack);
    });
}
```
I didn't touch the seed.conf.ts at all.

**Comment by ZuSe** [comment]
@mgechev 
I just did some testing. It works for me when I add the full path (e.g. /home/myuser/..../myproject/../index.js)

Seems like the problem is with relative path resolution.
