### ISSUE TITLE
Problem using external dependency ng2-table

### ISSUE THREAD

**Issue by sebastiannm** [mgechev/angular-seed#1620]
Hi,

I have been trying to add modules to the project and none of them works.
I tried with ng2-table (which is famous since angular1) and angular2-data-table.

My project.config.ts have this:

```
let additionalPackages: ExtendPackages[] = [];

    additionalPackages.push({
      name: 'ng2-table/ng2-table',
      path: `${this.APP_BASE}node_modules/ng2-table/ng2-table.js`,
      packageMeta: {
        main: 'ng2-table.js',
        defaultExtension: 'js'
      }
    });

    this.addPackagesBundles(additionalPackages);
```

And I import it from app.module.ts

```
import { Ng2TableModule } from 'ng2-table/ng2-table';
```

Any ideas?

**Comment by mgechev** [comment]
Use:

```ts
    this.addPackageBundles({
      name: 'ng2-table',
      path: 'node_modules/ng2-table/bundles/ng2-table.js'
    });
```

...and import with:

```ts
import * as table from 'ng2-table/ng2-table';

console.log(table);
```

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by sebastiannm** [comment]
No, same result I was having before:

'ng-table' is not a known element when using it inside a component. Ng Table is a module

**Comment by mgechev** [comment]
This is not a seed issue but a misuse of the Angular's API. Take a look at `NgModules` and `ng2-table`'s docs.
