### ISSUE TITLE
When I run npm run start for my dev work it keeps creating mapping files and the js files, how do I stop this?

### ISSUE THREAD

**Issue by markoddi** [mgechev/angular-seed#1621]
When I run npm run start for my dev work it keeps creating mapping files and the js files, how do I stop this?

For example: I have a component, and it has a module file, a route file, a component.ts file and a html file.

When I do npm run start it adds a map file and .js file for all my components and im constantly having to remove them.

Is there a setting in tsconfig or gulp to turn this off?

I turned sourcemaps of in the tsconfig but that didnt do anything.

Any ideas?

**Comment by mgechev** [comment]
That's my design.
