### ISSUE TITLE
Bug when serve.prod on bundling of node modules

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1625]
Bug when I do a **npm run serve.prod** in gitbash, and seems to have trouble bundling node modules.

This is the node module I added with : npm install ng2-metadata --save
(https://github.com/fulls1z3/ng2-metadata)

**Current outcome:**

When I run **npm run serve.prod** in git bash I get the following error: "Error on fetech for ng-2-metadata" (error my gitbash error at very bottom)

When I run npm run start it works fine and the node module works fine locally. Seems to be an issue when it bundles for **dist/prod folder.**

**This is my project.config file:**

```
import { join } from 'path';
import { SeedConfig } from './seed.config';

export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();

//Added this one for dev
    this.SYSTEM_CONFIG_DEV.paths['ng2-metadata'] = `${this.APP_BASE}node_modules/ng2-metadata/dist/bundles/ng2-metadata.umd.min.js`;   

//Added this one for prod
    this.SYSTEM_BUILDER_CONFIG.packages['ng2-metadata'] = { main: 'ng2-metadata.umd.min.js', defaultExtension : 'js' };

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES
    ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS
    ];
  }
}

```

**This is the screen grab of my error:**

![bug1](https://cloud.githubusercontent.com/assets/2556223/20239658/3087f24e-a8fd-11e6-9574-4ae11a6fd36e.png)

**Comment by markoddi01** [comment]
@mgechev any idea why the node module cannot be fetched?

**Comment by markoddi01** [comment]
I've had a look at that link and can't see what I'm doing wrong.

**Comment by jesperronn** [comment]
I am facing the same problem, and I probably found the cause

https://github.com/mgechev/angular-seed/blob/f043eb51ec19018856fcd1265859312491dcf4dd/src/client/app/system-config.ts#L3

```
System.config(JSON.parse('<%= SYSTEM_CONFIG_DEV %>'));
```

This line looks innocent at first.

When I run `npm run build.prod`, I can see the resulting js file

```
$ cat dist/tmp/app/system-config.js
System.config(JSON.parse('[object Object]'));
```

You see, the config has never been properly expanded. This is probably why SystemJS has no idea at where to look for files.

We need to fix this

**Comment by RoxKilly** [comment]
@markoddi01 The error you see suggests that the file `.../node_modules/ng2-metadata/ng2-metadata.umd.min.js` does not exist. So the line below from your project config is the problem:

```
 this.SYSTEM_BUILDER_CONFIG.packages['ng2-metadata'] = { main: 'ng2-metadata.umd.min.js', defaultExtension : 'js' };
```

I suggest your replace both that line, and the line above it: `this.SYSTEM_CONFIG_DEV.paths['ng2-metadata'] =...`

Instead of those two, use the `addPackageBundles` function which takes care of setting both `SYSTEM_CONFIG_DEV` and `SYSTEM_BUILDER_CONFIG`:

```
this.addPackageBundles({
  name:'ng2-metadata',

  // for "path" below first, try simply >>   node_modules/ng2-metadata
  path:'node_modules/ng2-metadata/dist/bundles/ng2-metadata.umd.min.js',

  packageMeta:{
    main: 'dist/bundles/ng2-metadata.umd.min.js',
    defaultExtension: 'js'
  }
});
```

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
