### ISSUE TITLE
yarn install failing in Windows

### ISSUE THREAD

**Issue by hellofornow** [mgechev/angular-seed#1632]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
$ yarn
yarn install v0.17.0
[1/4] Resolving packages...
warning compodoc > angular2-dependencies-graph > viz.js@1.3.0: Viz.js is deprecated.
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
error compodoc@0.0.8: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 < 7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Expected behavior**
install should succeed

**What is the motivation / use case for changing the behavior?**
Caused by PR #1623 

**Please tell us about your environment:**
Windows 10

**Angular Seed Version:** `aaaaf75`
 2f90871

**Node:** `node --version` =
$ node --version
v7.1.0
$ yarn --version
0.17.0

**Comment by Shyam-Chen** [comment]
try `yarn install --ignore-engines`

**Comment by jsayol** [comment]
I'm on Linux and I'm seeing the same error. The `--ignore-engines` flag @Shyam-Chen mentioned is the only workaround, other than using `npm install`.
