### ISSUE TITLE
Support serving multiple apps with different index files / paths

### ISSUE THREAD

**Issue by ZuSe** [mgechev/angular-seed#1633]
**I'm submitting a ...**  (check one with "x")
```
[X ] feature request
```
I had some time time to take a closer look on the multiple app support today.
I really like the idea of supporting more than one angular app in the same seed project as many projects share a common code base.

What I try to do now is serving my 2 apps in 2 different windows.
e.g. http://example.com/foo  and http://example.com/bar

Unfortunately the index.html gets modified so that SystemJS imports either foo or bar.
So that last app build wins.
What I would like to have are 2 index.html-files one for each app so that I can serve both at the same time listening on the same port. 

My expected outcome for the build would be more similar to:

dist/
-dev/
--assets/
--css/
--foo/
--- index.html
--- foo.module.ts
--bar/
--- index.html
--- bar.module.ts
 
Same for the production build.

What do you think about this? I really don't get the idea why multiple apps are supported but you can only run at the same time.. especially for development it sucks.
On production I have proxy in front that could be configured, there it is less a problem.

**Comment by sersart** [comment]
Really good idea.

**Comment by mgechev** [comment]
Yes, I like the idea too. @ZuSe at the moment I'm mostly busy with codelyzer. If you have some time it'll be awesome if you can open a PR. Let me know if you want to discuss the direction of the change.

**Comment by ZuSe** [comment]
@mgechev 
I can take a look on it after I found a solution for my current problem.
Atm, am working on running the seed with Shared/WebWorkers, so that can run my app in multiple windows without having to bootstrap the whole app in every window. I would really appreciate your feedback on this if you have any experience or idea on that issue :)

**Comment by mgechev** [comment]
@ZuSe let's chat about this on gitter. Would you ping me [here](https://gitter.im/mgechev)?

**Comment by lifaon74** [comment]
Naive approach : You have the same assets, style, but different entry html files and modules. Why not having one entry file (index.html and app.component.ts) and let angular router with a specific config file loading the proper app ?

The is currently what we're doing in the company where I work.

**Comment by mgechev** [comment]
@lifaon74 another alternative which is possible, is to have different production builds with the same `index.html` files but different bootstrap files.

I guess we can close this issue, although it's applicable in some cases.
