### ISSUE TITLE
In IE my app doesn't load and I get this error:  (SystemJS) No provider for PlatformRef! 

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1634]
In IE my app doesn't load and I get this error:  (SystemJS) No provider for PlatformRef! 

My app runs fine locally/ and live in all other browsers such as chrome and firefox.

I have the latest app.

This is the error I get:  (SystemJS) No provider for PlatformRef! 
I have no idea what this means.

**This is the erro I get in IE Edge:**

![error](https://cloud.githubusercontent.com/assets/2556223/20359828/6f6707b4-ac29-11e6-9a1a-8182b6b71cfd.png)

**Comment by markoddi01** [comment]
@mgechev this is really important I get a quick fix for this, because I have this website live and customers are complaining. Thank you in advance

**Comment by mgechev** [comment]
It's an Angular issue that you're having, not an Angular seed problem. You can use gitter's Angular channel or search in their issue tracker.

**Comment by markoddi01** [comment]
@mgechev what type of angular issue is it? can you help me isolate this issue?
