### ISSUE TITLE
where is hot_loader_main.ts ?

### ISSUE THREAD

**Issue by csreddy** [mgechev/angular-seed#1635]
I wanted to enable hot loading, but looks like `hot_loader_main.ts` is missing.

**Comment by mgechev** [comment]
You cannot enable hot reloading at this point. I'm not aware of transparent to developers hot reloader which will work reliably with the current module loaders without explicitly setting preserving components' state.

**Comment by csreddy** [comment]
Ok.  It's not clear in the documentation thats its is not available. Thanks for the quick response.

**Comment by mgechev** [comment]
I'll drop this from the readme today.
