### ISSUE TITLE
e2e tests with async/await 

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular-seed#1639]
Hi @mgechev, an excellent contribution just came into the advanced seed which is not specific to the extended features there and I wanted to point your attention to it here:
https://github.com/NathanWalker/angular-seed-advanced/pull/306

It's excellent and exciting work by @VladimirMakaev and curious if after having a look, you may be interested in those improvements to e2e testing here? If so, I can work with him to submit a PR here instead (which would of course end up in advanced seed as well).

**Comment by mgechev** [comment]
Looks great! I'd love to have this in the seed.

**Comment by NathanWalker** [comment]
@mgechev :) Ok I'll work with him to get a PR posted here first.
