### ISSUE TITLE
jQuery and Protractor @types conflict

### ISSUE THREAD

**Issue by ashblue** [mgechev/angular-seed#1645]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
jQuery types and Protractor types are having a global namespace conflict with $. Errors on compile about the conflict.

**Expected behavior**
Following the directions linked below on the official Protractor GitHub. You should be able to set `noGlobals: true` in protractor.conf.js to easily fix this issue. I've set that variable in my config, and I'm still seeing the same error.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2734#issuecomment-253891273

**Minimal reproduction of the problem with instructions**
1. Install jQuery types `npm install --save @types/jquery`
2. Run `build.js.dev` 
3. You'll see a compile error of `/Users/ashblue/Programming/angular-seed/node_modules/@types/protractor/index.d.ts(1844,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'JQueryStatic', but here has type 'cssSelectorHelper'.`

**What is the motivation / use case for changing the behavior?**
Types are now the standard way to include libraries. 

**Please tell us about your environment / Angular Seed Version:**
Latest Angular Seed release.

* **Node:** `node --version` = 7.0

**Comment by mgechev** [comment]
Here are links to [similar issues](https://github.com/mgechev/angular-seed/issues?q=is%3Aissue+Protractor+jquery+is%3Aclosed), already resolved.

**Comment by ashblue** [comment]
@mgechev I don't think this is resolved. I found the following ticket that's marked as a resolution. But it looks like it doesn't fix the typings issue, but circumvents it with a `let $: any` hack which nukes the imported typings. I'm currently hunting for a solution and will try to update this ticket if I find one. If you have any tips on where to look to de-load the Protractor globals please let me know 😄

**Comment by ashblue** [comment]
And here is another ticket for the official typings to get this fixed: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11187

**Comment by ashblue** [comment]
As a temporary solution until the official typings are fixed, you can put `let $: any = window['$'];` in your individual files. A nasty fix, but works for the moment.

Also @mgechev, it looks like we might be able to remove the Protractor typings and fix the global loading as they come included with 4.0.9+ from what I'm reading. Not super familiar with how protractor is rigged up yet (still learning seed's source). But will investigate further if they don't adjust the jQuery typings file naming conflict issue with `$`.

**Comment by mgechev** [comment]
Thanks for the comment. Yes, you're right that the type definitions are now distributed with protractor itself. I'll see if I can drop `@types/protractor` in the next a couple of days. Of course, if you have some time, a PR will be appreciated :-).

**Comment by ashblue** [comment]
@mgechev We're in the middle of a huge code base migration atm. But I'll try to delve into the typings issue and make a PR if I can swing around to it (going to vanish here for Thanksgiving break for a little while). Knowing that the typings is the source of the conflict makes this tremendously easier to tackle. Thx you so much.

Enjoy your vacation and take a break from this amazing project 😄
