### ISSUE TITLE
Can't get sass to work according to the wiki

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular-seed#1650]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Sass setup in the wiki, not working

**Please tell us about your environment:**

Windows 10, Vscode

* **Angular Seed Version:** ` 33f2dff`

* **Node:** `node --version` = 6.9.1

**Comment by TheDonDope** [comment]
Could you please be more specific?

**Comment by mgechev** [comment]
You need the `--scss` flag.
