### ISSUE TITLE
lodash makes production build fail

### ISSUE THREAD

**Issue by ospaarmann** [mgechev/angular-seed#1651]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Running the application with `npm start` works. But when running `npm run build.prod` it produces an error.

**Expected behavior**
Should run in dev and build to prod.

**Minimal reproduction of the problem with instructions**
I have installed lodash and lodash types via package.json:

```
    "@types/lodash": "^4.14.39",
    "bootstrap-sass": "^3.3.6",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "jquery": "~2.2.4",
    "lodash": "^4.17.1",
```

Now when importing lodash in a component like so: `import * as _ from 'lodash';`

I receive this error in the browser console when running npm start.

`localhost/:79 (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/lodash.js`

So I add/uncomment this part in `tools/config/project.config.ts`:

```
    let additionalPackages: ExtendPackages[] = [{
      name: 'lodash',
      path: `${this.NPM_BASE}lodash/lodash.js`,
      packageMeta: {
        main: 'index.js',
        defaultExtension: 'js'
      }
    }];
    
    this.addPackagesBundles(additionalPackages);
```

Now running `npm start` works. But running `npm run build.prod` produces this error:
```

[17:02:42] 'build.bundles.app' errored after 3.71 s
[17:02:42] Error on fetch for lodash at file:///node_modules/lodash/lodash.js
	Loading dist/tmp/app/+signup/signup.component.js
	Loading dist/tmp/app/+signup/index.js
	Loading dist/tmp/app/app.routes.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/node_modules/lodash/lodash.js'
    at Error (native)
[17:02:42] 'build.prod' errored after 22 s
[17:02:42] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for lodash at file:///node_modules/lodash/lodash.js
	Loading dist/tmp/app/+signup/signup.component.js
	Loading dist/tmp/app/+signup/index.js
	Loading dist/tmp/app/app.routes.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	ENOENT: no such file or directory, open '/node_modules/lodash/lodash.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/node_modules/lodash/lodash.js'
Stack:
Error on fetch for lodash at file:///node_modules/lodash/lodash.js
	Loading dist/tmp/app/+signup/signup.component.js
	Loading dist/tmp/app/+signup/index.js
	Loading dist/tmp/app/app.routes.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/node_modules/lodash/lodash.js'
    at Error (native)
```

Can't find a solution for this. 

Btw. using `this.APP_BASE` (plus `node_modules`) instead of `this.NPM_BASE` doesn't change anything.

**Please tell us about your environment:**

* **Angular Seed Version:** 2.1.2 - `365f0ecade4bea45e81d311889f4ed9a2a18d35b`

* **Node:** `node --version` = v6.4.0

**Comment by mgechev** [comment]
You have set invalid configuration. Setting package's meta is not necessary in case you provide path to the entire bundle of lodash.

**Comment by ospaarmann** [comment]
Thanks for your reply. I changed the relevant part in project.config.ts to:

```
let additionalPackages: ExtendPackages[] = [{
      name: 'lodash',
      path: `${this.NPM_BASE}lodash/lodash.js`
    }];
```

`npm run build.prod` still fails:

```
[17:24:13] 'build.bundles.app' errored after 3.91 s
[17:24:13] Error on fetch for lodash at file:///node_modules/lodash/lodash.js
	Loading dist/tmp/app/+signup/signup.component.js
	Loading dist/tmp/app/+signup/index.js
	Loading dist/tmp/app/app.routes.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/node_modules/lodash/lodash.js'
    at Error (native)
[17:24:13] 'build.prod' errored after 17 s
[17:24:13] Error in plugin 'run-sequence(build.bundles.app)'
```

**Comment by ospaarmann** [comment]
Oh, and btw. in 2.0.1 importing lodash just worked (after installing the types) without adding anything in project.config.ts.

**Comment by ospaarmann** [comment]
Ok, for anyone having a simliar issue. I fixed it by removing these lines completely (they are commented out originally anyway):

```
let additionalPackages: ExtendPackages[] = [{
      name: 'lodash',
      path: `${this.APP_BASE}node_modules/lodash/lodash.js`,
      packageMeta: {
        main: 'index.js',
        defaultExtension: 'js'
      }
    }];

this.addPackagesBundles(additionalPackages);
```

And adding these lines to fix the paths:

```
this.SYSTEM_CONFIG.paths['lodash'] = `${this.APP_BASE}node_modules/lodash/index`;
this.SYSTEM_BUILDER_CONFIG.paths['lodash'] = `node_modules/lodash/index.js`;
```

Credit goes to https://github.com/NathanWalker/angular-seed-advanced

**Comment by webia1** [comment]
We should add it into the readme file: "lodash-issue". 

`this.addPackagesBundles(additionalPackages);` was not executed on a jenkins build server at all,..

**Comment by arun-awnics** [comment]
Thank you @ospaarmann I was facing the same issue. Your answer resolved it.
