### ISSUE TITLE
Css generation problem with scss and production build.

### ISSUE THREAD

**Issue by EmanuelEriksson** [mgechev/angular-seed#1652]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)

**Current behavior**
I'm including two .css files in NPM_DEPENDENCIES and i'm using scss for my main css. When building for production the concatenated file will look like this [external css1, my scss, external css2]. My scss should be concatenated at the end of the file.

The reason for the bug is that the production build for scss uses merge to join the css and scss streams, but merge is interleaving the streams not concatenating them.

Workaround: Just include dummy scss files in APP_ASSETS before your main.scss.

* **Angular Seed Version:** `82d4da1`

**Comment by six006** [comment]
I update the code in build.html_css.ts

function getSCSSFiles(cacheName: string, filesToCompile: string[], filesToExclude: string[] = []) {

  // let allFiles: string[] = filesToCompile.concat(filesToExclude);
  // let filteredFiles: string[] = filesToCompile.concat(
  //   filesToExclude.map((path: string) => { return '!' + path; })
  // );

  // return gulp.src(allFiles)
  //   .pipe(plugins.cached(cacheName))
  //   .pipe(plugins.progeny())
  //   .pipe(filter(filteredFiles));

  return gulp.src(
    filesToCompile,
    filesToExclude.map((path: string) => { return '!' + path; })
  )
    .pipe(plugins.cached(cacheName))
    .pipe(plugins.progeny());
}

**Comment by lifaon74** [comment]
@EmanuelEriksson : 
Please take a look at https://github.com/mgechev/angular-seed/wiki/Working-with-SASS
With sass you should not include your css files into APP_ASSETS nor NPM_DEPENDENCIES but into your main.scss (this is one of the purpuse to use sass...) (```@import 'node_modules/some_lib/style.css';```)=> it bundles and properly minimizes your style and fasten build. AND you can choose the order of your style !

@six006 => I can identify some problems to your code (to confirm) : 

1) gulp.src(globs[, options]) so you're not inputing incorrect arguments
2) Gulp need to detect changes into excluded files too ! If you remove allFiles and filter(filteredFiles) it won't work...
=> The current code is correct and works fine for many users

PS: In my personal opinion, a proper css should not overload any other style, preffer a better path to identify 2 distinct elements...
- It creates confusion for others developers.
- Useless code redundancy (=> bigger file)
- Possible cause of bugs (ak: you posted here...)
