### ISSUE TITLE
How to write custom gulp tasks after building project

### ISSUE THREAD

**Issue by cuongdn** [mgechev/angular-seed#1658]
Hi,

My project has many file small css files in hierarchy folders (I don't want to organize the structure css folders for some reasons). After I build project in production mode, some fonts do not load correctly because of bundling css. I need to write some custom gulp tasks to copy these fonts. 

What is the right way to extend these tasks?

Thanks

**Comment by mgechev** [comment]
You can override an existing task by creating a file with `tools/tasks/project` with the same name as the task you want to override.

If you want to create a new task, again, create a file in `tools/tasks/project` and include it in `gulpfile.ts`.
