### ISSUE TITLE
/base/ is not being stripped off properly, causing 404 when testing

### ISSUE THREAD

**Issue by avhetman** [mgechev/angular-seed#1663]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

/base/ is not stripped off before /node/modules resulting in a 404 error when running tests. 

**Expected behavior**

I believe the base should not be there. 

**Minimal reproduction of the problem with instructions**

git clone --depth 1 https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install
npm i dragula ng2-dragula --save

seed.conf.ts:
SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    paths: {
       ...
      'app/*': '/app/*',
      // For test config
      'dist/dev/*': '/base/dist/dev/*',
      'dragula': `node_modules/dragula/dist/dragula`,
      '*': 'node_modules/*'
    },
    packages: {
    }
  };
SYSTEM_BUILDER_CONFIG: any = {
    ...
    paths: {
      [join(this.TMP_DIR, this.BOOTSTRAP_DIR, '*')]: `${this.TMP_DIR}/${this.BOOTSTRAP_DIR}/*`,
      'dist/tmp/node_modules/*': 'dist/tmp/node_modules/*',
      'node_modules/*': 'node_modules/*',
       'dragula': `node_modules/dragula/dist/dragula.min.js`,
      '*': 'node_modules/*'
    },
    ...

The project builds in both dev and prod, however when I run test I get:
23 11 2016 08:57:45.846:WARN [web-server]: 404: /base/node_modules/ng2-dragula/ng2-dragula.js
Chrome 54.0.2840 (Windows 10 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng2-d
ragula/ng2-dragula.js
        Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng2-dragula/ng2-dragula.js
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e6
4913b5669320b167e496fc94fc6928:647:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc9
4fc6928:236:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:136
:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167
e496fc94fc6928:304:33)
        Error loading http://localhost:9876/base/node_modules/ng2-dragula/ng2-dragula.js as "ng2-dragula/ng2-dragula" from http://loca
lhost:9876/base/dist/dev/app/home/home.component.js'
Chrome 54.0.2840 (Windows 10 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng2-d
ragula/ng2-dragula.js
        Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng2-dragula/ng2-dragula.js
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e6
4913b5669320b167e496fc94fc6928:647:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc9
4fc6928:236:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:136
:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167
e496fc94fc6928:304:33)
        Error loading http://localhost:9876/base/node_modules/ng2-dragula/ng2-dragula.js as "ng2-dragula/ng2-dragula" from http://loca
lhost:9876/base/dist/dev/app/home/home.component.js'
23 11 2016 08:57:45.963:WARN [web-server]: 404: /base/node_modules/ng2-dragula/ng2-dragula.js

In several places I see http://localhost:9876/base/node_modules/ng2-dragula/ng2-dragula.js and I believe that this problem has to do with /base/ not being stripped properly, but I am not sure. Any help is appreciated.

**What is the motivation / use case for changing the behavior?**

Testing is important

**Please tell us about your environment:**

Win 10 64

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.9.1 npm=3.10.8

**Comment by avhetman** [comment]
I'm still digging into this, but I may be wrong in presuming that the culprit is the /base/ part. Either way, I need help in getting ng2-dragula working properly.

**Comment by wudong** [comment]
seeing a similar issue, when adding lodash to the system.js config in ProjectConfig with:

```
this.SYSTEM_CONFIG_DEV.paths['lodash'] = `${this.APP_BASE}node_modules/lodash/lodash`;
this.SYSTEM_BUILDER_CONFIG.packages['lodash'] = { main: 'lodash.js', defaultExtension: 'js' };

```

npm start works but not in the karma test.

**Comment by Blankchen** [comment]
I have the same issue
the only way I found is the following code
`npm test -- --base /base/`

**Comment by vyakymenko** [comment]
1. ```sh $git clone --depth 1 https://github.com/mgechev/angular2-seed.git```
2. ```sh cd angular2-seed```
3. ```sh npm install```
4. ```sh npm i dragula ng2-dragula --save```
5.
`src/client/app/shared/shared.module.ts`
```ts
...
import { DragulaModule } from 'ng2-dragula/ng2-dragula';
...

@NgModule({
  ...
exports: [ToolbarComponent, NavbarComponent,
    CommonModule, FormsModule, RouterModule, DragulaModule]
....
```
6.
`karma.config.js`
```js
...
module.exports = function (config) {
  config.set({
      ....
      // Dragula
      { pattern: 'node_modules/dragula/**/*.js', included: false, watched: true },
      { pattern: 'node_modules/ng2-dragula/**/*.js', included: false, watched: true },
...
```
7.
```sh npm test```

**Comment by avhetman** [comment]
This worked, thanks so much!

**Comment by vyakymenko** [comment]
Added WIKI https://github.com/mgechev/angular-seed/wiki/Including-dependencies-in-karma.config.js
