### ISSUE TITLE
Cannot import modules using barrels files implicity

### ISSUE THREAD

**Issue by vlad0** [mgechev/angular-seed#1664]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Why we cannot use barrels files for imports? E.g.: ```import { SharedModule } from './shared/shared.module';``` could be ```import { SharedModule } from './shared/';``` and add  SharedModules to the `index.ts` in folder `./shared`. Any ideas why this doesn't work? 

**Expected behavior**

```import { SharedModule } from './shared/';``` should import the module since there is index.ts file in the shared folder. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
SystemJS doesn't support this out of the box. If you want to do that (which is not recommended by the style guide), you need to provide manual configuration as part of `project.config.ts`.

**Comment by TheDonDope** [comment]
Barrel files are no longer recommended by the styleguide, there is a possibility to introduce circular dependencies (since export order matters) which can be tricky to catch. Look here for details: http://stackoverflow.com/questions/37997824/angular-2-di-error-exception-cant-resolve-all-parameters/38000323#38000323

**Comment by fisenkodv** [comment]
@mgechev could you please point me out to that style guide?
