### ISSUE TITLE
Importing Showdown.js

### ISSUE THREAD

**Issue by Meistercoach83** [mgechev/angular-seed#1667]
Hi,
I´m trying to get showdown included to the seed. But I have no success.
I tried installing it via npm install showdown @types/showdown and including it in my project.config.ts:

```
this.addPackageBundles({
            name: 'showdown',
            path: 'node_modules/showdown/src/showdown.js',
            packageMeta: {
                main: 'showdown.js',  // also try index.js
                defaultExtension: 'js'
            }
        });
``` 

After that I wanted to import it in a component "import * as showdown from 'showdown';"

But I get an error: "getDefaultOpts is not define"
what else do i have to edit?

**Comment by mgechev** [comment]
In `path` provide path to showdown's **bundle**, i.e. `node_modules/showdown/dist/showdown.js`.

**Comment by Meistercoach83** [comment]
Hey! I tried it without the packageMeta and the bundle you wrote - with no success.
I´tried to import it in a component via import * as showdown from 'showdown';

**Comment by Meistercoach83** [comment]
@mgechev ??

**Comment by mgechev** [comment]
Add it in `project.config.ts` as:

```ts
this.addPackageBundles({
  name: 'showdown',
  path: 'node_modules/showdown/dist/showdown.js'
});
```

Use it as:

```ts
import * as showdown from 'showdown';

const converter = new showdown.Converter();
const text = '#hello, markdown!';
console.log(converter.makeHtml(text));
```

For support requests I'd recommend you to use stackoverflow or gitter in order to get responses faster.
