### ISSUE TITLE
(SystemJS) Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by codelovesme** [mgechev/angular-seed#1669]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When try to import "mapbox-gl/dist/mapbox-gl.js" as mentioned in https://www.npmjs.com/package/mapbox-gl 

**Expected behavior**

There would be no errors by default I think but if it is not a bug please lead me to solve it.

**Minimal reproduction of the problem with instructions**

Problem occurres while loading the module by Systemjs. By the way the project I am trying it to use a angular2 project.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Ubuntu 16.04LTS , Visual Studio Code, npm, Angular2, Systemjs

* **Angular Seed Version:** `0.0.0`

* **Node:** `node --version` =v6.8.0

**Comment by mgechev** [comment]
Would you provide a minimal example/code sample?

**Comment by mgechev** [comment]
Closing it due to no any updates. If you've resolved the issue or have any updates it'll be great if you can comment!

**Comment by codelovesme** [comment]
![image](https://cloud.githubusercontent.com/assets/2770826/20676687/aa103116-b5a1-11e6-922b-96102f30ddfb.png)

Hi, sorry for the absence.
I have attached a screenshot of error and sharing some code realted with it.

in index.html file there is a section which loads app/main.js

<script>
        System.import('app/main')
        .catch(function (e) {
            console.error(e,
                'Report this error at https://github.com/mgechev/angular2-seed/issues');
        });
    </script>

It is getting down while try to load module.

If you ask me what I have changed, I have added a module into dashboard.module.ts


@NgModule({
    imports: [
        CommonModule,
    	RouterModule,
    	DropdownModule,
        ModalModule,
    	HomeModule,
        ChartModule,
        MapModule,
        TableModule,
....


Here is Map Module

import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { MapComponent } from './map.component';

@NgModule({
    imports: [RouterModule],
    declarations: [MapComponent],
    exports: [MapComponent]
})

export class MapModule { }
