### ISSUE TITLE
WebStorm (v2.3.1): Live reload after file change (html) does not work. SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by webia1** [mgechev/angular-seed#1670]
possible bug ?
Windows 7, npm 4.0.1, node v6.8.1, TypeScript 2.0.10 

**Initial seed, nothing has been changed.** [Work-around here](https://github.com/mgechev/angular-seed/wiki/Known-Issues) does not work.

That's the Chrome Console: 

![webstorm_2 3 1_live_reload](https://cloud.githubusercontent.com/assets/2741558/20605988/7473fe88-b26e-11e6-9c4e-8db105559d8e.png)

``` javascript
VM661:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at http://localhost:5555/app/system-config.js:1:20(anonymous function) @ system-config.ts:2

    System.config(JSON.parse('<%= SYSTEM_CONFIG_DEV %>'));
    //# sourceMappingURL=system-config.js.map

(index):48 (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/app/main
	Error loading http://localhost:5555/app/main Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
```

As already [mentioned here](https://github.com/mgechev/angular-seed/wiki/Known-Issues) safe-write is activated:

![webstorm_safe_write](https://cloud.githubusercontent.com/assets/2741558/20606010/99ca30d0-b26e-11e6-9b2e-0ea406bf96dd.png)

**Comment by mgechev** [comment]
I don't have webstorm installed, neither a license so it'll be hard to reproduce...

**Comment by webia1** [comment]
You can always download an early access version (30 Days) here: https://confluence.jetbrains.com/display/WI/WebStorm+EAP

At reloading-time the `'<%= SYSTEM_CONFIG_DEV %>'` cannot be interpreted, whatever the problem is, it is time or order-related.

**Comment by TheDonDope** [comment]
Sounds a hell lot like https://github.com/mgechev/angular-seed/issues/1625#issuecomment-260276901

**Comment by webia1** [comment]
I've asked the question at stackoverflow: http://stackoverflow.com/questions/40805944/webstorm-v2-3-1-live-reload-after-file-change-html-does-not-work-syntaxerr?noredirect=1#comment68832698_40805944

**Comment by mgechev** [comment]
@webia1 I tried it with https://www.jetbrains.com/webstorm/download/ on macOS and it works great. Maybe it's something Windows related? Can you reproduce it with VSCode?

**Comment by webia1** [comment]
@mgechev Yes, you're right; no Problems on macOS and Unix/Linux,..

**Comment by webia1** [comment]
Can "inotify" be the problem on Windows7 ? See here [the update at Windows10.](https://blogs.msdn.microsoft.com/commandline/2016/10/07/wsl-adds-inotify-filesystem-change-notification-support/) 

Could that [here](https://github.com/thekid/inotify-win) help? 

Almost all the big (Banks/Insurance/Governmental/..)  companies use still Windows 7 in Austria and in Germany.  We have to solve this problem or in worst case change the seed :/

**Comment by ultimatedion** [comment]
1) Did you try to edit the HTML files outside of webstorm to see if the same problem happens?

This should tell us if it's WebStorm related or not.

2) How do you launch your app with live reload?

I might not have the same versions of node, npm etc) but I am using PhpStorm on Windows 7. I don't have any issues.

**Comment by mgechev** [comment]
@webia1 yes, definitely we should fix the problem. @ultimatedion good questions, @webia1 would you follow up?

**Comment by lifaon74** [comment]
I have something realy similar.

I use the last version of webstorm (2.3.1, windows 10) and ng2-seed, and since ~2 weeks ago I detect some strange compilation behaviour : one of my ts file (always the same, only containing one enum, and massivelly used)  partially compiles sometimes (1 times on 2 some enums values are missing but the file is always valid) and it always produces a external map file even if the sourceMappingURL is inlined into the js file. It's like if this file was cached and loading from a realy old version or than typescript was removing randomly some enum constants... just for this particular file. I'll try to inspect a maximum this problem today (problem from webstrom, lib update ?...).

Concerning @webia1 I encountered the same problem just one time, I just did another npm start and never saw it again (and I hope it will continue ;) )

**Comment by sangecz** [comment]
I have the same issue as @webia1 but on macOS (10.12.1) with webstorm (2016.3.1) but also with mcedit, so this is not webstorm related

**Comment by sangecz** [comment]
interesting is that this occurs only if I edit html file and save it, but it recovers (no need to new npm start) when I edit ts file.

**Comment by webia1** [comment]
yes, the problem occurs only by editing html files, no matter within WebStorm or Notepad.

**Comment by alaevka** [comment]
same problem started some hours ago. after then i update html got this error. my editor is sublime

**Comment by mgechev** [comment]
@alaevka again on Windows?

**Comment by alaevka** [comment]
@mgechev on mac os.

**Comment by webia1** [comment]
2 Seeds on a new windows 7 installation, the first one within git with remote  GitLab Community Edition 8.11.4, the second one without git.  The second one has no problems with reloading after modifying html files, the first one ist the exact copy but reloading after modifying html files does not work.

**Comment by artemverbo** [comment]
+1 on MacOS, Sublime Text, so not a WebStorm issue... running via `npm run start` or `serve.dev`

**Comment by webia1** [comment]
Could that be a reciprocal interference issue between npm and yarn?

**Comment by mgechev** [comment]
This is definitely weird. @webia1 thanks for pointing out your experience. I'm happy to hear that it's not an issue in the seed and scared that we don't know the exact cause.

**Comment by ultimatedion** [comment]
I had a similar trouble that started today... Took me a few hours to sort it out and debug it. 

It was caused by PhpStorm... Somehow, the Typescript compiler(inside intelliJ) got activated... This create .js files and these js files get copied to dist/dev when updating an html file. When updating a ts file, these js files gets overwrited by the build and fix the problem.

I thought at first that it was not related to PhpStorm because I tried to edit html file outside the IDE. It still happenned because the problem was with already generated .js by Phpstorm...
I had to remove them all.

Don't be mistaken, these JS files compiled doesn't show up in the IDE. 

Maybe, you had the same issue or it might help you to solve yours.

Solution: Make sure to disable the TypeScript Compiler in PHPStorm...
![image](https://cloud.githubusercontent.com/assets/4740888/21129610/c64c2d46-c0d0-11e6-9c2a-dc47ae3e4be8.png)

**Comment by webia1** [comment]
We have still this problem, disabling of TypeScript Compiler does not solve the problem.

The starting point of the problem is here (`src/client/app/system-config.ts`): 

```javascript
System.config(JSON.parse('<%= SYSTEM_CONFIG_DEV %>'));
```

This template beginning with `<%= ...` is not being evaluated at reload after html change:

```javascript
'<%= SYSTEM_CONFIG_DEV %>'
```

What kind of templating is that? [EJS ](http://www.embeddedjs.com/)? Where is this dependency in the seed? I've 2 suspicions:

1) Express server on Windows has problems with reloading of EJS templates ?
2) EJS is not be evaluated because of injection order of js-libraries ?

That is currently a big problem in our environment, my team members do not want to use this seed because of this problem on Windows (p.s no problems on Mac & Linux). 

Thank you for your answers, merry Christmas,..

**Comment by mgechev** [comment]
We're using `gulp-template` which behind the scene uses lodash/underscore templates. You can find where we're using [it here](https://github.com/mgechev/angular-seed/search?utf8=%E2%9C%93&q=template).

**Comment by ultimatedion** [comment]
This is not the problem.
Of course that '<%= SYSTEM_CONFIG_DEV %>' is not evaluated... 
<%= SYSTEM_CONFIG_DEV %> is replaced at build time. It won't evaluate at runtime. It need to be replaced in the build process

Look at dist/dev/app/system-config.js
**You should not see <%= SYSTEM_CONFIG_DEV %> in this file.**

Disabling typescript compiler is not the only part of the solution. Make sure you don't have system-config.**js** in your source folder.

**Comment by webia1** [comment]
hmm, ok, I've modified `start.deving.ts` und now it works also in windows:

```javascript
gulp.task('watch.while_deving', function () {
  watchAppFiles('**/!(*.ts)', (e: any, done: any) =>
    runSequence('build.assets.dev', 'build.html_css', 'build.js.dev', 'build.index.dev', () => { notifyLiveReload(e); done(); }));
  watchAppFiles('**/(*.ts)', (e: any, done: any) =>
    runSequence('build.js.dev', 'build.index.dev', () => {
      notifyLiveReload(e);
      runSequence('build.js.test', 'karma.run.with_coverage', done);
    }));
});
```

**Comment by skolli853780** [comment]
I am having the same issue..

Error: (SystemJS) Unexpected token < in JSON at position 0
	SyntaxError: Unexpected token < in JSON at position 0
	    at Object.parse (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/config/env.config.js:2:23)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:4:4)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:5:3)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/index.js:11:10)
	    at eval (http://localhost:5555/app/shared/index.js:15:4)
	    at eval (http://localhost:5555/app/shared/index.js:16:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/app/shared/config/env.config.js
	Evaluating http://localhost:5555/app/shared/index.js
	Evaluating http://localhost:5555/app/app.component.js
	Evaluating http://localhost:5555/app/app.module.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js
	    at Object.parse (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/config/env.config.js:2:23)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:4:4)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:5:3)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/index.js:11:10)
	    at eval (http://localhost:5555/app/shared/index.js:15:4)
	    at eval (http://localhost:5555/app/shared/index.js:16:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/app/shared/config/env.config.js
	Evaluating http://localhost:5555/app/shared/index.js
	Evaluating http://localhost:5555/app/app.component.js
	Evaluating http://localhost:5555/app/app.module.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by skolli853780** [comment]
issue is resolved by deleting js files from src
