### ISSUE TITLE
Export is not defined.

### ISSUE THREAD

**Issue by telvin** [mgechev/angular-seed#1682]
**I'm submitting a bug report** 

**Current behavior**

`npm test` failed with the error message

`28 11 2016 08:57:21.709:INFO [Chrome 54.0.2840 (Mac OS X 10.11.6)]: Connected on socket /#GP1bWs8hKg6HsSLrAAAA with id 30897730
Chrome 54.0.2840 (Mac OS X 10.11.6) ERROR
  Uncaught ReferenceError: exports is not defined
  at node_modules/ng2-cookies/cookie.js:110`

**Expected behavior**

`npm test` should run successfully without the error.

**Minimal reproduction of the problem with instructions**

I've installed a library at called [ng-cookies](https://github.com/BCJTI/ng2-cookies), it worked just fine on the build, however, the karma test was failed to run because it does not understand the `export` on that library. I also added the following like on the karma.config.ts

`{ pattern: 'node_modules/ng2-cookies/*.js', included: true, watched: false, served: true },`

**What is the motivation / use case for changing the behavior?**
It maybe irrelevant, but I also tried to run the similar test on the angular webpack starter version and did not get this problem and I know it is the different module loader mechanism, so how could I bypass this issue when working with third party module?

Updated: There is also an error when build, here is the log

```
[11:21:30] Finished 'build.html_css' after 857 ms
[11:21:30] Starting 'build.js.dev'...
/myweb/as2/node_modules/@angular/compiler/src/private_import_core.d.ts(17,46): error TS2339: Property '_ViewContainer' does not exist on type '{ isDefaultChangeDetectionStrategy: (changeDetectionStrategy: ChangeDetectionStrategy) => boolean...'.
```

** My environment **
OSX El Capitan 10.11.6, PHPStorm, NPM

* **Angular Seed Version:** `4a0209c`

* **Node:** `node --version` = v7.2.0

**Comment by mgechev** [comment]
Hey @telvin, this is module for Angular ^1.3.5. For an alternative modules take a look at [this](https://www.npmjs.com/package/angular2-cookie), or [this one](https://www.npmjs.com/package/ng2-cookies).

**Comment by telvin** [comment]
Thank you to look at this for me. You are also giving me the reference to exactly the module I am using (ng-cookies2). It is implemented for Angular 2. I also tried on both of angular2-cookie and ng2-cookies though. I have to emphasize that I can build and use them normally on this seed project, but the problem only happens when I run the test, karma cannot understand the keyword export and define. I found a reference on stackoverflow and they told that the module is using the commonJs, and if I use SystemJs to load it, I have spend more effort to do it, but I have no clue how to change the config to overcome.

**Comment by mgechev** [comment]
Misunderstanding from this paragraph with the highlighted link:

<img width="676" alt="screen shot 2016-11-28 at 17 35 48" src="https://cloud.githubusercontent.com/assets/455023/20693126/26c26596-b591-11e6-9c20-b7029e376578.png">

Late this week I'll take a look at the issue. Most likely it's not SystemJS related but based on misconfiguration. SystemJS supports CommonJS, AMD, SystemJS modules.

**Comment by mgechev** [comment]
@telvin sorry for the delay, I had quite busy two weeks. Here's how you can configure this package:

```ts
// In the constructor in your project.config.ts
let additionalPackages: ExtendPackages[] = [{
  name: 'ng2-cookies',
  packageMeta: {
    main: 'index.js'
  }
}];

this.addPackagesBundles(additionalPackages);
```

**Comment by telvin** [comment]
@mgechev Awesome, it works like a charm. Thank you.

**Comment by lakshman-wta** [comment]
hi mgechev
I got one bug .can you help me?

I install any module through npm get like

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 w
as not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and select
ing "Retarget solution". [E:\Lakshman\angular-seed-master\node_modules\weak\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Lakshman\angular-seed-master\node_modules\weak
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package express is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ sweetalert2@6.6.8
added 116 packages and updated 1 package in 20.143s
