### ISSUE TITLE
Cannot find external dependency using `build.prod.exp`

### ISSUE THREAD

**Issue by owndann** [mgechev/angular-seed#1683]
- [x] Bug Report

**Current behavior**
when i run `npm run build.prod.exp` i'm getting an error when the task of 
'compile.ahead.prod' starts that the task cannot find a external dependency in this case is jQuery i create my own manual typing for it and i don't know if this is the issue but 

**Expected behavior**
it should get the external dependency and compile. 

**environment:**
macOs Sierra  10.12.1 
Atom 
Using yarn.

* **Angular Seed Version:** `lastest`

* **Node:** `node --version` = v6.7.0
npm 3.10.3

This is what i get on my promt 

```
[15:29:51] Starting 'compile.ahead.prod'...
Error: Error at /dist/tmp/app/shared/news/news.component.ts:4:25: Cannot find module 'jquery'.
Error at /dist/tmp/app/shared/news/news.component.ts:26:5: Cannot find name 'jQuery'.
Error at /dist/tmp/app/shared/news/news.component.ts:30:5: Cannot find name 'jQuery'.
Error at /dist/tmp/app/shared/whyus/whyus.component.ts:4:25: Cannot find module 'jquery'.
Error at /dist/tmp/app/login/resetpassword/reset-password.component.ts:10:25: Cannot find module 'zxcvbn'.
    at check (/development/tools/@angular/tsc-wrapped/src/tsc.ts:43:11)
    at Tsc.typeCheck (/development/tools/@angular/tsc-wrapped/src/tsc.ts:104:5)
    at development/tools/@angular/tsc-wrapped/src/main.ts:47:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
Compilation failed
```

**Comment by mgechev** [comment]
This is a typing error which you need to resolve. For further information take a look at [this article](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/).

**Comment by owndann** [comment]
i just resolve the jquery typing error but i have a issue with a manual typing and i don't know how to fix this.
