### ISSUE TITLE
Cannot run npm run build.prod

### ISSUE THREAD

**Issue by victorcarvalhosp** [mgechev/angular-seed#1684]
With npm start everything work's fine, but when I try to run "npm run build.prod" I'm gettin the following error in my two diferent projects...:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\victo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build.prod' ]
2 info using npm@3.10.9
3 info using node@v4.4.2
4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
5 info lifecycle angular-seed@0.0.1~prebuild.prod: angular-seed@0.0.1
6 silly lifecycle angular-seed@0.0.1~prebuild.prod: no script for prebuild.prod, continuing
7 info lifecycle angular-seed@0.0.1~build.prod: angular-seed@0.0.1
8 verbose lifecycle angular-seed@0.0.1~build.prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed@0.0.1~build.prod: PATH: C:\Users\victo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\victo\Documents\DEV\workspace\medipop\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Java\jdk1.8.0_65\bin;C:\Users\victo\Documents\DEV\adt-bundle-windows-x86_64-20140702\sdk\tools;C:\Users\victo\Documents\DEV\adt-bundle-windows-x86_64-20140702\sdk\platform-tools;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Users\victo\Documents\DEV\apache-maven-3.3.9\bin;C:\Users\victo\Documents\DEV\putty;C:\Ruby23-x64\bin;C:\Users\victo\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\victo\AppData\Local\Microsoft\WindowsApps
10 verbose lifecycle angular-seed@0.0.1~build.prod: CWD: C:\Users\victo\Documents\DEV\workspace\medipop
11 silly lifecycle angular-seed@0.0.1~build.prod: Args: [ '/d /s /c',
11 silly lifecycle   'gulp build.prod --color --env-config prod --build-type prod' ]
12 silly lifecycle angular-seed@0.0.1~build.prod: Returned: code: 1  signal: null
13 info lifecycle angular-seed@0.0.1~build.prod: Failed to exec build.prod script
14 verbose stack Error: angular-seed@0.0.1 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\victo\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\victo\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular-seed@0.0.1
16 verbose cwd C:\Users\victo\Documents\DEV\workspace\medipop
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\victo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
19 error node v4.4.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error angular-seed@0.0.1 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
22 error Exit status 1
23 error Failed at the angular-seed@0.0.1 build.prod script 'gulp build.prod --color --env-config prod --build-type prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod --color --env-config prod --build-type prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mgechev** [comment]
It will be great if you can fill the issue template in order to give us the required information to resolve the problem:

```
<!--
IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING
-->

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
<!-- Describe how the bug manifests. -->

**Expected behavior**
<!-- Describe what the behavior would be without the bug. -->

**Minimal reproduction of the problem with instructions**
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem.
-->

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->

* **Angular Seed Version:** `aaaaf75`
<!-- Check which is the hash of the last commit from angular-seed that you have locally -->

* **Node:** `node --version` =
```

**Comment by mgechev** [comment]
What version of the seed are you using?

**Comment by victorcarvalhosp** [comment]
how can I see the seed version? (I do not clone the project, I downloaded the project on 11/23)

**Comment by mgechev** [comment]
Would you try with a clean clone and tell me if the issue is still reproducible? Also try the solutions of the already solved problems, most likely solution already exists if they are closed.

**Comment by rossedfort** [comment]
It seems to be caused by the latest version of @types/gulp-util (3.0.29) released earlier this afternoon

temporary fix: in package.json fix @types/gulp-util's version to be 3.0.28

src: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12997

**Comment by victorcarvalhosp** [comment]
I changed the @types/gulp-util's to 3.0.28 and still got the error...
With a clean clone worked... I will add primeNg again and see if still works...

**Comment by rossedfort** [comment]
Interesting, it worked for my project. It may just be a discrepancy in our dependencies. ( I haven't updated my app to reflect the latest angular-seed changes in a month or so)

**Comment by rossedfort** [comment]
Yeah a fresh clone built production fine for me as well. It must be a conflict with your dependencies. I would copy the devDependencies from the latest version of this repo into your project and see if that does it.

**Comment by victorcarvalhosp** [comment]
I'm wrong about my last comment... With a clean clone the error still occurs:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\victo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build.prod' ]
2 info using npm@4.0.2
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
5 info lifecycle angular-seed@0.0.0~prebuild.prod: angular-seed@0.0.0
6 silly lifecycle angular-seed@0.0.0~prebuild.prod: no script for prebuild.prod, continuing
7 info lifecycle angular-seed@0.0.0~build.prod: angular-seed@0.0.0
8 verbose lifecycle angular-seed@0.0.0~build.prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed@0.0.0~build.prod: PATH: C:\Users\victo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\victo\Documents\DEV\angular-seed\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Java\jdk1.8.0_65\bin;C:\Users\victo\Documents\DEV\adt-bundle-windows-x86_64-20140702\sdk\tools;C:\Users\victo\Documents\DEV\adt-bundle-windows-x86_64-20140702\sdk\platform-tools;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Users\victo\Documents\DEV\apache-maven-3.3.9\bin;C:\Users\victo\Documents\DEV\putty;C:\Program Files\nodejs\;C:\Ruby23-x64\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\victo\AppData\Local\Microsoft\WindowsApps;C:\Users\victo\AppData\Roaming\npm
10 verbose lifecycle angular-seed@0.0.0~build.prod: CWD: C:\Users\victo\Documents\DEV\angular-seed
11 silly lifecycle angular-seed@0.0.0~build.prod: Args: [ '/d /s /c',
11 silly lifecycle   'gulp build.prod --color --env-config prod --build-type prod' ]
12 silly lifecycle angular-seed@0.0.0~build.prod: Returned: code: 1  signal: null
13 info lifecycle angular-seed@0.0.0~build.prod: Failed to exec build.prod script
14 verbose stack Error: angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\victo\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\victo\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-seed@0.0.0
16 verbose cwd C:\Users\victo\Documents\DEV\angular-seed
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\victo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
19 error node v6.9.1
20 error npm  v4.0.2
21 error code ELIFECYCLE
22 error angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
22 error Exit status 1
23 error Failed at the angular-seed@0.0.0 build.prod script 'gulp build.prod --color --env-config prod --build-type prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod --color --env-config prod --build-type prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by victorcarvalhosp** [comment]
closing because a fresh clone worked
