### ISSUE TITLE
Additional includes/excludes for lint task

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#1686]
I've got a project using some code generated from Swagger. However, the generated code fails some linting checks. Ideally, I'd rather not have to keep manually tweaking it to avoid the lint warnings.

What do you think about a new SeedConfig property to specify additional globs to include or exclude from linting, which can be overridden in ProjectConfig?

Something like this in Config:
```ts
TSLINT_CONFIG: { includes: string[], excludes: string[] } = {
  includes: [],
  excludes: [] // e.g.: ["**/app/core/models/generated/*.ts"]
};
```

And something like this in `tslint.ts`:
```ts
let src = [
  join(Config.APP_SRC, '**/*.ts'),
 ...other entries omitted for brevity...
];

Config.TSLINT_CONFIG.includes.forEach(
  entry => src.push(join(Config.APP_SRC, entry))
);

Config.TSLINT_CONFIG.excludes.forEach(
  entry => src.push('!' + join(Config.APP_SRC, entry))
);
```

If you think that looks all right, let me know and I can shoot over a pull request.

**Comment by brian428** [comment]
May not even need the includes option, since by default everything is included already. Or, maybe the includes/excludes would specify the full path themselves, rather than assuming they're under `APP_SRC`? Meaning in theory you could include things outside of `APP_SRC` for some reason?

**Comment by mgechev** [comment]
Hey @brian428, currently you can exclude a file by using `/** tslint: disable */` and placing it in the beginning of the file. Lets keep it this way and not introduce additional configuration options for now.

**Comment by brian428** [comment]
OK, I've already got a custom task to allow for this. The issue is that I have a whole directory of generated files that get updated (re-generated) regularly. Obviously, manually adding tslint comments to every file each time they change isn't really an option. The custom task works fine, I just thought I'd mention it in case anyone thought it was worth adding into the seed. Thanks.

**Comment by mgechev** [comment]
Thanks for the suggestion! I definitely see value in it but I felt that it is more like a customization and I see that you approached this way too.
