### ISSUE TITLE
My app is really slow on live

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1688]
My app is running slow on live. 

It takes 10 seconds on mobile to load.
It takes 5 seconds on desktop to load.

This is my website: https://thepoolcover.co.uk

**Things I'm doing / tried:**

- I've compressed images and are on CDN the large ones.
- I minify css.
- I minify js.
- I use async and defer on my scripts.
- I use cloudflare for ssl and speed up the site.
- The scripts are small and the app only takes 500ms to load but it takes 5 seconds for dom to show.
- I commented out al lthe scripts to see if render blocking was issue.
- I spoke to host to see if any server errors. None reported.
- I used google speed test and get 75% desktop and 51% on mobile.
- I use CDN for scripts.
- My website in general is small.

Is there some sort of setting to this app to make it run faster?

*Let me know if you need more information about my app and any other things I can do.

**Comment by mgechev** [comment]
You can apply lazy loading and for smaller bundles.

**Comment by markoddi01** [comment]
How do I do that?

Do you know why the websites running slow?

**Comment by markoddi01** [comment]
@mgechev  I've use project config to add all ym third party local scripts. But locally and on live my angular2 app takes 4seconds to load. Is there something in my code that could be slowing it down? do you know any think I could look for in my code to remove?

**Comment by ultimatedion** [comment]
@markoddi01 On my side, it looks like it is your calls to firebaseio.com that takes some times.
