### ISSUE TITLE
In project.config how do you add third party css?

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1690]
In project.config how do you add third party css?

This is what I have so far but doesnt seem to add these css files:

      this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: './../../src/client/resources/animate.css', inject: 'css'},
      {src: './../../src/client/resources/bootswatch.css', inject: 'css'},
      {src: './../../src/client/resources/fonts.css', inject: 'css'},
      {src: './../../src/client/resources/fontAwesome.css', inject: 'css'}     
    ];

**Comment by mgechev** [comment]
Please take a look at the wiki and other already resolved issues.
