### ISSUE TITLE
Base href ignored for angular routes

### ISSUE THREAD

**Issue by visitsb** [mgechev/angular-seed#1692]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Setting base href explicitly or either using APP_BASE doesn't seem to be honored. Routes and injected css, js switch to using /

**Expected behavior**
I am not using / for my Angular app, and would like to use my sub-folder. Angular docs mention setting base href, and routes would automatically update.
Similar case is with dist files. All are using /, whereas they should use APP_BASE or relative paths instead.

**Minimal reproduction of the problem with instructions**
Start and serve under nginx as a proxy with a sub-folder. Set this subfolder as base href in index.html. You encounter a route not found exception.

**What is the motivation / use case for changing the behavior?**
Well ... not everyone will want to use a dedicated server, will they?

**Please tell us about your environment:**
CentOS, Nginx as reverse proxy

* **Angular Seed Version:** `aaaaf75`
 99594f9

* **Node:** `node --version` =
Node v6.9.1
Npm 3.10.8

**Comment by mgechev** [comment]
It works fine for me. How are you setting the base path? Are you using:

```
npm run build.prod **-- --base /my-app/**
```

**Comment by visitsb** [comment]
Thanks, I was setting `APP_BASE` in `ProjectConfig` in `tools/config/project.config.ts`, however that didn't work.

👍  Your suggestion to set --base worked, thanks.
