### ISSUE TITLE
Does this app have ahead of time compilation? because my app file loads really slowly

### ISSUE THREAD

**Issue by markoddi** [mgechev/angular-seed#1693]
Does this app have ahead of time compilation? because my app file loads really slowly.

I'm experiencing a 4 second delay which could be because this app uses Just-in-Time instead of Ahead-of-Time.

Questions:

1) If AOT (https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) doesn't exist in the app, will you be adding it?

2) Is there a way I can speed up the minified app file because its slow at compiling I think and showing the view for a route on load or refresh.

People are saying to move to webpack but I'd rather stay with your app and make it faster on-load if possible.

This is my website: https://thepoolcover.co.uk/

I look forward to hearing your response.

Thank you.

**Comment by TheDonDope** [comment]
Hi @markoddi, yes the seed supports AoT: https://github.com/mgechev/angular-seed#how-to-start-with-aot-compilation

**Comment by markoddi** [comment]
@TheDonDope thanks for your reply. Do I simply just run npm run build.prod.exp once ive updated my node version?

**Comment by mgechev** [comment]
Yes, you simply run `npm run build.prod.exp` instead of `npm run build.prod`. Note that there are some differences between AoT and JiT. You can read more about them on angular.io or [here](http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/).

**Comment by markoddi** [comment]
@mgechev I just read your blog. Very good I must say (http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/). I've read about the differences. Tomorrow I will test aot command on my code. One more thing... my website is called thepoolcover.co.uk and takes 4 seconds to load with JIT e.g. the npm run serve.prod command. By running "npm run build.prod.exp" will I get my website load time to 2-3seconds?

**Comment by mgechev** [comment]
AoT is only one of the optimizations. Take a look at the [performance checklist](https://github.com/mgechev/angular-performance-checklist).

**Comment by markoddi** [comment]
@mgechev Do you have all of the network optimizations in place from that checklist e.g. https://github.com/mgechev/angular-performance-checklist#network-performance

**Comment by sfabriece** [comment]
I'm curious, how many things on the checklist are provided by the seed and could a wiki be made of additions/changes one would have to make to come close to the ideal output/configuration. 

Thanks

**Comment by mgechev** [comment]
We have everything which is table and works in the general case:

- Bundling
- Minification & dead code elimination (not tree-shaking yet because I'm not confident in rollup and commonjs modules)
- AoT

Developers have to configure for their deployment:

- Compression
- Caching
- Service Workers

For service workers you can use the Angular Mobile Toolkit. 

Lazy loading is available in the lazy branch. Note that it is experimental and not complete!

**Comment by sfabriece** [comment]
Thanks 👍
