### ISSUE TITLE
Images referenced in CSS as background-image missing from production build

### ISSUE THREAD

**Issue by hhubik** [mgechev/angular-seed#1695]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I am running into trouble with background images referenced in `main.css` that are missing from the production build. I am using the latest (as of December 4) seed on Windows 8.1. and a third-party theme that has a css file located at
`node_modules/primeng/resources/themes/delta/`.

The css file includes this 

```
...
.ui-icon,
.ui-widget-content .ui-icon,
.ui-widget-header .ui-icon {
  background-image: url(images/ui-icons_222222_256x240.png);
}
...
```
which works fine in dev build because the background image is located in 
`node_modules/primeng/resources/themes/delta/images/`

However, I don't see any `images` directory in the `/dist/prod/css` which is where `main.css` is that contains the above css rule.

Is this an issue with the production build or do I need to add a step to the production build myself (if so, where?) that would copy `node_modules/primeng/resources/themes/delta/images/`  to `/dist/prod/css/images`?

* **Node:** `node --version` = 6.9.1

**Comment by Shyam-Chen** [comment]
`background-image: url("images/ui-icons_222222_256x240.png");` ?

**Comment by hhubik** [comment]
@Shyam-Chen 
Interesting. The third-party CSS indeed uses an unqouted URL in the url function, and that is what got copied into `main.css` that the above code snippet is from. But ...

this [https://developer.mozilla.org/en-US/docs/Web/CSS/url#The_url()_functional_notation](https://developer.mozilla.org/en-US/docs/Web/CSS/url#The_url()_functional_notation) says

> The URL may be unquoted, or quoted by single or double quotes. Relative URLs are allowed and are relative to the URL of the stylesheet (not to the URL of the web page).

So that should not be an issue.

**Comment by mgechev** [comment]
@hhubik do you copy the images to the production directory? You may need to make sure that the path in the CSS files is correct.

**Comment by hhubik** [comment]
@mgechev  no, I do not.  I was not sure if the process that creates `main.css` is also supposed to copy the images.  If I need to copy the images myself, is there an example (or instructions) on how to do that as part of the seed build process?

**Comment by mgechev** [comment]
In general [this task](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/build.assets.prod.ts) is supposed to copy all the assets. For example, there's image called "more.svg" which is being copied from the [svg directory here](https://github.com/mgechev/angular-seed/tree/master/src/client/assets).

**Comment by hhubik** [comment]
@mgechev Thanks.
