### ISSUE TITLE
When I run serve.prod.exp I get a type definition error because of missing Firebase type definiations

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1697]
When I run **run run serve.prod.exp** I get a type definition error.

This is when I run the command in git bash.

Error is: Error: Cannot find type definition file for 'Firebase'

My app uses Firebase and it seems I need to add the type Firebase some where.

Where do I add 'firebase' for serve.prod.exp to work? 

This is my attempt at adding the file firebase.d.ts:

![firebase](https://cloud.githubusercontent.com/assets/2556223/20971344/0ca8e21c-bc89-11e6-83be-99a3984e4401.png)

This is me trying to add firebase to tsconfig:

![tsconfig](https://cloud.githubusercontent.com/assets/2556223/20971433/52539028-bc89-11e6-86c3-2d2400919311.png)

**Below is a screen shot of the error:**

![errorserving](https://cloud.githubusercontent.com/assets/2556223/20970307/d4f3a86a-bc84-11e6-9dc8-359fddcab171.png)

**Comment by owndann** [comment]
i have the same problem with my own jquery type definition but i have another type definition of zxcvb and this works  :(

**Comment by mgechev** [comment]
@owndann there are a lot of issues closed regarding collision between Protractor's type definitions and jQuery. You can search for the answer there.

@markoddi01 you should use `npm i @types/firebase --save-dev`. Take a look at [this article](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/).
