### ISSUE TITLE
if had a better style for config environment?

### ISSUE THREAD

**Issue by acivang** [mgechev/angular-seed#1699]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

Hello everyone, after added env config, we had to set the environment value in 'tools/env/env-config.interface.ts'. the app's environment config file is under app, but we use it in gulp tools environment config file with relative path.I did not think it is a good style. What about set a dev api config file and a prod api config file, and config them in seed.config.ts? or someone had better method?

Thx for the better seed!

**Please tell us about your environment:**

* **Angular Seed Version:** `7f55f7e0d968e6b3f74cddad65b88c0c2c312c0a `

* **Node:** `node --version` = v7.2.1

**Comment by mgechev** [comment]
If we don't want to have such a relative import in the tools directory, we need to drop the interface either in tools or in app, or introduce it twice and maintain it the same on both places.

I don't like any of these two ideas so I prefer the relative path, although I agree that it doesn't look perfect.

**Comment by acivang** [comment]
Thank for your reply very much!
