### ISSUE TITLE
 Serve.prod.exp error on module when serving the app for AOT

### ISSUE THREAD

**Issue by markoddi** [mgechev/angular-seed#1702]
When I run serve.prod.exp I get an issue for my module.

It doesnt seem to like this line of code in my module: **AgmCoreModule.forRoot();**

**This is my module below:**

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule} from '@angular/forms';

import { AgmCoreModule } from 'angular2-google-maps/core';

@NgModule({
  imports: [CommonModule, RouterModule, FormsModule, AgmCoreModule.forRoot({apiKey: 'I've hidden my key'})],
  declarations: [NewJobComponent],
  exports: [NewJobComponent],
  providers: []
})
export class NewJobModule { }
```

Do I need to write this another way: AgmCoreModule.forRoot();

I have added AgmCoreModule as a dependency in the project config. And this code seems to work fine for serve.prod. But I'm trying to get AOT working instead of JIT. It just doesnt work for serve.prod.exp

I look forward to your responses.

**Comment by mgechev** [comment]
Some programs which work with JiT don't work with AoT. The reason is that with AoT metadata needs to be statically resolvable. You can look for similar issues in the Angular's issue tracker, the problem is not in the seed.

**Comment by markoddi** [comment]
@mgechev I understand. What other ways would you advise to improve performance of this seed app. Its very slow at 4-5 seconds to load each time. My customers are not happy. This is my url : thepoolcover.co.uk

**Comment by xalexslx** [comment]
@mgechev Can you please explain it better and how is possible to solve this problem? I'm experiencing the same problem. Honestly, I've tried to get help many times in the gitter chat but no one was willing to help me. I was tempted to create an issue as well. Maybe just leave a tag to people ask for help.

```
Error: Unexpected value 'FileUploadModule' imported by the module 'SCWidgetModule'
    at /Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:14675:33
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/alexslx/socialcondo/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/Users/alexslx/xxxx/sc-web/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
Compilation failed
```

**Comment by markoddi** [comment]
@xalexslx are you trying to improve your overall performance? if so have you tried many other ways?

**Comment by xalexslx** [comment]
@markoddi I'm trying to setup AoT to improve javascript performance time and then split up my js bundle to use lazy loading in order to load modules just when needed. However, I can't find good explanation how to fix the modules not working with AoT

**Comment by markoddi** [comment]
Same here. I need to improve performance. My apps 4 seconds slow each time on loading because of the minified app file. Have you tried just doing the lazy loading for now? if so how do you do lazy loading for it?

**Comment by xalexslx** [comment]
@markoddi I haven't tried yet. Probably needs to modify a lot of configuration files specially with systemjs which I suck at.

**Comment by markoddi** [comment]
@xalexslx yeah I have no idea what I'm doing either lol I could really do with some more guidance. Or some other performance things I could try.

**Comment by markoddi** [comment]
I'd be happy to get the app down to 2 seconds load time

**Comment by markoddi** [comment]
@mgechev is there another way for us to improve performance to our apps without going down the AOT route?

**Comment by markoddi** [comment]
@xalexslx there is blog: http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/ it refers to building an app for prod. I havent tried any of these things. I will tonight. I will let you know if any work. Let me know if you have any success.

**Comment by xalexslx** [comment]
@markoddi I partially fixed my error updating all libraries to latest version so they support AoT with a metadata configuration. However, I have one library which doesn't have it yet... angular2-infinite-scroll.

Try to update your library or create an issue there asking for AoT support. Please let me know if worked or if you find any other way to solve the issue.

**Comment by mgechev** [comment]
@xalexslx this is a type error that you need to resolve. Yes, you cannot use library which is not distributed with metadata.

**Comment by markoddi01** [comment]
@mgechev  I just ran **$ ls -lah app.js** and its 1.6mb. This is for my app.js prod. I'm guessing thats why the app takes 4 seconds to load? is there any other ways to make this file smaller. Currently I do npm run serve.prod to get it down to 1.6mb.
