### ISSUE TITLE
 App.js.gz not working with my production app

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1703]
@mgechev I just ran $ ls -lah app.js and its 1.6mb. This is for my app.js prod. I'm guessing thats why the app takes 4 seconds to load? is there any other ways to make this file smaller. Currently I do npm run serve.prod to get it down to 1.6mb.

I've done compression using these commands from your blog article:

$ gzip bundle.min.js
$ ls -lah bundle.min.js.gz

It got it down to 300k but called the file app.js.gz

Can I use app.js.gz for my live site now?

I've also just made a stackoverflow question: http://stackoverflow.com/questions/41047617/angular2-gzip-issue-when-i-run-my-app

I get this error:

app.js.gz?1481224056468:1 Uncaught SyntaxError: Invalid or unexpected token

This is my code:

![bug1](https://cloud.githubusercontent.com/assets/2556223/21027254/e1611aca-bd87-11e6-9248-013b4735b4d3.png)

**Comment by mgechev** [comment]
This is not how [it works](https://www.google.be/search?q=gzip+apache+nginx&oq=gzip+apache+nginx&aqs=chrome..69i57j0l3.5392j0j1&sourceid=chrome&ie=UTF-8).
