### ISSUE TITLE
The seed app doesn't work in production for lazy loading of module / routes

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1705]
The seed app doesn't work in production for lazy loading of module / routes

I get this error in production

Error: app.js?1481319435885:43 EXCEPTION: Uncaught (in promise): TypeError: System.import is not a function

This is the website visual console error: https://poolcover-dev.firebaseapp.com/terms

I followed the instructions of this plunker: https://plnkr.co/edit/SGsAFpGhFX3vg3PysjnX?p=preview

It works fine locally with npm run start. But when I push live or do npm run serve.prod it give the above error.

Are there any settings I need to do for this to work in prod?

**Comment by markoddi01** [comment]
@mgechev do I need to do something to the system.config for lazy loading of certain modules to work in serve.prod?

**Comment by mgechev** [comment]
Well, we don't officially support lazy loading although **it does work** in the lazy branch.
