### ISSUE TITLE
Multiple anonymous defines in module

### ISSUE THREAD

**Issue by Robophil** [mgechev/angular-seed#1706]
Hi,
Am trying to use `sails.io.js` library in my project. I followed the instruction [here](https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2) to get it included and register, but i keep finding this issue

![image](https://cloud.githubusercontent.com/assets/6032018/21066278/0dec154e-be65-11e6-9f13-6d71bc1803a4.png)

I've gone through closed issues like #1551 and still couldn't find a fix. 

```javascript
// Add packages (e.g. lodash)
    let additionalPackages: ExtendPackages[] = [{
      name: 'socket.io',
      path: `${this.APP_BASE}node_modules/socket.io-client/dist/`,
      packageMeta: {
        main: 'socket.io.js',
        defaultExtension: 'js'
      }
    }, {
      name: 'sails.io',
      path: `${this.APP_BASE}node_modules/sails.io.js/dist/`,
      packageMeta: {
        main: 'sails.io.js',
        defaultExtension: 'js'
      }
    }
```

**Comment by mgechev** [comment]
Duplicateion of https://github.com/mgechev/angular-seed/issues/1551.

**Comment by Robophil** [comment]
@mgechev I just stated and referred to #1551 and the solution didn't work for me.
