### ISSUE TITLE
Lazy loading not work in lazy branch when you serve.prod

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1707]
Lazy loading not work in lazy branch when you serve.prod.

I pulled the latest branch and it only works with npm run start and not npm run serve.prod.

I didnt add any of my code. I just ran yours.

This is my error:

![lazyerror](https://cloud.githubusercontent.com/assets/2556223/21073366/4b923062-bed4-11e6-9815-64ad329281fb.png)

**Comment by mgechev** [comment]
We do not officially support lazy loading, as I mentioned previously. The lazy branch is not tested under windows so most likely you'll have to tweak the SystemJS configuration.

Better take a look at the systemjs docs. Good luck.
