### ISSUE TITLE
Question: whats the best way to make this app load faster?

### ISSUE THREAD

**Issue by markoddi01** [mgechev/angular-seed#1710]
Question: whats the best way to make this app load faster?

I've tried loads of things in your documentation and everytime I try one there seems to be an error of some sort. The only thing I got working was lazy loading, which doesnt work in prod.

I need a way of making my app load faster than 4 seconds with this app.

I've spent nearly 3 weeks on doing this now.

I really need some help here

**Comment by mgechev** [comment]
Please, do not bring other off topics. In your other issues I pointed out resources that you can use to read more about how you can improve your application's runtime and network performance.
