### ISSUE TITLE
Support for asynchronous routing with lazy loaded bundles

### ISSUE THREAD

**Issue by denissb** [mgechev/angular-seed#1716]
I'm submitting a feature request.

I think currently this is the most mature Angular starter out there that is using SystemJS.
But sadly [Asynchronous Routing](https://angular.io/docs/ts/latest/guide/router.html#!#milestone-6-asynchronous-routing) is missing, and that is a crucial feature for most production apps.

Currently the build.prod task generates a single static (self-executable) bundle which can become quite big and delay the initial app load time. It would be good to have something like this instead:

```
.
├── dist
│   └── js
│       ├── vendor.js
│       ├── app.js
│       ├── route1.js
│       ├── route2.js
│       └── route..
``` 

I know most Webpack starters provide it out of the box now, so it would be cool to have it in a SystemJS starter, even if the structure is slightly pre-defined.

**Comment by mgechev** [comment]
Here's a demo https://github.com/mgechev/angular-seed/pull/1714. There's also a lazy branch which demonstrates a simplified version.

**Comment by denissb** [comment]
Thank you Minko!
