### ISSUE TITLE
docker and local development 

### ISSUE THREAD

**Issue by lmkerr** [mgechev/angular-seed#1717]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
No way of running docker instance and developing in container without building each time.

**Expected behavior**
Would like to be able to do something along the lines of 

> docker-compose up

and then navigate to the root of the seed and update my code at runtime for the dev environment.

**What is the motivation / use case for changing the behavior?**
Dockerizing my teams developer environment

**Please tell us about your environment:**
Operating systems vary from OS-X and Windows 7

* **Angular Seed Version:** `b218eeb`

* **Node:** `node --version` = 6.6

**Comment by Shyam-Chen** [comment]
@lmkerr build and test in Docker?

**Comment by lmkerr** [comment]
Well, I'm fairly new to docker, but right now it appears the "volumes" attribute is only pointing at the production build. While I haven't tested the functionality for that, I don't really ever see the need for it. What I'd like to see is, similarly, having the volumes attribute inside of the development docker so that my team members can spin up the docker instance, target the provided path in visual studio code, and then modify the code in real time so that a docker build isn't necessary afterwards. And if possible (really not sure the logistics here would work or not), have the gulp watch task and other dev dependencies functional during this time as well.

**Comment by Shyam-Chen** [comment]
@lmkerr Sample build, test, and deploy in Docker container on Firebase.

https://travis-ci.org/Shyam-Chen/Web-Starter-Kit/jobs/185110461

**Comment by mgechev** [comment]
@lmkerr let's close this issue for now it gets higher in the priority queue or someone from the team is available to implement it. If you have some time a PR will be appreciated!
