### ISSUE TITLE
Router issue Cannot match any routes even though Router config has route

### ISSUE THREAD

**Issue by harshpatel79** [mgechev/angular-seed#1719]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by harshpatel79** [comment]
Hey folks,

Can you help me out in this.

**Comment by mgechev** [comment]
Hey @harshpatel79, this is not an issue in Angular seed but misconfigured routing config. I'd recommend you to take a look at angular.io, or try Angular's gitter channel.
