### ISSUE TITLE
DO NOT set PROD_DEST = '/'; ~ Node and Windows System failure

### ISSUE THREAD

**Issue by uiuxdeveloper** [mgechev/angular-seed#1720]
WARNING: 
DO NOT set PROD_DEST = '/';

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Crashed my entire system and had to reinstall multiple programs including node, adobe suite, mozilla, git, etc.  My entire windows desktop and anything saved to it were also destroyed.

Results:
clean.prod tasks starts wiping out your system applications, shortcuts, etc.

**Expected behavior**
clean.prod should be scoped to only affect the local app

**Minimal reproduction of the problem with instructions**
- Open seed.config.ts
- Set the following config setting
  PROD_DEST = '/';
- Process a production build
  npm run build.prod

--- DEV_DEST should be tested and confirmed too ---

**What is the motivation / use case for changing the behavior?**
- was trying to get build assets and index.html to be generated outside of the default dist/prod directory

**Please tell us about your environment:**
Windows7
local dev environment specified by seed setup

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 
7.2.1

**Comment by mgechev** [comment]
The project will now block you if you try to remove files outside the project root. Take a look at this PR https://github.com/mgechev/angular-seed/commit/6c2536fe126635501659a1a5a726a1bdbc8fc0ca.

**Comment by uiuxdeveloper** [comment]
Thanks for your quick response.  I'm still recovering on this end, but hey
the amount of time it takes to recover pails in comparison to the work and
effort you put into this seed.  thanks!

**Comment by mgechev** [comment]
We've never expected such behavior/configuration. Hopefully with the next PR we'll prevent it from happening.
