### ISSUE TITLE
Use-Case: ts-node on the development server is not globally installed

### ISSUE THREAD

**Issue by webia1** [mgechev/angular-seed#1722]
[ x ] feature request

Is there an existing feature/way to bypass this problem? Without ts-node globally installed, we get errors like `Failed to load external module ts-node/register` etc.

Use-Case: Ts-node is not globally installed yet, requires further permissions from security/commission department.  In the mean time we have to setup our angular2 technology stack incl. this seed.

**Comment by mgechev** [comment]
Yes, you can precompile all the tasks and use the output JavaScript instead:

```
tsc --project tsconfig.json
npm start
```

**Comment by webia1** [comment]
Hi Minko @mgechev 

in which task should I place it best? In postinstall before gulp check.versions?

thank you!
