### ISSUE TITLE
docker: use yarn instead of npm install

### ISSUE THREAD

**Issue by wodCZ** [mgechev/angular-seed#1723]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
docker uses `npm install` to install dependencies as specified [here](https://github.com/mgechev/angular-seed/blob/master/.docker/angular-seed.production.dockerfile#L19)

**Expected behavior**
docker uses `yarn`, which respects `yarn.lock` lockfile and installs same revisions of dependencies. This should avoid "works on my pc" problems and there is no reason to not use yarn when angular-seed already has `yarn.lock`.

**What is the motivation / use case for changing the behavior?**
⬆️ 

---

While I'm not very experienced with Docker, I think I could prepare PR for this, if you find this feature useful.

**Comment by mgechev** [comment]
@wodCZ would you open a PR with the change?

**Comment by wodCZ** [comment]
After a quick try it seems that it won't be that easy, currently I'm stuck on following error:
<details>
<summary>error /home/app/angular-seed/node_modules/phantomjs: Command failed.</summary>
<pre>
error /home/app/angular-seed/node_modules/phantomjs: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /home/app/angular-seed/node_modules/phantomjs
Output:
PhantomJS not found on PATH
Phantom installation failed TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at findSuitableTempDirectory (/home/app/angular-seed/node_modules/phantomjs/install.js:127:30)
    at /home/app/angular-seed/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/home/app/angular-seed/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at findSuitableTempDirectory (/home/app/angular-seed/node_modules/phantomjs/install.js:127:30)
    at /home/app/angular-seed/node_modules/phantomjs/install.js:476:19
    at nextTickCallback (/home/app/angular-seed/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
</pre>
</details>

I will have a look at this later when I have more time.

**Comment by joshboley** [comment]
After looking through the code, it seems that `npm` commands are the ones currently being used throughout in both CI and Docker configurations.  It seems strange to offer users yarn but not fully commit to it in the code.  Another thing to consider is that installing yarn on a build server is not going to be easy for all users.  Lots of companies have red tape around what can and can't be installed on the build servers.  I, personally, prefer to just use npm.  If you need to lock your dependency versions, you can use `npm shrinkwrap`.

**Comment by wodCZ** [comment]
@joshboley thank you for your response. I'm aware of `npm shrinkwrap`.
That's true, it will be better to be consistent and stay with `npm`.

Should I close this issue, or do you want to discuss more about this?

Thanks for your time!

**Comment by joshboley** [comment]
I don't have any more comments.  In my opinion, it's best to stick with npm.  However, @wodCZ may have more to say about it.
