### ISSUE TITLE
Task 'clean.i18n' is not in your gulpfile

### ISSUE THREAD

**Issue by fridolin-koch** [mgechev/angular-seed#1729]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Running `npm run i18n` fails with error `Task 'clean.i18n' is not in your gulpfile`

**Expected behavior**
No errors occur while executing  `npm run i18n` 

**Minimal reproduction of the problem with instructions**
`npm run i18n`

**What is the motivation / use case for changing the behavior?**
i18n extraction

**Please tell us about your environment:**
Linux, PHPStorm 2016.3.1, Yarn

* **Angular Seed Version:** `d749869`

* **Node:** `node --version` = v6.9.1

**Comment by mgechev** [comment]
Using i18n is not straightforward at the moment. You will have to add the i18n task yourself and also follow the guide: https://github.com/mgechev/angular-seed/wiki/Enabling-Angular-i18n-native

I'm waiting for a more mature version of the official i18n module before enable it by default.

**Comment by zkirill** [comment]
I had to comment out all the AppModuleNgFactory stuff in main-prod.ts and run `./node_modules/.bin/ng-xi18n -p src/client/tsconfig.json` after which it seems to be working.
