### ISSUE TITLE
cant find namespace of included types

### ISSUE THREAD

**Issue by neridonk** [mgechev/angular-seed#1730]
Im trying to include a babylonjs tsd in the devdepedencies
(    "@types/babylonjs": "^2.3.31")

 but when I add them and refresh anything in VS studio 2015. 
It cant find the namespace.

In later versions of this seed I had to add a //reference path but as far I understood I dont need it anymore because of the 
  "typeRoots": [
      "./node_modules/@types",
      "./node_modules"
    ],

**Comment by mgechev** [comment]
Can you reproduce it with any other type definitions or this happens only with the type definitions of babylonjs?

**Comment by neridonk** [comment]
it seems to be a typescript error in 2015 had to update it only, now it is working! thx
