### ISSUE TITLE
socket.io-client  Cannot find module 'socket.io-client'.

### ISSUE THREAD

**Issue by nayab2iit** [mgechev/angular-seed#1732]
Cannot find module 'socket.io-client'
i implement this lib but its not working?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by nayab2iit** [comment]
i have follow all these instruction  but error 

![image](https://cloud.githubusercontent.com/assets/24757185/21468611/e582a3e6-ca3c-11e6-811c-30a0bbc77d07.png)
