### ISSUE TITLE
error TS2307: Cannot find module 'socket.io-client'.

### ISSUE THREAD

**Issue by nayab2iit** [mgechev/angular-seed#1734]
error TS2307: Cannot find module 'socket.io-client'.

i install 'socket.io-client' but its not working

**Comment by nayab2iit** [comment]
![image](https://cloud.githubusercontent.com/assets/24757185/21472117/30cf54c0-caec-11e6-9980-33cc093a6660.png)

any solve this?

**Comment by irsick** [comment]
Try this:


package.json

"devDependencies": {
...
"@types/socket.io-client": "^1.4.29"
},
"dependencies": {
...
"socket.io-client": "~1.7.x"
}


/tools/config/project.config.ts

...
        {
            name: 'socket.io-client',
            path: 'node_modules/socket.io-client/dist',
            packageMeta:{
                main: 'socket.io.min.js',
                defaultExtension: 'js'
            }
        }
...


Now you'll be able to use  SocketIOClient and io objects in your code.
