### ISSUE TITLE
e2e.ts file

### ISSUE THREAD

**Issue by csreddy** [mgechev/angular-seed#1736]
Where is e2e.ts used ? Definitely not for e2e task as the code invoked for e2e task does not seem to rely on this file ? Should this be removed ?

Also there is some discrepancy with code
```javascript
export = (done: any) => {
  new Protractor()
    .server(5555, './dist/prod')   <--- refers to PROD build
    .then((server: any) => {
      gulp
        .src('./dist/dev/**/*.e2e-spec.js') <----- refers to DEV build
        .pipe(protractor({ configFile: 'protractor.conf.js' }))
        .on('error', (error: string) => { throw error; })
        .on('end', () => { server.close(done); });
    });
};
```

**Comment by mgechev** [comment]
Yes, it seems `e2e.ts` is not in use anymore and should be removed. We need to revise all tasks and drop the unused ones.

If you have some time a PR will be appreciated!

**Comment by mgechev** [comment]
@csreddy `gulp e2e` is used for running e2e tests in CI.
