### ISSUE TITLE
Add ng2-bootstrap

### ISSUE THREAD

**Issue by Marcelh29** [mgechev/angular-seed#1737]
Im having this error while building AOT https://github.com/valor-software/ng2-bootstrap/issues/1343.

@mgechev gives the solution.

I tried: 
        this.SYSTEM_BUILDER_CONFIG.packages['ng2-bootstrap'] = { main: 'bundles/ng2-bootstrap.umd.min.js', defaultExtension: 'js' };
        this.SYSTEM_BUILDER_CONFIG.packages['ng2-bootstrap/component-loader'] = 
        { main: 'bundles/ng2-bootstrap.umd.min.js', defaultExtension: 'js' };

But that doesn't work.

Anyone?

**Comment by mgechev** [comment]
The solution is already posted in the thread:

```ts
  let additionalPackages: ExtendPackages[] = [
    {
      name:'ng2-bootstrap',
      path:'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js'
    },
    {
      name:'ng2-bootstrap/*',
      path:'node_modules/ng2-bootstrap/bundles/ng2-bootstrap.umd.min.js'
    },
    {
      name:'moment',
      path:'node_modules/moment',
      packageMeta:{
        main: 'moment.js',
        defaultExtension: 'js'
      }
    }
  ];
```

**Comment by Marcelh29** [comment]
Sorry for wasting your time, added the code above in project.config.ts, called this.addPackagesBundles(additionalPackages);, now it works. Thanks!
