### ISSUE TITLE
File serving and deployment clarifications

### ISSUE THREAD

**Issue by arnoutaertgeerts** [mgechev/angular-seed#1738]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)

**What is the motivation / use case for changing the behavior?**
Add extra information on how the application works and how the development and production environments serve the files. This will allow developers to more easily deploy the application themselves on a platform such as Heroku. For now, the following is unclear:

- How files are served (js/css/...) in the development and production environment
- Why opening index.html in the browser after a production built does not work
- What the docker images are used for
- How the application can be deployed to a platform like Heroku

Providing a short answer on these questions will help developers (such as me) to understand what is happening and it will allow them to deploy the application where needed.

**Comment by mgechev** [comment]
Currently there's plenty of documentation inline in the `tools` directory, wiki and readme.

An update of the readme for extra information of how the production build runs sounds like a good idea. Deployment to Heroku/AWS/now/etc. seems like a trivial task after developers have understanding of the infrastructure, I don't think it's necessary to add further information about this.
