### ISSUE TITLE
Nodejs 7 - Unhandled promise rejection

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1741]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Angular seed works well with Nodejs 6.x.x but with version 7.3 I am getting Unhandled Promise rejection error when I run npm start command

[12:20:56] Deleted gulpfile.js.map
[12:20:56] Deleted gulpfile.js
[12:20:56] Deleted tools\**\*.js.map
[12:20:56] Deleted tools\**\*.js
(node:16116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: done is not a function
(node:16116) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12:21:02] Finished 'check.tools' after 8.08 s
[12:21:02] Starting 'clean.dev'...
[12:21:02] Deleted dist/dev
[12:21:02] Finished 'clean.dev' after 292 ms
[12:21:02] Starting 'clean.coverage'...

**Expected behavior**

No errors running Angular seed with Nodejs 7.3

**Minimal reproduction of the problem with instructions**

Install Nodejs 7.3 and run Angular Seed (npm start)
**What is the motivation / use case for changing the behavior?**

Installed Nodejs latest version to take advantage of latest features
**Please tell us about your environment:**

Window 10, Chrome, 

Window 10, Chrome, 
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.3

**Comment by mgechev** [comment]
Thanks for the catch!

**Comment by skolli853780** [comment]
Thank you !! You are the best
