### ISSUE TITLE
Question: do you have any plans to provide server render support in order to support SEO?

### ISSUE THREAD

**Issue by consigliory** [mgechev/angular-seed#1742]
We are building spa app which has to be able to share on social networks and it requires open graph meta tags prerender. It seems like the only way is to have server render capability in place to render meta tags upfront. So you have any plans to provide this possibilities and if so when do you plan to do it. Thanks!

**Comment by mgechev** [comment]
Introducing Universal will make the seed too opinionated, since we'll have to stop on a BE technology. There's an [angular-universal](https://github.com/angular/universal-starter) starter which provides the foundation for Angular Universal application on top of express.

**Comment by patrickmichalina** [comment]
@consigliory been working on a universal starter project, hope it helps!

https://github.com/patrickmichalina/fusebox-angular-universal-starter
