### ISSUE TITLE
Launching with Visual Studio 2015

### ISSUE THREAD

**Issue by septst** [mgechev/angular-seed#1743]
Hello,

I am using Visual Studio 2015 with Update 3 for working on this seed. When I run from NPM, the app functions as expected. But, when I tru to launche same from VS 2015, An error is being thrown as below:
Line: 47
Error: 'System' is undefined

And the page has

Loading...    <% if (BUILD_TYPE === 'dev') { %> <% } %>    <% if (BUILD_TYPE === 'dev') { %> <% } %> 

Could any one please advise on the same?

Thank you

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

It works with NPM but not with VS 2015 update 3

**Expected behavior**

Should run with VS 2015 too

**Minimal reproduction of the problem with instructions**

Launch the seed app with VS 2015

**What is the motivation / use case for changing the behavior?**

For code dev using VS 2015

**Please tell us about your environment:**

Windows, NPM, Visual Studio 2015, Local/ Dev

* **Angular Seed Version:** `aaaaf75`

aaaaf75

* **Node:** `node --version` =

**Comment by mgechev** [comment]
As the readme explains, you can run the seed by running `npm start` in the terminal, I guess powershell in your case. I'm not a VS user but I bet there's an integration with the terminal.
