### ISSUE TITLE
ngx-Pipes

### ISSUE THREAD

**Issue by Meistercoach83** [mgechev/angular-seed#1746]
Hi!

I´ve a question about https://github.com/danrevah/ngx-pipes integration in project.config.ts.
what file do I have to import and how must my config file look like?

**Comment by mgechev** [comment]
You can take a look at [existing issues related to SystemJS configuration](https://github.com/mgechev/angular-seed/issues?q=is%3Aissue+systemjs+is%3Aclosed).

Good luck!

**Comment by Meistercoach83** [comment]
@mgechev Sorry for the reply but I don´t get it.

I tried it with 
`additionalPackages.push({
      name: 'ngx-pipes',
      path: 'node_modules/ngx-pipes/src/app',
      packageMeta: {
        main: 'index.js',
        defaultExtension: 'js'
      }
    });`

Then, the main file is loaded- but the pipes in subdirectories ´could´nt be found.. for example:

> Uncaught (in promise): Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/ngx-pipes/src/app/pipes/array.js
