### ISSUE TITLE
Browser-sync loading issues - html changes

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1747]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

After making changes to html files, browser-sync is not reloading the page.. I see a blank page.. 

Here is the error I get

Error: (SystemJS) Unexpected token < in JSON at position 0
	SyntaxError: Unexpected token < in JSON at position 0
	    at Object.parse (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/config/env.config.js:2:23)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:4:4)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:5:3)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/index.js:11:10)
	    at eval (http://localhost:5555/app/shared/index.js:15:4)
	    at eval (http://localhost:5555/app/shared/index.js:16:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/app/shared/config/env.config.js
	Evaluating http://localhost:5555/app/shared/index.js
	Evaluating http://localhost:5555/app/app.component.js
	Evaluating http://localhost:5555/app/app.module.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js
	    at Object.parse (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/config/env.config.js:2:23)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:4:4)
	    at eval (http://localhost:5555/app/shared/config/env.config.js:5:3)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:5555/app/shared/index.js:11:10)
	    at eval (http://localhost:5555/app/shared/index.js:15:4)
	    at eval (http://localhost:5555/app/shared/index.js:16:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/app/shared/config/env.config.js
	Evaluating http://localhost:5555/app/shared/index.js
	Evaluating http://localhost:5555/app/app.component.js
	Evaluating http://localhost:5555/app/app.module.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Expected behavior**

Any changes made to the html, browser-sync should reload the page without any issues
**Minimal reproduction of the problem with instructions**

start the application using npm start, make some changes to html page, check if the browser is getting reloaded with the changes
**What is the motivation / use case for changing the behavior?**

I do not want to restart the application every time I make changes to html
**Please tell us about your environment:**

Windows 10
NPM 3.10

Sync'd up latest Angular Seed version
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.3

**Comment by skolli853780** [comment]
I have looked at issue.. https://github.com/mgechev/angular-seed/issues/1670
and tried to implement the suggested fix but no luck

**Comment by mgechev** [comment]
This issue appears constantly. It's interesting under what conditions. I haven't had a chance to reproduce it but it'll be very helpful if you've noticed anything unusual/untypical in your environment.

**Comment by skolli853780** [comment]
if I make changes to css and ts files, no reloading issues, everything looks good.. only when I make changes to html, I get a blank page

**Comment by ultimatedion** [comment]
What editor are you using?

This errors seems to happen when there's an « uncompiled/unbuilt » system-config.js in your « dist » directory.

1) Start your app
2) Take a copy of **dist/dev/app/system-config.js**
3) Change an html file to reproduce the problem.
4) Compare the original copy of system-config.js with the new version in **dist/dev/app/system-config.js**
5) You'll most likely see <%= SYSTEM_CONFIG_DEV %> in system-config.js which is causing the error.
6) Actually, if you see <%= SYSTEM_CONFIG_DEV %> in your DIST folder.. then, it's the problem ;)

**Comment by skolli853780** [comment]
I am using webstorm.. after making changes to html, there is no difference in system-config.js.. 

I found where the problem is..
when the application is started..

/src/client/app/shared/config/env.config.ts

"use strict";
exports.Config = JSON.parse('{"API":"https://demo.com","ENV":"DEV"}');

after making changes to the html - env_config value is not getting replaced

"use strict";
exports.Config = JSON.parse('<%= ENV_CONFIG %>');
//# sourceMappingURL=env.config.js.map

**Comment by ultimatedion** [comment]
Look in /src/client/app/shared/config/
Do you have a javascript file there? You should only have the typescript files.

When you change an html file, it doesn't rebuild everything. If i remember right, it copies html and javascript files. So if you have /src/client/app/shared/config/env-config.**js**, it overwrite the one that was built when the application was started.

**Comment by skolli853780** [comment]
You got it right .. I see javascript files along with typescript.. not sure how they got there.. I have deleted js files and everything looks good.. Thank you very much for your help, appreciate it

**Comment by ultimatedion** [comment]
Look at issue #1670
After disabling typescript compiler, you had to manually delete all *.js
Well, if that was your problem. And if I remember right, I had that problem after updating Webstorm which enabled typescript compiler without asking me.

**Comment by skolli853780** [comment]
I see that js files are created for several ts files.. Typescript compiler is not enabled.. I am using webstorm 2016.3.2.. Under compiler - options checked are Track changes , use tsconfig.json, Generate source maps (Is this causing problem?)

**Comment by ultimatedion** [comment]
Typescript compiler only had to be enabled once to generate all the bugged js files.
Once you removed all of them, I think you should be all right.

If something else is still generating js files, I'm afraid that I can't help.

@mgechev While this problem is not caused by the seed itself, maybe we could modify the build tasks so it doesn't copy js files(generated by editors) from the src to the dist folder. I am not sure if it's a good idea or not. I'll think about it and see if it's possible.

**Comment by mgechev** [comment]
A lot of people have JavaScript (just drop random scripts) files in `src` and later `require` them. This is not a good practice but in case we stop copying `*.js` to `dist` we will break a lot of projects. If the problem is only with `config.js` we can ignore it?

**Comment by ultimatedion** [comment]
That's what I had in mind, maybe « protecting » seed configs files. On the other hand, it might be easier to solve issues if we leave it as it is. If we patch this, the problem might still occurs but on « custom/projects » files and it will be harder to help out people.

**Comment by skolli853780** [comment]
browser-sync reloading issue is resolved.. Please close this issue if no further discussion is needed.. Thank you for your help

**Comment by deli6z** [comment]
I was having the same issue, remove the js config file and it works now.
Not sure how the file was created there in the first place.
Thank you guys!
