### ISSUE TITLE
Gulp 4.0 - Upgrade Investigation / Deprecation Warnings

### ISSUE THREAD

**Issue by mko** [mgechev/angular-seed#1748]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
Angular Seed uses Gulp `3.x.x`.

**Expected behavior**
Angular Seed uses Gulp `4.0.x`.

**Minimal reproduction of the problem with instructions**
N/A. Gulp `3.x.x` lacks the `gulp.symlink` feature.

**What is the motivation / use case for changing the behavior?**
For importing local modules, `gulp.symlink` is a highly desired feature instead of using `gulp.dest`. There's lots of infrastructure in `angular-seed` and `angular-seed-advanced` that depends on Gulp `3.x.x` currently. Ideally, it would be useful to investigate the process of upgrading to Gulp `4.0.x` to identify things in the build system that should be highlighted and identified as deprecated in the seed.

**Please tell us about your environment:**
N/A

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = N/A

**Comment by mgechev** [comment]
I don't think Gulp 4.0 is officially release, neither I see a lot of activity in [their repository](https://github.com/gulpjs/gulp/tree/4.0). Since we've abstracted the build quite a bit, at some point we can just go with a custom solution if new version of the task runner is not released.

**Comment by mko** [comment]
Fair enough. The reason I bring it up is that we had to effectively replace `gulp` in the existing `build.*` tasks with `vfs` (i.e. `var vfs = require('vinyl-fs');`) in order to access the Symlinks functionality working with locally-owned submodules without having to deal with the hassles involved with `git submodule`.

I've wanted to investigate Webpack building myself, as that seems to be the direction many people are heading for AoT compilation, but I've not had the bandwidth to do so.

**Comment by mgechev** [comment]
Well, the AoT plugin for webpack doesn't perform the compilation any differently.

I kept this approach because it's very easy to script a complex deployment logic. At the moment I have AoT with lazy loading where the individual bundles go to S3. There's plenty of configuration involved - getting hash sums and transforming file names, etc. This flexibility seems essential to me.

**Comment by mgechev** [comment]
Closing the issue. We can't do anything until gulp 4 get released.
