### ISSUE TITLE
Unable to integrate google maps.

### ISSUE THREAD

**Issue by arungdg** [mgechev/angular-seed#1749]
**I'm submitting a ...**  bug in integrating google maps.
```
[ ] bug report => angular2-google-maps/core/core.umd.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
[ ] feature request=> please try to make this work.
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

The application works fine until I integrate the maps but fails to load once I route the map module to the app module. If I don't route the map module to the app module, the application seems to be working fine.

**Expected behavior**

Simple google map must be displayed on the screen.

**Minimal reproduction of the problem with instructions**

Error1:
XMLHttpRequest cannot load npm:angular2-google-maps/core/core.umd.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Error2:
(SystemJS) XHR error loading npm:angular2-google-maps/core/core.umd.js
	Error: XHR error loading npm:angular2-google-maps/core/core.umd.js
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:345:33) [<root>]
	    at ZoneTask.scheduleTask [as scheduleFn] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:1645:20) [<root>]
	    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:255:26) [<root>]
	    at Zone.scheduleMacroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:168:39) [<root>]
	    at http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:1669:25 [<root>]
	    at XMLHttpRequest.send (eval at createNamedFn (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:1181:17), <anonymous>:3:31) [<root>]
	    at new ZoneAwarePromise (http://localhost:5555/node_modules/zone.js/dist/zone.js?1483684762705:536:29) [<root>]
	Error loading npm:angular2-google-maps/core/core.umd.js as "angular2-google-maps/core" from http://localhost:5555/app/map/map.module.js Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**What is the motivation / use case for changing the behavior?**

Need of integration of ng2 google maps to the present app so that users can view the map on the screen.

**Please tell us about your environment:**

OS: Windows 10 Pro 64 bit, VS Code, NPM packet manager, run locally.

* **Angular Seed Version:** `aaaaf75`

I am not sure about the version.
You can find my project on https://github.com/arungdg/ng2-base.git
* **Node:** `node --version` =v6.9.1

**Comment by mgechev** [comment]
```ts
let additionalPackages: ExtendPackages[] = [{
  name: 'angular2-google-maps',
  // Path to the package's bundle
  path: 'node_modules/angular2-google-maps/core/core.umd.js'
}];
```

Will do the trick. For support requests I'd recommend you to use either gitter or stackoverflow. Thanks!

**Comment by arungdg** [comment]
It is not working yet. Do you have any other work around?

**Comment by Meistercoach83** [comment]
@arungdg I got it working:

```
{
        name: 'angular2-google-maps/core',
        path: `${this.NPM_BASE}angular2-google-maps/core/core.umd.js`
      },
```
