### ISSUE TITLE
SystemJS is loading .ts.js and .css.js instead of .ts and .css

### ISSUE THREAD

**Issue by tonychangcheng** [mgechev/angular-seed#1753]
Hi, 

I am trying to use a lib ngx-quill via npm. My issue is that Angular-seed is by default loading .js files. And I could not change this setting as it would cause other problems. Which means, instead of loading quill.module.ts SystemJS will require quill.module.ts.js (other issue such as .css.js) and of course will fail. 

How do I deal with the lib with .ts files. Should I change the defaultJSExtensions to false? Or I need to let the third party lib to compile all file to .js.

**Comment by mgechev** [comment]
You can't load `ts` file without transpilation runtime in the browser, which is not good practice for production, neither for development given the seed's setup.

Use the JavaScript bundle instead.

**Comment by tonychangcheng** [comment]
I am using npm to get the ngx-quill and there are only .ts files in the node_modules. Do I need to ask the third party lib to provide the Javascript bundle? (e.g. add tsconfig.json in the ngx-quill project)
