### ISSUE TITLE
reflect-metada package is not needed

### ISSUE THREAD

**Issue by joumenharzli** [mgechev/angular-seed#1755]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```
**What is the motivation / use case for changing the behavior?**

Since you are using core-js >= 2.4.1 you don't need to include reflect-metadata dependency in your seed
https://github.com/zloirock/core-js/commit/be094f9ba59742f529eac09b8c730f59ad0272ec

* **Angular Seed Version:** `aaaaf75`

**Comment by mgechev** [comment]
Thanks for pointing this out!
