### ISSUE TITLE
Unexpected value 'undefined' declared by the module 'AppModule' mgechev angular seed

### ISSUE THREAD

**Issue by RanaProgrammer** [mgechev/angular-seed#1756]
got this error whenever i change the html template in this repo mgechev angular seed and have to 'npm start' every time.

(SystemJS) Unexpected value 'undefined' declared by the module 'AppModule' Error: Unexpected value 'undefined' declared by the module 'AppModule'

**Comment by mgechev** [comment]
Hey @RanaProgrammer, you can take a look at the Angular's documentation to get a more complete idea how the framework works. I believe this is caused by a declaration which equals `undefined`.

**Comment by RanaProgrammer** [comment]
then why it works properly when i run 'npm start' again?

**Comment by felixivance** [comment]
@RanaProgrammer worked for me wen i did ng serve samething though

**Comment by nousacademy** [comment]
+1 worked for me after I killed server and did ng serve as well

**Comment by soonthanan** [comment]
what is ng serve ? someone pls explain how to re-run ng serve and what it is ?

**Comment by Ramin-Bateni** [comment]
@soonthanan, [to a narrative ](https://stackoverflow.com/questions/40190538/when-to-use-npm-start-and-when-to-use-ng-serve)they are equal here.

**Comment by sarfat96** [comment]
> @mgechev
> then why it works properly when i run 'npm start' again?

me too i run 'ng serve' again, then it works, no error like before

**Comment by veronesecoms** [comment]
same here, ocurred in 2020 after i declare a new pipe
