### ISSUE TITLE
`cannot find name space webdriver` when installing with yarn

### ISSUE THREAD

**Issue by SamVerschueren** [mgechev/angular-seed#1757]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
If you install the dependencies with the `yarn` command, it picks up the lockfile and install the correct dependencies. However, when running the project, you will receive the `cannot find name space webdriver` error. If you install the dependencies with `npm install`, this error does not occur.

**Expected behavior**
To work out of the box

**Minimal reproduction of the problem with instructions**
1. git clone https://github.com/mgechev/angular-seed
2. cd angular-seed
3. yarn
4. npm run build.prod.exp

**Please tell us about your environment:**
macOS Sierra, VS Code, yarn

* **Angular Seed Version:** https://github.com/mgechev/angular-seed/commit/ff742ea55141cdd4dad4f0dbc03866799fd3e7f6

* **Node:** `node --version` = v6.9.1

---------------------------------
After regenerating the `yarn.lock` file, everything works as expected. I will file a PR for that.

**Comment by tigercosmos** [comment]
It seems that "webdriver" makes troubles  lol
