### ISSUE TITLE
Protractor is causing issues

### ISSUE THREAD

**Issue by RicardoD7I** [mgechev/angular-seed#1759]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Running build for production, it throws some errors and cannot build.
I.e: http://stackoverflow.com/questions/41238376/angular2-npm-install-didnt-find-namespace-webdriver

It seems to be a protractor version issue. 

**Expected behavior**

It should run: npm run serve.prod

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.9.4

**Comment by RicardoD7I** [comment]
Version 4.0.14 works! I did the test and it pass! 👍 

    "protractor": "^4.0.14",

**Comment by mgechev** [comment]
@RicardoD7I would you open a PR by setting the correct version so I can add you in the list of contributors?

**Comment by RicardoD7I** [comment]
@mgechev  sure! give a second and I will do it! Thanks!

**Comment by RicardoD7I** [comment]
@mgechev this is the PR: https://github.com/mgechev/angular-seed/pull/1760

It will be great to keep working and contributing to this seed!

**Comment by mgechev** [comment]
I'm updating the contributors' section every week or so using [this tool](https://www.npmjs.com/package/github-contributors-list). You should be there in a couple of days. 

Thanks for the PR!

**Comment by mgechev** [comment]
@RicardoD7I I still don't see you in the list of contributors [here](https://github.com/mgechev/angular-seed/graphs/contributors) and hasn't included you in the generated markdown table. Maybe we should wait another a couple of days until your help get visible.
