### ISSUE TITLE
Enable Cors

### ISSUE THREAD

**Issue by ducmaxime** [mgechev/angular-seed#1761]
Hi everybody,

I try to call a remote web API (.NET) with my Angular 2 project.

But : 
<img width="628" alt="screen shot 2017-01-12 at 09 26 12" src="https://cloud.githubusercontent.com/assets/6499846/21882103/4b76fc36-d8a9-11e6-8707-0ce2a26368ee.png">

My code : 
<img width="832" alt="screen shot 2017-01-12 at 09 28 59" src="https://cloud.githubusercontent.com/assets/6499846/21882187/9ebd28ca-d8a9-11e6-9e35-ed7b25cbbf2e.png">

Any idea ?

**Comment by mgechev** [comment]
In order to solve this issue, you should get familiar with Cross Origin Request Sharing, and the way you can configure it in ASP.NET. The browser is not the place where you can enable CORS, it's your server by setting the `access-control-allow-origin` header. Good luck!

**Comment by Sn3b** [comment]
```csharp
        public void ConfigureServices( IServiceCollection services )
        {
            services.AddCors();
            var policy = new CorsPolicy();
            policy.Headers.Add( "*" );
            policy.Methods.Add( "*" );
            policy.Origins.Add( "*" );
            policy.SupportsCredentials = true;
            services.AddCors( x => x.AddPolicy( "corsGlobalPolicy", policy ) );
        }

        public void Configure( IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory )
        {
            app.UseCors( "corsGlobalPolicy" );
        }

```

**Comment by ducmaxime** [comment]
For Microsoft IIS7, merge this into the web.config file at the root of your application or site:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
</configuration>
