### ISSUE TITLE
Faulty @imports do not result in a build fail. Instead hangs.

### ISSUE THREAD

**Issue by Gideonnn** [mgechev/angular-seed#1762]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When SASS support is enabled and a `.scss` file contains an `@import` statement that wants to load a file that does not exist, it does not fail the build. Instead it hangs at the `[HH:MM:SS] Starting 'build.html_css'...` step. 

**Expected behavior**
Fail build and display an error.

**Minimal reproduction of the problem with instructions**

Just add one to many `../` to a `@import` statement in a random `.scss` file

**What is the motivation / use case for changing the behavior?**
It takes to long to debug a fault like this with no message and a failing build.

**Please tell us about your environment:**

Fresh download with SASS enabled.

* **Angular Seed Version:** `aaaaf75`

c9f675e6c394510fbbf6f8fbed839dd34eab54cf

* **Node:** `node --version` =
v6.5.0

**Comment by zladuric** [comment]
An older issue, but FWIW it might be resolved, or maybe it's related to specific sass versions. Here's what I have:

[15:32:30] Starting 'build.html_css'...
Error in plugin 'sass'
Message:
    src/client/css/variables.scss
Error: File to import not found or unreadable: ../../blah.
       Parent style sheet: /home/zlatko/projects/snakt-web/src/client/css/variables.scss
        on line 1 of src/client/css/variables.scss
>> @import '../../blah';
   ^

[15:32:30] Finished 'build.html_css' after 87 ms

Maybe it's good to be closed?

**Comment by mgechev** [comment]
@zladuric, thanks for the comment!
