### ISSUE TITLE
AoT compile fails when using ambient TSDs

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#1763]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

I'm not sure if this is an issue with the seed, an issue with the Angular AOT compiler, or an issue with TypeScript itself.

If I add a custom TSD (d.ts) to `tools/manual_typings/project`, I can do normal dev and prod builds OK. The build correctly handles the use of ambient definitions.

However, the AOT build will fail during `compile.ahead.prod` ("Cannot find name 'XXX'.").

The only way I could get it to work was to use more of an @types approach: 

- I created a folder containing my definition (in an index.d.ts) file under `tools/manual_typings/project`
- I modified the `src/client/tsconfig.json` to add a `typeRoot` and `type`:
```
"typeRoots": [
  "../../node_modules/@types",
  "../../node_modules",
  "../../tools/manual_typings/project"
],
"types": [
  "node",
  "jasmine",
  "protractor",
  "systemjs",
  "XXX"
]
```

I can create a branch that shows the issue if that would help, but I suspect you can reproduce it pretty easily. But as I said, I'm not sure if this means the way the seed project handles ambient definitions needs to change, or if this is expected behavior with the current AoT compiler.

**Comment by mgechev** [comment]
Seems like an issue with the seed. Thanks for reporting!

**Comment by mgechev** [comment]
@brian428 after the build passes I'll merge and the issue should be fixed. Again, thanks for letting me know!

**Comment by brian428** [comment]
Thanks, Minko. A quick follow up: while this seems to fix the build, I'm still having to use the "types" approach to get IDEA to see the ambient types. I'm using TypeScript 2.1.5, so not sure if this is something that changed in TS 2.1.x regarding nested tsconfig files, or if it's some bug in IDEA/WebStorm 2017.1. I'm leaning toward the latter, since things seem to build fine from the command line.

Just thought I'd mention this here in case anyone else runs into the same problem.

**Comment by mgechev** [comment]
Yeah, the manual typings are added by the build itself. In order to resolve your issue you have to add them manually. I'll add one additional line which drops duplicate files from `tsconfig.json`.

**Comment by brian428** [comment]
Hmm, interesting. When I tried to specify specific files in the `files` or `include` tsconfig arrays, it seemed to cause other problems (Angular decorators started being flagged as unknown). Almost like `files` or `include` killed the inclusion of `types`/`typeRoots`. I hated to do it, but I ended up having to use a TS <reference> tag to include the TSD.

I don't want to turn this into an annoying time sink for you, but if you have any ideas off the top of your head, I'm open to hearing them. :-)

**Comment by mgechev** [comment]
I'll put this into my todo list and think of a solution tomorrow or Wednesday.

**Comment by mgechev** [comment]
Something like this as content of your `src/client/app/tsconfig.json` should work:

```ts
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "lib": ["es2016", "dom"],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "../../node_modules/@types",
      "../../node_modules"
    ],
    "types": [
      "node",
      "jasmine",
      "protractor",
      "systemjs"
    ]
  },
  "files": [
    "./app/main.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "src"
  ],
  "compileOnSave": false
}
```

Just tried it, VSCode doesn't complain about the experimental decorators.
