### ISSUE TITLE
Wiki entry for prime faces needs to be updated

### ISSUE THREAD

**Issue by paulbdavis** [mgechev/angular-seed#1766]
The example `FONT_DEST` is incorrect, it should be

```
FONTS_DEST = `${this.APP_DEST}/fonts`;
```

**Comment by mgechev** [comment]
Thanks for pointing this out! Would you update the wiki if you have a minute?

**Comment by paulbdavis** [comment]
Done.. never edited a wiki page for someone before, didn't even see the "Edit" button..

**Comment by mgechev** [comment]
Thanks!
