### ISSUE TITLE
how to add new config value for access after build in all my app about APP_BASE

### ISSUE THREAD

**Issue by tamohugues** [mgechev/angular-seed#1770]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
Please use the issue template. I'm not exactly sure what you're asking.

**Comment by tamohugues** [comment]
I use ng2-config in my project, in the angular-seed I see APP_BASE, config in NgModule. I want to config NgModule of my component with value comming in my ng2-config key.
