### ISSUE TITLE
Error running "npm run compodoc"

### ISSUE THREAD

**Issue by dknesek** [mgechev/angular-seed#1771]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
npm run compodoc
...
Error during graph generation: : /bin/sh: /Users/doug/angular-seed/node_modules/.bin/ngd: No such file or directory

**Expected behavior**
No error

**Minimal reproduction of the problem with instructions**
Follow the instructions in your readme. When you get to "npm run compodoc", it blows up.

**What is the motivation / use case for changing the behavior?**
I want it to work.

**Please tell us about your environment:**
OSX 10.11

* **Angular Seed Version:** `aaaaf75`
commit 62684...

* **Node:** `node --version` =
v6.2.2

**Comment by mgechev** [comment]
Seems related to https://github.com/compodoc/compodoc/issues/23. If you install the project's dependencies with `npm` instead of `yarn` should work.
