### ISSUE TITLE
How to use i18n provider with input placeholder

### ISSUE THREAD

**Issue by ducmaxime** [mgechev/angular-seed#1778]
Hi every body,

I use I18n provider for my translations with success like this: 
  ```<h2 i18n> Lost Password ?</h2>```

but how to translate the placeholder of my inputs like "Email" :
      <input
      md-input
      placeholder="**Email**"
      type="text"
      [(ngModel)]="userEmail"
      [ngModelOptions]="{standalone: true}"
      required="true"/>

**Comment by mgechev** [comment]
It seems an issue related to the i18n module itself. Probably you'll get a response quicker if you ask this question in StackOverflow or Angular's gitter channel.
