### ISSUE TITLE
Feature request: order of shims libraries

### ISSUE THREAD

**Issue by negberts** [mgechev/angular-seed#1780]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
It appears as if the order in which shims are imported could be an issue. if we use the order of the seed.config we get an error: 

Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
shim.js (4035,12)

If we move the import of zone.js down the list like:

NPM_DEPENDENCIES: InjectableDependency[] = [
    { src: 'core-js/client/shim.min.js', inject: 'shims' },
    { src: 'intl/dist/Intl.min.js', inject: 'shims' },
    { src: 'systemjs/dist/system.src.js', inject: 'shims', buildType: BUILD_TYPES.DEVELOPMENT },
    { src: 'zone.js/dist/zone.js', inject: 'shims' },
    { src: 'zone.js/dist/long-stack-trace-zone.js', inject: 'shims', buildType: BUILD_TYPES.DEVELOPMENT },
    { src: 'rxjs/bundles/Rx.js', inject: 'shims', buildType: BUILD_TYPES.DEVELOPMENT },
    { src: 'rxjs/bundles/Rx.min.js', inject: 'shims', buildType: BUILD_TYPES.PRODUCTION },
  ];

We have no problems. So apparantly shim.min.js should be included before zone.js

**Expected behavior**
Add an order parameter for injection in shims.js so we are no longer dependent on the order in the array

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
Yes, you're correct! Thanks for the catch!

**Comment by negberts** [comment]
What I meant is maybe you could add a parameter order. So shim.js has order:1 and zone.js has order:2. And sort the array upon injection based on the order parameter.
