### ISSUE TITLE
Add bootstrap 

### ISSUE THREAD

**Issue by bwwilliam** [mgechev/angular-seed#1781]
Can anyone please point me to the right direction how add bootstrap 4.0 alpha into this project? 
I have added the following to the index.html page 
 ```
<!-- inject:css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <!-- endinject -->
```
However, after run the website, the references have been removed when I looked at the page source. 
It would be really appreciated if someone can send me some instructions. Or links to the instructions. 
Thank you very much.
William

**Comment by negberts** [comment]
Don't inject the css manually between the  and . Thats where the build process will inject the css files.  Just do it like this:

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">

    
    
</head>

Or even better, configure the APP_ASSETS  variables in project.config to include the bootstrap css there. Like so:

this.APP_ASSETS = [
            ...this.APP_ASSETS,
            {
                src: `${this.BOOTSTRAPCSS_SRC}/${this.BOOTSTRAP_PROD_BUNDLE}`,
                inject: true,
                vendor: false
            }
];
