### ISSUE TITLE
SystemJSBuilder lazy loading config

### ISSUE THREAD

**Issue by killzoner** [mgechev/angular-seed#1782]
Hi everyone,

First of all thanks for the great work, i was searching for a starter with gulp in mind and this one is very good.
I had a review of what the seed currently provides, and i didn't find any configuration about SystemJSBuilder working with lazy loaded component routes. So I gave it a try but i'm currently stuck on this (it's working well with dev config and SystemJS).

Is there any plan to include a config related to this feature or any guidelines in the wiki?
Such a thing would IMHO help using the full features of the current angular router.

**Comment by mgechev** [comment]
You can take a look at [already closed issues](https://github.com/mgechev/angular-seed/issues?q=is%3Aissue+lazy+loading+is%3Aclosed) related to this question. The seed doesn't officially support lazy loading, although a lot of people have already used it in production.

Implementing lazy loading which works in the general case (for all users) is not a trivial task with the current toolset available. Although I have implementation in a fork of the seed for a project that I'm working on, I'll prefer to not push it in the seed. You can find it in a discussion [here](https://github.com/mgechev/angular-seed/pull/1714).

**Comment by killzoner** [comment]
Thanks for the quick feedback i'll take a look at that

**Comment by tamohugues** [comment]
plz your problem is resolved. I have same help
