### ISSUE TITLE
SystemJS 0.20 support

### ISSUE THREAD

**Issue by meriturva** [mgechev/angular-seed#1785]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I'm testing new version of SystemJs 0.20 and i have a lot of problem on my fork. Are you going to try your solution with SystemJs 0.20?

**Comment by mgechev** [comment]
I'll play with it over the weekend.

**Comment by meriturva** [comment]
So thanks!

**Comment by mgechev** [comment]
I see that wildcards in `paths` no longer work. I can't think of a good replacement. Given the tens of deep imports that Angular does to rxjs, I don't think listing all of them is a good idea.

**Comment by mgechev** [comment]
The latest changes discard wildcard in the `paths`. This means that we cannot redirect all `rxjs/*` requests to the corresponding bundle but instead load each module separately.

I really don't like this since it slow downs application refreshes quite a bit.

**Comment by meriturva** [comment]
Actually my solution is to build rxjs bundle by myself. Anyway it seems that wildcard char is just removed but path works as usual: https://github.com/systemjs/systemjs/issues/1039#issuecomment-251283268
am i right?

**Comment by mgechev** [comment]
Yes:

```
// option 1
paths: {
  'rxjs/': 'node_modules/rxjs/'
}
```

is equivalent to:

```
// option 2
paths: {
  'rxjs/*': 'node_modules/rxjs/*'
}
```

But there's no alternative of:

```
// option 3
paths: {
  'rxjs/*': 'node_modules/rxjs/bundles/Rx.js'
}
```

Option 1 will make SystemJS download each individual requested module with a separate request, instead of reusing the bundle.

**Comment by meriturva** [comment]
Actually there are other angular starter projects using systemjs 0.20 version as: https://github.com/valor-software/angular2-quickstart

main problem is related to: https://github.com/angular/angular/issues/9359 and few issues related to RxJs and UMD package

my actual solution on my project is build RxJs bundle by my self.

**Comment by mgechev** [comment]
> Actually there are other angular starter projects using systemjs 0.20 version as: https://github.com/valor-software/angular2-quickstart

It looks like the project will send request for each module of RxJS so it hits the issue mentioned above. Let me know if I'm wrong.

Currently we build the RxJS bundle ourselves because Angular uses some nested imports which are not accessible via the UMD bundle (as far as I remember).

**Comment by negberts** [comment]
@meriturva any chance you could post your adapted version of seed.config here?

**Comment by meriturva** [comment]
@negberts we are still use 0.19 version.

**Comment by meriturva** [comment]
@mgechev i have found PR https://github.com/ReactiveX/rxjs/pull/2381 on rxjs repository related to: https://www.npmjs.com/package/rxjs-system-bundle

what do you think? are you going to give it a test with systemjs 0.20?

**Comment by mgechev** [comment]
I don't feel comfortable includig a not official package for rxjs. Maybe it can work as temporal solution but probably a better alternative will be to build the package ourselves as part of bootstrap/initialization proceeds of the seed.

**Comment by meriturva** [comment]
@mgechev same feeling here, and rxjs teams has rejected PR...they have to find a solution really! On my environment i use UMD packages during development that's why i have decided to implement my own build task just for rxjs.

**Comment by kylecordes** [comment]
@mgechev I made the unofficial system bundle package - and I agree with you, unofficial bundle is not a good idea. I'm eager to delete my package if RxJS starts shipped a System bundle. (Related... hopefully along with a FESM bundle, which I'm also eager for, to use with Closure Compiler.)

**Comment by meriturva** [comment]
Again new issue on RxJs about bundle support...... https://github.com/ReactiveX/rxjs/issues/2458
fingers crossed!

**Comment by ZuSe** [comment]
Shouldn't we update to systemJs 0.20 even the RxJS issue is still opened? It got a couple of benefits and in case Rx refuses to provide a bundle we keep the included build task.

**Comment by meriturva** [comment]
So after 4 months we are still in limbo. We have now https://www.npmjs.com/package/rxjs-system-bundle that it is downloaded quite a lot: https://npm-stat.com/charts.html?package=rxjs-system-bundle&from=2017-01-01&to=2017-04-28

but what i see is that unofficial bundle is not updated to latest version. @kylecordes could have few issues with version 5.3 but i really don't know reasons.

https://github.com/mgechev/angular-seed project still use systemjs 0.19 and no news from rxjs team.

Any advice here? i have to take a decision and i think that i will have to bundle rxjs manually on my solution... @mgechev will you still on systemjs 0.19 until a final rxjs decision? what's your feeling?

**Comment by brian428** [comment]
Any thoughts/progress on this, @mgechev?

**Comment by mgechev** [comment]
Haven't worked on this one after the previous experiments. In case anyone has this already working I'd be happy to review/merge a PR.

**Comment by brian428** [comment]
I have to admit that other than knowing that the seed doesn't work with SystemJS 0.20+, I don't understand the problem well enough to try addressing it. Same goes with the Karma 1.7+ issue (which seems to be that wildcards in file patterns won't resolve subdirectories any longer). 

In broader terms, I assume that the Webpack and Angular CLI stuff has dealt with these sorts of issues (or simply didn't have them). Are we getting to the point (or do you envision a future point) where folks should start thinking about transitioning to Webpack? I know that for a while the Webpack options were lacking, but the momentum there seems to be growing. Just curious on your thoughts there.

**Comment by mgechev** [comment]
CLI is always an option and if you're fine with using webpack for everything I don't see a reason not to switch to if you'll feel more comfortable.

**Comment by brian428** [comment]
That's the thing: I've never even really looked at webpack. I assume switching would be kind of a pain since I have a fairly customized seed build and I know basically nothing about webpack right now. 

I don't mean to spin this issue thread off on a tangent. I was really just wondering what your current opinion was vis-a-vis webpack. I know at least part of the initial reason for this seed was that webpack was lacking. Given where CLI/webpack is now, would you use it if you started a new project? Or would you still go with this seed project?

**Comment by meriturva** [comment]
Actually i work on an enterprise application (quite big) and we have found that systemjs during development phase is really comfortable, easy to configure and quite fast. We have something like 40 packages developed in different npms. On final build we just would like to build app using webpack but during development systemjs is perfect on our flow. Plus we have implemented lazy loading with [SystemJs.Import](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemjsimportmodulename--normalizedparentname---promisemodule) call in some modules. So i guess for big project it is really a must.
My two cents.

**Comment by mgechev** [comment]
@meriturva would you have time to chat about the lazy-loading that you've implemented? Is it related to lazy-loaded routes or you've implemented any other lazy-loading strategy?

**Comment by mgechev** [comment]
FYI https://github.com/mgechev/angular-seed/pull/1946

**Comment by meriturva** [comment]
@mgechev we have implemented a layout where we don't know about single component loaded. It is defined by configuration calls and user permissions.
So we have to load "modules" at run-time.

Really simple example:

```
 SystemJS.import(menuItem.path)
                        .then((module: any) => {
                            moduleType = module[moduleTypeName];
                            componentType = module[componentTypeName];
                            
                            return this.compiler.compileModuleAndAllComponentsAsync(<any>moduleType);
                        })
                        .then((moduleFactory: ModuleWithComponentFactories<any>) => {
                            let newModuleInjector = moduleFactory.ngModuleFactory.create(this.injector).injector;
                            let newComponentFactory = moduleFactory.componentFactories.find((componentFactory) => componentFactory.componentType === componentType);
```

Here some refs:
https://github.com/angular/angular/issues/12264
https://github.com/angular/angular/issues/14022

It is not so fast so we have now also a cache approach based on:

https://stackoverflow.com/questions/39678963/load-existing-components-dynamically-angular-2-final-release (see answer 2 ).

Next step is to give a try to `NgComponentOutlet`
