### ISSUE TITLE
Recommendation for gulp-protractor command line arguments such as "ignore_ssl"

### ISSUE THREAD

**Issue by patrickmichalina** [mgechev/angular-seed#1787]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When npm install is run behind a corporate proxy a TSL error occurs during the web-driver phase of installation. `unable to get local issuer certificate`

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Behind a proxy with a self-signed SSL chain of trust?

**What is the motivation / use case for changing the behavior?**
To use this seed even when behind SSL or when other gulp-protractor arguments are needed

**Please tell us about your environment:**

* **Angular Seed Version:** `365f0ec`
* **Node:** `node --version` = 7+

The code I wrote to pass in an argumetn to the gulp-protractor plugin is:
```typescript
import * as webdriver_update from 'gulp-protractor';

export = () => {
  return webdriver_update.protractor({
        configFile: './protractor.conf.js',
        args: ['--ignore_ssl']
    });
};
```

I am new to this project and wondering if you have a better way to support this? Thanks!

**Comment by mgechev** [comment]
@patrickmichalina according to https://github.com/angular/protractor/issues/3035, update in `package.json` should do the trick:

```js
"scripts": {
  ...
  "webdriver-update": "webdriver-manager update --ignore_ssl",
  ...
}
```

Let me know if this works.

**Comment by patrickmichalina** [comment]
@mgechev This works! Thanks 👍
