### ISSUE TITLE
build-assets-dev tasks takes too much time

### ISSUE THREAD

**Issue by ultrasonicsoft** [mgechev/angular-seed#1788]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

"build-assets-dev" tasks too much time to reload browsersync when template assets are large. With my custom assets and template, it's taking >3 min to finish "build-assets-dev" tasks.

**Expected behavior**

There should be option to run "build-assets-dev" tasks only once as "clean.once" tasks does. It has flag "firstrun" and based on that it skip this tasks on later reloads. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

For building any professional web application, developer will use other css/assets/templates. If they want to use angular2-seed as seed project, there should be provision to skip this tasks for faster development. 

**Please tell us about your environment:**

Windows 10, VSCode, npm 6+. Running command "npm start". 

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.9.4

**Comment by mgechev** [comment]
I think this happens by default:

```ts
export =
  class BuildAssetsTask extends AssetsTask {
    run() {
      ...
    }
  };
```

`AssetsTask`:

```ts
export abstract class AssetsTask extends Task {
  shallRun(files: String[]) {
    return files.reduce((a, f) => {
      return a || (!f.endsWith('.css') && !f.endsWith('.sass') &&
       !f.endsWith('.scss') && !f.endsWith('.ts'));
    }, false);
  }
}
```

The assertion in `shallRun` makes sure the resource is an asset and runs the task only in that case.

**Comment by mgechev** [comment]
By default `BulildAssetsTask` runs only when an asset is changed:

```ts
export =
  class BuildAssetsTask extends AssetsTask {
    run() {
      ...
    }
  };
```

`AssetsTask`:

```ts
export abstract class AssetsTask extends Task {
  shallRun(files: String[]) {
    return files.reduce((a, f) => {
      return a || (!f.endsWith('.css') && !f.endsWith('.sass') &&
       !f.endsWith('.scss') && !f.endsWith('.ts'));
    }, false);
  }
}
```

The assertion in `shallRun` makes sure the resource is an asset and runs the task only in that case.

The task can be optimized even further:

```ts
let firstRun = true;

/**
 * Executes the build process, copying the assets located in `src/client` over to the appropriate
 * `dist/dev` directory.
 */
export =
  class BuildAssetsTask extends AssetsTask {
    run(done: any, files: string[]) {
      let paths = files;
      if (firstRun) {
        paths = [
          join(Config.APP_SRC, '**'),
          '!' + join(Config.APP_SRC, '**', '*.ts'),
          '!' + join(Config.APP_SRC, '**', '*.scss'),
          '!' + join(Config.APP_SRC, '**', '*.sass')
              ].concat(Config.TEMP_FILES.map((p) => { return '!' + p; }));
        firstRun = false;
      }

      return gulp.src(paths)
        .pipe(gulp.dest(Config.APP_DEST));
    }
  };


```

This way you'll run the task only for the file which has actually been changed. All you need to do is override the `build.assets.dev` in `tools/seed/build.assets.dev.ts`. **Make sure you have the latest seed.**

**Comment by mgechev** [comment]
By default `BulildAssetsTask` runs only when an asset is changed:

```ts
export =
  class BuildAssetsTask extends AssetsTask {
    run() {
      ...
    }
  };
```

`AssetsTask`:

```ts
export abstract class AssetsTask extends Task {
  shallRun(files: String[]) {
    return files.reduce((a, f) => {
      return a || (!f.endsWith('.css') && !f.endsWith('.sass') &&
       !f.endsWith('.scss') && !f.endsWith('.ts'));
    }, false);
  }
}
```

The assertion in `shallRun` makes sure the resource is an asset and runs the task only in that case.

The task can be optimized even further:

```ts
let firstRun = true;

/**
 * Executes the build process, copying the assets located in `src/client` over to the appropriate
 * `dist/dev` directory.
 */
export =
  class BuildAssetsTask extends AssetsTask {
    run(done: any, files: string[]) {
      let dest = Config.APP_DEST;
      let paths = [
          join(Config.APP_SRC, '**'),
          '!' + join(Config.APP_SRC, '**', '*.ts'),
          '!' + join(Config.APP_SRC, '**', '*.scss'),
          '!' + join(Config.APP_SRC, '**', '*.sass')
              ].concat(Config.TEMP_FILES.map((p) => { return '!' + p; }));

      if (!firstRun) {
        paths = files.map(f => f.replace(join(Config.PROJECT_ROOT, '/'), ''));
        const file = paths[0].replace(__dirname, '');
        dest = dirname(file).replace(join('src', 'client'), dest);
        paths = [file];
      }

      firstRun = false;

      return gulp.src(paths)
        .pipe(gulp.dest(dest));
    }
  };

```

This way you'll run the task only for the file which has actually been changed. All you need to do is override the `build.assets.dev` in `tools/seed/build.assets.dev.ts`. **Make sure you have the latest seed.**

**Comment by ultrasonicsoft** [comment]
Hi Mgechev,
Thanks for reply. 

I tried this solution but it's giving compilation errors.
1. When I overload run method in "./task.ts' as below 

  `abstract run(done?: any): any | Promise<any> | void;`
  `abstract run(done?: any, files?: string[]): any | Promise<any> | void;`

And implemented your `run(done: any, files: string[])` function in `build.assets.dev` file, compiler giving error as duplicate identifier for `run` method. If I comment out first run method, then there is an error on line:
` dest = dirname(file).replace(join('src', 'client'), dest);`
`Can not find dirname`

Another question, from where should i pass `files` parameter to overloaded `run` method?

I am learning gulp I might be missing very basic things. Your help will be appreciated.

Thanks!
Best regards,
Balram

**Comment by mgechev** [comment]
Yes, you need to import `dirname` from `path`.
