### ISSUE TITLE
Adding lodash

### ISSUE THREAD

**Issue by nrbbrg-at** [mgechev/angular-seed#1790]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I tried to add lodash to the project and the typings aren't installed. I tried installing the typings and I get duplicate errors.

Without typings:

import _ as * from 'lodash';
error TS2307: Cannot find module 'lodash'.

With typings:

node_modules/@types/lodash/index.d.ts(244,13): error TS2300: Duplicate identifier '_'.

**Expected behavior**

Should be able to add lodash.

**Minimal reproduction of the problem with instructions**

In dependencies, add "lodash": "^4.17.4",
In devDependencies, add: "@types/lodash": "~4.14.50",
In project.config.ts add the following:
{
      name: 'lodash',
      path: `${this.APP_BASE}node_modules/lodash/lodash.js`,
      packageMeta: {
        main: 'index.js',
        defaultExtension: 'js'
      }
    }

**What is the motivation / use case for changing the behavior?**

Lodash makes things easier

**Please tell us about your environment:**

Macbook Pro 2015

* **Angular Seed Version:** `aaaaf75`

6268488913479ae66047b4dd91478e97584fcc31

* **Node:** `node --version` =

**Comment by negberts** [comment]
Lodash has errors. Not angular-seed. Version 4.14.50 works.

**Comment by mgechev** [comment]
@negberts thanks for the comment!

**Comment by sbryfcz** [comment]
To be clear. What is the solution? Downgrade lodash to a previous version? Do you have some exacts for people to follow? I tried lodash 4.14.2 and still have errors.

**Comment by negberts** [comment]
The types of Lodash beyond 4.14.50 are for typescript 2.1. 

We are at     "lodash": "4.17.4", and     "@types/lodash": "4.14.50",

And we include in the project.config like this:
```

let additionalPackages: ExtendPackages[] = [
             {
                name: 'lodash',
                path: 'node_modules/lodash/lodash.js'
            }
        ];
```

**Comment by nyxz** [comment]
I am still experiencing this issue with the latest seed version.

> commit eace08df83f8d632a4705e29cfa492d4060b4f54

```
➜  ~ node -v
v6.10.2
➜  ~ npm -v
5.4.1
```

### Problem

Running the production build with:
```
➜  ~ npm run serve.prod.rollup.aot
```

Results in:

```
[13:13:56] Finished 'build.bundles.app.rollup.aot' after 2.83 s
[13:13:56] Starting 'transpile.bundles.rollup.aot'...

/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:494
      case 0: return func.call(thisArg);
                          ^
SyntaxError: Invalid or unexpected token
    at /home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:14843:16
    at apply (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:494:27)
    at /home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:15227:16
    at apply (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:496:27)
    at /home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:6600:16
    at template (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:14842:20)
    at DestroyableTransform._transform (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/gulp-template/index.js:20:14)
    at DestroyableTransform.Transform._read (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 serve.prod.rollup.aot: `gulp serve.prod.rollup.aot --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 serve.prod.rollup.aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nyxz/.npm/_logs/2017-09-26T10_14_01_511Z-debug.log
```

### How to reproduce

```
➜  ~ npm install --save lodash @types/lodash
```

In `project.config.ts`:

    let additionalPackages: ExtendPackages[] = [{
        name: 'lodash',
        path: 'node_modules/lodash/lodash.js'
      }];

    this.addPackagesBundles(additionalPackages);

In `app.component.ts`:

```
import { Component } from '@angular/core';

import * as _ from 'lodash';

@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
})
export class AppComponent {
  constructor() {
    console.log('Is equal? ' + (_.isEqual({age: 1}, {age: 1})));
  }
}
```

Run the following to get the error:
```
➜  ~ npm run serve.prod.rollup.aot
```

**NOTE**: 
```
➜  ~ npm start
```
runs without any error and I get the following message in the console:
> Is equal? true
