### ISSUE TITLE
Different behaviour between dev and production builds

### ISSUE THREAD

**Issue by misamae** [mgechev/angular-seed#1791]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I'm experiencing different behaviour between dev and production builds. It seems to be related to library I added to the project. The following steps should reproduce the issue: 

**Expected behavior**
I can see that AdminLTE is added to shim.js in production build. Also, if I run $.AdminLTE from console I can see the object is defined. My guess is that the order of scripts are different between dev and production. Ideally these should be the same.

To reproduce the error you can follow these steps
1. cloned the project on 2017-01-30 commit 5fb5a8b
2. npm install --save jquery bootstrap admin-lte
3. update project.config.ts
```
      this.NPM_DEPENDENCIES = [
        ...this.NPM_DEPENDENCIES,
        {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
        {src: `bootstrap/dist/js/bootstrap.min.js`, inject: 'libs'},
        {src: `admin-lte/dist/js/app.min.js`, inject: 'libs'},
        {src: `bootstrap/dist/css/bootstrap.min.css`, inject: true},
    ];

```
4. update app.component.ts
```

declare var $: any;
@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
})
export class AppComponent implements OnInit {
  constructor() {
    console.log('Environment config', Config);
  }
  ngOnInit(): void {
    $.AdminLTE.layout.fix();
  }
}
```
4. run npm start and the console doesn't show any error
5. run npm run serve.prod and you see that $.AdminLTE during AppComponent OnInit call is undefined. This can be seen from the error in the console and there is an error there.

**Comment by mgechev** [comment]
Thanks for reporting this issue! I'll take a look at it today.

**Comment by misamae** [comment]
@mgechev Thank you!

**Comment by mgechev** [comment]
It's not a problem in the seed but a race condition.

The `$.AdminLTE.layout` is initialized on `document.ready` (i.e. `$(function () {...})`) which in case of development happens before the application gets loaded (since it's non-optimized and requires a bit more time in order to fetch all the required assets). On the other hand, when the application is bundled, the `ngOnInit` is invoked before the `document.ready` event is fired. This causes call of the `$.AdminLTE.layout.fix` method but `layout` is `undefined`.

To fix the problem use:

```ts
/**
 * This class represents the main application component.
 */
@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
})
export class AppComponent {
  constructor() {
    console.log('Environment config', Config);
  }
  ngOnInit(): void {
    $(function () {
      $.AdminLTE.layout.fix();
    });
  }
}
```

I'd not recommend you using Angular with jQuery in long term.

**Comment by misamae** [comment]
Thank you @mgechev. That fixed the issue. Regarding your suggestion about jquery, I fail to see a replacement with its vast ecosystem of code and plugins already available.

**Comment by mgechev** [comment]
Yes, jQuery is convenient for rapid development. Hopefully at some point we'll have enough high-quality Angular components :)

**Comment by misamae** [comment]
@mgechev Thank you!
