### ISSUE TITLE
How to include external TypeScript files from node_modules to the app

### ISSUE THREAD

**Issue by AlexanderLukin** [mgechev/angular-seed#1792]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I need to include [amcharts3-angular2](https://github.com/amcharts/amcharts3-angular2) directive to my project. It has been installed via npm without compilled .js version, so, in my `node_modules/amcharts3-angular2` folder I have the TypeScript file `amcharts.directive.ts` and need to import it in my `AppModule`. How can I configure angular-seed to accomplish this?

**Expected behavior**
Need the ability to import TypeScript files from external libs in `node_modules`. If it's already implemented, need a documentation how a user can do it.

**Minimal reproduction of the problem with instructions**
`npm install amcharts/amcharts3-angular2 --save`
then in `app.module.ts`
`import { AmChartsDirective } from 'amcharts3-angular2/amcharts.directive'`

**Please tell us about your environment:**
OS: Windows 10 x64;
Node v.7.3.0
NPM 3.10.10

* **Angular Seed Version:** `83071a3c2fa98a6894dac674dafa0b7071810f45`

* **Node:** `node --version` = 7.3.0

**Comment by mgechev** [comment]
Below are a few articles which explain how npm generally works. You can also find out what is TypeScript and what is its place in the JavaScript world. Finally, you can see how an Angular components need to be distributed as an npm module. Good luck!

- [A Beginner’s Guide to npm — the Node Package Manager](https://www.sitepoint.com/beginners-guide-node-package-manager/)
- [package.json](https://docs.npmjs.com/files/package.json)
- [What is TypeScript and why would I use it in place of JavaScript?](https://stackoverflow.com/questions/12694530/what-is-typescript-and-why-would-i-use-it-in-place-of-javascript)
- [The Future of Declaration Files](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)
- [Distributing an Angular Library - The Brief Guide](http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/)

**Comment by MarcoTregnaghi** [comment]
This is awesome!
