### ISSUE TITLE
Question: how to add ngrx/store, etc to the seed?

### ISSUE THREAD

**Issue by alvipeo** [mgechev/angular-seed#1793]
I've seen advanced seed but I don't need all of its features, so I'm trying to add ngrx myself. From what I see, I need to add '@ngrx/core' and '@ngrx/store' to NPM_DEPENDENCIES array:

```
  /**
   * The list of NPM dependcies to be injected in the `index.html`.
   * @type {InjectableDependency[]}
   */
  NPM_DEPENDENCIES: InjectableDependency[] = [
    { src: 'core-js/client/shim.min.js', inject: 'shims' },
    { src: 'zone.js/dist/zone.js', inject: 'libs' },
    { src: 'zone.js/dist/long-stack-trace-zone.js', inject: 'libs', buildType: BUILD_TYPES.DEVELOPMENT },
    { src: 'intl/dist/Intl.min.js', inject: 'shims' },
    { src: 'systemjs/dist/system.src.js', inject: 'shims', buildType: BUILD_TYPES.DEVELOPMENT },
    // Temporary fix. See https://github.com/angular/angular/issues/9359
    { src: '.tmp/Rx.min.js', inject: 'libs', buildType: BUILD_TYPES.DEVELOPMENT },
    { src: "@ngrx/core/bundles/core.min.umd.js", inject: "libs", buildType: BUILD_TYPES.DEVELOPMENT },
    { src: "@ngrx/store/bundles/store.min.umd.js", inject: "libs", buildType: BUILD_TYPES.DEVELOPMENT },
    { src: "@ngrx/store-devtools/bundles/store-devtools.umd.js", inject: "libs", buildType: BUILD_TYPES.DEVELOPMENT }
  ];
```
But when I 'npm start' I get these errors:
>> core.min.umd.js?1486120453962:1 Uncaught TypeError: Cannot read property 'Observable' of undefined
    at core.min.umd.js?1486120453962:1
    at core.min.umd.js?1486120453962:1
(anonymous) @ core.min.umd.js?1486120453962:1
(anonymous) @ core.min.umd.js?1486120453962:1
store.min.umd.js?1486120453962:1 Uncaught TypeError: Cannot read property 'core' of undefined
    at store.min.umd.js?1486120453962:1
    at store.min.umd.js?1486120453962:1

So, how can I added it?

**Comment by mgechev** [comment]
Here are a [couple of issues](https://github.com/mgechev/angular-seed/issues?utf8=%E2%9C%93&q=is%3Aissue%20ngrx%20is%3Aclosed%20) related to your problem. You don't have to use script injection but the module loader instead.
