### ISSUE TITLE
Package.json not found ng bootstrap

### ISSUE THREAD

**Issue by jayeshanandani** [mgechev/angular-seed#1795]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I try to inject ng-bootstrap it doesn't work just by adding it in additioanlPackages. Despite all the paths it is not able to locate package.json.

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Install ng-bootstrap and add following to additionalPackage:

```
{
      name: '@ng-bootstrap/ng-bootstrap',
      // Path to the package's bundle
      path: `${this.NPM_BASE}@ng-bootstrap/ng-bootstrap`,
      packageMeta: {
        main: 'bundles/ng-bootstrap.js',
        defaultExtension: 'js'
      }
    }
```

It won't work until we specify `join('node_modules', '@ng-bootstrap', '*', 'package.json')` in SYSTEM_BUILDER_CONFIG.packageConfigPaths. This parameter is not configurable in project config. If we try to over ride somehow it doesn't works.

**Please tell us about your environment:**

MAC OS, Visual Studio Code/Sublime Text

* **Node:** `node --version` =
6.9.2

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
