### ISSUE TITLE
Error on fetch for javascript library (npm run build.prod)

### ISSUE THREAD

**Issue by bwwilliam** [mgechev/angular-seed#1796]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I installed angular-2-local-storage from npm.
When I run the project by using "npm start" everything works fine as expected.
The problem comes when I run "npm run build.prod". 
It says Error on fetch for angular-2-local-storage.js at file:///C:/Dev/Web/node_modules/angular-2-local-storage.js, where there is not such file exist in the directory anyway.

**Expected behavior**

I am expecting the project to build and create the all the files in dist folder under prod.

**Minimal reproduction of the problem with instructions**

npm install angular-2-local-storage --save
go to seed.config.ts and add "'angular-2-local-storage': { main: 'dist/index.js', defaultExtension: 'js' }" to packages field.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, with git bash.
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.9

**Comment by mgechev** [comment]
Please, take a look at existing issues related to referencing external dependencies.

**Comment by bwwilliam** [comment]
hi, did you mean this thread? https://github.com/mgechev/angular-seed/issues/744
I have been digging through the existing threads and I could not find the right answer. 
Any help from you would be really appreciated. 
Thanks.

**Comment by mgechev** [comment]
Here are issues you can take a look at https://github.com/mgechev/angular-seed/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20external%20.
