### ISSUE TITLE
Support for Hot Module Replacement?

### ISSUE THREAD

**Issue by mikesmo** [mgechev/angular-seed#1798]
For a large project the workflow becomes quite slow waiting for the code to build. Any plans to include something like webpack hot module replacement?

**Comment by mgechev** [comment]
There's no HMR for Angular which preserves the state of the providers and directives' state implicitly. The current solutions are related to coupling the projects with explicit API calls or provide incomplete solutions.

I will prefer to not introduce HMR in Angular Seed. If you find it beneficial, you can always implement such feature in your custom fork.

**Comment by mikesmo** [comment]
https://github.com/AngularClass/angular2-hmr
seems to work ok for me.... 

Combined with redux, the state is preserved perfectly

**Comment by mgechev** [comment]
`hmrOnInit`, `hmrOnDestroy`, `hmrAfterDestroy` are hooks added by an API. In my opinion, HMR should be transparent to developers and should not require any additional logic.

Another incompatibility which makes integrating `angular2-hmr` with Angular Seed impossible is that the HMR is coupled to webpack.
