### ISSUE TITLE
Problem when loading fs.js and rxjs.js

### ISSUE THREAD

**Issue by fcollombon** [mgechev/angular-seed#1800]
I try to use ng2-translate and localize-router on angular-seed project. I have no problem to use ng2-translate but when I try to use localize-router, I have this errors:
```
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/fs.js
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/rxjs.js
```

**The path of the libs are incorrect and I don't know why because in my IDE the libs are correctly imported.**

This is my **tsconfig.json**:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015"],
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules"
    ],
    "types": [
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "src"
  ],
  "compileOnSave": false
}
```

Thanks a lot in advance.

**Comment by mgechev** [comment]
It seems the webpack bundle of the library you're trying to introduce doesn't play well with the UMD bundles of RxJS and Angular.

The RxJS problem, most likely, could be solved by adding:

```ts
...
packages: {
  rxjs: {
    main: 'Rx.js'
  }
}
```

As part of your System config but it most likely won't solve the issues with Angular since the framework is distributed with ESM packages by default which will cause System to try to download traceur (because of the ES6 syntax).

In all cases `tsconfig.json` doesn't has anything to do with the configuration. I'd recommend you to experiment with `tools/config/project.config.ts`.

**Comment by fcollombon** [comment]
In which file I have to add this: ?

```
...
packages: {
  rxjs: {
    main: 'Rx.js'
  }
}
```

I don't really understand. I have already this in my **seed.config.ts** : 

```
...
packages: {
  ...
  'rxjs': {
    main: 'Rx.js',
    defaultExtension: 'js'
  }
}
```

That's what you're talking about? But I don't touch this... I downloaded as it.

**Just for be sure, I have added ng2-translate and localize-router like this in my additionalPackages of project.config.ts:**

```
// Add packages (e.g. ng2-translate)
let additionalPackages: ExtendPackages[] = [{
    name: 'ng2-translate',
    // Path to the package's bundle
    path: 'node_modules/ng2-translate/bundles/ng2-translate.umd.js'
}, {
   name: 'localize-router',
   // Path to the package's bundle
   path: 'node_modules/localize-router/bundles/localize-router.umd.js'
}];

this.addPackagesBundles(additionalPackages);
```

It's correct, isn't it?

Thanks a lot in advance,

François

**Comment by ruffiem** [comment]
@fcollombon it seems correct to me. Did you try ?

**Comment by fcollombon** [comment]
Well yes I tried what I said before... And I always have the same error : 
```
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/rxjs.js
```

**Comment by ruffiem** [comment]
Can you post an example of your imports ?

**Comment by fcollombon** [comment]
The imports of my app.module.ts?

**Comment by ruffiem** [comment]
Any imports from your components after it started to crash

Le mer. 8 févr. 2017 à 10:40, François Collombon <notifications@github.com>
a écrit :

The imports of my app.module.ts?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mgechev/angular-seed/issues/1800#issuecomment-278278720>,
or mute the thread

**Comment by fcollombon** [comment]
This is my **app.module.ts**:
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { Http, HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

import { AboutModule } from './about/about.module';
import { HomeModule } from './home/home.module';
import { SharedModule } from './shared/shared.module';

import { TranslateModule, TranslateLoader, TranslateStaticLoader, TranslateService } from 'ng2-translate';
import { LocalizeRouterModule, LocalizeParser } from 'localize-router';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' }
];

@NgModule({
    imports: [BrowserModule, HttpModule, AppRoutingModule, AboutModule, HomeModule, SharedModule.forRoot(), TranslateModule.forRoot({
        provide: TranslateLoader,
        useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets/i18n', '.json'),
        deps: [Http]
    }), LocalizeRouterModule.forRoot(routes),
        RouterModule.forRoot(routes)],
    declarations: [AppComponent],
    providers: [{
        provide: APP_BASE_HREF,
        useValue: '<%= APP_BASE %>'
    }],
    bootstrap: [AppComponent]

})
export class AppModule { }
```

**Comment by ruffiem** [comment]
this is bad practice but try this:

```import { LocalizeRouterModule, LocalizeParser } from 'localize-router/localize-router';```

**Comment by fcollombon** [comment]
I tried and I have this:
```
XHR error (404 Not Found) loading http://localhost:5555/node_modules/localize-router/localize-router.js
```

**Comment by ruffiem** [comment]
@fcollombon I ran a few tests and there seems to be a dependencies path compatibility issue between localize-router and the seed which result into legions of 404 and / or "Module already loaded" errors. I believe localize-router was designed for angular-cli and was not tested with other seeds.

**Comment by ruffiem** [comment]
As for the fs.js problem. fs.js does not exist. Fs is a built-in node module and as far as I know, localize-router uses it to bypass angular Http service which is not loaded when the module tries to load locale files. I recommend to use a xhr request instead. Example code below:

```javascript
export class TranslateUniversalLoader implements TranslateLoader {
  /**
   * Gets the translations from the server
   * @param lang
   * @returns {any}
   */
  public getTranslation(lang: string): Observable<any> {
    return Observable.create(observer => {
      let xhr = new XMLHttpRequest;
      xhr.open('GET', `/assets/locales/${lang}.json`);
      xhr.onload = (data: any) => {
        observer.next(JSON.parse(data));
        observer.complete();
      };
      xhr.send();
    });
  }
}
```

**Comment by fcollombon** [comment]
Ok I understand... Do you know another lib to have the lang in the url?

**Comment by ruffiem** [comment]
No, sorry. I just saw your issue was flagged by localize-router's maintainer as a bug in its module maybe you should wait for it to be fixed.
