### ISSUE TITLE
Need help in deploying prod build in s3

### ISSUE THREAD

**Issue by syedsuhail** [mgechev/angular-seed#1803]
How do I serve angular seed from s3? 

I tried uploading the prod build to s3 but all the js urls are pointing to the wrong path. 
For e.g app.js is pointing to <s3 url>/js/app.js when it should point to <s3 url>/<bucket>/prod/js/app.js

How do i change the configuration to allow this?

**Comment by mgechev** [comment]
You need to set the [base path](https://github.com/mgechev/angular-seed#configuration) using the `--base` flag when building.
