### ISSUE TITLE
Really slow `npm run build.prod`

### ISSUE THREAD

**Issue by zte10200896** [mgechev/angular-seed#1804]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

We use the angular2 development front-end project, by using the angular seed.<br/>
But now I have the following questions:<br/>
When I use npm run build.prod, it takes a lot of time and it runs very slowly.
<br/> I checked my package.json file, part of the configuration is:<br/>

> 

"name": "angular-seed",
   "version": "0.0.0",
   "description": "Modular starter project for Angular 2(and beyond) with statically typed build and AoT compilation",
  "repository": {
                  "url": "https://github.com/mgechev/angular-seed"
     },
  "author": "Minko Gechev <mgechev>",
  "license": "MIT",
 "devDependencies": {
"@angular/compiler-cli": "^2.1.0",
"@angular/platform-server": "^2.1.0",
"@angular/tsc-wrapped": "^0.3.0",
"@types/async": "^2.0.32",
"@types/browser-sync": "^0.0.34",
"@types/core-js": "^0.9.34",
"@types/express": "^4.0.33",
"@types/gulp": "^3.8.32",
"@types/gulp-load-plugins": "^0.0.28",
"@types/gulp-protractor": "^1.0.29",
"@types/gulp-sass": "^0.0.29",
"@types/gulp-util": "^3.0.29"，
 "gulp": "^3.9.1"
}

When I run npm build.prod, generally need to spend more than 25 minutes.<br/> Using some better computer, at least 1380 seconds(23min). How can we reduce the time?
Other people have asked this similar question, but did not find a solution.
https://github.com/mgechev/angular-seed/issues/500

**Expected behavior**

npm   run build.prod   more   faster  && Reduces running time
**Minimal reproduction of the problem with instructions**
   nothing
 

**What is the motivation / use case for changing the behavior?**

nothing

**Please tell us about your environment:**

My computer configuration is as follows:
`system: x86_64 GNU/Linux

cpu:
     processor  : 5
vendor_id   : GenuineIntel
cpu family  : 6
model       : 42
model name  : Intel Xeon E312xx (Sandy Bridge)
stepping    : 1
microcode   : 0x1
cpu MHz     : 1899.999
cache size  : 4096 KB

memory: 8G`
* **Angular Seed Version:** `version": "0.0.0`

* **Node:** `node --version` =  v6.9.0

**Comment by mgechev** [comment]
Here's what you can do https://github.com/mgechev/angular-seed/wiki/Speeding-the-build-up.

**Comment by zte10200896** [comment]
@mgechev     Thanks very much!  goodluck!
