### ISSUE TITLE
Multiple application support documentation - Wiki

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1810]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

We are using Angular Seed for our application, would like to add one more application to the same repository so that we can use the same seed.. I do not see any documentation/Wiki for instructions on this
**Expected behavior**

If there is any Wiki on how to add an application to the existing angular Seed, that would be great

**Minimal reproduction of the problem with instructions**

Add an application to the existing Angular seed application
**What is the motivation / use case for changing the behavior?**

Add multiple applications to the same Angular Seed so that base configuration can be reused
**Please tell us about your environment:**

Windows 10, WebStorm
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.4

**Comment by mgechev** [comment]
Hey @skolli853780, you can use the same seed instance for multiple applications following these practices:

- Create directory in `src/client/APP_NAME`.
- Inside `src/client/APP_NAME` you should have `main.ts` (and `main-prod.ts` for you want to use AoT).
- Run your dev build with: `npm start -- --app APP_NAME` and your production: `npm run build.prod -- --app APP_NAME`.

**Comment by skolli853780** [comment]
Thank you..
