### ISSUE TITLE
Adding external Dependency

### ISSUE THREAD

**Issue by Meistercoach83** [mgechev/angular-seed#1818]
*I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

When I add a new APP_ASSET in project.config.js and then run npm start, the new file is not loaded in the index.html
`      {src: `${this.ASSETS_SRC}/js/cubeportfolio/jquery.cubeportfolio.js`, inject: true, vendor: false},`
After a second npm start it is loaded correctly.

**What is the motivation / use case for changing the behavior?**
Is this a bug or a feature? I think it should load the new dependency right after the first restart

* ** Windows 10
* **Angular Seed Version:** `bdce1efb551299cf3bf1ad3970ea50f709206e6d`
* **Node:** `node --version` = 3.10.9

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
