### ISSUE TITLE
Uncaught Module xx not present.

### ISSUE THREAD

**Issue by adshrc** [mgechev/angular-seed#1819]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Can't open built project because of error `Uncaught Module xx not present.`
The same error occurs when no package definition was added to project.config.

**Expected behavior**
That the built project loads fine, like the dev (`npm start`) does.

**Minimal reproduction of the problem with instructions**

- installed `angular2-swiper-wrapper` to the project, added the following package definition:

```
{
          name: 'angular2-swiper-wrapper',
          path: `${this.NPM_BASE}angular2-swiper-wrapper/bundles/angular2-swiper-wrapper.umd.js`,
          packageMeta: {
            main: '../dist/index.js', //tried almost every file from dist/
            defaultExtension: 'js'
          }
}
```

- imported SwiperModule, added `SwiperModule.forRoot(SWIPER_CONFIG)` to imports in home.module.ts and added 

```
const SWIPER_CONFIG: SwiperConfigInterface = {
  direction: 'horizontal',
  slidesPerView: 'auto',
  keyboardControl: true
};
```
to the same file

- added some `<swiper><div>content...</div></swiper>` to the html

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
MacOS 10.11.6, `npm serve.prod`

* **Angular Seed Version:** `2b8cc33`

* **Node:** `node --version` = 7.2.0

**Comment by ruffiem** [comment]
Try this in `project.config.ts` :

```JavaScript
    // Add packages (e.g. ng2-translate)
    let additionalPackages: ExtendPackages[] = [{
      name: 'angular2-swiper-wrapper',
      // Path to the package's bundle
      path: 'node_modules/angular2-swiper-wrapper/bundles/angular2-swiper-wrapper.umd.min.js'
    }];
    //
    this.addPackagesBundles(additionalPackages);
```

This was tested and it works.

**Comment by adshrc** [comment]
works perfectly! thank you very much!
