### ISSUE TITLE
angular2-seed@0.0.0 postinstall error

### ISSUE THREAD

**Issue by habibliu** [mgechev/angular-seed#1820]
**I'm a beginner on angular2, when i  execute the command  nom install ,i got the errors such as :**  
```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `rimraf typings && typings install && gulp check.versions && gulp postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'rimraf typings && typings install && gulp check.versions && gulp postinstall'.
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `0.0.0`

* **Node:** `node --version` =v7.5.0

**Comment by mgechev** [comment]
This seems like an old version of the project (if that's the correct project). We don't use typings anymore.

Try:

`git clone https://github.com/mgechev/angular-seed && cd angular-seed && npm i`
