### ISSUE TITLE
problem on add new external modules

### ISSUE THREAD

**Issue by sureshhustle** [mgechev/angular-seed#1823]
hi,
 i am installing a new external module in app it shows error for include in project.config.ts,
if it will be the .j extension then i can able to add but i am unable to add .ts extension module in project.config.ts.

can anyone please help me to solve this problem.
![desctop screenshot](https://cloud.githubusercontent.com/assets/24749025/23091157/9c4c87c2-f5d5-11e6-8623-a4d9debfb2e6.png)

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by sureshhustle** [comment]
here also they gave only for .js extension, when i add .ts extention it will not work.
i am using ng2-google-place-autocomplete it had only .ts format how can i add it in project.config.ts
