### ISSUE TITLE
issue on build prod app

### ISSUE THREAD

**Issue by sureshhustle** [mgechev/angular-seed#1826]
Hi,
    I had a problem on build production mode. but it display error i will upload that screenshot and debug-log file.
i am searching that issue it shows to change systemjs-builder version i done this but again it shows the error.
  i am using mac os
noe v7.4.0
npm 4.0.5
[debug-log.txt](https://github.com/mgechev/angular-seed/files/786678/debug-log.txt)
![screen shot 2017-02-20 at 11 21 13 am](https://cloud.githubusercontent.com/assets/24749025/23113825/dac71e36-f760-11e6-8dd4-23a5bd344adc.png)

please help me solve this issue

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
