### ISSUE TITLE
Trying to use the seed on one of the pages in already existing website

### ISSUE THREAD

**Issue by ShurikAg** [mgechev/angular-seed#1827]
Hi all, 

I know, that this is more of a question than reporting a problem, but I didn't get a response anywhere else and didn;t really find any answer for it. Please, let me know of there is any better place to ask this.

I was using the seed for a while now and I even have couple of apps in production with it. These apps are build fully with angular2 and everything is clear and straight forward.
My current target is a bit different:
I have a website that was build with Symfony2 and I am trying to find a way to use a seed only on user profile (anything under domain.com/jm/...).
In production mode, it seems like it is not a problem, since all I need to do is to include the right files on the page.
However, I am completely stuck with a setup for dev mode:
1. It references files not only from `dest` folder
2. If I try using `npm start` it cannot serve the app through port 80. and eventually the whole flow from website to the pages of the app will be broken.
3. Even if I'll somehow manage to set the paths to correct files manually, I will need to do it almost on any code change, because the the seed builds the project it adds a hash to every file to invalidate the cache. And I didn't find any way to generate the file I need in a location I need using seed's build.

My question is, what could be the approach to solve it (if even possible)? 
By the way, the auto-reloading of browser is not even important to me in this situation.
The most important that the original website and the app will be served from the same domain.

Thank you in advance.

**Comment by tarlepp** [comment]
@ShurikAg I recommend that you separate totally backend (symfony) and frontent (your ng2 application), with this way it's more clearer to dev your application(s). I have multiple examples about this kind of application structure.

**Comment by mgechev** [comment]
@ShurikAg the answer of @tarlepp is the correct way to go. You can run the dev server on port 5555 and communicate with the PHP backend running in Apache/nginx/etc. through HTTP with CORS.

**Comment by ShurikAg** [comment]
So what you propose is to run it completely differently in dev vs prod? 
Run it through `npm start` for dev and build the target page by hand for production?
Also, session sharing going to be much more challenging.

**Comment by tarlepp** [comment]
@ShurikAg for production you compile your angular app, and then just upload the output html + css + js to your server - note that these are static files at this point.

And for session sharing - you really don't need any sessions. Just use stateless JWT. You can take a closer look of my repositories:

https://github.com/tarlepp/symfony-backend
https://github.com/tarlepp/angular-cli-frontend

Let's continue this on gitter channel
