### ISSUE TITLE
Codelyzer 3.0.0

### ISSUE THREAD

**Issue by negberts** [mgechev/angular-seed#1838]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

I am probably way ahead of things but how can we integrate the new codelyzer into angular seed?

I tried things like modifying the seed.tslint.json with 

```
"linterOptions": {
    "typeCheck": true
  },
```

Or suppling `{ typeCheck: true }` to the tslint program but no effects.

**Comment by mgechev** [comment]
You can change the `lint` script in `package.json` to:

```
tslint --type-check --project src/client/tsconfig.json
```

In `tsconfig.json` add `app/main.ts` in the `files` section. Now you should be able to run:

```
$ npm run lint
```

**Comment by negberts** [comment]
But how is it done in the tslint task? (tools/tasks/seed/)

**Comment by mgechev** [comment]
This will involve `gulp-tslint`. You need to take a look at the plugin's docs.
