### ISSUE TITLE
npm run build.prod on a fresh git clone does not seem to sork

### ISSUE THREAD

**Issue by alarive** [mgechev/angular-seed#1841]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

I could not get the bundle produced by ``npm run build.prod`` to work. 

Trying to point my browser to the generated index.html (served by httpd) gives the following error in chrome :
```
app.js:1 Uncaught ReferenceError: Invalid left-hand side expression in postfix operation
```

In Firefox I get:
```
SyntaxError: invalid increment operand app.js:1:728
```

npm version : 3.10.10
node version : v6.10.0

**Comment by mgechev** [comment]
@alarive do you think this could be related https://github.com/mgechev/angular-seed/issues/1840?

**Comment by alarive** [comment]
Indeed, those 2 issues are related. Since you downgraded rxjs I cannot reproduce it. Thanks !
