### ISSUE TITLE
probleme in ng2-page-scroll

### ISSUE THREAD

**Issue by zarga86** [mgechev/angular-seed#1842]
probleme in ng2-page-scroll ?

![capture d ecran 2017-03-01 a 12 47 57](https://cloud.githubusercontent.com/assets/25960782/23458737/b1f9df6a-fe7d-11e6-84d5-af2cf8d36eae.png)
![capture d ecran 2017-03-01 a 12 48 17](https://cloud.githubusercontent.com/assets/25960782/23458738/b1fd31a6-fe7d-11e6-9677-fbb144baaf40.png)
![capture d ecran 2017-03-01 a 12 48 36](https://cloud.githubusercontent.com/assets/25960782/23458739/b2011c30-fe7d-11e6-939f-574d473af178.png)
![capture d ecran 2017-03-01 a 12 48 49](https://cloud.githubusercontent.com/assets/25960782/23458740/b2068116-fe7d-11e6-913f-8f8e59a5d932.png)

**Comment by lifaon74** [comment]
In project.config.ts, you'll need to import the external modules/libs that you want to use.

**Comment by zarga86** [comment]
Still problem

![capture d ecran 2017-03-01 a 15 12 03](https://cloud.githubusercontent.com/assets/25960782/23463380/8c0da7b4-fe91-11e6-8e94-2b80051a8f57.png)
![capture d ecran 2017-03-01 a 15 12 12](https://cloud.githubusercontent.com/assets/25960782/23463381/8c15b454-fe91-11e6-8c8c-dd222ab1f601.png)

**Comment by lifaon74** [comment]
You need to do something like:

```ts
additionalPackages.push({
      name: 'moment',
      path: `${this.APP_BASE}node_modules/moment/moment.js`,
      packageMeta: {
        main: 'moment.js',
        defaultExtension: 'js'
      }
    });
```
Please take a look at the wiki and the comments inside project.config.ts.

Moreover, I encourage you to use less libs or angular 2 libs. For example, you could use ng2-bootstrap, avoid jQuery by using document.querySelector and css animations (all polyfilled by core-js). In general you should use a maxium native functionalities (including es6 and 7, CSS4) and polyfill them if necessary => It goes faster and use less bandwidth !
And you could bundle the external css into a scss file.

**Comment by zarga86** [comment]
thnx that's very useful
