### ISSUE TITLE
Overriding dev or prod destination directories in ProjectConfig not getting picked up

### ISSUE THREAD

**Issue by rishinaveen** [mgechev/angular-seed#1843]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Override DEV_DEST, PROD_DEST in ProjectConfig don't reflect during builds due to all build scripts using APP_DEST which is derived from SeedConfig (parent) which doesn't take the overridden properties from ProjectConfig (child) into effect.

<pre>
project.config.ts
--------------------------------
constructor() {
--
this.DEV_DEST = 'dist/build'
this.PROD_DEST = 'dist/build'
--
}
--------------------------------

seed.config.ts
--------------------------------
--
APP_DEST = this.BUILD_TYPE === BUILD_TYPES.DEVELOPMENT ? this.DEV_DEST : this.PROD_DEST;
--
--------------------------------
</pre>

**Expected behavior**

Expected the build script generated files to be put in the overridden location.

**Minimal reproduction of the problem with instructions**

Update project.config.ts as described above and do "npm run build.dev"

**What is the motivation / use case for changing the behavior?**

I am trying to integrate angular seed into a java-spring-maven driven application and would like to copy over files from a common location all the time.

**Please tell us about your environment:**

Mac OSX, Intellij, Java 1.7, Node 6.10.0, NPM 3.10.x

* **Angular Seed Version:** `aaaaf75`

580605ad35a4b1731db628a5de0d8df01b132dc4

* **Node:** `node --version` =
6.10.0

**Comment by mgechev** [comment]
Yes, this issue has been discussed a lot in the past. Currently, overriding config variables is not as clean as we wished it is. If you have some time, it'll be great if you open a PR.

You can follow the discussion [from before here](https://github.com/mgechev/angular-seed/issues?q=is%3Aissue+override+is%3Aclosed).

**Comment by mgechev** [comment]
Closed due to inactivity.

**Comment by rishinaveen** [comment]
Sorry. I wanted to contribute but work's crazy. Will get to this when time permits.

**Comment by mgechev** [comment]
No worris. It's not a high priority issue which breaks a lot of things but it's good to have.
