### ISSUE TITLE
Lazy loading does not work in production mode

### ISSUE THREAD

**Issue by ogousa** [mgechev/angular-seed#1844]
I'm submitting a bug report.

I have problems with **"lazy" branch** of the seed project (Windows 10) while creating production build.

First, I have to use

**import { HomeComponent } from '../home/home.component';
import { HomeRoutingModule } from '../home/home-routing.module';**

instead of

**import { HomeComponent } from './home.component';
import { HomeRoutingModule } from './home-routing.module';**

The same trick for about module. Otherwise build.lazy-bundles.app.ts cannot find home folder:

![image](https://cloud.githubusercontent.com/assets/11968221/23477764/0a550130-fe8d-11e6-98ea-3bcb3370f78d.png)

With these changes I can create bundles, but when I copy result to my web server I have this error:

![image](https://cloud.githubusercontent.com/assets/11968221/23477827/436416a0-fe8d-11e6-9fdb-098ffefb1c47.png)

Does anybody implement lazy loading in production?

Thanks.

**Comment by mgechev** [comment]
Lazy loading is not one of the features that Angular seed supports officially. It involves custom configuration that you should implement yourself. For support requests I'd recommend you either stackoverflow or gitter.
