### ISSUE TITLE
Third party package.json bundling issue.

### ISSUE THREAD

**Issue by senthilkumar04** [mgechev/angular-seed#1846]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
The third party package is not getting bundled during the build.bundles.app task.For including third packages such as @ng-bootstrap, i have used the project.seed.config file to extend the extend actual seed.config and inject those packages. But When i try to add the "ng-bootstrap" feature to the paths and while building for the production environment, it is throwing an error in the "build.bundles.app" task that it is unable to find the "package.json" file. It is working fine in the development environment.

project.config.ts
---------------------------------------
import { ExtendPackages } from './seed.config.interfaces';

let additionalPackages: ExtendPackages[] = [{
    name: '@ng-bootstrap', //This is object is for dev build
    path: 'node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js'
},{
    name: '@ng-bootstrap/*', //This object is for prod build
    path: 'node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js'
}];
this.addPackagesBundles(additionalPackages);
`

**Expected behavior**
Expected the third party package to be added to the bundle in the production environemnt.

**Minimal reproduction of the problem with instructions**
Update project.config.ts as described above and do "npm run build.prod"

**What is the motivation / use case for changing the behavior?**
The option should be given to join the package.json to the packageConfigsPath in the SYSTEM.BUILDER.CONFIG through the project.seed.config

**Please tell us about your environment:**
Mac OSX, VS Code, Java 1.7, Node 6.10.0, NPM 3.10.x

* **Angular Seed Version:** `aaaaf75`
580605a

* **Node:** `node --version` = 6.10.0

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
