### ISSUE TITLE
Error: Cannot run npm run build.prod:'gulp build.prod ---color ---env-config prod --build-type prod Exit status 1

### ISSUE THREAD

**Issue by srinivasan-g** [mgechev/angular-seed#1847]
![image](https://cloud.githubusercontent.com/assets/8088685/23514139/41085e58-ff5e-11e6-9b12-913a4548f6e9.png)

**Comment by mgechev** [comment]
Would you share minimal demo where I can reproduce the problem? The screenshot doesn't provide enough information.

**Comment by srinivasan-g** [comment]
Hi,
Please check the link and download the demo file
https://drive.google.com/open?id=0ByvW48_lWN5aSTNKa0lidXBXQ0U

npm start is working fine. but when i try to build prod
npm run build.prod
npm run build.prod.aot
getting error

Thanks
Sri

**Comment by srinivasan-g** [comment]
Hi
This is the debug I am getting: may be it will help you 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build.prod' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
5 info lifecycle angular-seed@0.0.0~prebuild.prod: angular-seed@0.0.0
6 silly lifecycle angular-seed@0.0.0~prebuild.prod: no script for prebuild.prod, continuing
7 info lifecycle angular-seed@0.0.0~build.prod: angular-seed@0.0.0
8 verbose lifecycle angular-seed@0.0.0~build.prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed@0.0.0~build.prod: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Webpack\DemoCode\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\IronRuby 1.1\bin;%TFSPowerToolDir%;C:\Program Files (x86)\Java\jre1.8.0_111\bin;C:\Users\srinivasan.govindara\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle angular-seed@0.0.0~build.prod: CWD: D:\Webpack\DemoCode
11 silly lifecycle angular-seed@0.0.0~build.prod: Args: [ '/d /s /c',
11 silly lifecycle   'gulp build.prod --color --env-config prod --build-type prod' ]
12 silly lifecycle angular-seed@0.0.0~build.prod: Returned: code: 1  signal: null
13 info lifecycle angular-seed@0.0.0~build.prod: Failed to exec build.prod script
14 verbose stack Error: angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-seed@0.0.0
16 verbose cwd D:\Webpack\DemoCode
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
22 error Exit status 1
23 error Failed at the angular-seed@0.0.0 build.prod script 'gulp build.prod --color --env-config prod --build-type prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod --color --env-config prod --build-type prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks
Sri

**Comment by mgechev** [comment]
I will take a look at the sample code and let you know.

**Comment by mgechev** [comment]
There are a bunch of warnings for mismatching peer dependencies, changes in `seed.config.ts` and other changes. This doesn't seem like a problem in Angular Seed itself.
