### ISSUE TITLE
TypeError: Cannot read property ‘map’ of undefined at Evaluator.evaluateNode -npm run build.prod.aot 

### ISSUE THREAD

**Issue by srinivasan-g** [mgechev/angular-seed#1848]
![image](https://cloud.githubusercontent.com/assets/8088685/23514321/e453a4e6-ff5e-11e6-8fa3-4cc468cf739a.png)

**Comment by mgechev** [comment]
This is not an issue in Angular Seed, seems like a problem in Angular Compiler or an invalid construct in your codebase. It will be great if you can upload a minimum demo of the problem.
