### ISSUE TITLE
Different build results 

### ISSUE THREAD

**Issue by bonaparte89** [mgechev/angular-seed#1849]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
We have three enviroment configs. test, stage, production. Just today it appeared again that test and stage are working fine. Production was actually working, but not displaying any data we fetch from the database... But the data was actually arround. (chrome dev networking..). 
So maybe from the beginning: 
The whole building etc is handled by a build server... With every deploy the application gets completly new installed and then depending on the enviroment build with one of the provided configs. The drop folder then gets automatically uploaded to S3 were some more magic is happening...

When test succeeded, stage and then prod will be deployed. (same sources - no changes).

So comparing the two app.js files from stage and production should actually only show differences within the enviroment config. 

But the following lines showed up as different (winmerger)
 stage-app-js:
    `r = r || e, 0 == --n && t(r)`
prod-app-js
    `r = r || e, 0 == n-- && t(r)`

There are some more lines in those files which show exactly the same differences.
After deploying production env again the app is finally up and running...

Any ideas how to solve this kind of behaviour? 

using the latest seed version....

thanks

**Comment by mgechev** [comment]
Angular Seed provides only production build so I suppose the problem is not in this project. You can take a look at your staging build and verify if the only difference is in the environment variables.
