### ISSUE TITLE
TypeError: System.import is not a function

### ISSUE THREAD

**Issue by tamohugues** [mgechev/angular-seed#1851]
When I run production mode I got this error, plz help me any people know this problem.

I have latest node and npm in windows 10. 

this is the error. 

Unhandled Promise rejection: System.import is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: System.import is not a function

**Comment by tamohugues** [comment]
I using lazy loading in my projet

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by tamohugues** [comment]
I going to gitter and wiki page, but I don't see anything about lazy loading. Plz help

**Comment by jigarpt** [comment]
Hi, I am looking to use lazy loading in my project and I was facing a same issue as mentioned below.

Unhandled Promise rejection: System.import is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: System.import is not a function

However, I followed the [changes done](https://github.com/mgechev/angular-seed/compare/master...lazy) in lazy branch and could make it work for my project. 

This may help someone to resolve this issue. 

Thanks.
