### ISSUE TITLE
I see an error when running npm test on fresh clone

### ISSUE THREAD

**Issue by lobo-tuerto** [mgechev/angular-seed#1852]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When running `npm test`, before `START:` you can see this:
```
Starting 'build.js.test'...
src/client/app/home/home.component.spec.ts(35,39): error TS2352: Type 'NameListService' cannot be converted to type 'MockNameListService'.
  Property 'returnValue' is missing in type 'NameListService'.
```
Tests run fine though.

**Expected behavior**
There should be no errors before the tests run.

**Minimal reproduction of the problem with instructions**
`git clone`, `yarn install`, `npm test`

**Please tell us about your environment:**
Node: v7.7.1
NPM: 4.1.2
SO: Ubuntu 16.04

* **Angular Seed Version:** `8bfec1a`

* **Node:** `node --version` =v7.7.1

**Comment by mgechev** [comment]
That's weird. The Travis tests pass successfully. I will try to verify tomorrow.

**Comment by mgechev** [comment]
@lobo-tuerto thanks for the catch! Caused by change in the `ReflectiveInjector` API.
