### ISSUE TITLE
Is it possible to config karma to test a prod environment?

### ISSUE THREAD

**Issue by PMashaI** [mgechev/angular-seed#1858]
I would like to launch my karma tests on prod environment if it is possible. 

Could someone advise me how to set up the karma config for that?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
