### ISSUE TITLE
Setting to Remove Query String From Assets in index.html

### ISSUE THREAD

**Issue by treyrich** [mgechev/angular-seed#1859]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Currently all assets injected into index.html get a timestamp appended as a query string to the URL. However, when making use of Angular Mobile Toolkit's service worker, this causes none of the static assets to be cached properly. When working with a service worker, there are other methods of managing cached resources than query strings.

**Expected behavior**

It would be nice if we could add a setting in the config to prevent this query string being appended if desired.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To allow service workers to properly cache static assets without using the option `ignoreSearch` which has limited support.

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
Once the build passes we can merge [this](https://github.com/mgechev/angular-seed/pull/1860/files) to master.

PS: Do you have an integration with the mobile toolkit?

**Comment by treyrich** [comment]
Killer! That's great.

I do have an integration, but it's not super well tested at this point. I'm happy to open a PR with what I have at this point though.

Are you looking to get the mobile toolkit service worker integrated into to core project? Or just getting a wiki in place to allow users to integrate for themselves like I suggested in #1857? Personally, I think it would be nice to have it integrated into the core project, and I'm not sure there's much of a downside to users, but I based #1857 off of the comment made in #1693 which stated it was up to the user to handle the service worker implementation.

Let me know, I'm happy to contribute.

**Comment by mgechev** [comment]
Yes, integration into the core sounds good! Sometime back I introduced integration in the seed but right after that we came up with a different architecture for the mobile toolkit and then I dropped it.

Would love to merge a PR with it!
