### ISSUE TITLE
Use angular-seed as a full stack project

### ISSUE THREAD

**Issue by calebeaires** [mgechev/angular-seed#1869]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

Does this project let us use Express to make an Rest API. Something like an isomorphic full-stack framework. I take a look at package.json and Express is already there.

**Comment by mgechev** [comment]
We've discussed this previously and I was against including backend related functionality in the seed. Nowadays, given that `@angular/platform-server` moved to the official monorepo, I think it might not be such a bad idea.

Since it's not in the roadmap, it'll be great if anyone is willing to open a PR/discuss the feature.

**Comment by Shyam-Chen** [comment]
see https://github.com/angular/angular/issues/13822

**Comment by MarkPieszak** [comment]
Only thing I'd caution is that most apps don't need SSR, on top of that it raises the complexity quite a bit as you're required to do/not do certain things (or not use certain angular 3rd party libraries, jQuery, anything related to window etc). So you'll have a lot more people confused why things aren't working than normal. 

Maybe pointing out how it could be added to a fresh/existing repo, but I don't think I'd offer it by default? @mgechev

**Comment by mgechev** [comment]
Closing this one. Let's keep only the FE of the application in the seed.
