### ISSUE TITLE
Cannot build Angular's animations package

### ISSUE THREAD

**Issue by MarcAragones** [mgechev/angular-seed#1870]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Can run `npm start` but it fails with `npm run build.prod`. A package is not found:

```
Error on fetch for @angular/platform-browser/animations.js at file:///Users/PATH_TO_PROJECT/@angular/platform-browser/animations.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/Users/PATH_TO_PROJECT/node_modules/@angular/platform-browser/animations.js'
    at Error (native)
```

**Expected behavior**
Build the project like in development mode.

**Minimal reproduction of the problem with instructions**
What I have done (following [Angular's CHANGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md#installing-rc1)):
- Install animations package (version 4.0.0-rc.1):

  ```
  $ npm install --save @angular/animations
  ```

- Add `BrowserAnimationsModule` to `app.module.ts`:

  ```typescript
  import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

  @NgModule({
     imports: [BrowserAnimationsModule, ...],
     ...
  ```

- Add the package to `SYSTEM_CONFIG_DEV` in `project.config.ts` file (**this makes `npm start` work**):

  ```typescript
  this.SYSTEM_CONFIG_DEV.paths['@angular/animations'] =
    'node_modules/@angular/animations/bundles/animations.umd.js';
  this.SYSTEM_CONFIG_DEV.paths['@angular/platform-browser/animations'] =
    'node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js';
  this.SYSTEM_CONFIG_DEV.paths['@angular/platform-browser/animations/testing'] =
    'node_modules/@angular/platform-browser/bundles/platform-browser-animations-testing.umd.js';
  ```

- Add the package to `SYSTEM_BUILDER_CONFIG` in `project.config.ts` file:
  
  ```typescript
  this.SYSTEM_BUILDER_CONFIG.packages['@angular/animations'] = {
    main: 'bundles/animations.umd.js',
    defaultExtension: 'js'
  };
  this.SYSTEM_BUILDER_CONFIG.packages['@angular/platform-browser/animations'] = {
    main: 'bundles/platform-browser-animations.umd.js',
    defaultExtension: 'js'
  };
  ```

**What is the motivation / use case for changing the behavior?**
With Angular version 4.0.0-rc.2, animations don't work anymore.

**Please tell us about your environment:**
- Operating system: macOS Sierra (10.12.3)
- IDE: WebStorm

* **Angular Seed Version:** `cc08608`

* **Node:** `node --version` = v6.9.5

**Comment by MarcAragones** [comment]
Hi, @mgechev.

Still not working:

- I cloned the project with the commit [f568c69](https://github.com/mgechev/angular-seed/commit/f568c694f3668bdb15ff1f7cecc241bc5bb621e7).
- I added `BrowserAnimationsModule` to `app.module.ts`:
  ```typescript
  import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

  @NgModule({
    imports: [BrowserModule, BrowserAnimationsModule, HttpModule, AppRoutingModule, AboutModule, HomeModule, SharedModule.forRoot()],
  ```

And I still get the same error on `npm run build.prod`

**Comment by mgechev** [comment]
@MarcAragones fixed by https://github.com/mgechev/angular-seed/commit/26864c1a8fcd49afccb92e7400c27bdd8b4d2f96.

**Comment by Mig1st4ck** [comment]
@mgechev  you also need to add this so it can work in build.prod:

`
      '@angular/animations/browser': 'node_modules/@angular/animations/bundles/animations-browser.umd.js',`

**Comment by sjawaji** [comment]
@Mig1st4ck - Your suggestion works.

Following needs to be added to both SYSTEM_CONFIG_DEV.paths & SYSTEM_BUILDER_CONFIG.paths
'@angular/animations/browser': 'node_modules/@angular/animations/bundles/animations-browser.umd.js'

**Comment by mgechev** [comment]
@sjawaji would you open a PR?

**Comment by fireyoshiqc** [comment]
@Mig1st4ck 
Make sure to also include this line to your configs, if needed (I had to, in my case):
`'@angular/animations': 'node_modules/@angular/animations/bundles/animations.umd.js'`

**Comment by Lucius0909** [comment]
Please, i have tried all, and nothing  :/

I'm getting : 

> Runtime Error
> Object prototype may only be an Object or null: undefined

When I run `npm install`, get all this:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN @angular/animations@4.0.0 requires a peer of @angular/core@4.0.0 but none was installed.
> npm WARN @angular/platform-server@4.3.6 requires a peer of @angular/animations@4.3.6 but none was installed.
> npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/common@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/compiler@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/compiler-cli@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/core@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/forms@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/http@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/platform-browser@4.1.3 but none was installed.
> npm WARN ionic-angular@3.6.1 requires a peer of @angular/platform-browser-dynamic@4.1.3 but none was installed.
