### ISSUE TITLE
How to configure build

### ISSUE THREAD

**Issue by dereklin** [mgechev/angular-seed#1875]
When the build is done, it creates dist/prod and dist/tmp.  How can I set it up so that there is no dist/prod nor dist/tmp.  And whatever in dist/prod is in dist, like this?:

![dist](https://cloud.githubusercontent.com/assets/2231799/24085995/eaac26fc-0cc3-11e7-9041-dd2652ee2ff3.PNG)

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
