### ISSUE TITLE
Compodoc not parsing through files in src/client/**

### ISSUE THREAD

**Issue by vigneshnrfs** [mgechev/angular-seed#1876]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

when I run `npm run compodoc` the files inside src folder are not being parsed, since the `/src/client/tsconfig.json` excludes src folder. 
**Expected behavior**

`npm run compodoc` should parse through the files in  `src/client/**`

**Comment by mgechev** [comment]
`compodoc` [does not use the `tsconfig.json` file in the root](https://github.com/mgechev/angular-seed/blob/master/package.json#L43).

**Comment by vigneshnrfs** [comment]
@mgechev But the [tsconfig.json](https://github.com/mgechev/angular-seed/blob/master/src/client/tsconfig.json#L33 ) in the client folder also excludes src folder

**Comment by mgechev** [comment]
`src` in [here](https://github.com/mgechev/angular-seed/blob/master/src/client/tsconfig.json#L30-L33) doesn't match any directories since there's no subdirectory of `src/client` called `src`.

But yeah, we should drop the `src` element from `exclude` since it's not required.
