### ISSUE TITLE
Importing BrowserAnimationsModule Throws 404 - SystemJS Config Issue?

### ISSUE THREAD

**Issue by lfarran** [mgechev/angular-seed#1880]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Importing  BrowserAnimationsModule with Angular v4.0.0 (3/23/17) with:

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
@NgModule({imports: [BrowserAnimationsModule],

Follow Animations install updates described here: https://github.com/angular/angular/blob/master/CHANGELOG.md#installing-rc1

Throws the following error:
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/animations/browser.js

	Error loading http://localhost:5555/node_modules/@angular/animations/browser.js as "@angular/animations/browser" from http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**Expected behavior**

No 404 and successful load of @angular/animations/browser

**Minimal reproduction of the problem with instructions**

Add the following to app.module.ts
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
@NgModule({imports: [BrowserAnimationsModule],

**What is the motivation / use case for changing the behavior?**

Support Angular 4.0.0 animations

**Please tell us about your environment:**

Mac OS X El Capitan 10.11.6, WebStorm, npm v3.10.8

* **Angular Seed Version:** `20e68d5`

* **Node:** `node --version` = 6.9.1

**Comment by damonwildercarr** [comment]
I had the same issue upgrading from 2.0 to 4.0. In the end I was missing the following from my systemjs.config.js:

      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',   

At first I had the first and third line - everything started working once I added the second line for @angular/animations/browser.

**Comment by rcng** [comment]
When you have updated to Angular 4, you must install @angular/animations, it solves the problem. 
npm install @angular/animations --save

**Comment by romafederico** [comment]
I couldn't make it work so far.

macOS 10.12.1 

├── @angular/animations@4.0.1
├── @angular/cli@1.0.0
├── @angular/common@4.0.1
├── @angular/compiler@4.0.1
├── @angular/compiler-cli@4.0.1
├── @angular/core@4.0.1
├── @angular/forms@4.0.1
├── @angular/http@4.0.1
├── @angular/material@2.0.0-beta.2
├── @angular/platform-browser@4.0.1
├── @angular/platform-browser-dynamic@4.0.1
├── @angular/platform-server@4.0.1
├── @angular/router@4.0.1
├── @types/jasmine@2.5.38
├── @types/node@6.0.68
├── codelyzer@2.0.1
├── core-js@2.4.1
├── hammerjs@2.0.8
├── jasmine-core@2.5.2
├── jasmine-spec-reporter@3.2.0
├── karma@1.4.1
├── karma-chrome-launcher@2.0.0
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@0.2.3
├── karma-jasmine@1.1.0
├── karma-jasmine-html-reporter@0.2.2
├── protractor@5.1.1
├── rxjs@5.3.0
├── ts-node@2.0.0
├── tslint@4.5.1
├── typescript@2.2.2
└── zone.js@0.8.5

**Comment by pankajparkar** [comment]
After applying @damonwildercarr comment, I still need to import `BrowserAnimationsModule` and injected inside `imports` metadata option of AppModule's `NgModule`

`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

**Comment by zijianhuang** [comment]
this page: https://material.angular.io/guide/getting-started should put the comment of @damonwildercarr

**Comment by thejavascriptways** [comment]
I had the same issue,  but after installing @angular/animations@4.1.0  and manually adding it to dependencies worked for me 
 "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4",
    "@angular/animations":"^4.1.0"

**Comment by cacothi** [comment]
This issue is still happening with me after installign AngularMaterial, I have the following:

on the app.module.ts

import { BrowserAnimationsModule, NoopAnimationsModule } from '@angular/platform-browser/animations';

imports:      [ BrowserModule, MaterialModule, HttpModule, BrowserAnimationsModule, NoopAnimationsModule],

on the systemjs.config.js

      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',  

getting the following error:

Error: (SystemJS) Cannot read property 'prototype' of undefined
	TypeError: Cannot read property 'prototype' of undefined
	    at __extends (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:15:68)
	    at eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:328:5)
	    at Object.eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:337:2)
	    at Object.eval (http://localhost:3000/app/app.module.js:10:20)
	    at eval (http://localhost:3000/app/app.module.js:32:4)
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js
	    at __extends (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:15:68)
	    at eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:328:5)
	    at Object.eval (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:337:2)
	    at Object.eval (http://localhost:3000/app/app.module.js:10:20)
	    at eval (http://localhost:3000/app/app.module.js:32:4)
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js

**Comment by luxueyan** [comment]
Me too. I used the ng-cli to create my project. And when I import BrowserAnimationsModule, it throw this error.
@angular/cli: 1.1.1
node: 7.9.0
os: darwin x64
@angular/animations: 4.2.2
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

**Comment by esc-co** [comment]
@luxueyan 
Finally a solution, thank you!
