### ISSUE TITLE
Can no longer use `dispatchEvent()` with Angular 4?

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#1881]
I'm not sure if this is a seed "bug", or a SystemJS config issue, or something that changed in Angular 4, but trying to use `import { dispatchEvent } from '@angular/platform-browser/testing/src/browser_util'` now results in a runtime error saying `browser_util` can't be loaded and/or `dispatchEvent` doesn't exist.

I believe it has to exist because the [Angular unit tests use dispatchEvent()](https://github.com/angular/angular/blob/master/packages/forms/test/template_integration_spec.ts#L14), but the seed app just can't see it for some reason?

**Comment by brian428** [comment]
Actually this may not matter. I thought there was something "magic" about their `dispatchEvent()` method, but looking at the source, it seems that I'm able to just do something like `myElement.dispatchEvent( new Event( "input" ) ) ;` to get the same result.

So, if you think it's worth looking into this further, feel free. Otherwise, feel free to close it. :-)

**Comment by Jmadih** [comment]
@brian428  Thank you for the solution.

**Comment by Sean-Brown** [comment]
Question: where do you import 'Event' from?

**Comment by brian428** [comment]
It's a built-in ES6 type, so it doesn't need to be imported.

**Comment by ohabash** [comment]
do i need to import something?

**Comment by RayKimEX** [comment]
isn't there security issue dispatchEvent() like Changing DOM using elementRef?
