### ISSUE TITLE
Lazy branch does not compile

### ISSUE THREAD

**Issue by PRR24** [mgechev/angular-seed#1882]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Lazy branch does not compile.
npm run build.prod.exp results
Error: Error at .../angular-seed-lazy/node_modules/@types/jasmine/index.d.ts:40:38: A parameter initializer is only allowed in a function or constructor implementation.

**Expected behavior**
Should run :)

**Minimal reproduction of the problem with instructions**
Check out the branch,
npm install
npm run build.prod.exp

**What is the motivation / use case for changing the behavior?**
Having lazy loading AOT multimodule prod build.

**Please tell us about your environment:**
N/A

* **Angular Seed Version:** `7d2175b`

* **Node:** `node --version` = 6.10

**Comment by mgechev** [comment]
I will remove the lazy branch. It's not maintained.
