### ISSUE TITLE
Confusing Proxy Wiki Instructions

### ISSUE THREAD

**Issue by gforceg** [mgechev/angular-seed#1883]
**I'm submitting a ...**  (check one with "x")
```
[X?] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
The [wiki instructions](https://github.com/mgechev/angular-seed/wiki/Add-a-Proxy-to-browsersync) for adding a proxy are not logically consistent and I am unable to successfully setup my proxy.

The document instructs me to install `proxy-middleware` and to require it as a variable called proxy in project.config.ts like this:

```
const proxy = require('proxy-middleware');
```

But the proxy variable is never used. Instead there is an inline require method to load a similarly named module called `http-proxy-middleware`:
```
require('http-proxy-middleware')({ ws: false, target: 'http://localhost:3003' })
```

My intent is to route all my api calls (http://localhost:5555/api/**/*) to port 5000. But I believe the suggested instructions would route all http requests on port 5555 to port 3003, not just the api calls.

I tried doing something like this (among many other variations):
```
    this.PROXY_MIDDLEWARE = [
      require('http-proxy-middleware')(
        {
          ws: false,
          target: 'host:localhost:5000',
          router: {
            '/api' : 'http://localhost:5000',
            '/**/*': 'http://localhost:5555'         
        }
      })
    ];
```

Using the above configuration I can touch my endpoint through port 5555 (yay!) but if I try to load the angular app (http://localhost:5555/) I get a 404.

**Expected behavior**

I would expect all routes except '/api/' to load on port 5555 without issue.

**Minimal reproduction of the problem with instructions**
try to follow the wiki, which states: 

> If you have an API Server running on a different port, you may want to proxy requests from you application to your api.

but it seems incomplete and inaccurate.

**What is the motivation / use case for changing the behavior?**

I would like to know how to properly **setup a proxy middleware only for api end points** as described in the wiki.

I am willing to update the wiki myself if I can successfully get this working.

**Please tell us about your environment:**
I'm running windows 7 (yuck)
The endpoint is running over a dotnet core webapi.

* **Angular Seed Version:** `e5aace`

* **Node:** `node --version` = 6.9.5

**Comment by gforceg** [comment]
I tried it on a different machine:
Fedora 24
node version 6.10.1

using the following middleware configuration:
```
    /* Add proxy middleware */
    this.PROXY_MIDDLEWARE = [
      require('http-proxy-middleware')(
        {
          ws: false,
          target: 'http://localhost:5000',
          router: {
            '/api': 'http://localhost:5000',
            '/': 'http://localhost:5555'
          }
        })
    ];
```

**Comment by gforceg** [comment]
The suggested middleware configuration from the wiki is:
```
 /* Add proxy middlewar */
 this.PROXY_MIDDLEWARE = [
   require('http-proxy-middleware')({ ws: false, target: 'http://localhost:3003' })
 ];
```
When I use that one (substitutiong the port my api lives on which is 5000) then the API still works on 5555 like it should. But when I try to access my application on port 5555 I get error 404.

**Comment by gforceg** [comment]
Found the solution on [http-proxy-middleware examples page](https://github.com/chimurai/http-proxy-middleware/blob/master/examples/browser-sync/index.js)
change `require('http-proxy-middleware')({ ws: false, target: 'http://localhost:3003' })`
to `require('http-proxy-middleware')('/api': { ws: false, target: 'http://localhost:3003' })`

**Comment by mgechev** [comment]
@gforceg thanks for helping out with this!

**Comment by gforceg** [comment]
thanks for making angular-seed! :+1: 
updated wiki!
https://github.com/mgechev/angular-seed/wiki/Add-a-Proxy-to-browsersync

**Comment by gforceg** [comment]
correction!!!
`require('http-proxy-middleware')('/api': { ws: false, target: 'http://localhost:3003' })`
should be:
`require('http-proxy-middleware')('/api', { ws: false, target: 'http://localhost:3003' })`

(there is a comma after '/api' rather than a colon.
