### ISSUE TITLE
How to use environment variables in controller

### ISSUE THREAD

**Issue by mujtaba-ahmad** [mgechev/angular-seed#1884]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

I am new here an i want to use environment variable in controller, how to use then, cannot find anything in documentation.

Help needed.

**Comment by patrickmichalina** [comment]
An example of its use can be seen in the top level app component. It reads a value to the console.

**Comment by TheDonDope** [comment]
Like @patrickmichalina said, have a look at https://github.com/mgechev/angular-seed/blob/master/src/client/app/app.component.ts#L16
