### ISSUE TITLE
how to  add Timestamp for the js  file ???

### ISSUE THREAD

**Issue by Christian-Yang** [mgechev/angular-seed#1887]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

![problem](https://cloud.githubusercontent.com/assets/25613332/24574242/cbfde594-16c1-11e7-8c9c-05ab884dcd6a.jpg)

angular seed can now add timestamps or random numbers to app.js and shim.js and css files 。<br/>
In the above figure we can see.<br/>
However, the module we added can not be added to the timestamp or random number.<br/>
for example  there is  a login.module.js，there is no  timestamp or random number on it.<br/>
So, when we package and make the release, and update, it will find app.js updated, because it has a timestamp or random number, but login.module.js has not been updated, is still an old page.<br/>Is there any way to write our own login.module.js add timestamp or random number? Through configuration angular seed?<br/>

wish your help!  thanks very much!

**Expected behavior**

there is no timestamp or random number on the js file which we added .
**Minimal reproduction of the problem with instructions**

nothing
**What is the motivation / use case for changing the behavior?**

nothing
**Please tell us about your environment:**

$:uname -v<br/>
~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015<br/>
IDE: webstorm<br/>
package manager：npm<br/>
HTTP server:nginx<br/>
* **Angular Seed Version:** `aaaaf75`

 "name": "angular-seed",
  "version": "0.0.0",
* **Node:** `node --version` = v6.9.0

**Comment by mgechev** [comment]
Everything which is injected from the seed has an appended query parameter. I'm not sure how you're loading the `login.module.js` (looks like you're loading it lazily) but this seems out of the scope of the seed.

What you can do is just append `+ "?<%= HASH %>"` to the end of the module URI where `HASH` is some random hash used for preventing the browser from caching.

**Comment by Christian-Yang** [comment]
@mgechev    thanks very much  ! I will try it  !!!
