### ISSUE TITLE
AOT build of ng2-tag-input library fails, but works with Webpack and Angular cli

### ISSUE THREAD

**Issue by JunusErgin** [mgechev/angular-seed#1895]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Hi all,
i tried to include the library [ng2-tag-input](https://github.com/Gbuomprisco/ng2-tag-input). Unfortunately, the AOT build fails. 

```
[11:24:46] Error on fetch for ng2-tag-input/dist/modules/components/icon.js at file:///C:/Dev/my_project_angular2/node_modules/ng2-tag-input/dist/modules/components/icon.js
        Loading ng2-tag-input/dist/modules/ng2-tag-input.module.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        Error: ENOENT: no such file or directory, open 'C:\Dev\my_project_angular2\node_modules\ng2-tag-input\dist\modules\components\icon.js'
    at Error (native)
[11:24:46] 'build.prod.aot' errored after 1.43 min
[11:24:46] Error in plugin 'run-sequence(build.bundles.app.aot)'
Message:
    Error on fetch for ng2-tag-input/dist/modules/components/icon.js at file:///C:/Dev/my_project_angular2/node_modules/ng2-tag-input/dist/modules/components/icon.js
        Loading ng2-tag-input/dist/modules/ng2-tag-input.module.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        ENOENT: no such file or directory, open 'C:\Dev\my_project_angular2\node_modules\ng2-tag-input\dist\modules\components\icon.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\Dev\my_project_angular2\node_modules\ng2-tag-input\dist\modules\components\icon.js'
Stack:
Error on fetch for ng2-tag-input/dist/modules/components/icon.js at file:///C:/Dev/my_project_angular2/node_modules/ng2-tag-input/dist/modules/components/icon.js
        Loading ng2-tag-input/dist/modules/ng2-tag-input.module.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        Error: ENOENT: no such file or directory, open 'C:\Dev\my_project_angular2\node_modules\ng2-tag-input\dist\modules\components\icon.js'
    at Error (native)
```
Did anyone figure out a solution so far? 
@Gbuomprisco suggested to ask here since **Webpack and Angular cli works.**

He suggested in his repo to use the following SystemJS config:

```
// packages object
{
    'ng2-tag-input': {
        main: 'dist/ng2-tag-input.bundle.js',
        format: 'cjs',
    },
    'ng2-material-dropdown': {
        defaultExtension: 'js',
        main: 'dist/ng2-dropdown.bundle.js',
        format: 'cjs',
    },
    'ng2-tag-input/modules/components/tag-input.template.html': {
        defaultJSExtension: false
    }
    // rest of the configuration
};
```

Expected behavior**

`gulp build.prod.aot` builds without any errors.

**Minimal reproduction of the problem with instructions**

`npm install ng2-tag-input --save`

My SystemJS config in the app.config.ts looks like the following:
```
    // NG2-TAG-INPUT
    additionalPackages.push({
      name: 'ng2-tag-input',
      path: `${this.NPM_BASE}ng2-tag-input/dist/ng2-tag-input.bundle.js`,
      packageMeta: {
        main: 'dist/ng2-tag-input.bundle.js',
        format: 'cjs'
      }
    });

    // NG2-MATERIAL-DROPDOWN
    additionalPackages.push({
      name: 'ng2-material-dropdown',
      path: `${this.NPM_BASE}ng2-material-dropdown/dist/ng2-dropdown.bundle.js`,
      packageMeta: {
        defaultExtension: 'js',
        main: 'dist/ng2-material.bundle.js',
        format: 'cjs'
      }
    });
```

I also tried to add the template as he suggested, even if it seems very strange to link a HTML file in the SystemJS:

```
    additionalPackages.push({
      name: 'ng2-tag-input/modules/components/tag-input.template.html',
      packageMeta: {
        defaultJSExtension: false
      }
    });
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10.0.15063, Webstorm x64 (latest version)
Also tested with Ubuntu Xenial and Webstorm 64 bit

* **Angular Seed Version:** `23b0515`

* **Node:** `node --version` = `v6.9.1`

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by ZuSe** [comment]
@mgechev  There is nothing in the project wiki that helps with that problem. It's more about using barrel imports with SystemJS. Would open again the discussion how to improve the usage of systemjs within the seed.

**Comment by mgechev** [comment]
Updated `app.component.ts` with:

```ts
import { Component } from '@angular/core';
import { Config } from './shared/config/env.config';
import './operators';

import * as foo from 'ng2-tag-input';

console.log(foo);

/**
 * This class represents the main application component.
 */
@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
})
export class AppComponent {
  constructor() {
    console.log('Environment config', Config);
  }
}
```

and run `npm run build.prod.rollup.aot`. Everything worked out-of-the-box. You can try using Rollup as bundler in this case.

**Comment by ZuSe** [comment]
Why would you import in app.component.ts? 
Don't we need to import in the module for selector resolution?

It still fails for me, also with rollup build resulting in:
app.js?1493025985090:15 Uncaught TypeError: Cannot read property 'TagInputComponent' of undefined
    at app.js?1493025985090:15
    at t (app.js?1493025985090:1)
    at app.js?1493025985090:14
    at app.js?1493025985090:17

but I have imported the module in app.module.ts as i don't see how it should work in component.
You can check it here: https://github.com/ZuSe/angular2-seed

However, still the question is how we can deal with nested barrel imports in the seed project :(

**Comment by mgechev** [comment]
The import above only aims to verify if the application can be successfully bundled (i.e. the path to `ng2-tag-input` is successfully resolved). I the logs I'm getting an object with the exported properties from the package.

**Comment by anandgupta193** [comment]
I am facing build failure when trying with: ng build --aot

The error which I am getting is as follows:
`ERROR in Error: Template parse errors:
Can't bind to 'readOnly' since it isn't a known property of 'tag'. ("eyDown)="handleKeydown($event, item)"
             [attr.tabindex]="readonly ? -1 : 0"
             [ERROR ->][readonly]="readonly"
             [template]="!!hasCustomTemplate() ? templates.first : undefined"
 "): TagInputComponent@14:13
Can't bind to 'template' since it isn't a known property of 'tag'. ("
             [attr.tabindex]="readonly ? -1 : 0"
             [readonly]="readonly"
             [ERROR ->][template]="!!hasCustomTemplate() ? templates.first : undefined"
             [model]="item">
       "): TagInputComponent@15:13
Can't bind to 'model' since it isn't a known property of 'tag'. ("eadonly"
             [template]="!!hasCustomTemplate() ? templates.first : undefined"
             [ERROR ->][model]="item">
        </tag>

"): TagInputComponent@16:13
'tag' is not a known element:
1. If 'tag' is an Angular component, then verify that it is part of this module.
2. If 'tag' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    
    <div class="ng2-tags-container">
        [ERROR ->]<tag *ngFor="let item of items; trackBy: value"
             (onSelect)="selectItem(item)"
          "): TagInputComponent@9:8
    at SyntaxError.BaseError [as constructor] (D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:1597:31)
    at new SyntaxError (D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:1795:20)
    at TemplateParser.parse (D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:11435:23)
    at AotCompiler._compileComponent (D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:24806:72)
    at D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:24708:117
    at Array.forEach (native)
    at AotCompiler._compileSrcFile (D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:24692:24)
    at D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:24667:95
    at Array.map (native)
    at D:\Grace\GRACE\webapp\node_modules\@angular\compiler\bundles\compiler.umd.js:24667:60
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)`

Please help me how to resolve this.
