### ISSUE TITLE
Upgrade to TS 2.2.x, remove typeless build, add cache usage

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#1898]
Minko, I know you're at ng-conf, so this is probably for when you get back. It looks like the TS folks made a breaking change in 2.2.x that affects the typeless build option I added a long time back. 

Basically, when using `isolatedModules`, the TS compiler emits `Object.defineProperty(exports, "__esModule", { value: true });` at the top of each file. This will cause runtime errors because `exports` doesn't exist. This **seems** like a TS bug, but the TS folks seem to be thinking this is intended behavior (https://github.com/Microsoft/TypeScript/issues/14351).

So, in order to update to TS 2.2.x, I think we'll have to remove/deprecate the typeless compile option. I've got TS 2.2.2 working in my project by turning off the typeless compile. I also added in use of gulp-cached to the `build.js.dev` and `build.js.test` tasks. We had issues with this before, where the cached build file sets were missing all the unchanged TS files, which caused compile errors. It seems to work OK now and reduces subsequent compile times by about 50-75%. Not as fast as using `isolatedModules` but still better than recompiling everything.

I can create a pull request for this if you like, but wanted to make sure it sounded OK to you first.

**Comment by mgechev** [comment]
Hey @brian428, I run the seed with the latest version of TypeScript and wasn't able to reproduce the issue.

**Comment by brian428** [comment]
Just checking: did you try it with the typeless compile counter set to something other than 0? Try that, start it up, then make a change and reload to confirm that the isolatedModules export doesn't throw errors.

**Comment by mgechev** [comment]
I enabled `isolatedModules` in both branches of the conditional statement in `build.js.dev` and didn't get any issues.

Do you think this can be caused by environment specific configuration?

**Comment by brian428** [comment]
I'll try it with a new seed just to confirm whether it's something in my environment and report back.

**Comment by carmelone** [comment]
Here the same problem.

`Object.defineProperty(exports, "__esModule", { value: true })` when `isolatedModules: true;` after a change in ts file (typeless compiling)...

How to fix?

Can you @brian428 post your modified code in `build.js.dev.ts`?

**Comment by brian428** [comment]
Sure, I just changed the if block on line 38 to omit the use of isolatedModules:

```
if (typedBuildCounter < Config.TYPED_COMPILE_INTERVAL) {
  isFullCompile = false;
  tsProject = makeTsProject();
  projectFiles = projectFiles.pipe(plugins.cached('build.js.dev'));
  util.log('Performing cached TypeScript compile.');
} else {
  tsProject = makeTsProject();
  projectFiles = merge(typings, projectFiles).pipe(plugins.cached('build.js.dev'));
}
```

Also did this in `build.js.test.ts`. It's not really the "correct" solution, but it was enough of a band aid to get it working again while I tried to figure out what was going on.

I meant to circle back around to try this out again, but got delayed while JetBrains updated IDEA to support the new TS language service. I'll try to re-test `isolatedModules` when I have some time.

One odd thing is that I'm pretty sure I pulled down a fresh seed clone and tested things, and it all seemed to work correctly (using `isolatedModules`). So at the time, it seemed like this was specific to my setup rather than something in the seed.

**Comment by carmelone** [comment]
Thanks for the code.

If you download the latest release of the seed (4.0.0) it works good with `"typescript": "^2.1.5"` which is 2.3.3 now...

Some added `@types` maybe? What do you think?

I also have the problem with `typescript 2.1.5`.

**Comment by carmelone** [comment]
Dear @mgechev, can you reopen please?

**Comment by brian428** [comment]
Well, if it works fine with a clean seed clone, it seems to be something project specific rather than an issue with the seed. I'm not sure how Minko can help when we really have no idea what the problem is.

**Comment by carmelone** [comment]
Do you have public code to reproduce bug?

Maybe on github itself?

**Comment by brian428** [comment]
I don't. The issue manifests in my primary client project, which is rather large and customized. So trying to track down the cause would probably be fairly time-intensive (which is why I haven't had time to try yet).
