### ISSUE TITLE
Uncaught Module f4 not present in production mode

### ISSUE THREAD

**Issue by LeBaThuan** [mgechev/angular-seed#1899]
Please help. I got this error when I build production mode. Everything works fine when running dev mode.
 
![errorprod](https://cloud.githubusercontent.com/assets/6970185/24893254/b3e2e0fc-1eac-11e7-9c4b-38bee9b5010e.png)

I tried this [sluttion](https://github.com/mgechev/angular-seed/issues/1819) but it's still not working.

**Please tell us about your environment:**

OS ubuntu 16.04 
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.5.0

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
