### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by idamaeungab** [mgechev/angular-seed#1903]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

it looks like this 
(index):60 (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/core/@angular.js
	Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/core/@angular.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1492128391288:1199:29) [<root>]
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1492128391288:165:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1492128391288:460:38) [<root>]
	Error loading http://localhost:5555/node_modules/@angular/core/@angular.js as "@angular/core/@angular" from http://localhost:5555/app/courses.component.js

**Expected behavior**

I have imported components from the node_modules that i need for making component but it displays an error after the browsersync that it cannot find some .js files.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

HTTP server

* **Angular Seed Version:** `a264079`

* **Node:** `node --version` =v6.10.2

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
