### ISSUE TITLE
Not able to import directives from common packgage '@angular/common';

### ISSUE THREAD

**Issue by ionicappworld** [mgechev/angular-seed#1904]
Not able to import directives from common packgage

import {FORM_DIRECTIVES} from '@angular/common';
we are getting exception while importing 'PAGINATION_DIRECTIVES', 'CORE_DIRECTIVES' the common module

error TS2305: Module '"@angular/common"' has no exported member 'FORM_DIRECTIVES'

**Comment by mgechev** [comment]
Yes, `FORM_DIRECTIVES` is not in `@angular/common`.

Not sure if you're using the seed or that's just an error you get in your custom build/custom app?

**Comment by ionicappworld** [comment]
i am using the angular seed structure. And module  @angular/common also available in node_modules folder. But while importing directives, i am getting the above exception.
