### ISSUE TITLE
node_modules/.bin/ng version && ng init --name <welcome>

### ISSUE THREAD

**Issue by Basuchi** [mgechev/angular-seed#1906]
![image](https://cloud.githubusercontent.com/assets/20046781/25166256/12ad49be-24f8-11e7-8ed1-b5081c38f8c1.png)

I am trying to create angular project in Eclipse Oxygen IDE
Kindly help me

**Comment by TheDonDope** [comment]
Wrong GitHub Repo, you should take a look at https://github.com/angular/angular-cli :)
