### ISSUE TITLE
multiple extensions at end of Url .ts.js 

### ISSUE THREAD

**Issue by hardy91** [mgechev/angular-seed#1908]
**I'm submitting a bug report .**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**
 file should load properly. 

**Minimal reproduction of the problem with instructions**

i followed all the  steps in this link  before heading customize 
https://www.npmjs.com/package/angular-2-dropdown-multiselect

this if system-config.ts file 
declare var System: SystemJSLoader.System;

System.config(JSON.parse('<%= SYSTEM_CONFIG_DEV %>'));

**What is the motivation / use case for changing the behavior?**
I was trying to implement multiselect dropdown in an angular2 app
and getting following error 

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts.js
	patchProperty/desc.set/wrapFn@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:636:26
	ZoneDelegate.prototype.invokeTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:225:23
	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:125:28
	ZoneTask/this.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:293:28
	EventListener.handleEvent*scheduleEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:709:16
	ZoneDelegate.prototype.scheduleTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:205:21
	Zone.prototype.scheduleEventTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:145:20
	zoneAwareAddListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:762:9
	addEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181 line 863 > Function:1:43
	patchProperty/desc.set@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:641:13
	ZoneAwarePromise@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:467:29
	ZoneDelegate.prototype.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:192:19
	Zone.prototype.run@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:85:24
	scheduleResolveOrReject/<@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:451:52
	ZoneDelegate.prototype.invokeTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:225:23
	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:125:28
	drainMicroTaskQueue@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:357:25
	EventListener.handleEvent*scheduleEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:709:16
	ZoneDelegate.prototype.scheduleTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:205:21
	Zone.prototype.scheduleEventTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:145:20
	zoneAwareAddListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:762:9
	addEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181 line 863 > Function:1:43
	patchProperty/desc.set@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:641:13
	ZoneAwarePromise@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:467:29
	ZoneDelegate.prototype.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:192:19
	Zone.prototype.run@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:85:24
	scheduleResolveOrReject/<@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:451:52
	ZoneDelegate.prototype.invokeTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:225:23
	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:125:28
	drainMicroTaskQueue@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:357:25
	EventListener.handleEvent*scheduleEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:709:16
	ZoneDelegate.prototype.scheduleTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:205:21
	Zone.prototype.scheduleEventTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:145:20
	zoneAwareAddListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:762:9
	addEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181 line 863 > Function:1:43
	patchProperty/desc.set@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:641:13
	ZoneAwarePromise@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:467:29
	ZoneDelegate.prototype.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:192:19
	Zone.prototype.run@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:85:24
	scheduleResolveOrReject/<@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:451:52
	ZoneDelegate.prototype.invokeTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:225:23
	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:125:28
	drainMicroTaskQueue@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:357:25
	EventListener.handleEvent*scheduleEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:709:16
	ZoneDelegate.prototype.scheduleTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:205:21
	Zone.prototype.scheduleEventTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:145:20
	zoneAwareAddListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:762:9
	addEventListener@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181 line 863 > Function:1:43
	patchProperty/desc.set@http://localhost:5555/node_modules/zone.js/dist/zone.js?1492943643181:641:13
	

**Please tell us about your environment:**
 windows Os , visual studio code , npm  package manager, using node server , ... 

* **Angular Seed Version:** `
dont know, using a app which already had seed 

* **Node:** `node --version` =7.2.1

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
