### ISSUE TITLE
Cannot build a production with npm after added new package in config

### ISSUE THREAD

**Issue by sayeko** [mgechev/angular-seed#1910]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter]
```

**Current behavior**
I've added a new package slim loader added new package and added it to 
SYSTEM_CONFIG_DEV

```
'ng2-slim-loading-bar': 'node_modules/ng2-slim-loading-bar/bundles/index.umd.js',

 'ng2-slim-loading-bar': {
        main: 'bundles/index.umd.js',
        defaultExtension: 'js'
    },
```

When I run npm run build.prod I get this error message
Error on fetch for ng2-slim-loading-bar.js at file://node_modules/ng2-slim-loading-bar.js
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open '\node_modules\ng2-slim-loading-bar.js'

**Please tell us about your environment:**

* **Angular Seed Version:** `0.0.0`

* **Node:** `node --version` = 7+

**Comment by mgechev** [comment]
Did you try running `npm run build.prod.rollup.aot`?

If you hve troubles configuring SystemJS, rollup may work for you.

**Comment by sayeko** [comment]
after this command I encounter this

ERROR Error: Uncaught (in promise): TypeError: System.import is not a function
TypeError: System.import is not a function

**Comment by mgechev** [comment]
In case you have problems configuring SystemJS I'd recommend you to switch to the CLI. Although Angular seed provides great flexibility and allows you to squeeze every byte out of your bundle, Angular CLI provides a good way to get started without understanding the required tooling in depth.
