### ISSUE TITLE
How to make rollup not convert "this" to undefined. 

### ISSUE THREAD

**Issue by ganeshsarathi** [mgechev/angular-seed#1914]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Hi, while running the the app in dev mode, "ng2-validation" equalTo is working. But in prod mode, with rollup, its not working.

Throwing Error: Uncaught (in promise): TypeError: Cannot read property 'equalTo' of undefined.

I'm assuming  rollup makes "this" keyword as "undefined", so "ng2-validation" euqalTo is not working.  

I do understand this is not an issue with seed project, but could be mostly with ng2-validation  package.  I'm looking for some help to solve this. 

Component code.
`<div class="col-md-9"> <input type="number" class="form-control" name="mobilePhone" #mobilePhone="ngModel" required [ngModel]="model.mobilePhone" id="mobilePhone"> </div>`

`<div class="col-md-9"> <input type="number" class="form-control" ngModel name="mobilePhoneVerify" #mobilePhoneVerify="ngModel" [equalTo]="mobilePhone" required> <p class="form-control-static text-danger" *ngIf="mobilePhoneVerify.errors?.equalTo">Please enter same cell number here.</p></div>
`

Can you please help to solve this. Thanks.

**Expected behavior**

I'm assuming If roleup can avoid converting "this"  to "undefined" for few cases, then it would make that validation stuff to work. 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

MAC, VE, NPM,  wildfly. 
* **Angular Seed Version:** `aaaaf75`

laste one with angular 4. 
* **Node:** `node --version` =

**Comment by mgechev** [comment]
This is not an issue in the project.

In case you have problems configuring rollup I'd recommend you to either review their documentation or switch to the CLI. Although Angular seed provides great flexibility and allows you to squeeze every byte out of your bundle, Angular CLI provides a good way to get started without understanding the required tooling in depth.

**Comment by ganeshsarathi** [comment]
thanks a lot for you quick help. May be for now I shall try to have the prod build without rollup.  I do use your seed project since first day of my angular learning. Its very much helpful. The project will go live within next few weeks.   Thanks again.
