### ISSUE TITLE
Convert to Named Export to prevent error in build

### ISSUE THREAD

**Issue by oxycoder** [mgechev/angular-seed#1917]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Tree-shaking with Rollup build fail with this config
```
const config: ProjectConfig = new ProjectConfig();
export default config;
```
Error:
```
"TypeError: Cannot read property 'kind' of undefined"
```

**Expected behavior**
None

**What is the motivation / use case for changing the behavior?**
According to https://github.com/angular/angular/issues/11402 , we should prevent use default export
change tools/config.ts to
```
const Config: ProjectConfig = new ProjectConfig();
export { Config };
```
It affected many file in seed task, change from:
```
import  Config from '../../config';
```
To
```
import { Config } from '../../config';
```
After do refactor to named export, build success.

**Please tell us about your environment:**
MacOS 10.12.4
Visual studio code

* **Angular Seed Version:** `0bac91b`

* **Node:** `node --version` = v7.6.0
npm version 4.1.2

**Comment by mgechev** [comment]
Thanks for reporting the issue. I haven't experienced the problem that you mentioned and wasn't able to reproduce it. So I'd suggest to close the issue.

On the other hand, using named exports makes the code easier for tree-shaking and static analysis in general. In case you have some time, I'd appreciate a PR updating the default exports to named ones.

Also, lets keep an eye on the issue in case anyone else experience it.
