### ISSUE TITLE
Upgrade from Angular 2 to Angular 4 based on the seed project.

### ISSUE THREAD

**Issue by bwwilliam** [mgechev/angular-seed#1919]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I would like to upgrade my project from angular 2 to angular 4. 
Can you please let me know how I can achieve this? 
I understand the following code meant to do the upgrade.  https://github.com/mgechev/angular-seed#how-to-update
But this is the message I received. 
**$ git remote add upstream https://github.com/mgechev/angular-seed 
fatal: remote upstream already exists.**

I have checked your commit 95e87cd4672518c6d167c0e235d6f844805884bb and 819e3807b70d0a7e16d3bd907a96bec3ab78df74, but it did not work for me. 

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by Karasuni** [comment]
Read the error message again.

**Comment by Flood** [comment]
Just type: "git pull upstream master" after that message. You will probably get some conflicts that you have to solve.

**Comment by bwwilliam** [comment]
This is what I got after $ git pull upstream master

From https://github.com/mgechev/angular-seed
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories

**Comment by bwwilliam** [comment]
Thanks for everyone's input. 
The problem was solved by using
`git pull upstream master --allow-unrelated-histories
`
