### ISSUE TITLE
Cannot import "deck.gl"

### ISSUE THREAD

**Issue by skokenes** [mgechev/angular-seed#1923]
I am trying to import deck.gl like so:
`import {LayerManager, WebMercatorViewport, ScatterplotLayer} from "deck.gl";`

It looks like it is trying to find `deck.gl.js`, instead of `deck.gl`?
I am getting the following error:
`GET http://localhost:5555/node_modules/deck.gl.js 404 (Not Found)`

How do I load a node module that has a period in its name?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
