### ISSUE TITLE
Is there a plan to have angular cli included ? 

### ISSUE THREAD

**Issue by UCJava** [mgechev/angular-seed#1925]
I am fairly new to this but would be nice to use angular cli to build and run , it might be a simple thing, any help ? 

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[*] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
https://github.com/mgechev/angular-seed/issues?q=is%3Aissue+angular-cli+is%3Aclosed
