### ISSUE TITLE
npm run webdriver-update not working on Windows

### ISSUE THREAD

**Issue by qiuzhong** [mgechev/angular-seed#1926]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Failed to run <code>npm run webdriver</code> on Windows.

**Expected behavior**
Run <code>npm run webdriver</code> without any errors and webdriver packages are downloaded.

**Minimal reproduction of the problem with instructions**
1. <code>git clone https://github.com/mgechev/angular-seed.git</code>
2. <code>cd angular-seed && npm install</code>
3. <code>npm install webdriver-manager && npm run webdriver-update</code>
```
C:\workspace\work\angular-seed [master ≡]> npm run webdriver-update

> angular-seed@1.0.0 webdriver-update C:\workspace\work\angular-seed
> ./node_modules/protractor/bin/webdriver-manager update

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "webdriver-update"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.0.0 webdriver-update: `./node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 webdriver-update script './node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\work\angular-seed\npm-debug.log
```

**What is the motivation / use case for changing the behavior?**
During the <code>npm install</code> procedure, the webdriver fails to download and I have to run 
<code>npm run webdriver-update</code> to update webdriver.

**Please tell us about your environment:**
Windows 10
Git Shell ( from GitHub for Windows)

* **Angular Seed Version:** `6e7b991`

* **Node:** `node --version` =v6.10.3

**Comment by mgechev** [comment]
Would you remove the `./` from the beginning if the npm script `webdriver-update` and tell me if that helps?

**Comment by qiuzhong** [comment]
Removing the <code>./</code> doesn't help.
```
C:\workspace\work\angular-seed [master ≡ +0 ~1 -0 !]> npm run webdriver-update

> angular-seed@1.0.0 webdriver-update C:\workspace\work\angular-seed
> node_modules/protractor/bin/webdriver-manager update

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

npm script <code>webdriver-update</code> is defined as:
```
"webdriver-update": "./node_modules/protractor/bin/webdriver-manager update"
```
But <code> ./node_modules/protractor/bin/webdriver-manager</code> is not considered as an executable on Windows and there is no batch file with the same name there.

**Comment by mgechev** [comment]
Probably this is caused by the latest update of the dependencies that I did.

Would you try to revert back to `ece3e66fedcfd8309205af643c2a0670565c6f77` and tell me if everything works as expected?

**Comment by qiuzhong** [comment]
Cloned and reset the repository to <code>ece3e66fedcfd8309205af643c2a0670565c6f77</code>.

It still doesn't work on Windows.

**Comment by mgechev** [comment]
Fix in the latest seed. Thanks for reporting the issue.

**Comment by qiuzhong** [comment]
I just tried with the update: it works.
