### ISSUE TITLE
Global error logging options

### ISSUE THREAD

**Issue by salemdar** [mgechev/angular-seed#1929]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
App just prints the errors to the console.

**Expected behavior**
App gives you ability to log the errors on backend or do whatever you want.

**What is the motivation / use case for changing the behavior?**
It would be really nice to be able to log the error on backend, so the dev could analyze them and fix the bugs. This feature could be handled in [such way](http://stackoverflow.com/a/43859724/1784230) with (imho) minimal effort.

* **Angular Seed Version:** `aaaaf75`

**Comment by mgechev** [comment]
This is too opinionated. Some developers will have a custom login service, others will prefer to use [Sentry](https://sentry.io/welcome/).

If we go with custom error reporting, we should also provide a server for collecting the logs. This is out of the scope of an Angular starter project.
