### ISSUE TITLE
Build problem with SASS compilation

### ISSUE THREAD

**Issue by pcorderoe** [mgechev/angular-seed#1930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**

When i compiled and start app (npm start) it shows an error on browser (404) in some css files.

**Expected behavior**

it must compile without update the file.

**Minimal reproduction of the problem with instructions**

When i compiled and start app (npm start) it shows an error on browser like 

`zone.js:567 Unhandled Promise rejection: Failed to load http://localhost:5555/app/modules/users/login/login.component.css ;`

to make work this, i have to modify related file (/modules/users/login/login.component.scss) and save to resolve.

I put this.ENABLE_SCSS = 1; on project.config.ts file

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, VSC

* **Angular Seed Version:** `aaaaf75`

From master, commit 0bac91b6473118d51ac5c28befc221ebeb162f72
* **Node:** `node --version` = 6.9.3

**Comment by mgechev** [comment]
So the issue is that the Sass files don't get compiled, or styleUrls are pointing the wrong path?

**Comment by pcorderoe** [comment]
Sass files are not compiled and show a 404 error. I check again and found a reason: i have a scss on another section with an error. I fix that and works again. :) thanks for your time

**Comment by mgechev** [comment]
Sure!
