### ISSUE TITLE
Links to NativeScript and Electron setups are broken

### ISSUE THREAD

**Issue by Hirse** [mgechev/angular-seed#1935]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

The links to *Setup instructions here* for Electron and NativeScript in the [Advanced Seed Option](https://github.com/mgechev/angular-seed#advanced-seed-option) section of the README are broken.
They link to a missing section in the same README.

**Expected behavior**

They should link to an existing target. Presumably in the Advanced Seed project.

**Minimal reproduction of the problem with instructions**

Click on the link in the README or directly here:
https://github.com/mgechev/angular-seed/blob/master/README.md#electron-app

**What is the motivation / use case for changing the behavior?**

I was reading the section, clicked the link to get more information, but was disappointed.

* **Angular Seed Version:** `6918a16`

**Comment by mgechev** [comment]
Thanks for pointing this out! Would you open a PR with the suggested change?

**Comment by Hirse** [comment]
I would love to, but looking at the [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced) README, their links are broken too.

@mgechev, @NathanWalker Would the following links make sense?
Electron setup instructions -> https://github.com/NathanWalker/angular-seed-advanced#desktop-app
NativeScript setup instructions -> https://github.com/NathanWalker/angular-seed-advanced#mobile-app
