### ISSUE TITLE
Getting module not resolved on javascript files

### ISSUE THREAD

**Issue by ankitkapoor2493** [mgechev/angular-seed#1936]
In my project, I'm using javascript files of type
export var a = 10;
having declaration file 
export var a;
It was working fine earlier but now with aot.rollup build, this is not getting resolved as I'm getting error 'module_path' is not resolved

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
