### ISSUE TITLE
Message export failing

### ISSUE THREAD

**Issue by donvaughn** [mgechev/angular-seed#1937]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Script `npm run i18n` fails to produce messages file, displaying the following error:

```zsh
 TypeError: Cannot read property 'toLowerCase' of null
    at Extractor.serialize (/Users/donvaughn/Developer/Projects/DonVaughn/forks/angular-seed-issue/node_modules/@angular/compiler-cli/src/extractor.js:45:32)
    at /Users/donvaughn/Developer/Projects/DonVaughn/forks/angular-seed-issue/node_modules/@angular/compiler-cli/src/extractor.js:32:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
Extraction failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 i18n: `ng-xi18n -p src/client/tsconfig.json && gulp clean.i18n`
npm ERR! Exit status 1
```

**Expected behavior**

Creation of `messages.xlf`

**Minimal reproduction of the problem with instructions**

This can be reproduced by

1. grabbing a fresh clone
1. implementing steps 1-3 in the [enabling i18n wiki page](https://github.com/mgechev/angular-seed/wiki/Enabling-Angular-i18n-native)
1. then running `npm run i18n` from step 4.  

or.. 

1. just clone [this fork](https://github.com/donvaughn/angular-seed/tree/i18n) ([see the changes](https://github.com/donvaughn/angular-seed/commit/76a28047987fe8ef77384ee71f078f6f73d43bbc)) and 
1. `npm run i18n`

**What is the motivation / use case for changing the behavior?**

n/a

**Please tell us about your environment:**

Mac, zsh, installed via yarn

* **Angular Seed Version:** `e325ba8b567f4caa1f3c2b64d6020231595b3370`

* **Node:** `node --version` = 7.10.0, npm version = 4.6.1

**Comment by mgechev** [comment]
There's open PR regarding i18n. You can try it to see if it works for you.

**Comment by donvaughn** [comment]
I saw that PR but it's not directly related to this issue. It might, however, provide some refactoring or insight that will solve this issue. I'll take a closer look at the PR asap....

**Comment by donvaughn** [comment]
It seems that this is an angular issue [that they are aware of](https://github.com/angular/angular/issues/16235).  Adding the ` --i18nFormat=xlf` parameter to the i18n script solves this issue.  

I'll prepare a PR for that in a bit, but now that message extraction is working I run into [this issue: Cannot find module './app.module.ngfactory'. ](https://github.com/mgechev/angular-seed/issues/1582).  I don't think I changed any variables anywhere that would cause `main-prod.ts` to be used.  Any ideas on that?

**Comment by donvaughn** [comment]
I see that ocombe did mention in [that thread](https://github.com/angular/angular/issues/16235) that he'll work on it... I'm assuming this means that the default value (xlf) is just broken (and will be coming back).  So until they solve this it's not worth changing the seed.

**Comment by mgechev** [comment]
Ok, thanks for pointing this out! Let's close this issue then.

**Comment by donvaughn** [comment]
I've been looking into this issue and it seems that the [`ngfactory`](https://github.com/mgechev/angular-seed/issues/1582) error occurs because `ng-xi18n` looks into every file (because, of course, it knows nothing about the seed environment variables).  

I've come up with a solution using tsconfig inheritance that gets around this.  As to the [clean:i18n error](https://github.com/mgechev/angular-seed/issues/1729) (which then occurs after the tsconfig error occurs), is that task necessary?  Could it just be removed?

Even though it may be a bit too early, I'll submit a PR tomorrow and explain the details.
