### ISSUE TITLE
NPM INSTALL DOESN'T ADD TO NODE_MODULES

### ISSUE THREAD

**Issue by quesurifn** [mgechev/angular-seed#1938]
NPM INSTALL DOES NOT ADD TO NODE MODULES 

`npm install angular2-highcharts`

```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

`npm install angular2-highcharts`
**Expected behavior**
Add package to node_modules

**Minimal reproduction of the problem with instructions**
`npm install angular2-highcharts`
**Please tell us about your environment:**

OSX Sierra, VISUAL CODE STUDIO, NPM 4.5.0, 
* **Angular Seed Version:** `aaaaf75`

EDGE / f57d6c8

* **Node:** `node --version` = 7.7.4

**Comment by arun-awnics** [comment]
It is getting added. I see highcharts folder that is being created in node_modules folder after `npm install angular2-highcharts --save`
