### ISSUE TITLE
Command npm run webdriver-start is broken

### ISSUE THREAD

**Issue by ArnaudPel** [mgechev/angular-seed#1940]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
```

**Current behavior**
The command `npm run webdriver-start` outputs the following then exits:
`W/start - the out_dir path [...]/angular-seed/node_modules/webdriver-manager/selenium does not exist, run webdriver-manager update`
Even though this update has been run as per the readme (see reproduction path below).

**Expected behavior**
Being able to run e2e tests.

**Minimal reproduction of the problem with instructions**
Follow readme with a freshly cloned angular-seed (#023cdab):
```
npm install
npm install webdriver-manager
npm run webdriver-update
npm run webdriver-start
```

**Please tell us about your environment:**
Ubuntu 16.04
IDE: Pycharm
npm: 3.10.10

* **Angular Seed Version:** `023cdab`

* **Node:** `node --version` = v6.10.3

**My two cents**
I smell something in `package.json`, because a different webdriver is used across the two following (consecutive) commands:
```
    "webdriver-start": "webdriver-manager start",
    "webdriver-update": "./node_modules/protractor/bin/webdriver-manager update",
```
Since the change that introduced this difference is two months old already (#da0729c), I suspect seasoned angular-seed maintainers are not running their e2e tests as per the readme :)

In any case, using `./node_modules/protractor/bin/webdriver-manager` for both commands seems to work fine.

**Comment by mgechev** [comment]
Yes, the wrong `webdriver-manager` binary.
