### ISSUE TITLE
after update to angular 4 , npm run  build.lint   occur  error

### ISSUE THREAD

**Issue by Christian-Yang** [mgechev/angular-seed#1941]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

after update to angular 4 , npm run  build.lint   occur  error.
first  i  run the command  as  follow

npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save

then run npm run build.lint the error occur
![question](https://cloud.githubusercontent.com/assets/25613332/26302459/e592487e-3f16-11e7-9b2f-58d188631c71.jpg)

npm  start   can  run normal！

**Expected behavior**

the lint  check  can  run  
**Minimal reproduction of the problem with instructions**

nothing
**What is the motivation / use case for changing the behavior?**

nothing
**Please tell us about your environment:**

$:uname -v<br/>
~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015<br/>
IDE: webstorm<br/>
package manager：npm<br/>
HTTP server:nginx<br/>
* **Angular Seed Version:** `aaaaf75`

 "name": "angular-seed",
  "version": "0.0.0",
* **Node:** `node --version` = v6.9.0

thank  you  very  much !

**Comment by mgechev** [comment]
It looks like you're using old codelyzer version. Update to codelyzer@^3.0.0 and try again.

Also, updating only Angular versions may break other peerDependencies as well. I'd recommend you to update the entire Angular Seed by using the master branch.

Doesn't seem like an issue in the project but looks like unmatched peerDependencies instead.

**Comment by Christian-Yang** [comment]
@mgechev    thank you very much !

after  commands  as follow,npm run build.lint  worked!

npm install gulp-load-plugins@latest --save-dev
npm install rxjs@^5.0.1 --save
npm install zone.js@^0.8.4 --save
npm install codelyzer@^3.0.0 --save-dev
npm install gulp-tslint@latest --save-dev
npm install tslint@latest --save-dev
