### ISSUE TITLE
Development with Docker?

### ISSUE THREAD

**Issue by tomlobato** [mgechev/angular-seed#1942]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ maybe] feature request
[X ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Unable to develop with Docker via docker-compose.yml
File changes doesn`t make browser to update or app to be rebuit.

**Expected behavior**

Develop with Docker like a local 'npm start', eg: file changes triggers gulp watchers and browser reload.

**Minimal reproduction of the problem with instructions**
(https://github.com/mgechev/angular-seed#development-build-and-deployment)
$ docker-compose build
$ docker-compose up -d

**What is the motivation / use case for changing the behavior?**

Streamline the JS stack setup for team members.

**Please tell us about your environment:**

Mac Sierra
$ node -v
v6.10.0
$ npm -v
3.10.10

* **Angular Seed Version:** `aaaaf75`

Angular 4.0.0

* **Node:** `node --version` = 6.10.0

**Comment by Karasuni** [comment]
In `tools/utils/seed/watch.ts/` change line 28 to:
```
plugins.watch(paths, { usePolling: true }, (e: any) => {
```

This should solve your issue for virtualbox, docker, vagrant, ..
