### ISSUE TITLE
generate api documentation throws error

### ISSUE THREAD

**Issue by premiumwd** [mgechev/angular-seed#1945]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

running the following commands in cmd within project folder
# api document for the app
$ npm run build.docs

# generate api documentation
$ npm run compodoc
$ npm run serve.compodoc

**Expected behavior**

**Minimal reproduction of the problem with instructions**
1. open cmd
2. cd to project folder
3. run npm tasks to build api documentation
$ npm run build.docs
$ npm run compodoc
$ npm run serve.compodoc

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

1.0

* **Node:** `node --version` =
v7.10

**Comment by premiumwd** [comment]
I found the build.docs.ts is commented out. Is this on purpose?

**Comment by mgechev** [comment]
For generation of documentation use:

```
$ npm run compodoc
$ npm run serve.compodoc
```

**Comment by premiumwd** [comment]
H:\angular-seed-master>npm run compodoc

> angular-seed@1.0.0 compodoc H:\angular-seed-master
> node ./node_modules/.bin/compodoc -p src/client/tsconfig.json

H:\angular-seed-master\node_modules\.bin\compodoc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 compodoc: `node ./node_modules/.bin/compodoc -p src/
client/tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ChrisR\AppData\Roaming\npm-cache\_logs\2017-05-26T18_17_41
_748Z-debug.log

**Comment by mgechev** [comment]
@premiumwd try removing `node` prefix from the `compodoc` script.

**Comment by premiumwd** [comment]
removed node prefix from the following, it works

    "webdriver-start": "./node_modules/protractor/bin/webdriver-manager start",
    "webdriver-update": "./node_modules/protractor/bin/webdriver-manager update",
    "compodoc": "./node_modules/.bin/compodoc -p src/client/tsconfig.json",
    "serve.compodoc": "./node_modules/.bin/compodoc -s"

**Comment by mgechev** [comment]
I added the prefix because of https://github.com/mgechev/angular-seed/issues/1926...

**Comment by premiumwd** [comment]
It is probably because of his associations with node in windows.

**Comment by premiumwd** [comment]
Thanks anyway! You have a great project!
