### ISSUE TITLE
SCSS Support - Doesn't output compiled css file

### ISSUE THREAD

**Issue by premiumwd** [mgechev/angular-seed#1950]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

removes main.scss which includes all references to other scss files, empties those folders which provide the .scss files. Outputs nothing.

I have .scss enabled and directory is correct.

**Expected behavior**

This is for all commandes, prod|dev|watch

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.1

**Comment by mgechev** [comment]
Cannot reproduce it. Start the seed with `npm start -- --scss` to enable Sass.

**Comment by premiumwd** [comment]
I used the following command with no luck, I really think this is a bug and should be addressed.

**Comment by premiumwd** [comment]
All you have to do is create a scss folder in client, add some scss files and it disappears on npm start.

**Comment by premiumwd** [comment]
https://drive.google.com/open?id=0B4FIhZuY-3DzdzktS3AzYjdSWTA
