### ISSUE TITLE
reload-port does not have any effect

### ISSUE THREAD

**Issue by Hirse** [mgechev/angular-seed#1951]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Using `--reload-port` or `LIVE_RELOAD_PORT` does not have any effect.

**Expected behavior**
I would expect them to change the port of the `/browser-sync` calls when running in dev mode.

**Minimal reproduction of the problem with instructions**
Run the command described in the [Configuration section of the README](https://github.com/mgechev/angular-seed#configuration):
```
$ npm start -- --port 8080 --reload-port 4000 --base /my-app/
```
Or simplified

```
$ npm start -- --reload-port 4000
```

**What is the motivation / use case for changing the behavior?**
When using a proxy to access the app in development the BrowserSync feature is not working unless explicitely proxied.

* **Angular Seed Version:** `00c6e8c`

**Comment by mgechev** [comment]
Will take a look at this one later this week or today if I fix https://github.com/mgechev/angular-seed/issues/1952 on time.

**Comment by mgechev** [comment]
@Hirse it looks over time we've removed this configuration option. I'll update the readme accordingly.

**Comment by Hirse** [comment]
While I would have liked to use the feature, I appreciate the documentation update.
