### ISSUE TITLE
Add IMG Compression to gulp tasks

### ISSUE THREAD

**Issue by premiumwd** [mgechev/angular-seed#1953]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

There is no img compression, thought I create one.

There is a free api I use called gulp-tinypng-compress, it is very useful, all you need to do is sign up www.tinypng.com and put your key in code below. It also checks through a sigfile if the file has already been compressed, it will skip if that's the case.

```
import Config from '../../config';
import { Task } from '../task';
import * as gulp from 'gulp';

var tinypng = require('gulp-tinypng-compress');

export abstract class ImgTask extends Task { 
    return gulp.src( Config.ASSETS_SRC + '/**/*.{png,jpg,jpeg}')
            .pipe(tinypng({
                key: 'ZQYuaG04bZkQiZaaRT8DuzLhQl7ZjAne',
                sigFile: Config.ASSETS_DEST + '/.tinypng-sigs',
                log: true
            }))
            .pipe(gulp.dest(Config.ASSETS_DEST));
}
```

Let me know your thoughts.

**Comment by patrickmichalina** [comment]
Cool task! But I don't think it belongs in the seed because it is too opinionated and bound to a single external provider.

**Comment by premiumwd** [comment]
Maybe not opinionated, but yes its bound to a single provider. You have to have img compression in a project for enterprise type software, no?

**Comment by patrickmichalina** [comment]
Naturally we want optimized images, but this task is not configureable as it is now. There is no way to overwrite the apiKey, compression settings, dimensions, and etc.

**Comment by premiumwd** [comment]
Okay then let me give you some options and not bound this for one provider.

Options like in your seed.config.ts
```
IMG_SRC =  ${this.APP_SRC} + '/img';
IMG_DEST = ${this.APP_DEST} + '/img';;
IMG_OPTIONS = {
      optimizationLevel: 3,
      progessive: true,
      interlaced: true
}

import Config from '../../config';
import { Task } from '../task';
import * as gulp from 'gulp';

var imagemin = require('gulp-imagemin');
var size     = require('gulp-size');

export abstract class ImgTask extends Task { 
    return gulp.task('optimize:images', function() {
     return gulp.src(config.src)
       .pipe(imagemin(config.options))
       .pipe(gulp.dest(config.dest))
       .pipe(size());
   });
}
```

**Comment by mgechev** [comment]
@premiumwd thanks for the suggestion! This really sounds cool and useful. I agree with @patrickmichalina that the seed can get even bigger, more complicated and opinionated.

Would you mind adding a wiki article about this?

**Comment by premiumwd** [comment]
@mgechev yeah of course! This is kind of necessary for enterprise solutions for imgs that should be compressed at core level. https://www.npmjs.com/package/gulp-imagemin

**Comment by mgechev** [comment]
Yep, makes sense. I had similar task for SVGs in my previous Angular project.
