### ISSUE TITLE
Adding Core Module

### ISSUE THREAD

**Issue by RicardoD7I** [mgechev/angular-seed#1957]
I was taking a look at the project structure and as per angular 4 guidelines we are missing the Core Module:

https://angular.io/styleguide#!#04-11

Do create a feature module named CoreModule in a core folder (e.g. app/core/core.module.ts defines CoreModule).

Do put a singleton service whose instance will be shared throughout the application in the CoreModule (e.g. ExceptionService and LoggerService).

What do you think about this?
Will this be a good idea to keep the best practices?

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Comment by TheDonDope** [comment]
Hi @RicardoD7I, you can find a styleguide conforming implementation here: https://github.com/TheDonDope/crudular/blob/develop/src/app/core/core.module.ts

**Comment by mgechev** [comment]
In our case makes sense to change the `SharedModule` to be `CoreModule` because it includes all the core functionality of the application.

@RicardoD7I let me know if you want to open a PR with the change.

**Comment by RicardoD7I** [comment]
@mgechev  I agree that we should rename Shared to Core, but also it will be great to provide a generic sharedModule like this one:

https://github.com/TheDonDope/crudular/blob/develop/src/app/shared/shared.module.ts
(thanks @TheDonDope for the repo!) 

That will provide both modules that are specified as best practices on ng4. 
Also, i'm pretty overloaded at work, but I can have this for the next week probably.

**Comment by mgechev** [comment]
Thinking about this further:

Having both `CoreModule` and `SharedModule` seems like an overhead given the project's complexity.

I understand the reasoning behind this and as one of the co-authors of the style guide I respect the suggestions. On the other hand, I also realize that following the practices in the inappropriate context can lead to a confusion rather than better semantics/scalability of a project.

Lets close the issue for now.
