### ISSUE TITLE
Location information in generated messages.xlf points to wrong location

### ISSUE THREAD

**Issue by Hirse** [mgechev/angular-seed#1958]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I run `npm run i18n` to generate the `messages.xlf` each `trans-unit`-entry contains location information which point to the wrong file.

Based on the master branch I get the following file:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="6cdb1fea93d77c07950c0c76c6e0ad79ebbef084" datatype="html">
        <source>Features</source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">C:/Users/hirse/git/angular-seed/dist/tmp/app/about/about.component.ts</context>
          <context context-type="linenumber">3</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

The `sourcefile` (`C:/Users/hirse/git/angular-seed/dist/tmp/app/about/about.component.ts`) is wrong in multiple ways:
1. It points to the absolute location on my device, not the location in the project.
2. It points to a file in `dist/tmp` which doesn't even exist anymore by the time I see the `messages.xlf`.
3. It points to the TypeScript file, but the translated text is in the HTML-template.
4. On Windows, it is displaying a Windows-style path, but using the wrong slashes.

**Expected behavior**
I would expect the `sourcefile` to be `src/client/app/about/about.component.html`.

**Minimal reproduction of the problem with instructions**
Run `npm run i18n` and look at the `messages.xlf`.

**What is the motivation / use case for changing the behavior?**
The location information in the `messages.xlf` should be useful (or removed).

**Please tell us about your environment:**
Windows, although I expect equivalent problems to be present on other OS as well.

* **Angular Seed Version:** `649257d`
* **Node:** `node --version` = v8.0.0

**Comment by nhutcorp** [comment]
Hi Hirse,
Please check this PR https://github.com/mgechev/angular-seed/pull/1987
