### ISSUE TITLE
Unable to dynamically transpile ES module

### ISSUE THREAD

**Issue by ZuSe** [mgechev/angular-seed#1960]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Dev build throws ES module loader error

> localhost/:86 TypeError: Unable to dynamically transpile ES module
>    A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
>     at transpile (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496923443688:3690:11)
>     at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496923443688:3473:12
>     at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1496923443690:391:26)
>     at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1496923443690:141:43)
>     at http://localhost:5555/node_modules/zone.js/dist/zone.js?1496923443690:818:57
>     at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1496923443690:424:31)
>     at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1496923443690:191:47)
>     at drainMicroTaskQueue (http://localhost:5555/node_modules/zone.js/dist/zone.js?1496923443690:584:35)
>     at <anonymous> Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
> (anonymous)	@	localhost/:86

**Expected behavior**
Should either ignore ES modules and import without transpiling or use proper transpiler

**Minimal reproduction of the problem with instructions**
Create a new seed and add the following dependencies https://paste.ubuntu.com/24807795/

**What is the motivation / use case for changing the behavior?**
Problems with third party dependencies that are compiled as es6 module

**Please tell us about your environment:**
SystemJS 20.12, Node 6.10.2, Ubuntu 17.04

* **Angular Seed Version:** `aaaaf75`
 0e1c1b5 

__________________________________________

Sorry for having no time to reduce it down to proper package that triggers the error, but it seems to be a more general issue. With SystemJS the default traceur transpiler was changed, which now requires to use either one of the plugins or ignore transpiling es modules.
Maybe we should add typescript as default transpiler to the project?

Best,
ZuSe

**Comment by mgechev** [comment]
Thanks for reporting the issue! It's most likely caused by the SystemJS update. Until it's fixed you can revert back to https://github.com/mgechev/angular-seed/commit/158c3889a3b868051a321040e2427198c033e14d.

**Comment by mgechev** [comment]
I fact, this is a configuration issue. If you want to consume modules with ES2015+ syntax, I'd recommend you to take a look at systemjs's manual page. I'd prefer to use the ES5 bundle in order to speed up my page reload.

**Comment by ZuSe** [comment]
@mgechev 

Minko, that doesn't make that much sense.
Ofc it would be nice if every 3rd party project would provide an umd bundle with the npm package.
But as we can't count on that we should be flexible to a maximum.
That's why I would suggest that the seed also supports ES6 provided libraries. 

Your thoughts?

Best,
Patrick

**Comment by tomwanzek** [comment]
If I may add on an additional consideration, there are cased where using UMD for a third party library may not be an option for module imports. As an example, I build a service that wraps a number of D3 Modules (the data visualization library) The issue with providing my service library in UMD format is that it breaks the live binding to a `d3.event` property which underlies key D3 features like d3-zoom, d3-drag, and d3-brush.

The live binding is not an issue with a library provided in ES2015 format (even when compiled down from TypesScript to an ES5 target.)

**Comment by ravivit9** [comment]
Looks like this issue is happening again.

**Comment by snarun** [comment]
Even if you provide transpiler through ` 'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
        'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-browser.js',` in systemjs configuration, the dynamic transpilation will not work, due to the missing decorators of angular modules and components in UMD bundles.  

In my case, I'm getting the errors such as errors such as ‘**No NgModule metadata found for XyzModule**’ or ‘**Please add a @Pipe/@Directive/@Component annotation**’ 

Any updates??
