### ISSUE TITLE
Multiple apps: loading fails when app is not "app"

### ISSUE THREAD

**Issue by locinus** [mgechev/angular-seed#1965]
**I'm submitting a ...**
```
[X ] bug report
```

**Current behavior**
Tried to create multiple apps within the seeds. Except the app in the "app" folder, other apps fail when running: `npm start -- --app myApp`, whith error:
> (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/appchien/main
	Error loading http://localhost:5555/appchien/main Not expecting this error? Report...

thrown by

>   System.import('myApp/main')
    .catch(function (e) {
      console.error(e.stack || e,..

**Expected behavior**
The apps not called "app" would load and work.

**Minimal reproduction of the problem with instructions**
From seed sources:
- move src/client/app/* => src/client/myApp/ (except src/client/app/system-config.ts)
- npm start -- --app myApp

**What is the motivation / use case for changing the behavior?**
Definitely use multiple apps with shared code.

**Please tell us about your environment:**
Windows 7
Netbeans 8.1

* **Angular Seed Version:**
commit 171f4ef0d217e1336527cac356cf86968036d2d9

* **Node:**
6.10.3

**Comment by mgechev** [comment]
You will need to update the SYSTEM_DEV_CONFIG accordingly. Take a look at the configuration for app.

**Comment by locinus** [comment]
I was checking SYSTEM_CONFIG_DEV in seed.config.ts, but everything looks in order, based on variable BOOTSTRAP_MODULE itself based on the app name given with "--app". I'm not exactly sure what I'm trying to update here?

**Comment by mgechev** [comment]
You'd want to override the `SYSTEM_CONFIG_DEV` by setting the correct path for your extra application. In the past the seed was doing this automatically but there was just too magic involved.

You can see how the configuration looks for the `app` module and update accordingly.

**Comment by locinus** [comment]
Thanks !
Ok, so I added this in seed.config.ts :

```
SYSTEM_CONFIG_DEV: any = {
...
packages: {
  app: {
    defaultExtension: 'js'
  },    // <--
  [this.BOOTSTRAP_DIR]: {
    defaultExtension: 'js'
  }    // -->
}
```
and `start.deving` and `build.prod.rollup.aot` seems to work fine with option `-- --app=myApp` now.
Wouldn't that fit the general case?

**Comment by mgechev** [comment]
Actually this sounds good. Would you open a PR with the change?

```
  app: {
    defaultExtension: 'js'
  },    // <--
```

Doesn't seem necessary since `this.BOOTSTRAP_DIR` is going to have `app` as value by default.

**Comment by locinus** [comment]
I will.
I was letting the setting for 'app', because `app/system-config.js` is required in index.html and karma config. Though I don't know why system-config.js is in the app folder, surely it could fit in src/client instead (parent folder)?
So I'd suggest:
- moving system-config.js up one level (in src/client)
- modifying references to it in index.html and karma.conf.js
I'll post a PR with that.

**Comment by mgechev** [comment]
Yes, sounds good.
