### ISSUE TITLE
Setting proxy to API server

### ISSUE THREAD

**Issue by locinus** [mgechev/angular-seed#1969]
**I'm submitting a ...**
```
[X] feature request
```

**Problem**
It is possible via command `ng serve` to indicate a parameter `--proxy-config proxy.conf.json` so a call to the API on a different server would work, without going through a CORS conflict. This is precious when the API server can't be configured to allow cross-origin.

```
// proxy-conf.json
{
  "**/api/**": {
    "target": {
		"host": "localhost",
		"protocol": "http",
		"port": 11111
	},
	"changeOrigin": true,
    "secure": false
  }
}

```
=> I can't find a way to configure a proxy of this kind in Angular-Seed. Any guidance to how to pass such a parameter, or how to tweak the tasks to do so?

**Minimal reproduction of the problem with instructions**
Make a request to a server different than the seed server (localhost:5555).

**Please tell us about your environment:**
Windows 7
Netbeans 8.1

* **Angular Seed Version:**
Commit 171f4ef0d217e1336527cac356cf86968036d2d9

* **Node:**
6.10.3

**Comment by mgechev** [comment]
This is out of the scope of the project. Here's a [how-to article](http://thelillysblog.com/2016/11/02/MEAN-stack-with-Angular2/).

**Comment by locinus** [comment]
Ok. But isn't that a widely wanted feature?
