### ISSUE TITLE
compiling npm modules

### ISSUE THREAD

**Issue by deli6z** [mgechev/angular-seed#1971]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Right now when I include a module in the package.json file and reference module in the code it can not find the corresponding js file because module does not have it compiled, only 'ts' version of it exists
**Expected behavior**

have a way to compile that module ts files to js on the fly
**Minimal reproduction of the problem with instructions**
I am trying to include the module from internal git repo which does not have j compiled files.
I know angular cli handles it somehow but wanted to figure out how to make it work in angular seed.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** 1.0.0

* **Node:** `node --version` = 6.9.5

**Comment by mgechev** [comment]
Thanks for the proposal. This is out of the scope of the project.

**Comment by deli6z** [comment]
Thank you for a reply! Is there a way to handle it manually now somehow within angular seed?

**Comment by mgechev** [comment]
Probably you can achieve this behavior using `ts-node`.
