### ISSUE TITLE
I'm trying to use minio in this project but can't import the depencies used in minio.js

### ISSUE THREAD

**Issue by oMinGWo** [mgechev/angular-seed#1972]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I'm trying to use minio to uplaod my file to a private oss server. I followed the js guaid from minio doc, npm install minio. After installing minio, I tried to import into my ts file. When i used minio just like this, my browser's console told me can not find the depencies required in minio.js

`import * as Minio from 'minio';`

```
this.minioCliet=new Minio.Client({
          endPoint: 'kikbug.net',
          port: 9000,
          secure: false,
          accessKey: '123123123',
          secretKey: '123123123'
        });
```

**Expected behavior**
I expected to start my project and use the minio api successfully

**Minimal reproduction of the problem with instructions**

1. npm install minio
2. import minio in a ts file 
3. npm start to start the project

**Please tell us about your environment:**

Windows10, WebStrom, Nginx

* **Angular Seed Version:** `don't know`

* **Node:** `node --version` =6.10.0

**Comment by oMinGWo** [comment]
![minio](https://user-images.githubusercontent.com/7437349/27119713-7ff11ff4-5113-11e7-8490-d7a02a6447dd.png)
Here is the screenshot of my browser

**Comment by TheDonDope** [comment]
Hey @oMinGWo, see here https://github.com/mgechev/angular-seed/issues/1592#issuecomment-258307173
