### ISSUE TITLE
bundle analyzer

### ISSUE THREAD

**Issue by hkashlan** [mgechev/angular-seed#1975]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I want to reduce the bundle size but I don't have tools to do it,
it will be cool if we integrate angular-seed with tools like [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer)

**Expected behavior**
generate reports like [webpack-bundle-analyzer](https://cloud.githubusercontent.com/assets/302213/20628702/93f72404-b338-11e6-92d4-9a365550a701.gif) which it will be useful to reduce the bundle size

* **Angular Seed Version:** `649257dc3f76f76c5b553e6c269db5fab6846d11`

**Comment by mgechev** [comment]
Source map explorer is something that we have considered in the past. If anyone is interested in implementing such feature I will be happy to assist.

**Comment by hkashlan** [comment]
I am interested in implementing like this feature,

could you please give some hints to do it

**Comment by mgechev** [comment]
@hkashlan would you message me on gitter?

**Comment by salemdar** [comment]
@mgechev @hkashlan Is this being developed?

**Comment by mgechev** [comment]
No, nobody is working on this yet.

**Comment by salemdar** [comment]
@mgechev Then I would like to contribute.

**Comment by mgechev** [comment]
Sound good! Do you have plan for the implementation?

**Comment by hkashlan** [comment]
I would like to contribute too
 @mgechev  I messaged you on gitter
so let's start do it, shall we meet on gitter?

**Comment by mgechev** [comment]
My high-level idea for implementation is:

- Introduce additional `npm` script which invokes a `gulp` task.
- The script (and respectively the task name), could be `source-map-explorer`, for instance.
- The gulp script should do almost exact same thing as the production build (i.e. you can reuse the flags), however, it'll preserve the source maps.
- In the end the task will invoke source map explorer, so that it will produce the final chart.

**Comment by salemdar** [comment]
@mgechev Makes sense. It seems like a straightforward process. How about this:

```
npm run sme.prod
npm run sme.prod.exp
npm run sme.prod.rollup.aot
npm run sme.prod.aot
```

**Comment by mgechev** [comment]
Yes, `exp` doesn't seem necessary since it's alias for backwards compatibility of `aot`.

**Comment by salemdar** [comment]
Cool. I will try to make it to weekend.

**Comment by salemdar** [comment]
@mgechev It is done except the `sme.prod.rollup.aot`. Preserving sourceMap for `app.js` is trickier than I thought, or I am missing something. I am able to create sourceMap for `bundle.js` and for other files in `tmp/app`, but not for `prod/js/app.js`. Any tips?

**Comment by mgechev** [comment]
@salemdar, my guess is that either: `transpile.bundles.rollup.aot` or `minify.bundles` drops the source map.

**Comment by salemdar** [comment]
It was minify, thanks for the hint 👍 . Do you think this output is fine?

![image](https://user-images.githubusercontent.com/6159613/28184146-75e8a4da-6812-11e7-8b31-0719f58b86ff.png)

**Comment by mgechev** [comment]
Looks very good! We need to research why rollup uses the es5 bundles because this prevents from efficient bundling with tree-shaking.

**Comment by hkashlan** [comment]
@salemdar it is really good
