### ISSUE TITLE
Integration with AngularFire2 error

### ISSUE THREAD

**Issue by DmitriyPotapov** [mgechev/angular-seed#1977]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I following this guide https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularFire2 
When i tried use 'AngularFireAuth' (**import { AngularFireAuth } from 'angularfire2/auth'**;) i have an error in browser console:

```
Failed to load resource: the server responded with a status of 404 (Not Found) :5555/node_modules/angularfire2/bundles/angularfire2.umd.js/auth.js

localhost/:89 Error: Fetch error: 404 Not Found
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1497644285152:1500:13
    at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1497644285155:391:26)
    at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1497644285155:141:43)
    at http://localhost:5555/node_modules/zone.js/dist/zone.js?1497644285155:817:57
    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1497644285155:424:31)
    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1497644285155:191:47)
    at drainMicroTaskQueue (http://localhost:5555/node_modules/zone.js/dist/zone.js?1497644285155:584:35)
    at <anonymous> Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Win 10, VsCode, NPM,
* **Angular Seed Version:**  latest

* **Node:** `node --version` = 8.0

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by DmitriyPotapov** [comment]
OK, but your wiki page https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularFire2 out-of-date...
