### ISSUE TITLE
multibyte characters (Japanese) in the xlf file are escaped with i18n command.

### ISSUE THREAD

**Issue by MSakamaki** [mgechev/angular-seed#1986]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

When you generate an xlf file containing Japanese with the `npm run i18n` command, all the contents of the xlf file after the second time are escaped.

**Expected behavior**

It will not be escaped the second time and so on, and the characters of the i18n tag seem to be displayed as it is.

**Minimal reproduction of the problem with instructions**

define i18n in Japanese.

```html
 <h2 i18n>特徴</h2>
```

`npm run i18n` command to generate an xlf file in `dist/locale/`.

The contents are as follows.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="87ee4feeed6e3cc603a76552641e3cae1c179d2c" datatype="html">
        <source>特徴</source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">app/about/about.component.ts</context>
          <context context-type="linenumber">3</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>

```

again generate the xlf file in `dist/locale/` with `npm run i18n` command.

`特徴` is escaped to `&#x7279;&#x5FB4;`.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="87ee4feeed6e3cc603a76552641e3cae1c179d2c" datatype="html">
        <source>&#x7279;&#x5FB4;</source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">app/about/about.component.ts</context>
          <context context-type="linenumber">3</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**What is the motivation / use case for changing the behavior?**

The problem seems to be how to use [cheerio](https://github.com/cheeriojs/cheerio).

I could avoid this problem by adding `decodeEntities: false` to [parserOptions of cheerio](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/i18n.merge.ts#L21).

**Please tell us about your environment:**

OS X, VsCode, NPM,

* **Angular Seed Version:** `b935bfe`

* **Node:** `node --version` = v7.10.0

**Comment by nhutcorp** [comment]
Hi MSakamaki,
Thanks for your checking and give your solution, I did a PR here https://github.com/mgechev/angular-seed/pull/1987

**Comment by mgechev** [comment]
@nhutcorp, thanks for the fixes!
