### ISSUE TITLE
[SUGGEST] Add noop 'finalize' task to all composite tasks

### ISSUE THREAD

**Issue by RoxKilly** [mgechev/angular-seed#1989]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

In `/tools/config/seed.tasks.json` the build tasks all begin with an `initialize` task. If I understand things correctly, this task does nothing. It's up to the user to override it with his own custom routine. This is really helpful for users who always do the same thing before building. I'm suggesting adding a common `finalize` task at the end of all the build composite chains

**What is the motivation / use case for changing the behavior?**

It would be great to have a mirror noop `finalize` task. If a user needs to run a routine at the end of every build (eg: push to a remote location, or create a backup) all he would have to do is override the noop `finalize` task with his own.  Currently, the user has to copy the entire task group, add his task at the end, and place it in `project.tasks.json` so it will override the original. 

**project.tasks.json**
```
  "build.dev": [
    "initialize",
    "clean.once",
    "build.assets.dev",
    "build.html_css",
    "build.js.dev",
    "build.index.dev",
    "sw.manifest.static",
    "my.custom.task"  //<------ copied the whole block just so I could have a "finalize" task
],
```
This will make upgrading more complicated than it needs to be if the seed changes `seed.tasks.json` to edit the task sequence for a particular build -- because the user would have to copy over the whole new sequence to `project.tasks.json` again, whereas with my proposal, no change would be required at all: the seed's `finalize` would continue to be overwritten by the user's `finalize`, and the change in `seed.tasks.json` would be transparent to the user.

Finally, to make things even easier, a noop `initialize` and `finalize` task could be placed in `tools/tasks/project/` as a hint to the user

**Comment by mgechev** [comment]
Hey @RoxKilly, sounds good. Would you have time to open a PR with the feature?

**Comment by RoxKilly** [comment]
@mgechev apologize for all the commits. I'm learning my way around version control so I mistakenly pushed before being done, then had to revert my changes and push again. The PR is ready.

**Comment by mgechev** [comment]
No worries :-)

I'll review and merge later today / tomorrow.

**Comment by mgechev** [comment]
Lets close the issue for now.
