### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#1992]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I am trying to use Angulartics2 and getting an error SyntaxError: Unexpected token import (import { NgModule, Inject, Optional, OpaqueToken, SkipSelf } from '@angular/core';
)

**Expected behavior**

Angular seed works Angulartics2 with no issues
https://github.com/angulartics/angulartics2

**Minimal reproduction of the problem with instructions**

Integrate Angulartics2 (https://github.com/angulartics/angulartics2) with Angular-Seed..
**What is the motivation / use case for changing the behavior?**

Project.config.ts

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'angulartics2/dist/index.js', inject: 'libs'},
      // inject into css section
  ];

    // Add packages (e.g. ng2-translate)
     let additionalPackages: ExtendPackages[] = [
       {
         name: 'angulartics2',
         path: 'node_modules/angulartics2/dist/index.js'
       }
     ];

app.component.ts

import { Angulartics2GoogleAnalytics } from 'angulartics2';
  constructor(public angulartics2GoogleAnalytics: Angulartics2GoogleAnalytics) {}

app.module.ts

import { Angulartics2Module, Angulartics2GoogleAnalytics } from 'angulartics2';

@NgModule({
  imports: [ Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ]) ],

**Please tell us about your environment:**

Windows 10, Chrome

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.7.1

**Comment by skolli853780** [comment]
we are on Angular 2.4

**Comment by Karasuni** [comment]
> we are on Angular 2.4

angular-seed is on angular 4.x
