### ISSUE TITLE
SCSS fails in prod build

### ISSUE THREAD

**Issue by AdrianAgui** [mgechev/angular-seed#1995]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I have enabled prod mode and also enabled scss. SCSS works fine if i build in dev mode. But in prod mode it is not able to find css or scss file. The output error when compile in prod is:

![image](https://user-images.githubusercontent.com/18145972/27629513-e024bb4e-5bf2-11e7-9068-a7a01f5b026a.png)

**Expected behavior**
Compile in prod (serve.prod) without sass errors.

**Minimal reproduction of the problem with instructions**
My project structure is this:

![image](https://user-images.githubusercontent.com/18145972/27629607-30e36486-5bf3-11e7-80c6-2586669ad11c.png)

![image](https://user-images.githubusercontent.com/18145972/27629612-3516e974-5bf3-11e7-8d35-ae089467e210.png)

I realized the @media from sass files cause this error and i dont know how can i fix it, can anyone help me? @mgechev 

**Please tell us about your environment:**
Windows 10, Visual Code IDE.

* **Angular Seed Version:** latest

* **Node:** `node --version` = v6.5.0

**Comment by vyakymenko** [comment]
@AdrianAgui , `main.css` line 1009 you forgot `}`. 

This issue can be closed ;)

**Comment by AdrianAgui** [comment]
@vyakymenko main.css is  the file created on the compile process, is not my main.css.

The problem here is with @media sass, without @medias in my code build prod works well, but when i put one the build fails (the error above).

**Comment by vyakymenko** [comment]
@AdrianAgui , it's not a seed issue. Can u share your code, I think error in one of your scss file ?

**Comment by AdrianAgui** [comment]
I found the error, and yes, is a seed issue. In tasks/seed/build.html_css.ts file, when the build is prod, is used plugins.cached('process-component-css') on some functions, I replaced this by plugins.util.noop() which is used in dev build.
I dont know why is working now but I suggest you take a look in build prod gulp task.

Thanks.
