### ISSUE TITLE
SyntaxError: Unexpected token < at eval (<anonymous>)

### ISSUE THREAD

**Issue by arun-awnics** [mgechev/angular-seed#1996]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

[
![image](https://user-images.githubusercontent.com/25379505/27676592-2db64858-5ccc-11e7-94b6-7c487903bf18.png)
](url)
**Expected behavior**

Needs to compile and run without error

**Minimal reproduction of the problem with instructions**

It works with previous version but I get this error when I update my code with the latest version of angular-seed.

**Please tell us about your environment:**

OS: Windows X
IDE: None
Package manager: npm v.6.9.1

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = v6.9.1

**Comment by mgechev** [comment]
That's incorrect import, not an issue in Angular seed.

**Comment by arun-awnics** [comment]
Is it the third party library you are talking about?

**Comment by mgechev** [comment]
@arun-awnics you can take a look at the network tab and see which file is not being loaded properly. What happens is:

- You try to load a non-existing module with SystemJS.
- The dev server returns `index.html`.
- SystemJS tries to run `index.html` as JavaScript.
- You can the error `SyntaxError: Unexpected token < at eval`.

**Comment by arun-awnics** [comment]
I am doubting that's not the problem I am facing. I did what you said in the network tab. I see that I have included all the imports in `project.config.ts`. 

I get this error while compiling:
`src\client\app\system-config.ts(1,13): error TS2451: Cannot redeclare block-scoped variable 'System'.`

What does that mean? Can you please tell me what it is? @mgechev 
Thank you in advance.

**Comment by maxmarkus** [comment]
@arun-awnics With seed update some changes got introduced here. 
I also had to disable/remove the first `declare var System: SystemJSLoader.System;` line inside `src\client\app\system-config.ts`, then it worked.

**Comment by arun-awnics** [comment]
Hey @maxmarkus Even after removing or commenting the first line, I still get the same error.

**Comment by MathijsHoogland** [comment]
I'm having the same problem, did you find a solution @arun-awnics?

**Comment by arun-awnics** [comment]
No @MathijsHoogland I tried everything said above and it still doesn't work. Were you able to find the solution?

**Comment by hhubik** [comment]
Also running into this.  Started working again on my Angular 2 project after about 4 months.  The project used to work fine at that time. Made no other changes, just updated to the latest Seed, which brought my project from Angular 4.0.0 to 4.2.3.  Don't see any errors (missing files) in the Network tab of Dev tools.  Also removed and re-installed `node_modules` directory.

**Comment by skolli853780** [comment]
I am getting same error..arun, Did you fix this issue?

**Comment by hhubik** [comment]
@skolli853780 - in my case the problem was due to some third part libraries/packages not getting loaded.  I managed to use the debugger (set a break point in code just before the error occurs, then turn on 'break on exception') to identify the library that could not be loaded.  For each of the 'unloadable' libraries, I had to add the following code (using `base64-js` as example) to `additionalPackages` in my `project.confiig.ts`:
```
{
      name: 'base64-js',
      path: 'node_modules/base64-js/index.js',
      packageMeta: {
        defaultExtension: 'js'
      }
    }
```

**Comment by sparachi** [comment]
@hhubik your suggestion helped me to resolve the unexpected token issue. I had multiple packages breaking so fixed one by one added entries to project.config.ts file . Attaching screenshot if it might help others, please have breakpoint at the file and look for 'address' that indicates you the package. 

![seed issue unexpected token](https://user-images.githubusercontent.com/15947845/38067418-9e016d06-32da-11e8-94c8-a97827db3895.png)

below are 2 such packages

      {
        name: 'rxjs',
        path: 'node_modules/rxjs/bundles/Rx.js',
      },
      {
        name: 'moment',
        path: 'node_modules/moment',
        packageMeta: {
          main: 'moment.js',
          defaultExtension: 'js'
        }
      }
