### ISSUE TITLE
build.prod.rollup.aot: ReferenceError: error is not defined

### ISSUE THREAD

**Issue by RoxKilly** [mgechev/angular-seed#1998]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

In the bundled application, `build.prod.rollup.aot` fails with error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
ReferenceError: error is not defined
    at eval (lodash.templateSources[118]:9:10)
    at DestroyableTransform._transform (C:\...\node_modules\gulp-template\index.js:21:40)
```

I modified gulp-template to log the problematic path to the console. The result:
```
failed to parse: C:/.../dist/tmp/app/shared/name-list/name-list.service.js
```
The error stems from `handleError()` in `name-list.service.ts`. 
```
  private handleError (error: any) {
    let errMsg = (error.message) ? error.message :
      error.status ? `${error.status} - ${error.statusText}` : 'Server error';
    console.error(errMsg); // log to console instead
    return Observable.throw(errMsg);
  }
```
More specifically, it is triggered by the use of the [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) string. If I replace
```
`${error.status} - ${error.statusText}`
```
with
```
error.status + ' - ' + error.statusText
```
the error goes away.  Might be related to [this comment](https://github.com/mgechev/angular-seed/issues/1498#issuecomment-271716174) about how `${` in a template can cause problems.

**Expected behavior**

Rollup AOT compilation to work for the included project

**Minimal reproduction of the problem with instructions**

* Clone the master branch at `4285f1a`
* Make [this change](https://github.com/mgechev/angular-seed/pull/1991/commits/ea039e5b608da5736a261f0dbc4d9476b40f91dc) to remove the optional argument from gulp-template options (should make no difference since the argument was set at its default anyway)
* run `build.prod.rollup.aot`

**Please tell us about your environment:**

Windows 7

* **Angular Seed Version:** `4285f1a`

* **Node:** `node --version` = 8.1.3

**Comment by RoxKilly** [comment]
On further inspection, it's not the template literal as much as the `${`.  If I replace the backticks with single-quotes, `'${error.status} - ${error.statusText}'` thus turning the whole thing into a regular string, the same error is thrown.

Perhaps the template engine sees `${` and tries to evaluate what's inside -- `${error.status}`--  Since it doesn't know anything called `error` it throws the exception: *"error is not defined"*

**Comment by mgechev** [comment]
As the Angular compiler suggests, you need to use:

`${{ '{' }}error.status{{ '}' }} - ${{ '{' }}error.statusText{{ '}' }}`.
