### ISSUE TITLE
Protractor e2e tests fail on prod build

### ISSUE THREAD

**Issue by tobiaseisenschenk** [mgechev/angular-seed#2001]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Local protractor e2e-tests against a dev build run successfully, while the same tests against the prod build fail with the error message: "Timed out waiting for asynchronous Angular tasks to finish after 60 seconds." I am aware of the protractor timeout documentation and the fix to run asynchronous requests outside of the angular zone. However this does not solve my problem, since my tests runs through against a dev build.

**Expected behavior**
e2e tests with protractor show the same behavior on the production build as well as on the development build of the angular seed.

**Minimal reproduction of the problem with instructions**
Executing the gulp tasks for dev e2e tests:

1. npm run webdriver-start

2. npm run serve.e2e

3. npm run e2e

vs. Executing gulp tasks for e2e tests against prod:

1. npm run e2e.ci.dev

**What is the motivation / use case for changing the behavior?**
The tests fail without clear indication why.

**Please tell us about your environment:**
OSX 10.11.6, WebStrom 2017.1.4, NPM 3.10.8, protractor: ^5.1.2, @types/gulp-protractor: ^1.0.29, @types/selenium-webdriver: ^3.0.3

* **Angular Seed Version:** `aaaaf75`
649257dc3f76f76c5b553e6c269db5fab6846d11

* **Node:** `node --version` =
NPM 3.10.8

**Comment by mgechev** [comment]
@tobiaseisenschenk thanks for reporting this issue. Will take a look ASAP.

**Comment by mgechev** [comment]
Tried to reproduce the issue. The protractor tests run successfully for me. Probably this is environment specific issue.

**Comment by fawaysheh** [comment]
Same issue here, the test ran successfully when I create the build using "ng build", but not "ng build --prod", it keeps telling me that the protractor is not seeing the elements that leads to timeout issues.

Could you please tell me what is the different here?
Thanks
