### ISSUE TITLE
Cannot Import Any Module., Error Is Unexpected Token <

### ISSUE THREAD

**Issue by Bigetion** [mgechev/angular-seed#2006]
I have installed angular2-cookie, ng2-smart-table, angular-2-data-table..
and when i import module, error is always "Unexpected token <at eval (<anonymous>)"
any new module can't import.. please help me.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by mim-narola** [comment]
Facing same issue.Not getting any solution for this.
