### ISSUE TITLE
Cannot import fs in node

### ISSUE THREAD

**Issue by oMinGWo** [mgechev/angular-seed#2007]
**Current behavior**
I'm trying to import fs in node to upload file. 
But my browser told that cannot find fs.js in node_module file.
I think it should not try to find fs.js in node_module

* **Node:** `node --version` =6.12

![image](https://user-images.githubusercontent.com/7437349/27995162-6e5d32c6-64fc-11e7-9185-69bfa3b5f5cd.png)

**Comment by mgechev** [comment]
You cannot import fs in your application since this module is usable only in node.

Check where you are referencing fs in your source code.
