### ISSUE TITLE
Allow build.prod.rollup.aot for multiple apps

### ISSUE THREAD

**Issue by codez** [mgechev/angular-seed#2009]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When I run `build.prod.rollup.aot` with `-- --app other`, I get 

`dist/tmp/app/main-prod.ts(8,36): error TS2307: Cannot find module './app.module.ngfactory'.` 

in `build.js.prod.rollup.aot`.

**Expected behavior**

Rollup AOT build works.

Comparing with `build.js.prod.aot`, the `toIgnore` section is missing in `build.js.prod.rollup.aot`. When this section is copied, the build works for me.

**Angular Seed Version:** `aaaaf75`

**Comment by mgechev** [comment]
I will take a look at the issue in the next week or two. In case you have some spare time a PR will be highly appreciated.

**Comment by Doehl** [comment]
I was having the exact same issue, and can confirm that the copy of the `toIgnore` does fix it.

I will create a PR for the fix.
