### ISSUE TITLE
about.component.spec.ts file has incorrect tabbing 

### ISSUE THREAD

**Issue by abrahamq** [mgechev/angular-seed#2015]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

`
export function main() {
   describe('About component', () => {
    // Setting module for testing
    // Disable old forms
`
There's 3 spaces of indentation for the describe block, instead of 2. 

**Expected behavior**

2 spaces of indentation. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Sorry for this inane issue, found it because I copied the about.component.spec.ts file to write my own tests. Thought I'd save someone else the hassle of changing all of their tests if they do the same thing as me.

**Please tell us about your environment:**

* **Angular Seed Version:** `307a8be9173ca9b72bb73fd7d1629d5c874db4d5`

* **Node:** `node --version` =7.9.0

**Comment by abrahamq** [comment]
I have a local branch that fixes this. How do I push that up? Fork the repo? Thanks, sorry for the dumb question.

**Comment by mgechev** [comment]
@abrahamq no worries! Thanks for reporting the incorrect indentation. The issue should be fixed now.

**Comment by abrahamq** [comment]
Awesome thanks! How does one go about submitting a PR? I saw this: https://github.com/mgechev/angular-seed/blob/master/.github/CONTRIBUTING.md but it doesn't say how actually submit the PR.

**Comment by mgechev** [comment]
The PR submission is something generic between all projects hosted on GitHub. It's best to [Google it](https://yangsu.github.io/pull-request-tutorial/).

**Comment by abrahamq** [comment]
Okay, thank you!
