### ISSUE TITLE
creation trace on string - app not starting

### ISSUE THREAD

**Issue by superstarmcawesome** [mgechev/angular-seed#2016]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Download latest seed.
npm install
npm start
see picture console-output.

**Expected behavior**

no console output error....

**Minimal reproduction of the problem with instructions**
Download latest seed.
npm install
npm start
check console output
![bildschirmfoto 2017-07-13 um 12 09 50](https://user-images.githubusercontent.com/18305534/28161616-763a9978-67c4-11e7-96fc-db54c3b8c85b.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

latest
* **Node:** `node --version` = 6.9.1

same error on mac and windows.

**Comment by pbazurin-softheme** [comment]
Set zone.js version to 0.8.12

**Comment by JuliaRakitina** [comment]
Same issue

**Comment by mgechev** [comment]
@pbazurin-softheme thanks for pointing this out and for the PR!
