### ISSUE TITLE
Typescript not compiling

### ISSUE THREAD

**Issue by ngentads** [mgechev/angular-seed#2020]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I checkout the 4.0.0 tag, `npm install` fails with the following error during the postinstall task:

    [14:23:57] Requiring external module ts-node/register
    
    /home/ngent/Workspace/angular-seed/node_modules/ts-node/src/index.ts:316
              throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                        ^
    TSError: ⨯ Unable to compile TypeScript
    Cannot find type definition file for 'node'. (2688)
    gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
    gulpfile.ts (2,23): Cannot find module 'gulp-util'. (2307)
    gulpfile.ts (3,30): Cannot find module 'run-sequence'. (2307)
    gulpfile.ts (5,20): Cannot find module './tools/config'. (2307)
    gulpfile.ts (6,47): Cannot find module './tools/utils'. (2307)
        at getOutput (/home/owuser/Workspace/angular-seed/node_modules/ts-node/src/index.ts:316:17)
        at /home/owuser/Workspace/angular-seed/node_modules/ts-node/src/index.ts:347:18
        at Object.compile (/home/owuser/Workspace/angular-seed/node_modules/ts-node/src/index.ts:474:19)
        at Module.m._compile (/home/owuser/Workspace/angular-seed/node_modules/ts-node/src/index.ts:410:44)
        at Module._extensions..js (module.js:565:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/home/owuser/Workspace/angular-seed/node_modules/ts-node/src/index.ts:413:12)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.require (module.js:483:17)

**Expected behavior**
The postinstall task would complete successfully and print the banner on completion.

**Minimal reproduction of the problem with instructions**

1. Clone the repository
2. Create a branch at the 4.0.0 tag's commit
3. run `npm install`

**What is the motivation / use case for changing the behavior?**
We're upgrading our internal project that uses the seed to Angular 4, and we'd like to do it off of that tag rather than master

**Please tell us about your environment:**
OS: Linux Mint 18.1 Serena

* **Angular Seed Version:**
`bdb0e1d`

* **Node:**
`node --version` = 6.5.0
`npm --version` = 3.10.3

**Comment by ngentads** [comment]
I should also note that I just tried running `docker-compose build` and the npm install step of the Dockerfile fails with the same error, so I'm thinking/hoping this isn't an environment-specific issue. Furthermore, when I run `npm install` on master it finishes as expected.

**Comment by mgechev** [comment]
Yes, use master. That's the latest stable version and it uses Angular 4.x.x.

**Comment by teterovic** [comment]
have exactly the same issue after updating :/ There was probably an update in the configuration

**Comment by ScreeM92** [comment]
I have the same problem. Any update on this issue?
