### ISSUE TITLE
source-map-explorer command not working on windows

### ISSUE THREAD

**Issue by fr-esco** [mgechev/angular-seed#2022]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I run `npm run sme.prod` and, after `Finished 'sme.prod' after 59 s`, I get the error:
`source-map-explorer error: Error: Command failed: ./node_modules/.bin/source-map-explorer --html dist\prod\js\app.js dist\prod\js\app.js.map > sme\prod_2017-07-17T09_26_26_652Z.html`
because `"." is not a valid command`.

**Expected behavior**

On Windows, the correct line should be:
`.\node_modules\.bin\source-map-explorer.cmd  --html dist\prod\js\app.js dist\prod\js\app.js.map > sme\prod_2017-07-17T09_26_26_652Z.html`.

This one works as expected.

**Minimal reproduction of the problem with instructions**

`npm install`
`npm run sme.prod`

**What is the motivation / use case for changing the behavior?**

The executable "hard-coded" at `tools\utils\seed\sme.ts#L14` should be different for Windows.

**Please tell us about your environment:**

- Windows 10 Pro
- Node.js 6.11.1
- npm 3.10.10

* **Angular Seed Version:** `821d745847a378bce0a7746fb2be1b1123417370`

* **Node:** `node --version` = 6.11.1

**Comment by mgechev** [comment]
@fr-esco would you try the `sme` branch and tell me if this fixes the issue?

**Comment by fr-esco** [comment]
@mgechev It works, thank you.

**Comment by mgechev** [comment]
cool
