### ISSUE TITLE
Problems changing location of bootstrap files

### ISSUE THREAD

**Issue by pos1tron** [mgechev/angular-seed#2028]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

If I change the location of the bootstrap files and update the corresponding config properties, fetching of rxjs deps return 404. So far I can't figure it out! Hopefully it's something simple.
![image](https://user-images.githubusercontent.com/586635/28345983-df591d90-6bfb-11e7-8753-6d298f91b799.png)

**Expected behavior**

rxjs deps would be fetched as normal.

**Minimal reproduction of the problem with instructions**

Move `src/client/app/main.ts` to `src/client/main.ts` and `src/client/app/main-prod.ts` to `src/client/main-prod.ts`. Update imports to app module within each. Then update config:
```
  this.BOOTSTRAP_DIR = '';
  this.BOOTSTRAP_MODULE = `${this.BOOTSTRAP_DIR}main`;
  this.BOOTSTRAP_PROD_MODULE = `${this.BOOTSTRAP_DIR}main`;
  this.NG_FACTORY_FILE = 'main-prod';
  this.BOOTSTRAP_FACTORY_PROD_MODULE = `${this.BOOTSTRAP_DIR}main-prod`;
  this.SYSTEM_CONFIG.paths[this.BOOTSTRAP_MODULE] = `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`;
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `85c0a48 `

* **Node:** `node --version` = `6.10.0`

**Comment by mgechev** [comment]
the `SYSTEM_CONFIG_DEV` path needs to also include the following package configuration:

```js
packages: {
  '': { defaultExtension: 'js' },
  // Additional config
  rxjs: { defaultExtension: '' }
}
```
