### ISSUE TITLE
Additional Deps documentation confusing

### ISSUE THREAD

**Issue by renestalder** [mgechev/angular-seed#2029]
**I'm submitting a ...** 
```
[x ] bug report
[ ] feature request
[ ] support request 
```

..probably in the documentation!

**Current behavior**
Installed `npm angular-svg-icon --save` and added it as described in their config. This didn't work. So I saw the documentation of angular-seed to setup additional dependencies.
https://github.com/mgechev/angular-seed/wiki/Add-external-scripts-and-styles and tried to set it up, but that didn't work either. I always get a runtime error:
`http://localhost:5555/node_modules/angular-svg-icon.js 404 (Not Found)`

Then I found out, there are two pages in angular-seed describing how to set this up, and they differ:
* https://github.com/mgechev/angular-seed/wiki/Add-external-dependency
* https://github.com/mgechev/angular-seed/wiki/Add-external-scripts-and-styles

I've tried the second method with this code:
```
let additionalPackages: ExtendPackages[] = [{
            name: 'angular-svg-icon',
            // Path to the package's bundle
            path: 'node_modules/angular-svg-icon/index.js'
        }];

        this.addPackagesBundles(additionalPackages);
```

This didn't work either.

This time I get
`GET http://localhost:5555/node_modules/traceur.js 404 (Not Found)`.

**Expected behavior**
Only one Wiki page describing the correct implementation of an additional library. Additional, commented out configuration options to comment in and use.

**Minimal reproduction of the problem with instructions**
-

**What is the motivation / use case for changing the behavior?**
A better understanding of how this should work and should be used

**Please tell us about your environment:**
npm, PHPStorm

* **Angular Seed Version:**
Latest

**Comment by mgechev** [comment]
`GET http://localhost:5555/node_modules/traceur.js 404 (Not Found).` is caused by ES2015+ syntax in your JavaScript file that you're importing through SystemJS.

In case you're just getting started with the entire ecosystem I'd recommend you to use Angular CLI, which provides more abstracted way to manage your build.

**Comment by renestalder** [comment]
I didn't formulate this as support request. I clearly pointed out that I (or better, our team) don't understand the Wiki pages, which have two different descriptions of how use external dependencies and that the default project config could be improved in the way that it adds all possible options, commented out and described in the file that should be edited.
