### ISSUE TITLE
Multiple apps, would like a config setting and wiki rewrite :)

### ISSUE THREAD

**Issue by nuba** [mgechev/angular-seed#2030]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```
I'd like to volunteer to improve the wiki page on this and work with the project developers to get a visible and documented config setting for users to add additional apps.

Please check: https://github.com/mgechev/angular-seed/compare/master...nuba:multiple-apps-working?expand=0#diff-3fcb68aa9b42edfb0e375f00b412f553

I saw from an earlier commit that "automagically" adding additional apps was removed for being "too esoteric". So I'd like to ask what's the view on that, currently.

**Current behavior**
Adding additional apps requires tweaking config settings that are slightly buried and somewhat complex for newcomers to angular, systemjs and to this seed.

**Expected behavior**
I'd expect to follow the wiki page with no hassle and get additional apps going.

**What is the motivation / use case for changing the behavior?**
Users of this seed having an easier time when setting up additional apps.

**Please tell us about your environment:**
Linux, Fedora 25, node v6.11.1, JetBrains IDEA 2017.2, npm 3.10.10

* **Angular Seed Version:** `facd07577735ba61b50c2e7443db18415175aa04`

* **Node:** `node --version` = v6.11.1

BTW, thanks for this awesome starter! Keep rocking! :)

**Comment by mgechev** [comment]
@nuba looks pretty cool! The `project.config.ts` part doesn't modify the seed config which is great.

Would you add it as wiki entry?

I believe we can close this issue. Thanks for the suggestion again! Looks cool!

**Comment by aamir1995** [comment]
@mgechev I think this was never merged, @nuba could you please open a PR for this?
