### ISSUE TITLE
Isn't better to improve angular-cli ?

### ISSUE THREAD

**Issue by amineparis** [mgechev/angular-seed#2032]
I don't think the existence of such a project is a good idea. Isn't better and more flexible to concentrate contributions effort on angular-cli giving hight level, more customized commands other than dispersing effort on such projects !

**Comment by patrickmichalina** [comment]
This project existed before the CLI and offers more flexibility for customized builds. It helps many people.

**Comment by tarlepp** [comment]
angular-cli has some flaws atm, eg. you cannot use it with electron quite well.

**Comment by amineparis** [comment]
the problem with seed projects is that it forces people to use many pre-made choices that are not suited for every project. however a command in Angular-cli we can use it with default options, custom options, or even ignore it. adding the fact that the project will be freshly created. 

_What I hate about many open source projects that shouldn't exist is that contributors privilege their visibility over community benifits_

**Comment by mgechev** [comment]
Thank you for sharing your opinion. I will add link to Angular CLI in the readme. CLI is my personal recommendation for beginner and eventually intermediate use cases. Otherwise, you can choose between ejected CLI project or angular seed (in case you're not a webpack fen/prefer the seed setup).
