### ISSUE TITLE
Support 4.3 HttpClient from @angular/common/http

### ISSUE THREAD

**Issue by patrickmichalina** [mgechev/angular-seed#2033]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When importing the new HttpClient for Angular 4.3, SystemJS fails to find the module.

**Comment by maxklenk** [comment]
I had to adjust the SystemJS configuration to load the `common-http.umd.js` bundle right. It requires tslib so I included it too.

tools/config/project.config.ts
```Javascript
    let additionalPackages: ExtendPackages[] = [
      {
        name: '@angular/common/http',
        path: 'node_modules/@angular/common',
        packageMeta: {
          main: 'bundles/common-http.umd.js',
          defaultExtension: 'js'
        }
      },
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      },
    ]
```

**Comment by patrickmichalina** [comment]
Yea I had to do the same! Thanks

**Comment by mountpoint** [comment]
The same problem... I have added `'@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js'` in systemjs.config.js, but the next error throws: http://i.imgur.com/ydtjPaH.png

**Comment by Arekusei** [comment]
@maxklenk when i run `npm start` all ok. But sometimes when browsersync reloads a page, I getting this http://c2n.me/3MuEuhx

**Comment by maxklenk** [comment]
@Arekusei I don't have that problem and I thought that that SystemJS config is not read again while `npm start` is running. 
A "sometimes" problem most often has an asynchronous reason, perhaps `@angular/common` is read before `@angular/common/http` when it fails. Try to add them both in the right order in same list to check if that helps.

**Comment by mountpoint** [comment]
@Arekusei I have resolved the problem. Just use angular cli.
ng new project-name
And move your components to new project. It's all.

**Comment by Arekusei** [comment]
@maxklenk It didn't resolve problem.
@mountpoint If possible, I would prefer to use this seed, because it is flexible.
But if I have no other choice...

**Comment by mgechev** [comment]
@Arekusei if you're getting started with Angular or the JavaScript ecosystem I recommend you to use the CLI. In the worst case you will be coupled to webpack with ejected application.

**Comment by aGoncharuks** [comment]
I'm experiencing problems with adding new HttpClient to SystemJS in Angular seed. What I've done so far:
1. npm install tslib --save-dev
2. add these to packages to additionalPackages in tools/config/project.config.ts (as mentioned above in @maxklenk comment):
       {
        name: '@angular/common/http',
        path: 'node_modules/@angular/common',
        packageMeta: {
          main: 'bundles/common-http.umd.js',
          defaultExtension: 'js'
        }
      },
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      },
3. add HttpClientModule import to app.module.ts

And I get this error as result: http://imgur.com/a/ZoYYW

I did these steps afterwards:
- delete node modules folder
- npm cache clean
- npm install 

And still have the same error when run "npm start".
Angular version: 4.3.1

Any advice?

**Comment by madhavsharmaagra** [comment]
Adding  
      '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
      'tslib': 'npm:tslib/tslib.js',
in my systemjs.config file resolved the issue for me.

**Comment by hshiva** [comment]
Hi madhavsharmaagra it worked for me , Thanks

**Comment by kcuttam** [comment]
@madhavsharmaagra it worked for me... thanks!

**Comment by amir-alic** [comment]
Adding "tslib" worked! Thanks. 
.. I wonder how someone should figure that out, did not see any dependency to it or any info in error :(
