### ISSUE TITLE
Running tasks in vs code

### ISSUE THREAD

**Issue by ASalihov** [mgechev/angular-seed#2036]
I'm a very new in angular, gulp and so on. Can somebody help me to understand how gulp tasks are configured in this template and how can I run some using vs code. 
I found out that vs code runs tasks using tasks.json, and that in this project tasks lie in package.json but cannot understand how to make it all work. 
Any suggestions?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
