### ISSUE TITLE
Update the Lazy Loading example branch.

### ISSUE THREAD

**Issue by bbadc** [mgechev/angular-seed#2038]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Trying to implement lazy loading with rollup.aot.. builds but fails to display in browser.

TypeError: can't convert undefined to object  app.js:1:790013
Unhandled Promise rejection: "expected expression, got '<'
  Evaluating http://localhost:5555/@angular/core
  Evaluating http://localhost:5555/dist/tmp/app/main.js
  Loading dist/tmp/app/main.js" ; Zone: <root> ; Task: Promise.then ; Value: Error: expected expression, got '<'
  Evaluating http://localhost:5555/@angular/core
  Evaluating http://localhost:5555/dist/tmp/app/main.js
  Loading dist/tmp/app/main.js
Stack trace:
_t@http://localhost:5555/js/shims.js?1501280973574:1:97132
Ct/</<@http://localhost:5555/js/shims.js?1501280973574:1:103600
E@http://localhost:5555/js/shims.js?1501280973574:1:83769
x@http://localhost:5555/js/shims.js?1501280973574:1:83271
k@http://localhost:5555/js/shims.js?1501280973574:1:82270
_/<@http://localhost:5555/js/shims.js?1501280973574:1:82455
@http://localhost:5555/js/app.js?1501280973575:1:789755
E@http://localhost:5555/js/shims.js?1501280973574:1:83769
x@http://localhost:5555/js/shims.js?1501280973574:1:83271
k@http://localhost:5555/js/shims.js?1501280973574:1:82270
f.prototype[i.resolveInstantiate]/</<@http://localhost:5555/js/shims.js?1501280973574:1:109527
l</t.prototype.invoke@http://localhost:5555/js/shims.js?1501280973574:1:181596
s</r.prototype.run@http://localhost:5555/js/shims.js?1501280973574:1:176745
l/<@http://localhost:5555/js/shims.js?1501280973574:1:186394
l</t.prototype.invokeTask@http://localhost:5555/js/shims.js?1501280973574:1:182271
s</r.prototype.runTask@http://localhost:5555/js/shims.js?1501280973574:1:177439
o@http://localhost:5555/js/shims.js?1501280973574:1:174508
M/</<@http://localhost:5555/js/shims.js?1501280973574:1:40840
M/<@http://localhost:5555/js/shims.js?1501280973574:1:40710
l@http://localhost:5555/js/shims.js?1501280973574:1:45023
 _t@http://localhost:5555/js/shims.js?1501280973574:1:97132
Ct/</<@http://localhost:5555/js/shims.js?1501280973574:1:103600
E@http://localhost:5555/js/shims.js?1501280973574:1:83769
x@http://localhost:5555/js/shims.js?1501280973574:1:83271
k@http://localhost:5555/js/shims.js?1501280973574:1:82270
_/<@http://localhost:5555/js/shims.js?1501280973574:1:82455
@http://localhost:5555/js/app.js?1501280973575:1:789755
E@http://localhost:5555/js/shims.js?1501280973574:1:83769
x@http://localhost:5555/js/shims.js?1501280973574:1:83271
k@http://localhost:5555/js/shims.js?1501280973574:1:82270
f.prototype[i.resolveInstantiate]/</<@http://localhost:5555/js/shims.js?1501280973574:1:109527
l</t.prototype.invoke@http://localhost:5555/js/shims.js?1501280973574:1:181596
s</r.prototype.run@http://localhost:5555/js/shims.js?1501280973574:1:176745
l/<@http://localhost:5555/js/shims.js?1501280973574:1:186394
l</t.prototype.invokeTask@http://localhost:5555/js/shims.js?1501280973574:1:182271
s</r.prototype.runTask@http://localhost:5555/js/shims.js?1501280973574:1:177439
o@http://localhost:5555/js/shims.js?1501280973574:1:174508
M/</<@http://localhost:5555/js/shims.js?1501280973574:1:40840
M/<@http://localhost:5555/js/shims.js?1501280973574:1:40710
l@http://localhost:5555/js/shims.js?1501280973574:1:45023

**Expected behavior**
Should be able to use lazy loading

**Minimal reproduction of the problem with instructions**
Take the current rev of angular-seed, manually merge in the tweaks from the current lazy branch to keep all the 'new' stuff > npm run serve.prod || serve.prod.aot || serve.prod.rollup.aot.

**What is the motivation / use case for changing the behavior?**
Want to use lazy loading for a larger app

**Please tell us about your environment:**
OSX, this seed app

* **Angular Seed Version:** `aaaaf75`
see above

* **Node:** `node --version` = 7.5.0

**Comment by mgechev** [comment]
The lazy branch is not actively maintained. You can see a sample implementation of lazy loading there and adapt it to master.

**Comment by light24bulbs** [comment]
It would be great if you had it working on your machine if you could just package lock it, commit the lock, and be done.  It won't even run for anyone else because it doesn't have a package lock

**Comment by jigarpt** [comment]
Hi @mgechev ,
I am trying to build my project with lazy loading. I have referred "lazy" branch for the same. However, serve.prod fails at "build.lazy-bundles.app". 

It is not able to locate routing module file. See the logs below. So "about-us.module.js" is being picked up correctly; however "about-us-routing.module.js" is being picked up directly from "app" folder instead of "app/about-us/". 

![image](https://user-images.githubusercontent.com/28896871/33514804-1e904278-d780-11e7-854f-b1120476cb16.png)

It looks like I am missing some configuration parameters. I know that "lazy" branch is not maintained actively and support; however any help / direction here will help me to achieve lazy loading with prod build. 

Thanks in advance.
