### ISSUE TITLE
https://github.com/tjoskar/ng-lazyload-image install issue

### ISSUE THREAD

**Issue by itranga** [mgechev/angular-seed#2039]
I try to install ng-lazyload-image . I got the following issue 

localhost/:106 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1501726896719:2821:16)
    at

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
