### ISSUE TITLE
transpile.bundles.rollup.aot - Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Mrandles89** [mgechev/angular-seed#2041]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
We currently have a fairly large production app that we have been using the aot rollup for. I just tried to update to the latest seed project, and now when we run the build.prod.rollup.aot command and we are seeing the following error. The last time we synced up with the seed project was on April 20th. Is there a good way to debug this error to find out exactly what file/property is causing the issue?

[13:36:16] Finished 'build.bundles.app.rollup.aot' after 31 s
[13:36:17] Starting 'transpile.bundles.rollup.aot'...

C:\xxx\node_modules\typescript\lib\typescript.js
:9341
        if (node.type) {
                ^
TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\xxx\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (C:\xxx\node_modules\typescript\lib\typescript.js:41658:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\xxx\node_modules\typescript\lib\typescript.js:41954:29)
    at checkExpressionWorker (C:\xxx\node_modules\typescript\lib\typescript.js:42965:28)
    at checkExpression (C:\xxx\node_modules\typescript\lib\typescript.js:42904:42)
    at checkExpressionCached (C:\xxx\node_modules\typescript\lib\typescript.js:42785:38)
    at checkReturnStatement (C:\xxx\node_modules\typescript\lib\typescript.js:45424:54)
    at checkSourceElement (C:\xxx\node_modules\typescript\lib\typescript.js:46769:28)
    at Object.forEach (C:\xxx\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (C:\xxx\node_modules\typescript\lib\typescript.js:44569:16)

**Expected behavior**
AOT / rollup works as expected

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `c94e983`

* **Node:** `node --version` =v6.11.2

**Comment by rikup88** [comment]
Did you get this working? I have same problem, seed version also c94e983.

**Comment by rikup88** [comment]
For me, the problem was rxjs imports. They were like
`
import { Observable, Subject } from 'rxjs/Rx';
`
and when I changed them to
`
import { Observable } from 'rxjs/Observable';
import { Subject } from 'rxjs/Subject';
`
everything started working again.

**Comment by ZuSe** [comment]
We have similar issues but I think the root cause is the way the rollup build is configured
@mgechev correct me if I am wrong but for rollup es6 is used as build target.
Now if you are using umd bundles in your projects that work for serving dev or normal aot build you might expect build failures because they are not rdy to work with es6 as target.
Check here for an example: https://github.com/ng-bootstrap/ng-bootstrap/issues/1735
We are running in exactly the issue @Mrandles89 described with ng-boostrap and ng2-translate

Best
Patrick

**Comment by rikup88** [comment]
I have ngx-bootstrap and ngx-translate in my AoT project and they build with rollup without issues. I have configured SystemJS to use bundles while development but I don't use bundles when compiling AoT builds.

**Comment by ZuSe** [comment]
@rikup88 Can you share your config how to tell the seed to use bundles only for development? That would be exactly what we need.

**Comment by mgechev** [comment]
> @mgechev correct me if I am wrong but for rollup es6 is used as build target.

Yes, you're correct. The reason is because we want to apply tree-shaking.

**Comment by Mrandles89** [comment]
@rikup88 Fixing the rxjs imports seems to have fixed this issue, thanks a lot!

**Comment by negberts** [comment]
We are running into this issue too, but don't have any rxjs/Rx imports. We do include thirdparties like primeng and ngx-charts. Could the problem be in those packages?

**Comment by ZuSe** [comment]
@negberts 

For us its the same. Thus we have to stick with the the default aot build. A solution would be what @rikup88 mentioned as the rollup build breaks with some umd bundles imported (actually we really don't want to import them when targeting es6).

**Comment by negberts** [comment]
@ZuSe we rollbacked typescript to 2.3.4 which has no issues with the rollup build.

**Comment by negberts** [comment]
@ZuSe and @mgechev, what I don't get is the not using bundles thing during AOT build. Isn't the seed.config filled with Angular bundles? How would they not be used during AOT build?

**Comment by negberts** [comment]
What I also don't get is that if rollup is supposed to use ES6, why am I getting warnings on core.es5.js for instance?
