### ISSUE TITLE
Using "baseUrl" in tsconfig, with absolute imports, breaks build.prod

### ISSUE THREAD

**Issue by michelcve** [mgechev/angular-seed#2043]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Edit tsconfig.json, and add **"baseUrl": "."** in the **compilerOptions** section.
Now add an absolute import somewhere, e.g.: **import { CoreModule } from 'app/core/core.module';**.
Dev build works perfectly, however, building prod results in an error (in build.bundles.app):
**Error on fetch for app/core/core.module.js at file:///C:/data/myproject/node_modules/app/core/core.module.js**

**Expected behavior**

No problems building for prod.

**Minimal reproduction of the problem with instructions**

See current behaviour

**What is the motivation / use case for changing the behavior?**

Easier imports (without all the ../../../../)

**Please tell us about your environment:**

Windows, PHPStorm

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =
v6.2.1

**Comment by mgechev** [comment]
For this purpose you will have to update the production build files. Will be happy to merge a PR addressing this issue.

**Comment by michelcve** [comment]
I'm relatively new to web/Angular, but learning fast ;-) Though I have my doubts that I will be able to make a PR for this to be honest... The whole build system eludes me a.t.m. ;-)

Any pointers at where changes would need to be made?

**Comment by mgechev** [comment]
@michelcve sorry for the delayed response. Lets close this issue for now. It's nice to heave but it may break existing projects.

**Comment by michelcve** [comment]
Okay, if you would think that it would break existing projects, then I understand.
