### ISSUE TITLE
How to register a service worker?

### ISSUE THREAD

**Issue by avinashs95** [mgechev/angular-seed#2045]
I need help with integrating Firebase cloud messaging in my angular2 app. The firebase official documentation mentions the use of **firebase-messaging-sw.js.** I am getting error for the same thing as well that the file could not be found. 

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Firebase is initialised with my configuration in app module. I have a service file fcm.service.ts where permissions are requested and messages will be listened. After granting the permission for notification in my browser, I get the following error,

`Notification permission granted. 
Unable to get permission to notify. 
Failed to load resource: net::ERR_INVALID_RESPONSE                       /firebase-messaging-sw.js 
code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…t. browserErrorMessage: "Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script."...`
I searched for the error, some tell to include **firebase-messaging-sw.js.**. I am not sure where to do it.

**app.module.ts:**

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule, Routes } from '@angular/router';
import { Angulartics2Module, Angulartics2GoogleAnalytics } from 'angulartics2';
import { AppRoutingModule } from './app-routing.module';

//import { HeroesModule } from './heroes/heroes.module';
import { CommunityModule } from './community/community.module';
import { LearningModule } from './learning/learning.module';
import { AngularFireModule } from 'angularfire2';
import { AppComponent } from './app.component';
import { RedirectComponent } from './redirect.component';
import { FooterComponent } from './shared/footer/footer.component';
import { TourComponent } from './shared/tour/tour.component';
import { Config } from './shared/config/env.config';
@NgModule({
  declarations: [
    AppComponent,
    RedirectComponent,
    FooterComponent,
    TourComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    CommunityModule,
    LearningModule,
    AngularFireModule.initializeApp(Config.firebase),
    Angulartics2Module.forRoot([ Angulartics2GoogleAnalytics ]),
    AppRoutingModule,
  ],
  providers: [
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
`

**fcm.service.ts**:

```
import { Injectable, Inject }          from '@angular/core';
// import * as firebase from 'firebase/app'; // brings in app in typings
// import 'firebase/messaging'; // naked import to bring in feature
// import 'rxjs/add/operator/take';
import { FirebaseApp } from "angularfire2";
import * as firebase from 'firebase';

import { BehaviorSubject } from 'rxjs/BehaviorSubject';

@Injectable()
export class FCMService {
  // messaging : firebase.messaging.Messaging;
  private messaging: firebase.messaging.Messaging;

  currentMessage = new BehaviorSubject(null)
  constructor(@Inject(FirebaseApp) private firebaseApp: firebase.app.App) {
      console.log("constructor FCMService");
  }
  initialise() {

      console.log("initialise FCMService");
       this.messaging = firebase.messaging(this.firebaseApp);
    //   this.messaging = firebase.messaging();
      this.currentMessage = new BehaviorSubject(null)
  }
  getPermission() {
      this.messaging.requestPermission()
      .then(() => {
        console.log('Notification permission granted.');
        return this.messaging.getToken()
      })
      .then(token => {
        console.log("FCM token " + token);

        //this.updateToken(token)
      })
      .catch((err) => {
        console.log('Unable to get permission to notify.', err);
      });
    }
    receiveMessage() {
       this.messaging.onMessage((payload : any) => {
        console.log("Message received. ", payload);
        this.currentMessage.next(payload)
      });
    }
}

```

**test.component.ts:**

```
import {}....
export class TestComponent {
     private message : any;

     constructor(private fcmService : FCMService) {}

     ngOnInit(){
         this.fcmService.initialise()
         this.fcmService.getPermission()
         this.fcmService.receiveMessage()
         this.message = this.fcmService.currentMessage
    }
}
```

**Expected behavior**
Firebase messaging should get initialized properly after granting permission for notifications. firebase-messaging-sw.js should be in right place which will be used by firebase messaging.

**Minimal reproduction of the problem with instructions**
1. Follow this : [Integration with Firebase](https://github.com/mgechev/angular-seed/wiki/Integration-with-Firebase)
2. Then create new Service **fcm.service.ts** with above shown code
3. Call the method **getPermission()**  from another component.

**What is the motivation / use case for changing the behavior?**
Need to integrate FCM for real time notifications in my web app.

**Please tell us about your environment:**
OS: Windows 10, IDE: Atom

* **Node:** `node --version` = v6.11.0

**Comment by mgechev** [comment]
Most likely the issue is not setting the correct path to the `angularfire2` bundle in the config.

I'd recommend you to take a look at the SystemJS documentation and make sure you're setting the correct options.

I'll leave the issue open in order to update the wiki page.

**Comment by mgechev** [comment]
Lets close it due to lack of activity.
