### ISSUE TITLE
Some node packages not working with angular seed

### ISSUE THREAD

**Issue by rakeshtembhurne** [mgechev/angular-seed#2048]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I installed `sjcl` node package with `yarn add sjcl` and `yarn add @types/sjcl`. Loaded this library like `import * as sjcl from 'sjcl'`. When I try to use sjcl in component, it gives me this error: 
```
SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502265077241:2821:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502265077241:3620:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502265077241:1144:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502265077241:1091:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502265077241:999:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502265077241:1017:20
    at Object.eval (http://localhost:5555/app/home/home.component.js:14:12)
    at eval (http://localhost:5555/app/home/home.component.js:56:4)
    at eval (http://localhost:5555/app/home/home.component.js:57:3) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
```
The error is not generated when the module is loaded, but throws error trying to use it, even when doing `console.log(sjcl)`;

**Expected behavior**

I can use the same module in other projects and it works. I tried with simple NodeJS project, it works. I tried with new Angular project using Angular CLI, it works. I tried at least two different angular seed projects, it shows error with angular-seed projects. 

**Minimal reproduction of the problem with instructions**

Steps I followed:
- Created new angular-seed project
- Added packages with `yarn add sjcl @types/sjcl`
- Add line `import * as sjcl from 'sjcl';` on top of the file `home.component.ts`
- Added following lines in `ngOnInit()` function after `this.getNames();`:
```
    let theText = "my some secret text";
    console.log(sjcl);
    console.log("ORIGINAL", theText);
    console.log("TO BITS", sjcl.codec.base64url.toBits(theText).length);
    console.log("FROM BITS", sjcl.codec.base64url.fromBits(sjcl.codec.base64url.toBits(theText)));
```
Now the error is thrown.

**What is the motivation / use case for changing the behavior?**

I need to use this library to decrypt the information received from server. Converting this AWS Cognito based ionic app into Angular App: https://github.com/awslabs/aws-serverless-auth-reference-app

**Please tell us about your environment:**

Mac OS, Sublime Text 3, Yarn 0.27.5

* **Angular Seed Version:** `aaaaf75`

6f8a821

* **Node:** `node --version` = v8.1.4

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
