### ISSUE TITLE
Update to lastest Karma

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#2049]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

The seed currently locks down the version of Karma to 1.3.x, which is roughly a year old. I tried updating to the latest Karma, but ran into issues with the wildcard patterns in the Karma config. It looks like something changed regarding how patterns are handled in Karma 1.6 or 1.7.

I would take a stab at updating and issuing a pull request, but I'm honestly not sure how to address this pattern handling change.

Have you looked at this at all, Minko?

**Comment by brian428** [comment]
Any thoughts on this, Minko? I'm just getting a bit worried that the seed is now rather far out of sync with the current Karma.

**Comment by mgechev** [comment]
Hey @brian428 I can take a look at it today.

**Comment by brian428** [comment]
Awesome, I'll give it a try! Thanks.
