### ISSUE TITLE
remove about.routes.ts from readme

### ISSUE THREAD

**Issue by hkashlan** [mgechev/angular-seed#2050]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

I think this is simple 
current version of readme contains ***routes.ts** and we replaced with *routing.module.ts

Could you please update the readme :)

**Comment by mgechev** [comment]
Would you open a PR? Will be happy to get it merged!

**Comment by hkashlan** [comment]
I will Thank you :)

**Comment by hkashlan** [comment]
Hi is there a wiki page how to do a PR?
I did the change try to make a remote branch, but I am getting permission deneid 

`Pushing to https://github.com/mgechev/angular-seed.git
remote: Permission to mgechev/angular-seed.git denied to hkashlan.`

**Comment by mgechev** [comment]
Hey @hkashlan, you should push the change in your fork and after that open a PR in this repo.

Here's the [section you need](https://www.thinkful.com/learn/github-pull-request-tutorial/Time-to-Submit-Your-First-PR#Time-to-Submit-Your-First-PR).
