### ISSUE TITLE
Staging build in addition to production

### ISSUE THREAD

**Issue by Karasuni** [mgechev/angular-seed#2054]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

I'd be interested in having a 'staging' build. This would build the exact same code as the production build but with a different base and API variables. The easiest implementation would probably be to copy all the production tasks reading from a `stage.ts` file. However since the code is built the same as production it would also make sense if it was built during a production build task as a copy but with different variables injected.

Is this feature something you'd be interested in adding to the seed?

**Comment by mgechev** [comment]
I'd prefer to keep it out of the seed for now. It shouldn't be hard to add and developers who need it can implement it in their custom projects.
