### ISSUE TITLE
Prod Deployment Issue

### ISSUE THREAD

**Issue by mikelsulanjaku** [mgechev/angular-seed#2055]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
The project runs just fine in JIT mode. I can build and compile successfully for prod but when the app is served in prod I get the following error:

app.js?1502899920981:formatted:64608 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at r (app.js?1502899920981:formatted:64608)
    at app.js?1502899920981:formatted:65649
    at Object.<anonymous> (app.js?1502899920981:formatted:65715)
    at app.js?1502899920981:formatted:64600
    at p (app.js?1502899920981:formatted:154)
    at app.js?1502899920981:formatted:121
    at p (app.js?1502899920981:formatted:153)
    at app.js?1502899920981:formatted:121
    at app.js?1502899920981:formatted:85293

**Expected behavior**
Not have errors. 

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`
The very latest that is currently on git.

* **Node:** `node --version` =
v6.10.3

**Comment by mgechev** [comment]
For debugging the issue I'd need access to the source code, however, I suppose this is not a public project. Did you make any modifications in the build scripts of the seed?

**Comment by mikel1978** [comment]
I only updated the seed.config.ts file to add a few dependencies such as @ngx-translate, ngx-infinite-scroll. 

I also updated project.config.ts with:

 let additionalPackages: ExtendPackages[] = [
      {
        name: '@ngx-translate/core',
        // Path to the package's bundle
        path: 'node_modules/@ngx-translate/core/bundles/core.umd.js'
        //@ngx-translate/core': 'node_modules/@ngx-translate/core/bundles/core.umd.js',
      },
      {
        name: '@angular/common/http',
        path: 'node_modules/@angular/common',
        packageMeta: {
          main: 'bundles/common-http.umd.js',
          defaultExtension: 'js'
        }
      },
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      },
      { name: 'hammerjs', path: 'node_modules/hammerjs/hammer.js'}

The project is compiling just fine but it seems some dependency is missing after everything is bundled for prod.

Any idea?

**Comment by mikelsulanjaku** [comment]
Any luck? Also wanted to mention, we have a pretty heavy shared area. Knowing that, can you give me some directions on how you would proceed to debug this?

Thank you.

**Comment by mikelsulanjaku** [comment]
@mgechev , when I check the debugger console it is failing at this spot on app.js (see in bold):

function(i, o) {
        "object" == typeof n && void 0 !== r ? o(n, e("@angular/common"), e("@angular/core")) : t.registerDynamic("f", ["e", "c"], !1, function(t, e, n) {
            return "function" == typeof o ? o.call(e, e, t("e"), t("c")) : o
        })
    }(0, function(t, e, n) {
        "use strict";
        function r(t, e) {
            function n() {
                this.constructor = t
            }
            **M(t, e),**
            t.prototype = null === e ? Object.create(e) : (n.prototype = e.prototype,
            new n)
        }

**Comment by zladuric** [comment]
Fails with ngx-infinite-scroll for me too. I also got it to build, too, just can't repeat it now on my laptop (the successful build is on my desktop back home). Maybe something there is not set properly?

**Comment by mikelsulanjaku** [comment]
@zladuric Thank you my friend will try it without the infinite scroll. I am suspecting something is not beeing bundled properly. I will let you know if I manage to fix it.

**Comment by mikelsulanjaku** [comment]
In my project.config.ts I am adding additional packages. It appears one of them is causing the error:

 let additionalPackages: ExtendPackages[] = [
      {
        name: '@ngx-translate/core',
        // Path to the package's bundle
        path: 'node_modules/@ngx-translate/core/bundles/core.umd.js',
        //@ngx-translate/core': 'node_modules/@ngx-translate/core/bundles/core.umd.js',
      },
      **{
        name: '@angular/common/http',
        path: 'node_modules/@angular/common',
        packageMeta: {
          main: 'bundles/common-http.umd.js',
          defaultExtension: 'js'
        }
      },**
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      },
      { name: 'hammerjs', path: 'node_modules/hammerjs/hammer.js'},
      {
          name: '@angular/cdk',
          path: 'node_modules/@angular/cdk/bundles/cdk.umd.js'
      }
  ];
    this.addPackagesBundles(additionalPackages);

See the bolded area. That is what's failing and I need it in there to make the @ngx-translate work. 
@mgechev @zladuric  any idea how to fix this?

**Comment by mgechev** [comment]
@mikelsulanjaku thanks for filling the issue template.

> [X] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)


As mentioned there, for support requests you should use the correct channels - gitter or stackoverflow. Thanks for using the seed.
