### ISSUE TITLE
about ngx-bootstrap 

### ISSUE THREAD

**Issue by kimi009** [mgechev/angular-seed#2060]
1. npm install ngx-bootstrap bootstrap -save
2. modify project.config.ts  
    https://github.com/valor-software/ngx-bootstrap/blob/development/docs/getting-started/angular-seed.md
3. import { AlertModule } from 'ngx-bootstrap/alert';    in home.modules.ts
4    `<alert type="success">
              <strong>Well Done</strong>
    </alert>`

but npm start has errors 
![Uploading error.png…]()

**Comment by kimi009** [comment]
i hope fix it ,thanks

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
