### ISSUE TITLE
I want to leave Typescript comment under development

### ISSUE THREAD

**Issue by MSakamaki** [mgechev/angular-seed#2062]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I would like to use the [ignore function of istanbule](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md). So in build.js.dev I thought that it would be better to do removeComments: false.
(Because there is a comment delete function, it is troubled because coverage skip can not be performed. )

**Expected behavior**

There is problem.
When there are specific conditions in comments [gulp-template](https://github.com/sindresorhus/gulp-template) causes an error.

**Minimal reproduction of the problem with instructions**

```typescript
  constructor(private http: HttpService) {
    // this.API = `${http}op-api/box/kitting/config/:serial`;
  }
```
An error saying that `ReferenceError: http is not defined` as follows occurs.
If this is correct `this.http` will not raise an exception.

```sh

ReferenceError: http is not defined
    at eval (lodash.templateSources[51]:9:10)
    at DestroyableTransform._transform (/Users/names/sample/node_modules/gulp-template/index.js:21:40)
    at DestroyableTransform.Transform._read (/Users/names/sample/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Readable.read (/Users/names/sample/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:436:10)
    at flow (/Users/names/sample/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:806:34)
    at DestroyableTransform.<anonymous> (/Users/names/sample/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:676:7)
    at emitNone (events.js:86:13)

```

**What is the motivation / use case for changing the behavior?**

This function can be realized by adding `{ removeComments: false }` to the `makeTsProject()` argument of the target file `./tools/tasks/seed/build.js.dev.ts`.

```typescript
      // Only do a typed build every X builds, otherwise do a typeless build to speed things up
      if (typedBuildCounter < Config.TYPED_COMPILE_INTERVAL) {
        isFullCompile = false;
        tsProject = makeTsProject({
          isolatedModules: true,
          removeComments: false // <- Add
        });
        projectFiles = projectFiles.pipe(plugins.cached());
        util.log('Performing typeless TypeScript compile.');
      } else {
        tsProject = makeTsProject({
          removeComments: false // <- Add
        });
        projectFiles = merge(typings, projectFiles);
      }

```

If you have problems that arise by including `{removeComments: false}` in `build.js.dev.ts` besides the problem I understand please let me know.
Or, if it is difficult to include `{removeComments: false}` in build.js.dev, please tell me the smallest way to achieve this function in project extension.

**Please tell us about your environment:**

OS X, VsCode, NPM,

* **Angular Seed Version:** `6339052`

* **Node:** `node --version` = v7.10.0

**Comment by mgechev** [comment]
Dropping comments might not be solution to the problem, seems like a workaround.

In the perfect case we'd want to use different symbol for the template interpolation part of the build process. Then you'd not get such error.

Let's keep the issue open. Hopefully I'll find time to work on it soon.

**Comment by mgechev** [comment]
@MSakamaki I added an option to change the [interpolation config](https://github.com/mgechev/angular-seed/pull/2068/files#diff-3d695f3c2a28f15f1129d3a122b806d5R378). You can update it as part of your `project.config.ts` and you won't have to drop comments.
