### ISSUE TITLE
How to create multiple bundles inside prod app? 

### ISSUE THREAD

**Issue by diegofalciola** [mgechev/angular-seed#2072]
Hi all,
  Lets say I have an app with this format:

- Login module
- Home module
- About module

 Is there a way to split the login module and the "main" modules (Home/about) in two files, to reduce the app.js final size of the app?

Are there any other alternatives?

Thanks

**Comment by dalmarcogd** [comment]
Hi,
Yes, you can split the in two files, but you need export de modules, 

filename : mainModules.ts

export class AboutModule {
}

export class HomeModule {
}

When you want use, you need import
import {AboutModule, HomeModule} from './mainModules'

**Comment by dalmarcogd** [comment]
You want that the compilation of tsconfig generate the two files .js, but you have 3 files typescript?
