### ISSUE TITLE
running build.prod.aot -- --lang [your language] fails with file not found AND/OR Missing translations

### ISSUE THREAD

**Issue by mikejohanson** [mgechev/angular-seed#2073]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Currently, if you run `npm run i18n` the .xlf file gets placed in `dist\locale\messages.en.xlf`. From that you make your translations and place them (per step 4 in wiki: https://github.com/mgechev/angular-seed/wiki/Enabling-Angular-i18n-native) in the `src/client/assets/locale` directory.  When you run `npm run build.prod.aot -- -- lang en`, it is looking in the directory that is configured with `this.LOCALE_DEST` which is set to `dist\locale\`. This results in a couple different errors depending what you did. I.e File Not Found if you removed it or if you copied it out and did your translations somewhere else, it will tell you that all your translations are missing. 

**Expected behavior**
That running npm run build.prod.aot -- -- lang en will look in the directory that the wiki told me to put it in.

**Minimal reproduction of the problem with instructions**
See Current Behavior. As far as an attempt at a resolution I tried to just change the `this.LOCALE_DEST` variable in my project.config.ts file to something like `${this.PROD_DEST}/assets/locale`, and this will work for building AoT with the lang parameter. However, it breaks `npm run i18n` when you need to regenerate the .xlf file. Specifically it creates the.xlf file  then deletes it due to how the scripts are setup. 

So ultimately I think the best way to handle it is to create a new variable in the seed.config.ts that points to the `assets/locale` directory and update the `compile.ahead.prod.ts` file to use the new variable. Something like: 
```
 if (args.lang) {
    args['i18nFile'] = `${Config.TRANSLATED_DIR}/messages.${args.lang}.xlf`;
    args['locale'] = args.lang;
    args['i18nFormat'] = 'xlf';
  }
```

**What is the motivation / use case for changing the behavior?**
To be able to successfully build prod AoT with various languages on my build server. 

**Please tell us about your environment:**
Windows 10, VS Code

* **Angular Seed Version:** `aaaaf75`
Version: `d991b69`

* **Node:** `node --version` =
Node 8.4.0

**Comment by nhutcorp** [comment]
@mikejohanson This problem has fixed, please update seed.
