### ISSUE TITLE
Multiple browsers sync

### ISSUE THREAD

**Issue by fcollombon** [mgechev/angular-seed#2074]
**I'm submitting a ...**
```
npm start
```

**Current behavior**
When I run my project on multiples browsers, every events, session are shared. If I scroll, all navigators scrolls. I want to have separate session when nothing is shared.

**Expected behavior**
I want to have separate session where nothing is shared.

* **Node:** `node --version` = 3.10.10

**Comment by Sn3b** [comment]
What if you simply disable all sync options in browser sync?

**Comment by mgechev** [comment]
@Sn3b thanks for the response.

**Comment by fcollombon** [comment]
Can I have the code I have to comment? I don't really understand.

**Comment by Sn3b** [comment]
[seed.config.ts](https://github.com/mgechev/angular-seed/blob/master/tools/config/seed.config.ts) is the main config file, however, the idea is to not modify this file directly to allow for seed updates, instead, you will write your config in [project.config.ts](https://github.com/mgechev/angular-seed/blob/master/tools/config/project.config.ts), which you're not supposed to update whenever you update the parent seed.

Check out `seed.config.ts`, you will notice some config for browser sync that you can override in `project.config.ts`.

Alternatively, when you run `npm start`, you will notice a couple of URLs, the one with port 3001 (http://localhost:3001) is the one to the browser sync UI, navigate to it and go to the sync options and click disable all. The only problem with this method is that you'll have to do it every time you run `npm start`.
