### ISSUE TITLE
firebase.messaging() is not a function in Production build

### ISSUE THREAD

**Issue by avinashs95** [mgechev/angular-seed#2075]
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I'm using firebase cloud messaging in my project. It's working completely fine in dev build. But after production build using **sudo npm run build.prod -- --base /user/**, I'm getting an error that messaging() is not a function. But its actually present during dev build,
`app.js?1505206966369:98 TypeError: s.messaging is not a function
    at new e (app.js?1505206966369:96)
    at eInjector.get (/e/module.ngfactory.js:492)
    at eInjector.getInternal (/e/module.ngfactory.js:839)
    at eInjector.o.get (app.js?1505206966369:98)
    at proxyViewClass.e.injectorGet (app.js?1505206966369:99)
    at proxyViewClass.View_e_Host0.createInternal (/e/e/host.ngfactory.js:15)
    at proxyViewClass.e.createHostView (app.js?1505206966369:99)
    at e.create (app.js?1505206966369:98)
    at t.bootstrap (app.js?1505206966369:98)
    at app.js?1505206966369:97
    at Array.forEach (<anonymous>)
    at t._moduleDoBootstrap (app.js?1505206966369:97)
    at app.js?1505206966369:97
    at t.invoke (shims.js?1505206966365:5)
    at Object.onInvoke (app.js?1505206966369:100)`

**s.messaging() refers to firebase.messaging().**

**app.module.ts:**

`import * as firebase from 'firebase/app'; // brings in app in typings
import 'firebase/messaging';
firebase.initializeApp(Config.firebase);
console.log("firebase initialized App ", firebase);
@NgModule({
  declarations: [
  
  ],
  imports: [
  
  ],
  providers: [
      FCMService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**fcm.service.ts:**
import * as firebase from 'firebase/app'; // brings in app in typings
import 'firebase/messaging';
@Injectable()
export class FCMService {
    constructor() {
        console.log("FCMService constructor ");
        this.messaging = firebase.messaging();
        console.log("got firebase.messaging()");
    }
}

**In Dev Build:** firebase object is printed as,
```
Object {__esModule: true, initializeApp: function, app: function, Promise: function…}
INTERNAL:Object
Promise:function ZoneAwarePromise()
SDK_VERSION:"4.3.1"
app:function app(name)
apps:(...)
default:Object
initializeApp:function initializeApp(options, name)
messaging:function serviceNamespace(appArg)
__esModule:true
get apps:function getApps()
__proto__:Object
```
**In Production Build:** 
```
Firebase object is getting printed as: 
Promise:function ZoneAwarePromise()
SDK_VERSION:"4.3.1"
app:function app(name)
apps:(...)
default:Object
initializeApp:function initializeApp(options, name)
__esModule:true
get apps:function getApps()
__proto__:Object
```

messaging function is missing in it.

**Expected behavior**
Firebase messaging function should be accessible in production build. 

**Minimal reproduction of the problem with instructions**

1. npm install firebase.
2. Add entry in project.config.ts 
`{
        name: 'firebase',
        path: 'node_modules/firebase/',
        packageMeta: {
            main: 'firebase-browser.js',
            defaultExtension: 'js'
        }
    },`

3. Import firebase in app.module.ts and initialize it with firebase credentials as shown above.
4. Create new service fcm.service.ts where firebase.messaging() will be accessed.

**What is the motivation / use case for changing the behavior?**
Need to use firebase cloud messaging for real-time push notifications

**Please tell us about your environment:**
OS : Ubuntu 16.04
package manager : npm

* **Node:** `node --version` = 8.4.0

**Comment by mgechev** [comment]
Seems related to misconfigured production build.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by ALBlancoIV** [comment]
@avinashs24 

have you solved this? unfortunately, I'm having a similar error.
