### ISSUE TITLE
Multiple Applications thrown not found shared module error

### ISSUE THREAD

**Issue by VitalyVrublevskyy** [mgechev/angular-seed#2076]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Multiple Applications  thrown error:  Can't load shared.module 404 (Not Found) 
Can't start application (sub-project)

**Expected behavior**

Sub-App should start without errors

**Minimal reproduction of the problem with instructions**

Go strict wiki steps:
https://github.com/mgechev/angular-seed/wiki/Multiple-Applications
Start sub-app.

**What is the motivation / use case for changing the behavior?**

Some time ago I upgraded from angular2 into v4.3.x and related sub-applications was broken
**Please tell us about your environment:**

Mac Os, Webstorm
* **Angular Seed Version:** `d991b69e8fc6cc37f035a2ac2bb284423679a773`

latest: _d991b69e8fc6cc37f035a2ac2bb284423679a773_
* **Node:** `node --version` =
v7.4.0

**Comment by mgechev** [comment]
Probably this is caused my misconfiguration.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
