### ISSUE TITLE
httpclientmodule error 

### ISSUE THREAD

**Issue by gabhub1** [mgechev/angular-seed#2084]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

After importing HttpClientModule from - 
import { HttpClientModule } from '@ angular / common/http';   ( i had to put spaces because github collapsed text for some reason )
error pops up
Error trace:
localhost/:53 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:2821:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:3620:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:1144:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:1091:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:999:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:1017:20
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:1089:11)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:999:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506079427789:1017:20 Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**Expected behavior**

**Minimal reproduction of the problem with instructions**

download angular-seed, install, import httpclient and run  with npm start

* **Angular Seed Version:** 

Merge pull request `eace08d` , Sep 21, 2017

**Comment by mgechev** [comment]
@tobiaseisenschenk would you take a look at this?

**Comment by ahmadqarshi** [comment]
To fix this problem add the entry for `tslib` into `additionalPackages`  inside "tools/config/project.config.ts" file like below:

    let additionalPackages: ExtendPackages[] = [
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      },
    ]

**Comment by ZuSe** [comment]
this works for me 2

**Comment by mgechev** [comment]
@ahmadqarshi and @ZuSe thanks for the comments! Would you want to open a PR adding this in `seed.config.ts`?

**Comment by ahmadqarshi** [comment]
@mgechev I've done that in my local branch but when I try to push my local branch to the repository I am getting error 'remote: Permission to mgechev/angular-seed.git denied to ahmadqarshi.'.

**Comment by jigarpt** [comment]
@mgechev @ahmadqarshi 
I am still facing the same issue. unexpected token >. I am integrating ngx-translate module, while integrating ngx-translate; I am importing HttpClientModule and HttpClient. 

If I remove these modules (HttpClientModule and HttpClient) and switch back to Http; I don't see this error. 

Looking forward for your help. Thanks.

**Comment by ahmadqarshi** [comment]
@jigarpt Do you get the error message when you import the HttpClientModule only? Please remove the import for ngx-translate and just import HttpClientModule and see the behaviour.

**Comment by jigarpt** [comment]
@ahmadqarshi 
Thanks a lot for you prompt response. 

Your answer did the trick; actually I missed to include ngx-translate in project.config.ts -> additionalPackages. 

It works fine. 

Thanks
