### ISSUE TITLE
AOT Build when using date-fns

### ISSUE THREAD

**Issue by blaur** [mgechev/angular-seed#2086]
Hi everyone,

Hope you are well and might be able to assist me.

I'm struggling with my aot build after having included date-fns into my project (through angular-calendar). It all builds okay with the normal production build.

I'm including the functions in my code like this:
```
import {
  startOfDay,
  subDays,
  addDays,
  endOfMonth,
  isSameDay,
  isSameMonth,
  addWeeks,
  subWeeks,
  addMonths,
  subMonths,
  addHours
} from 'date-fns';
```

In my seed.config.ts I am including the lib in the following way (also as illustrated in other examples):
```
paths: {
    ....
   'date-fns': 'node_modules/date-fns/index.js',

packages: {
    ....
    'date-fns': {
        main: './index.js',
        defaultExtension: 'js'
      }

```

Everywhere I read and everyone I ask tells me the above is sufficient for them. But for some reason I am not able to compile it when used in the angular-seed here.

The error is:
` Error on fetch for date-fns/get_iso_week.js`

Obivously the mapping is for some reason not correct. Is there anything special I need to do for the angular-seed-advanced to make it right?

If I add the following line to my paths it can succesfully build aot and prod build, but then nothing that uses date-fns works anymore on runtime so I am but out of ideas:
'date-fns/*': 'node_modules/date-fns/index.js',

Any suggestions?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by jaggu07** [comment]
Hi @blaur can you the post codes for using date-fns
Thanks
