### ISSUE TITLE
css changes cause to refreshing page, can we apply css injection without browser refresh

### ISSUE THREAD

**Issue by gvolkan** [mgechev/angular-seed#2088]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
changing css cause to refreshing page, its very hard for big projects.

**Expected behavior**

ionic solve that issue but i couldnt found also hot module replacement not useful for me. 

thanks for help
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
No, applying CSS changes requires browser refresh as well.
