### ISSUE TITLE
npm start failed with the following errors.

### ISSUE THREAD

**Issue by sunkaraphani** [mgechev/angular-seed#2090]
**I'm submitting a ...**  (c
[npm-debug.log](https://github.com/mgechev/angular-seed/files/1335743/npm-debug.log)
[npm-debug.log](https://github.com/mgechev/angular-seed/files/1335745/npm-debug.log)

heck one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
Here's a related issue. You can follow the discussion there https://github.com/angular/angular/issues/6097.
