### ISSUE TITLE
zebkit.js run different on angular seed and  angular cli 

### ISSUE THREAD

**Issue by erata** [mgechev/angular-seed#2094]
**Current behavior**
zebkit.js gives error.

**Expected behavior**
zebkit.js run properly in angular 2 seed

**Minimal reproduction of the problem with instructions**
Third party script run different in angular 2 seed and angular cli ([zebkit.js](http://zebkit.org/ver/latest/zebkit.js))

**What is the motivation / use case for changing the behavior?**

i create a new angular 2 CLI project and test it with zebkit.js as  settings belove and it run properly

index.html ref:

> <script type="text/javascript" src="http://zebkit.org/ver/latest/zebkit.min.js"></script>

the code:
   ```
 console.warn(zebkit);
    zebkit.ui.config("theme", "light");

    zebkit.require("ui", function(ui) {
        var c = new ui.zCanvas(800,600);
        c.setBackground("yellow")
        console.log(zebkit);
        c.root.add(new ui.Button("Test").setBounds(30, 30, 200, 80));
        c.root.add(new ui.Button("Test2").setBounds(30, 130, 200, 80));
        console.log(c);
    });
```
zebkit js with angular-cli
![zebkit js with angular-cli](https://user-images.githubusercontent.com/3416873/31125711-f520f2a0-a851-11e7-9c8e-1053379ac2ff.PNG)

when i run the same code with same settings in angular 2 seed

network tab

![network tab](https://user-images.githubusercontent.com/3416873/31125724-037bd428-a852-11e7-9d6f-c75d1637ef14.PNG)

console error message:
zebkit err
![zebkit err](https://user-images.githubusercontent.com/3416873/31125752-2154c8ce-a852-11e7-9cd7-f6e98ac5bd23.PNG)

i also test sandbox version( http://zebkit.org/ver/sandbox/zebkit.min.js ) it run with angular cli but not angular seed. i got the same result above of them.

angular cli and angular seed results are different.

zebkit.js is made of different packages and although angular seed see the variable 

> declare var zebkit:any

it does not see sub package variable (e.g. zebkit.ui) which defined in require block -> zebkit.require("ui", function(ui) {..}

i also tried giving script reference as 

> {src: `${this.APP_SRC}/template/js/plugins/ui/zebkit/zebkit.min.js`, inject: true, vendor: false},

in project.config.ts but nothing change.

script does not run in seed properly.

**Please tell us about your environment:**
npm, intellij idea, angular 2

* **Angular Seed Version:** `aaaaf75`
last version or previous version of last.

* **Node:** `node --version` =6.9.1

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

If you're getting started with Angular I'd definitely recommend you to go with Angular CLI instead of the seed. The build in Angular seed is not that much encapsulated which requires deeper understanding of the underlying tooling.
