### ISSUE TITLE
template of html file other than index.html is not replaced

### ISSUE THREAD

**Issue by MSakamaki** [mgechev/angular-seed#2095]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

The templates of html and asset files below `src/client` are not replaced.

**Expected behavior**

It creates `sample.html` in the `src/client` folder and will not be converted like <% = APP_BASE%>.

should be converted to `/`.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I find it helpful to convert html files other than `src/client` index.html to templates.

I have confirmed that it can be modified by adding the following to the build task.

 + `tools/tasks/seed/build.assets.dev.ts`

```typescript

/**
 * Executes the build process, copying the assets located in `src/client` over to the appropriate
 * `dist/dev` directory.
 */
export =
  class BuildAssetsTask extends AssetsTask {
    run(done: any) {
      let paths: string[] = [
        join(Config.APP_SRC, '**'),
        join(Config.NPM_BASE, '@angular', 'service-worker', 'bundles', 'worker-basic.js'),
        '!' + join(Config.APP_SRC, '**', '*.ts'),
        '!' + join(Config.APP_SRC, '**', '*.scss'),
        '!' + join(Config.APP_SRC, '**', '*.sass')
            ].concat(Config.TEMP_FILES.map((p) => { return '!' + p; }));

      return gulp.src(paths)
        // adding to the build task 
        .pipe(
          plugins.template(
            new TemplateLocalsBuilder().withoutStringifiedEnvConfig().build(),
            Config.TEMPLATE_CONFIG
          )
        )
        .pipe(gulp.dest(Config.APP_DEST));
    }
  };
```

We anticipate that we need to fix the following files as well.

`tools/tasks/seed/build.assets.prod.ts`
`tools/tasks/seed/build.html_css.ts`

**Please tell us about your environment:**

OS X, VsCode, NPM,

* **Angular Seed Version:** `39a548fa168`

* **Node:** `node --version` =v7.10.0

**Comment by mgechev** [comment]
I think your proposal sounds good. Let's consider corner cases where we won't want to apply template interpolation for some of the selected files.

**Comment by mgechev** [comment]
@MSakamaki lets keep this out of the seed for now, unless anyone else requests this issue. Until then, you can override the task in the `project` directory.

Thank you for the suggestion and thank you for giving the project a try!
