### ISSUE TITLE
Material 2.0.0-beta.11 currently does not work in aot mode with this seed

### ISSUE THREAD

**Issue by jimmybillings** [mgechev/angular-seed#2096]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When installing Material beta.11 per these instructions (https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2) and running build.prod.aot it throws the following error during the build.bundles.app.aot task: 

Error on fetch for `@angular/material/core.js` at `file:///wazee-ui/node_modules/@angular/material/core.js`

If I add this path in the project.config.ts file then it falls over on the next material module, autocomplete I think. Something is wonky with the systemjs config I suspect, but as a note build.prod works fine.

**Expected behavior**
build.prod.aot should work without errors after following the instructions to install material.

**Minimal reproduction of the problem with instructions**
I have created a fork to reproduce this problem. Just clone, npm install and npm run serve.prod.aot
https://github.com/jimmybillings/angular-seed

**What is the motivation / use case for changing the behavior?**
We have several production applicaitons dependent on this seed and we would like to update material so we can take advantage of the new data table module.

**Please tell us about your environment:**
Mac OS Sierra 10.12.6
Visual Code (latest) 
Node 7.2 

* **Angular Seed Version:** `aaaaf75`

bec0b75291247a57be708747686a754eed343c00

* **Node:** `node --version` = 7.2

**Comment by jimmybillings** [comment]
Hey @mgechev, any clue on this or know anyone that might be able to help. I question whether Material has changed there packaging format/structure.

**Comment by jimmybillings** [comment]
I was able to get the build running with rollup 'build.prod.rollup.aot' but 'build.prod.aot' fails. Previously rollup would error on other external packages but that is now fixed. As a note, I can get the regular aot mode to work however I have to import material packages using the entire file path instead of just @angular/material. Unfortunately a couple of material modules: MatNativeDateModule & MatRippleModule need to be imported from @angular/material so without tree shaking this effectly causes material to be bundled twice.

**Comment by mgechev** [comment]
@jimmybillings thanks for the updates. I'll see what the issue is over the weekend. A lot of traveling this week, sorry for the delay.

**Comment by mgechev** [comment]
Just updated the wiki. Of course, there are less explicit/verbose options, or alternatively you can use the rollup bundler, this is just a sample, working option.

**Comment by aamir1995** [comment]
Hi @mgechev, I'm having the same issue with `build.prod.aot`, any possible fix for this problem?
