### ISSUE TITLE
Prod Rollup AOT - Unexpected key 'moduleName' found, expected one of: acorn, amd...

### ISSUE THREAD

**Issue by ravivit9** [mgechev/angular-seed#2097]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
npm run build.prod.rollup.aot
The above command ends with the following error.
```
[21:19:05] Finished 'compile.ahead.prod' after 5.44 s
[21:19:05] Starting 'build.js.prod.rollup.aot'...
[21:19:08] Finished 'build.js.prod.rollup.aot' after 3.16 s
[21:19:08] Starting 'build.bundles'...
[21:19:08] Finished 'build.bundles' after 42 ms
[21:19:08] Starting 'build.bundles.app.rollup.aot'...
options.entry is deprecated, use options.input
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (/Users/USER-A/dev/PROJ-NAME/node_modules/rollup/dist/rollup.js:171:11)
    at checkInputOptions (/Users/USER-A/dev/PROJ-NAME/node_modules/rollup/dist/rollup.js:10412:14)
    at Object.rollup (/Users/USER-A/dev/PROJ-NAME/node_modules/rollup/dist/rollup.js:10483:3)
    at module.exports (/Users/USER-A/dev/PROJ-NAME/tools/tasks/seed/build.bundles.app.rollup.aot.ts:36:10)
    at AnonTask.run (/Users/USER-A/dev/PROJ-NAME/tools/utils/seed/tasks_tools.ts:115:18)
    at Gulp.<anonymous> (/Users/USER-A/dev/PROJ-NAME/tools/utils/seed/tasks_tools.ts:144:27)
    at module.exports (/Users/USER-A/dev/PROJ-NAME/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/USER-A/dev/PROJ-NAME/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/USER-A/dev/PROJ-NAME/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/USER-A/dev/PROJ-NAME/node_modules/orchestrator/index.js:134:8)
```

**Expected behavior**
Should generate Tree-shaking with Rollup option production ready scripts.

**Minimal reproduction of the problem with instructions**
Updated repo and run the following command.
$npm run build.prod.rollup.aot

**What is the motivation / use case for changing the behavior?**
Would like to have the most performant code for production.

**Please tell us about your environment:**
Mac OS, Webstorm, npm, Firebase, etc

* **Angular Seed Version:** `eace08d`
Commit eace08d

* **Node:** `node --version` = v6.11.0

** Other package Info **
  "devDependencies": {
    "AT-angular/compiler-cli": "^4.4.4",
    "AT-angular/platform-server": "^4.4.4",
    "AT-compodoc/compodoc": "^1.0.1",
    "AT-types/async": "^2.0.44",
    "AT-types/browser-sync": "^0.0.36",
    "AT-types/express": "^4.0.37",
    "AT-types/gulp": "^4.0.4",
    "AT-types/gulp-filter": "^3.0.30",
    "AT-types/gulp-htmlmin": "^1.3.30",
    "AT-types/gulp-load-plugins": "^0.0.30",
    "AT-types/gulp-protractor": "^1.0.30",
    "AT-types/gulp-sass": "^0.0.30",
    "AT-types/gulp-util": "^3.0.31",
    "AT-types/jasmine": "^2.6.0",
    "AT-types/node": "^8.0.33",
    "AT-types/rimraf": "2.0.2",
    "AT-types/run-sequence": "^0.0.29",
    "AT-types/selenium-webdriver": "^3.0.7",
    "AT-types/systemjs": "^0.20.5",
    "AT-types/yargs": "^8.0.2",
    "async": "^2.5.0",
    "autoprefixer": "^7.1.5",
    "browser-sync": "^2.18.13",
    "codelyzer": "^3.2.1",
    "connect-history-api-fallback": "^1.3.0",
    "cssnano": "^3.10.0",
    "deep-extend": "^0.5.0",
    "event-stream": "^3.3.4",
    "express": "~4.16.1",
    "express-history-api-fallback": "^2.2.1",
    "gulp": "^3.9.1",
    "gulp-cached": "^1.1.1",
    "gulp-cheerio": "^0.6.2",
    "gulp-concat": "^2.6.1",
    "gulp-concat-css": "^2.3.0",
    "gulp-filter": "^5.0.1",
    "gulp-htmlmin": "^3.0.0",
    "gulp-inject": "^4.3.0",
    "gulp-inline-ng2-template": "^4.0.0",
    "gulp-load-plugins": "^1.5.0",
    "gulp-plumber": "~1.1.0",
    "gulp-postcss": "^7.0.0",
    "gulp-progeny": "^0.4.0",
    "gulp-protractor": "^4.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.6.1",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "2.6.1",
    "gulp-template": "^4.0.0",
    "gulp-tslint": "^8.1.2",
    "gulp-typescript": "~3.2.2",
    "gulp-uglify": "^3.0.0",
    "gulp-util": "^3.0.8",
    "gulp-watch": "^4.3.11",
    "is-ci": "^1.0.10",
    "isstream": "^0.1.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "~1.1.0",
    "karma-mocha-reporter": "^2.2.4",
    "karma-remap-istanbul": "^0.6.0",
    "merge-stream": "^1.0.1",
    "minimatch": "^3.0.4",
    "open": "0.0.5",
    "protractor": "^5.1.2",
    "remap-istanbul": "^0.9.5",
    "rimraf": "^2.6.2",
    "rollup": "^0.50.0",
    "rollup-plugin-commonjs": "^8.2.1",
    "rollup-plugin-includepaths": "0.2.2",
    "rollup-plugin-node-resolve": "^3.0.0",
    "run-sequence": "^2.2.0",
    "semver": "^5.4.1",
    "serve-static": "^1.13.1",
    "slash": "~1.0.0",
    "source-map-explorer": "^1.5.0",
    "supports-color": "^4.4.0",
    "systemjs-builder": "0.16.11",
    "systemjs-plugin-babel": "0.0.25",
    "temp": "^0.8.3",
    "tildify": "^1.2.0",
    "traceur": "^0.0.111",
    "ts-node": "^3.3.0",
    "tslint": "^5.7.0",
    "typescript": "^2.3.4",
    "walk": "^2.3.9",
    "yargs": "^9.0.1"
  },
  "dependencies": {
    "AT-angular/animations": "^4.4.4",
    "AT-angular/cdk": "^2.0.0-beta.12",
    "AT-angular/cli": "^1.4.5",
    "AT-angular/common": "^4.4.4",
    "AT-angular/compiler": "^4.4.4",
    "AT-angular/core": "^4.4.4",
    "AT-angular/forms": "^4.4.4",
    "AT-angular/http": "^4.4.4",
    "AT-angular/material": "^2.0.0-beta.12",
    "AT-angular/platform-browser": "^4.4.4",
    "AT-angular/platform-browser-dynamic": "^4.4.4",
    "AT-angular/router": "^4.4.4",
    "AT-angular/service-worker": "^1.0.0-beta.16",
    "AT-ngui/map": "^0.18.6",
    "AT-types/core-js": "^0.9.43",
    "AT-types/googlemaps": "^3.29.1",
    "angularfire2": "^5.0.0-rc.2",
    "bower": "^1.8.2",
    "core-js": "^2.5.1",
    "firebase": "^4.5.0",
    "geofire": "^4.1.2",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "ionic": "^3.12.0",
    "promise-polyfill": "^6.0.2",
    "rxjs": "^5.4.3",
    "systemjs": "0.20.19",
    "zone.js": "0.8.18"
  }

**Comment by ravivit9** [comment]
Since @ symbol was removed while saving the comment, I have replaced @ with "AT-".

**Comment by mgechev** [comment]
@ravivit9 see https://github.com/jvandemo/generator-angular2-library/issues/195 and let me know if it works for you.

**Comment by ravivit9** [comment]
@mgechev, 
Thanks for your input.  The above looks like to creating a new repo with the above generator.

But I am half way through my project integration.  Is there any way that I can make the following command to work.

$ npm run build.prod.rollup.aot

Thanks.

**Comment by mgechev** [comment]
@ravivit9 the link above points to an issue with sample solution for your problem. When I run:

```
$ npm run build.prod.rollup.aot
```

I got the production build without any errors, so quite likely, the issue is caused by your local setup.

As the issue template says explicitly, here's not the right place for support requests. Thanks for the understanding.

**Comment by ravivit9** [comment]
Thanks for your note. Sometimes it is a bit tricky to understand whether the issue is a bug or a local issue.

May be in future I will try to revert local npm updates and then try to run the suit. And moreover this is the first time I am running AOT using this seed.

Once again Thanks all of yours and teams  hardwork.
