### ISSUE TITLE
How to update, if it is inside sub folder?

### ISSUE THREAD

**Issue by AntonyBaasan** [mgechev/angular-seed#2102]
This might be a question more related to git.
> How to update?
> `git remote add upstream https://github.com/mgechev/angular-seed`
> `git pull upstream master`

Can anyone tell me what are the strategies for the case when the `angular-seed` project is one of the subfolders in my repository? Other   ##words, how to add remote upstream for subfolders?
My folder structure:
```
Project
--.git
--Frontend (this is the angular-seed repo, which I want to update time to time)
--Backend
--Utility
--...
```

**Comment by vyakymenko** [comment]
Hello @AntonyBaasan , you can use `Repository Merge Strategy`.

**Comment by vyakymenko** [comment]
@mgechev , I think we can close this issue.
