### ISSUE TITLE
localhost/:56 Error: (SystemJS) require is not defined 	ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Vishal07MobileDev** [mgechev/angular-seed#2104]
**localhost/:56 Error: (SystemJS) require is not defined
	ReferenceError: require is not define**d
	    at eval (http://localhost:5555/node_modules/traceur/src/node/api.js:22:12)
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/node_modules/traceur/src/node/api.js
	Error loading http://localhost:5555/node_modules/traceur/src/node/api.js
	Unable to load transpiler to transpile http://localhost:5555/node_modules/angularfire2/angularfire2.js
	Error loading http://localhost:5555/node_modules/angularfire2/angularfire2.js as "angularfire2" from http://localhost:5555/app/app.module.js
	    at eval (http://localhost:5555/node_modules/traceur/src/node/api.js:22:12)
	    at eval (<anonymous>)
	Evaluating http://localhost:5555/node_modules/traceur/src/node/api.js
	Error loading http://localhost:5555/node_modules/traceur/src/node/api.js
	Unable to load transpiler to transpile http://localhost:5555/node_modules/angularfire2/angularfire2.js
	Error loading http://localhost:5555/node_modules/angularfire2/angularfire2.js as "angularfire2" from http://localhost:5555/app/app.module.js "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by mgechev** [comment]
The build is passing. Looks like an environment specific issue.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
