### ISSUE TITLE
Add HttpClientTestingModule to seed.config.ts

### ISSUE THREAD

**Issue by emilio-simoes** [mgechev/angular-seed#2111]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Tests fail when using HttpClient because the HttpClientTestingModule is not loaded. 

**Expected behavior**
HttpClientTestingModule should be loaded when using the HttpClient.

**Minimal reproduction of the problem with instructions**
Change the NameListService to use the HttpClient.

**Solution**
Add the HttpClientTestingModule to the seed.config.ts.
This line is missing:

```
'@angular/common/http/testing':
        'node_modules/@angular/common/bundles/common-http-testing.umd.js',
```

**Comment by mgechev** [comment]
Sounds good! Would you open a PR with the suggested change?

**Comment by emilio-simoes** [comment]
Created the pull request: #2113

**Comment by mgechev** [comment]
Thanks!
