### ISSUE TITLE
Error 404 for rxjs/operators.js on running unit tests

### ISSUE THREAD

**Issue by ahmadqarshi** [mgechev/angular-seed#2112]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Initially I was getting the error "'build.bundle.rxjs' errored after 562 ms". After the fix made in [#2109](https://github.com/mgechev/angular-seed/pull/2109) that error disappeared but now when I run the unit tests, I get below error:

`    24 10 2017 13:15:34.764:WARN [web-server]: 404: /base/node_modules/rxjs/operators.js
    Chrome 61.0.3163 (Windows 10 0.0.0) ERROR: 'Error: Fetch error: 404 Not Found
        at http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?3c2cb0bc284db65a3e67e988
    cdb7175dc5362244:1475:13
        at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?5946249a94
    dbe0baef6f1ef0e76e9bb02decfe1a:392:26)
        at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?5946249a94dbe0baef6f1
    ef0e76e9bb02decfe1a:142:43)
        at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?5946249a94dbe0baef6f1ef0e76e9bb
    02decfe1a:873:57
        at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?594624
    9a94dbe0baef6f1ef0e76e9bb02decfe1a:425:31)
        at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?5946249a94dbe0bae
    f6f1ef0e76e9bb02decfe1a:192:47)
        at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?5946249a94
    dbe0baef6f1ef0e76e9bb02decfe1a:602:35)
        at <anonymous>'
`

**Expected behavior**

Should not get 404 for RxJs and unit tests should run without any issue.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
VS Code
* **Angular Seed Version:** `d6abbf96184babb00c3f32482edbcd0ddcb6e243`

* **Node:** `node --version` = 6.9.5

**Comment by ahmadqarshi** [comment]
I found that with "rxjs": "^5.5.0" in packages.json, it downloads version "5.5.2". I tried "rxjs": "5.4.3" and it started working again.

**Comment by mgechev** [comment]
@ahmadqarshi fix for `^5.0.0` should be updating the SystemJS configuration.

**Comment by ahmadqarshi** [comment]
@mgechev I tried that already but it didn't work for me. I also tried below pattern entry in `karma.conf.js` file under the `files` array but to no avail

`
{
        pattern: 'node_modules/rxjs/operators/**/*.js',
        included: false,
        watched: false
      }
`

**Comment by mikejohanson** [comment]
While not ideal...the hacky fix that worked for me was to copy the `rxjs/operators/index.js` to `rxjs/operators.js` and do a find and replace on `'./` with `'./operators/`. Fixes the build.prod issue as well. You could do something like: `sed -e "s/'\./'.\/operators/" <node_modules/rxjs/operators/index.js >node_modules/rxjs/operators.js`. Check out https://github.com/ReactiveX/rxjs/issues/2971 for a disussion on the issue
