### ISSUE TITLE
Is it possible to develop a web app? 

### ISSUE THREAD

**Issue by sunsgs** [mgechev/angular-seed#2117]
Hi all,
as per my question : Is it possible to develop a web app? 

If yes , i tried to run a build also in prod mod. I try to launch the index file but it not find the css and all the files (the app is not running).

Any help?

thanks

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
