### ISSUE TITLE
  Error on fetch for rxjs/operators.js during build.prod task

### ISSUE THREAD

**Issue by MichaelSemchenko** [mgechev/angular-seed#2118]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
npm run build.prod

**Minimal reproduction of the problem with instructions**
after update npm modules
"karma-mocha-reporter": "^2.2.0", -> 2.2.5
"rollup-plugin-commonjs": "^8.0.2" -> 8.2.5
"tslint": "^5.0.0", -> 5.8.0
@angular/** 4.4.4 -> 4.4.6
 **"rxjs": "^5.4.2 -> 5.52**

I get the follow issue after run npm run build.prod:

_Error in plugin 'run-sequence(build.bundles.app)'
Message:
Error on fetch for rxjs/operators.js at file:///d:/dev/OpenServer/domains/test/node_modules/rxjs/operators.js
        Loading rxjs/Rx.js
        Loading dist\tmp\app\services/http-wrapper.service.js
        Loading dist\tmp\app\sections/wrapper/wrapper.module.js
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        ENOENT: no such file or directory, open 'd:\dev\OpenServer\domains\test\node_modules\rxjs\operators.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'd:\dev\OpenServer\domains\test\node_modules\rxjs\operators.js'
Stack:
Error on fetch for rxjs/operators.js at file:///d:/dev/OpenServer/domains/test/node_modules/rxjs/operators.js
        Loading rxjs/Rx.js
        Loading dist\tmp\app\services/http-wrapper.service.js
        Loading dist\tmp\app\sections/wrapper/wrapper.module.js
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'd:\dev\OpenServer\domains\test\node_modules\rxjs\operators.js'_

It looks almost similar with https://github.com/mgechev/angular-seed/issues/2105

* **Node:** `node --version` = 8.1.2

**Comment by skolli853780** [comment]
I am seeing the same issue..

**Comment by skolli853780** [comment]
downgrading rxjs 5.5.2 to 5.5.0 fixed the problem

**Comment by aamir1995** [comment]
@skolli853780 downgrading the rxjs to 5.5.0 didn't solve the issue, I'm getting the following error.

`[22:00:54] Error on fetch for rxjs/operators.js at file:///D:/temp/my project/node_modules/rxjs/operators.js
        Loading @angular/flex-layout/bundles/flex-layout.umd.js
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'D:\temp\my project\node_modules\rxjs\operators.js'
[22:00:54] 'build.prod' errored after 27 s
[22:00:54] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for rxjs/operators.js at file:///D:/temp/my project/node_modules/rxjs/operators.js
        Loading @angular/flex-layout/bundles/flex-layout.umd.js
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        ENOENT: no such file or directory, open 'D:\temp\my project\node_modules\rxjs\operators.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'D:\temp\my project\node_modules\rxjs\operators.js'
Stack:
Error on fetch for rxjs/operators.js at file:///D:/temp/my project/node_modules/rxjs/operators.js
        Loading @angular/flex-layout/bundles/flex-layout.umd.js
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'D:\temp\my project\node_modules\rxjs\operators.js'`

**Comment by vyakymenko** [comment]
@MichaelSemchenko , is your issue resolved with `rxjs` ugrade ?

**Comment by MichaelSemchenko** [comment]
@vyakymenko , downgrading rxjs to 5.4.3 make it works

**Comment by MichaelSemchenko** [comment]
p.s. after updating I get the same error. But it was my bad: 
I used
`import { Observable } from 'rxjs/Rx';`
in my http interceptor instead of
`import { Observable } from 'rxjs/Observable'; `

May be will useful for somebody.

**Comment by anth0** [comment]
Getting the same issue with the latest version of master (4531659) after a fresh clone and install.
Starting the app works well but _npm run build.prod.aot_ returns 

```
[17:50:01] Starting 'build.bundles.app.aot'...
[17:50:04] 'build.bundles.app.aot' errored after 2.37 s
[17:50:04] Error on fetch for rxjs/operators.js at file:///Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js
        Loading @angular/core/bundles/core.umd.js
        Loading dist/tmp/app/main-prod.js
        Error: ENOENT: no such file or directory, open '/Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js'
[17:50:04] 'build.prod.aot' errored after 13 s
[17:50:04] Error in plugin "run-sequence(build.bundles.app.aot)"
Message:
    Error on fetch for rxjs/operators.js at file:///Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js
        Loading @angular/core/bundles/core.umd.js
        Loading dist/tmp/app/main-prod.js
        ENOENT: no such file or directory, open '/Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js'

Stack:
Error on fetch for rxjs/operators.js at file:///Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js
        Loading @angular/core/bundles/core.umd.js
        Loading dist/tmp/app/main-prod.js
        Error: ENOENT: no such file or directory, open '/Users/anth0/tmp/angular-seed/node_modules/rxjs/operators.js'
```

**Comment by styxiak** [comment]
I Have the same issue with build.prod. npm 6.01, nodejs 6.11.4.

**Comment by alfirin** [comment]
Getting the same issue over here too.

```
[17:30:36] Error on fetch for rxjs/operators.js at file:///home/.../dev/github/angular-seed/node_modules/rxjs/operators.js
        Loading dist/tmp/app/shared/name-list/name-list.service.js
        Loading dist/tmp/app/shared/shared.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/home/.../dev/github/angular-seed/node_modules/rxjs/operators.js'

```

**Comment by mattisebastian** [comment]
I have a similar problem to @alfirin 

```
Stack:
Error on fetch for rxjs/operators.js at file:///home/.../angular/node_modules/rxjs/operators.js
	Loading @angular/core/bundles/core.umd.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/home/.../angular/node_modules/rxjs/operators.js'

```

**Comment by Zahen** [comment]
I have the same error with the last release of seed when executing `npm run serve.prod`
Angular 6.0.1 
Rxjs: ^6.1.0

Error on fetch for rxjs/operators.js at file:///home/.../node_modules/rxjs/operators.js
        Loading @angular/core/bundles/core.umd.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/home/.../node_modules/rxjs/operators.js'

**Comment by redevill** [comment]
Hey folks,

For anyone else having this issue (when running build.prod) on the last release tag 6.0.1:
Error: Error on fetch for rxjs/operators.js at file:///Users/.../Development/MEANjs/TOK/nucleus/node_modules/rxjs/operators.js

In the file /tools/config/seed.config.ts there is a system_builder_config that provides path resolutions to systembuilder.js. For reasons unknown to me, packages spec for rxjs is not good enough.

However, if you include a path of this format for each referenced rxjs - e.g.:
'rxjs/operators': 'node_modules/rxjs/operators/index.js',
'rxjs/internal-compatibility': 'node_modules/rxjs/internal-compatibility/index.js',

...In the paths specification portion. This does allow systembuilder to find the referenced rxjs items.
