### ISSUE TITLE
npm run build.prod

### ISSUE THREAD

**Issue by AunR** [mgechev/angular-seed#2121]
We are facing issue with "npm run build.prod" , here is the exact error message:

> [10:33:44]

 Error on fetch for @angular/core/index.js at file:///opt/iehr-ui/node_modules/@angular/core/index.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/opt/iehr-ui/node_modules/@angular/core/index.js'
    at Error (native)
[10:33:44] 'build.prod' errored after 1.62 min
[10:33:44] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for @angular/core/index.js at file:///opt/iehr-ui/node_modules/@angular/core/index.js
        Loading dist/tmp/app/main.js
        ENOENT: no such file or directory, open '/opt/iehr-ui/node_modules/@angular/core/index.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/opt/iehr-ui/node_modules/@angular/core/index.js'
Stack:
Error on fetch for @angular/core/index.js at file:///opt/iehr-ui/node_modules/@angular/core/index.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/opt/iehr-ui/node_modules/@angular/core/index.js'
    at Error (native)

Here is screenshot of error:

![angular](https://user-images.githubusercontent.com/30073438/32272944-93b5bf96-bebd-11e7-8251-aadd83ad5ebb.png)

We have migrated the angular-seed2 project to angular 4 after that we are facing this build error. 

@mgechev or anyone else, kindly help on this error, Thanks!

**Comment by mgechev** [comment]
Dis you incorporate the latest changes in the seed's configuration? In such case, make sure you don't override it.

**Comment by mshahzad2017** [comment]
@mgechev i am also getting this same error same scenario i have updated old seed project based on angular 2 to angular 4 .Can you elaborate little more which configuration files needs to be updated and which files i need to protect from overridden. thanks.

**Comment by AunR** [comment]
@mgechev I haven't override it, can please advise how i should get the build to succeed?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
