### ISSUE TITLE
Update to angular version 5.0.0

### ISSUE THREAD

**Issue by arun-awnics** [mgechev/angular-seed#2122]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```
**What is the motivation / use case for changing the behavior?**

Angular latest release

**Comment by mgechev** [comment]
Yes, will do that probably after AngularConnect next week. Together with this feature, additional improvement is adding ngc's watch mode.

**Comment by lfarran** [comment]
I started a branch to upgrade to 5.0.0 at https://github.com/lfarran/angular-seed/tree/2122.  So far, this is missing the updates needed for AOT, but I'll keep looking into this.  It'd be great is somebody wanted to review the Service Worker config updates.  I didn't add the ServiceWorkModule into the app as I assumed that was beyond what's needed for the seed.

**Comment by mgechev** [comment]
@lfarran for the AoT related stuff take a look at `@angular/compiler-cli/ngtools2` as @vyakymenko pointed out.

**Comment by vyakymenko** [comment]
@lfarran , @mgechev , yeah only `@angular/compiler-cli/ngtools2` or we need to migrate to `ngc` with watcher.

**Comment by aamir1995** [comment]
Any update on Angular 5 support? Thanks. :)

**Comment by Karasuni** [comment]
@aamir1995 The angular-connect conference ran until yesterday. Might have to wait at least another day for the upgrade

**Comment by aamir1995** [comment]
We are using Material, ngrx and other libs in our project which is built using Angular-seed, We can't update these dependencies anymore because of they're now supporting only Angular V5, I'll really appreciate it if we can see any progress on this.

**Comment by mgechev** [comment]
Try https://github.com/mgechev/angular-seed/pull/2127

**Comment by lfarran** [comment]
@mgechev #2127 looks good to me.  

A trivial issue might need to be opened for updating the karma config:
START:
[20:02:03] Angular Service Worker config success
Failed to parse file: /angular-seed/dist/dev/ngsw-worker.js
11 11 2017 20:02:07.529:ERROR [preprocessor.coverage]: Line 353: Unexpected identifier
  at /angular-seed/dist/dev/ngsw-worker.js

**Comment by zackmcginnis** [comment]
@lfarran I'm running into the same "Unexpected identifier" issue.  Any progress on your end?
