### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by theblindprophet** [mgechev/angular-seed#2130]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Does NOT build with `npm run build.prod.aot` but works with `npm run start.deving`

**Expected behavior**

To build without error.

* **Angular Seed Version:** `8d78fa95`

* **Node:** `node --version` = v8.6.0

I have added this to my `project.config.ts`:

    this.addPackageBundles({
      name: 'firebase',
      path: 'node_modules/firebase',
      packageMeta: {
        main: 'firebase.js',
        defaultExtension: 'js'
      }
    });

    // Add AngularFire configuration to SystemJS
    this.addPackageBundles({
      name: 'angularfire2',
      path: 'node_modules/angularfire2/bundles',
      packageMeta: {
        main: 'angularfire2.umd.js',
        defaultExtension: 'js'
      }
    });

and when I run the project with `npm run start.deving` it works well. Firebase does work and it pulls results.

When I try and AOT build with `npm run build.prod.aot` it fails with this error:

    [21:38:32] Error on fetch for angularfire2 at file:///Users/jamie/Grasp/RRL/angular-seed/node_modules/angularfire2/bundles
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/app.module.ngfactory.js
	Loading dist/tmp/app/main-prod.js
	Error: EISDIR: illegal operation on a directory, read
    [21:38:32] 'build.prod.aot' errored after 17 s
    [21:38:32] Error in plugin 'run-sequence(build.bundles.app.aot)'
    Message:
    Error on fetch for angularfire2 at file:///Users/jamie/Grasp/RRL/angular-seed/node_modules/angularfire2/bundles
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/app.module.ngfactory.js
	Loading dist/tmp/app/main-prod.js
	EISDIR: illegal operation on a directory, read
    Details:
    originalErr: Error: EISDIR: illegal operation on a directory, read

Why would it work when running and not here? I understand the error but not sure how to fix.

**Comment by mgechev** [comment]
Just use:

```
// Add AngularFire configuration to SystemJS
this.addPackageBundles({
  name: 'angularfire2',
  path: 'node_modules/angularfire2/bundles/angularfire2.umd.js'
});
```
