### ISSUE TITLE
Live-reload broken after latest update

### ISSUE THREAD

**Issue by aamir1995** [mgechev/angular-seed#2132]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I have updated my project with latest angular V5, everything seems to be working fine except live reloading. Just curious what could be wrong with my config?

**Expected behavior**

Live reload should work as expected.

**Minimal reproduction of the problem with instructions**
Tried to reproduce the issue with a fresh clone, but it was working fine, looks like just issue with my config.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
Visual studio code
Node v8.9.1
NPM 5.5.1

* **Angular Seed Version:** `aaaaf75`
2e34161

* **Node:** `node --version` =

**Comment by vyakymenko** [comment]
Hi @aamir1995,
If issue can’t be reproduced on clean clone , how we can help you ? 

Maybe you can provide your fork with issue ?

**Comment by aamir1995** [comment]
Hi @vyakymenko thanks for the quick response, I just upgraded the project after a long time there were lots of conflicts when pulling the code from `Angular-seed`, So maybe there is something wrong with my config. can you give some hints where I can debug this issue?

**Comment by vyakymenko** [comment]
Hi @aamir1995 , one of the best solutions is to make a clean clone and copy your `app` files from old version to the new clone, then resolve dependencies issues if you have some in `project.config.ts` and migration issues if you use some deprecated stuff.

**Comment by aamir1995** [comment]
That's what I was thinking, Will move the app to a new clone. Thanks.

**Comment by vyakymenko** [comment]
@aamir1995 , I think we can close this issue.

**Comment by mgechev** [comment]
@vyakymenko thanks!
