### ISSUE TITLE
Use the Angular build optimizer in the minify task

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular-seed#2133]
https://www.npmjs.com/package/@angular-devkit/build-optimizer

**Comment by vyakymenko** [comment]
Hi @mgechev , 

I tested `build-optimizer` locally, and the diff was about `300 bytes`. I'm not sure that this is a powerfull optimization, please take a look at my tests:

<img width="1672" alt="with build optimizer" src="https://user-images.githubusercontent.com/7300673/33039883-2fd09d54-ce42-11e7-8482-70aac1928da7.png">


If it's ok I can continue to work on implementation.

**Comment by vyakymenko** [comment]
Hi @mgechev , 

After alot testing, with `compressed` and `non-compressed` files:

<img width="1669" alt="bo purify" src="https://user-images.githubusercontent.com/7300673/33043193-38c6ae70-ce4d-11e7-8c58-e6b144c5647d.png">

<img width="1669" alt="bo purify uglify" src="https://user-images.githubusercontent.com/7300673/33043281-8a486d60-ce4d-11e7-8383-073bd15c06d6.png">

I don't think that we need to implement this feature,
Output files will be large for few `bytes` with `build-optimizer`.

Thanks!

**Comment by mgechev** [comment]
@vyakymenko I dug into the implementation of the optimizer and found out that the bundles we have are actually not processed at all. Here's a PR I opened https://github.com/angular/devkit/pull/279.

After a further research I found a better way to implement this so the PR might not be necessary.

**Comment by vyakymenko** [comment]
@mgechev , ok, sounds good.
