### ISSUE TITLE
problem in angular2-localstorage library

### ISSUE THREAD

**Issue by vinayn143** [mgechev/angular-seed#2135]
how to resolve error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5560/node_modules/angular2-localstorage/LocalStorageEmitter.js for angular2-localstorage

**Comment by vyakymenko** [comment]
Hi @vinayn143 , how please verify how you add a dependency for this lib:
https://github.com/mgechev/angular-seed/wiki/Add-external-dependency

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
