### ISSUE TITLE
Drop @angular/http dependency

### ISSUE THREAD

**Issue by salemdar** [mgechev/angular-seed#2147]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**What is the motivation / use case for changing the behavior?**
`@angular/http` is deprecated with **v5.0.0**. We already refactored the service, but dependency is still there in the `package.json` and `seed.config.ts`. Shouldn't we simply ditch it completely?

**Comment by mgechev** [comment]
Would you open a PR with the change? I think dropping it from package.json and the config files is enough.

**Comment by salemdar** [comment]
Done.
