### ISSUE TITLE
output hashing in filename, for invalidat cache! Is possible include hash in filename build.prod?

### ISSUE THREAD

**Issue by lucrod1** [mgechev/angular-seed#2148]

**Comment by lucrod1** [comment]
ex: app.js to app.1asdasd123.js

**Comment by vyakymenko** [comment]
Hello @lucrod1 , yes this is possible, you need to update `tasks/seed/minify.bundles.ts` and add code that will generate hash in output that you need, then in `tasks/seed/build.index.prod.ts` modify `inject` of your files with hash.

**Comment by vyakymenko** [comment]
@lucrod1 , does your issue resolved?

**Comment by vyakymenko** [comment]
@mgechev , I think we can close this issue.
