### ISSUE TITLE
configure tslint to pick files from src folder

### ISSUE THREAD

**Issue by vijaygawade18** [mgechev/angular-seed#2150]

**Comment by vijaygawade18** [comment]
@mgechev How to configure tslint to pick files from src folder.

**Comment by vyakymenko** [comment]
Hello @vijaygawade18 , please look for lint config here `tools/config/seed.tslint.json`. And add additional folders that you need.

**Comment by vijaygawade18** [comment]
@vyakymenko Thanks for the help!
