### ISSUE TITLE
Accepting any PR's from TDE's with full working examples e.g. full application

### ISSUE THREAD

**Issue by lelong37** [mgechev/angular-seed#2153]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
n/a

**Expected behavior**
Have full blown samples  e.g. OData, Northwind, Grids with full CRUD, etc. , seed project can be modules, each module illustrating a real world dev use case

**Minimal reproduction of the problem with instructions**
n/a

**What is the motivation / use case for changing the behavior?**
No real world examples with full implementation

**Please tell us about your environment:**
Windows, etc.

* **Angular Seed Version:** `aaaaf75`
Current

* **Node:** `node --version` =
v6.11.2

Please let us know if we anyone or TDE's can start submitting PR's that illustrate real world dev use cases, thanks, something like this: e.g. https://github.com/OData/ODataSamples/tree/master/WebApi/v4

**Comment by mgechev** [comment]
How is this related to Angular Seed?
