### ISSUE TITLE
Missing TS peer dependency (for @angular/compiler-cli@5.0.1)

### ISSUE THREAD

**Issue by brian428** [mgechev/angular-seed#2161]
```
[X] bug report => search github for a similar issue or PR before submitting
```

Minko, after updating to the latest seed, I'm getting the following inscrutable error:
```
Error: Error: Debug Failure. False expression: import= for internal module references should be handled in an earlier transformer.
    at visitImportEqualsDeclaration (C:\Developer\Projects\BAH\medusa\ui\node_modules\typescript\lib\typescript.js:63184:22)
    at sourceElementVisitor (C:\Developer\Projects\BAH\medusa\ui\node_modules\typescript\lib\typescript.js:62959:28)
```

Obviously, this error from TypeScript tells me nothing. The only thing I can think (hope?) may be the cause is the current dependency mismatch between TS and angular/compiler-cli:

`npm ERR! peer dep missing: typescript@>=2.4.2 <2.5, required by @angular/compiler-cli@5.0.1`

I tried downgrading TS to 2.5.2 to see if that helps, but it appears there are other dependencies in the Seed that require TS 2.6+.

Were you aware of this mismatch? Any thoughts on whether the error I'm getting could be caused by this mismatch?

**Comment by vyakymenko** [comment]
@brian428 , it can be a peer dependency, which package require `@angular/compiler-cli` ?

**Comment by brian428** [comment]
It's a seed dependency (https://github.com/mgechev/angular-seed/blob/master/package.json#L54). However, the `compiler-cli` is usually a bit behind the current release version of `typescript`, so there are often version mismatches shown by npm, because the seed is usually on the latest Angular version and the latest TypeScript version.

**Comment by mgechev** [comment]
We'll fix this together with the version 6 update. I'm not sure if I'll manage to find the time this week.

**Comment by vyakymenko** [comment]
I hope that I'll have some time for an update to v.6 at this Weekend or Friday.

**Comment by vyakymenko** [comment]
I think is is resolved ?
