### ISSUE TITLE
Rollup fails with Unexpected token error while parsing json. (node_modules/libphonenumber-js/metadata.min.json)

### ISSUE THREAD

**Issue by ganeshsarathi** [mgechev/angular-seed#2163]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

While running <npm run build.prod.rollup.aot> , json file throws unexpected token. 
**Expected behavior**

There shouldn't be any parse error for json file. 
**Minimal reproduction of the problem with instructions**

Add ng2-validation, which has libphonenumber-js as dependency.  Use validation api in the code.  Then try to run rollup. 

**What is the motivation / use case for changing the behavior?**

Somehow json parsing is not working. 

**Please tell us about your environment:**

MacOS High Sierra, VSC, NPM
* **Angular Seed Version:** `aaaaf75`

5.0.1
* **Node:** `node --version` = v7.1.0

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
