### ISSUE TITLE
Run e2e tests with mock backend

### ISSUE THREAD

**Issue by salemdar** [mgechev/angular-seed#2167]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Expected behavior**
We should be able to run e2e tests with some fake data without communicating to backend at all.
I was thinking maybe we could use a combination of [json-server](https://github.com/typicode/json-server) and [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware). I am willing to create a PR for this if the feature request gets approved.

**Comment by mgechev** [comment]
This is a good suggestion, however, it'll provide value to only a limited number of users and require additional implementation and maintenance work.

Lets keep this out of the scope of the project for now.
