### ISSUE TITLE
Create CoreModule

### ISSUE THREAD

**Issue by salemdar** [mgechev/angular-seed#2168]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**What is the motivation / use case for changing the behavior?**
[Angular Style Guide](https://angular.io/guide/styleguide#core-feature-module) suggests creating a `CoreModule` and collecting application wide classes such as `NavbarComponent` in there. Since this repo follows the guide, I think we can create one and move `NavbarComponent` there.

**Comment by vyakymenko** [comment]
Hello @salemdar, I think that if we will create `core.module`, this will be for `ToolbarComponent` and `NavbarComponent` not only `NavbarComponent`.
