### ISSUE TITLE
Multiple anonymous defines

### ISSUE THREAD

**Issue by alivalinasab** [mgechev/angular-seed#2176]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When using jspdf npm start works fine however I get the following error when trying npm run build.prod under "build.bundles.app" step.

Error on dependency parsing for jspdf at file:///C:/Repo/Clinician.Web/node_modules/jspdf/dist/jspdf.min.js

Error: unknown multiple anonymous defines. 

**Expected behavior**
Be able to bundle using build.prod

**Minimal reproduction of the problem with instructions**

npm install jspdf --save

Add following to project.config.ts under ExtendPackages.

{
        name: 'jspdf',
        path: 'node_modules/jspdf/dist/jspdf.min.js'
}

I've also tried 

this.SYSTEM_BUILDER_CONFIG.paths.jspdf = 'node_modules/jspdf/dist/jspdf.min.js'; 

based on what you guys suggested under #1551 but I get the same error.

**What is the motivation / use case for changing the behavior?**
I'm trying to export HTML to pdf.

**Please tell us about your environment:**
Same on windows machines and servers 
npm version 3.10.10

Dependencies

"dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@angular/service-worker": "^1.0.0-beta.16",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.8",
    "@types/jquery": "^3.2.16",
    "@types/jspdf": "^1.1.31",
    "angular2-fontawesome": "^0.9.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.5.1",
    "intl": "^1.2.5",
    "jquery": "^3.2.1",
    "jspdf": "^1.3.5",
    "moment": "^2.19.1",
    "ng-pick-datetime": "^5.0.0-beta.12",
    "ng2-bootstrap": "^1.6.3",
    "ng2-toasty": "^4.0.3",
    "ngx-bootstrap": "^2.0.0-rc.0",
    "rxjs": "^5.5.0",
    "systemjs": "0.20.19",
    "zone.js": "0.8.18"
  }

* **Angular Seed Version:** `aaaaf75`
Latest

* **Node:** `node --version` =
v6.11.5

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by arraintxo** [comment]
Hi @alivalinasab,
did you find a solution for this? I'm having the same problem here.

**Comment by arraintxo** [comment]
Hi again,
I found the solution in https://github.com/InfomediaLtd/angular2-materialize/issues/115#issuecomment-254809673

Seems that jspdf needs the ``format: "global"`` attribute on the packageMeta configuration when adding it to additionalPackages. So this works for me:

```
{
        name: 'jspdf',
        packageMeta: {
            format: "global"
        },
        path: 'node_modules/jspdf/dist/jspdf.min.js',
}
```

**Comment by Tonemnguyen** [comment]
@arraintxo Did you have JSPDF added to project.config? I applied this, it allows my project to successfully run "npm run build.prod" but the actual function of the plugin fails.

**Comment by arraintxo** [comment]
I had to change the constructor call in my code to :

`
this.doc = new (jsPDF['jsPDF'])();
`

Not the cleanest solution, but works for me by now...

**Comment by sparachi** [comment]
@arraintxo  your suggestion helped on a different package 

let additionalPackages: ExtendPackages[] = [
      {
        name: 'auth0-js',
        path: 'node_modules/auth0-js',
        packageMeta: {
          format: 'global',
          main: 'build/auth0.js',
          defaultExtension: 'js'
        }
      }]

this.addPackagesBundles(additionalPackages);
