### ISSUE TITLE
Error with brand-new angula-seed and @auth0/angular-jwt

### ISSUE THREAD

**Issue by kzimny** [mgechev/angular-seed#2177]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I'm getting the following generic error on npm start within brand-new angular-seed project:

>  SyntaxError: Syntax error
   at evaluate (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:2818:8)
   at Anonymous function (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:3621:11)
   at dynamicExecute (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:1142:5)
   at doEvaluate (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:1089:7)
   at ensureEvaluate (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:997:3)
   at Anonymous function (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:1015:11)
   at Anonymous function (eval code:18:1)
   at Anonymous function (eval code:1:31)
   at eval code (eval code:1:2)
   at evaluate (http://localhost:5556/node_modules/systemjs/dist/system.src.js?1514481224019:2818:8) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**Expected behavior**
Being able to use `@auth0/angular-jwt` v1.0 package

**Minimal reproduction of the problem with instructions**
Install angular-seed and `@auth0/angular-jwt` package
```
git clone --depth 1 https://github.com/mgechev/angular-seed.git
cd angular-seed
npm install
yarn install
npm install @auth0/angular-jwt --save
```
open project.config.ts file and add the package dependency as follow:
```
import { ExtendPackages } from './seed.config.interfaces';
...
    const additionalPackages: ExtendPackages[] = [{
      name: '@auth0/angular-jwt',
      // Path to the package's bundle
      path: 'node_modules/@auth0/angular-jwt',
      packageMeta: {
        defaultExtension: 'js',
      }
    }];

    this.addPackagesBundles(additionalPackages);
```
after that modify the app.module.ts file as described in [branch v1.0 of @@auth0/angular-jwt package](https://github.com/auth0/angular2-jwt/tree/v1.0):
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

import { AboutModule } from './about/about.module';
import { HomeModule } from './home/home.module';
import { SharedModule } from './shared/shared.module';

import { JwtModule, JWT_OPTIONS } from '@auth0/angular-jwt';

export function jwtOptionsFactory() {
  return {
    tokenGetter: () => {
      return localStorage.get('access_token');
    }
  };
}


@NgModule({
  imports: [BrowserModule, HttpClientModule, AppRoutingModule, AboutModule, HomeModule, SharedModule.forRoot(),
      JwtModule.forRoot({
        jwtOptionsProvider: {
          provide: JWT_OPTIONS,
          useFactory: jwtOptionsFactory
        }
    })],
  declarations: [AppComponent],
  providers: [{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  }],
  bootstrap: [AppComponent]

})
export class AppModule { }
```
or try another configuration option:
```
import { JwtModule } from '@auth0/angular-jwt';
import { HttpClientModule } from '@angular/common/http';

@NgModule({
  bootstrap: [AppComponent],
  imports: [
    // ...
    HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return localStorage.getItem('access_token');
        }
      }
    })
  ]
})
export class AppModule {}
```
Go back to you command line and run the project with npm start.
You will get the following error message:
![image](https://user-images.githubusercontent.com/12007674/34418643-6e670438-ebff-11e7-85ff-2c9a54e0e291.png)

**What is the motivation / use case for changing the behavior?**
The master version of angular2-jwt package ([master branch](https://github.com/auth0/angular2-jwt/tree/master)) is going to be deprecated:
![image](https://user-images.githubusercontent.com/12007674/34418710-b3a454ec-ebff-11e7-93aa-ee01477ddbe7.png)

BTW: how to get the error stack instead of generic error message in the console?

I found a very similar question which has been already closed without useful answer #2079 

**Please tell us about your environment:**
* **Angular Seed Version:** `d7cd656`
* **Node:** `node --version` = 8.9.3
* **Angular version:** 5.0.1
* **OS:** Windows Professional
* **npm:** 4.6.1

**Comment by mgechev** [comment]
Set the `path` property of the object literal you pass as `ExtendPackages` to the `path` to the `angular-jwt` bundle.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by kzimny** [comment]
Thanks. In angular-seed project I changed the path to the bundle
```
    const additionalPackages: ExtendPackages[] = [{
      name: '@auth0/angular-jwt',
      // Path to the package's bundle
      path: 'node_modules/@auth0/angular-jwt',
       packageMeta: {
         defaultExtension: 'js',
           main: '/bundles/core.umd'
       }
    }];
```
and it works, but in my own project the path need to changed for some reason to:
```
    const additionalPackages: ExtendPackages[] = [{
      name: '@auth0/angular-jwt',
      path: 'node_modules/@auth0/angular-jwt/index.js'
    }];
```
