### ISSUE TITLE
Is there a way to generate new component files?

### ISSUE THREAD

**Issue by rncrtr** [mgechev/angular-seed#2181]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I couldn't find in the docs whether the best practice is to create files manually or if there is a way to generate the files for a new component. If there isn't a way, that's fine, it would be a good feature to add, but I am fine adding them manually. Just don't want to do it the hard way if you've already been brilliant. Thanks!

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac Sierra, NPM 5.6.0, Node 6.11.1

* **Angular Seed Version:** `aaaaf75`

78074ef
* **Node:** `node --version` =
Node 6.11.1

**Comment by mgechev** [comment]
No, Angular seed does not provide generators and that's not part of the roadmap. You can consider Angular CLI, if you need such features.

**Comment by rncrtr** [comment]
Well, Angular CLI isn't as flexible as I need (can't modify webpack, etc), that's why I love this project. Thanks for all the hard work.

**Comment by mgechev** [comment]
In Angular CLI, you can `ng --eject` and modify the webpack config afterwards.

**Comment by rncrtr** [comment]
It looks like they updated it to `ng eject` in the latest version of cli. Thanks.
