### ISSUE TITLE
routing issue in linux server

### ISSUE THREAD

**Issue by manojkukkala** [mgechev/angular-seed#2192]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I deployed my angular app in linux server. but routing is not working. 

**Expected behavior**
getting below errore
"Not Found

The requested URL /home/index was not found on this server.""

**What is the motivation / use case for changing the behavior?**
I followed all these steps https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-apache-2

still not working

**Please tell us about your environment:**
Linux with apache

* **Angular Seed Version:** `aaaaf75`
Angular 4 

* **Node:** `node --version` =
 6.11

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
