### ISSUE TITLE
Switch to Cypress for e2e testing

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular-seed#2196]
Consider switching to Cypress to improve the development experience and prevent random build failures because of glitches in the webdriver.

I believe the TypeScript support of Cypress is mature enough for this step. @bahmutov, any thoughts?

**Comment by bahmutov** [comment]
I think it is good enough to try it. I will make a pull request ;)

**Comment by mgechev** [comment]
Thanks! My guess is that we should be able to get rid of `e2e.ts`, `clean.e2e.ts`, `watch.e2e.ts`, and `build.js.e2e.ts`.
