### ISSUE TITLE
Unable to instantiate rxjs/Subject in production build

### ISSUE THREAD

**Issue by tsvetomir** [mgechev/angular-seed#2201]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Loading a component that imports 'rxjs/Subject' results in a run-time error:
> Error: Uncaught (in promise): TypeError: Subject is not a constructor

This only occurs when using `npm run serve.prod.aot`. Using `npm start` or `npm run serve.prod.rollup.aot` works fine.

**Expected behavior**
The dependencies should be resolved correctly.

**Minimal reproduction of the problem with instructions**
1. `git clone git@github.com:telerik/kendo-angular-quickstart-seed.git`
1. `cd kendo-angular-quickstart-see`
1. `git checkout seed-bug-report`
1. `npm install`
1. `npm run serve.prod.aot`
1. Click on the "KENDO UI" tab 

**What is the motivation / use case for changing the behavior?**
There are no obvious reasons why this shouldn't work. The fact that it works with Rollup and in Angular CLI projects suggests that this is a bundling issue.

The source code that throws the error looks like:
```
import { Subject } from "rxjs/Subject";

export abstract class ExpandStateService {
    public changes: Subject<{ dataItem: any, expand: boolean, index: number }> =
        new Subject<{ dataItem: any, expand: boolean, index: number }>();

    constructor(protected isInitiallyCollapsed: boolean) { }
}
```

**Please tell us about your environment:**
Linux, npm 5.6.0

* **Angular Seed Version:** `4947751289c3b15ba018323e64a4f27297faf13c`

* **Node:** `node --version` = 8.9.4

**Comment by mgechev** [comment]
It looks like SystemJS builder is messing things up because of incorrect configuration. An easy workaround would be to use rollup for bundling which will also produce a smaller & correct output:

```
npm run build.prod.rollup.aot
```

**Comment by tsvetomir** [comment]
Indeed it does, thanks!

I suspect the problem does have something to do with the way Rx is bundled in the seed. We're using the prebuilt [rxjs-system-bundle](https://www.npmjs.com/package/rxjs-system-bundle) with great success in other places - I might give it a shot here if I find the time.

**Comment by pvskasyrskiy** [comment]
Seems like AOT compiler uses field `"typings"` from `package.json` to resolve dependencies.
For example if this field has value:  `"typings": "dist/es/main.d.ts",`
compiler  will add to app.module.ngfactory.js references to DIST/ES folder **regardless** what we want to use in fact:
```
var i82 = require("@progress/kendo-angular-grid/dist/es/filtering/shared-filtering.module");
var i83 = require("@progress/kendo-angular-grid/dist/es/filtering/cell/row-filtering.module");
```
Therefore SystemJS builder will process kendo as ES6 ignoring configuration and `kendo` module will be registered with System.register instead of System.registerDynamic.

**Comment by tsvetomir** [comment]
Thanks @pvskasyrskiy, this is the case indeed. A small correction - the AoT compiler builds references based on where the .json metadata files are. In our case they're next to the .d.ts files.

We're working on fixing this by shipping a flat metadata file. This way the references always point to the root package, allowing the bundler to resolve the module type correctly:

```js
var i82 = require("@progress/kendo-angular-grid");
```

**Comment by tsvetomir** [comment]
Works fine with the latest Kendo UI package versions.
