### ISSUE TITLE
Seed.Config.ts Changes

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular-seed#2223]
Hi Guys,

We need to incorporate the angular-seed project in another web application.
So we have decided to download angular-seed and place it at the root: /angular-seed-project/etc...

Now, in Seed.Config.ts there are the paths for the node_modules, which is in the angualr-seed-project folder. Now, since this is in our project root, we need that change that path to /angualr-seed-project/node_modules/etc...

Are there any practical solution on how I can do that instead of modifying the seed.config.ts itself?

Thank you in advance

**Comment by mgechev** [comment]
All parameters defined in `seed.config.ts` can be overridden in `project.config.ts`.
