### ISSUE TITLE
Aot build throws error with Material

### ISSUE THREAD

**Issue by achervatiuk-softheme** [mgechev/angular-seed#2231]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Used guide to integrating Material
https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2
Aot build will trow error if we import some modules from "angular/material".
We have investigated that bundles require modules like that "../../node_modules/angular/material/{name}/typings/index.ngFactory.js", and these modules require modules like "angular/material/{name}", etc. So it is required both "angular/material" and another modules like "angular/material/{name}".

Build throws error that, for example, "../../node_modules/angular/material/core/core.js" couldn't be fetched and so forth.

**Minimal reproduction of the problem with instructions**
npm run serve.prod.aot

**Please tell us about your environment:**
npm: `3.10.10`,
os: `windows 7`,
node: `6.11.0`

* **Angular Seed Version:** `79e92bd`

* **Node:** `node --version` = `v6.11.0`

**Comment by vyakymenko** [comment]
@achervatiuk-softheme , please integrate `Angular Material` using this [tutorial](https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2)

**Comment by vyakymenko** [comment]
@mgechev , I think we can close this issue.

**Comment by pbazurin-softheme** [comment]
The tutorial works for simple jit or dev builds. But aot build fails (npm run serve.prod.aot).
Please update the integration steps or mention this "aot limitation" in the integration tutorial.
