### ISSUE TITLE
how load same library for multiple apps in angular 4 build?

### ISSUE THREAD

**Issue by molikh** [mgechev/angular-seed#2253]
[X] Question.
I already asked this question in stackoverflow, But I though maybe it could be helpful if I ask here too.

how load same library for multiple apps in angular 4 build?

I have 5 different app for same project. I'm trying to use same library for all 5 , so client doesn't needed to load same libraries in all app's. I know if libraries be in same file(url), browser will use cached library. But problem is how get that library file out of angular build process. Any tips would be helpful.

Tnx!

[https://stackoverflow.com/questions/49953615/how-load-same-library-for-multiple-apps-in-angular-4-build](url)

**Comment by mgechev** [comment]
Yes, stackoverflow was the right place for this discussion. Closing the issue here.
