### ISSUE TITLE
Allow Angular to run in Webworker mode

### ISSUE THREAD

**Issue by iota-seed-vault** [mgechev/angular-seed#2254]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Angular runs in the main thread of the browser

**Expected behavior**
Is it possible to make Angular run in a Webworker with this seed? The changes required to the ts files are minimal (see https://blog.angularindepth.com/angular-with-web-workers-step-by-step-dc11d5872135) but the changes in the build system are not so easy for me to grasp. Is it possible to add a Webworker build mode? Most interesting for me would be a webworker build mode for "npm run" (dev mode) and the "rollup aot prod build"

**What is the motivation / use case for changing the behavior?**
Less laggy UI for complex applications

**Please tell us about your environment:**
Windows + Sublime

* **Angular Seed Version:** `aaaaf75`t

* **Node:** `node --version` =

**Comment by mgechev** [comment]
Hey, thanks for the interest. There are a couple of tutorials out there for how you can bootstrap your application and run it into a web worker.

Since the WW support in Angular is still not finalized, I plan to keep it outside the starter.
