### ISSUE TITLE
Error After Importing angular-auth-oidc-client in appModule

### ISSUE THREAD

**Issue by flakronkadriu** [mgechev/angular-seed#2264]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I installed the angular-auth-oidc-client package from @damienbod https://github.com/damienbod/angular-auth-oidc-client and when i add **AuthModule.forRoot()** in  imports it gives me exception of: 

**SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:60000/node_modules/systemjs/dist/system.src.js?1525789356291:2802:18)
    at http://localhost:60000/node_modules/systemjs/dist/system.src.js?1525789356291:3607:23
    at dynamicExecute (http://localhost:60000/node_modules/systemjs/dist/system.src.js?1525789356291:1138:28)
    at doEvaluate (http://localhost:60000/node_modules/systemjs/dist/system.src.js?1525789356291:1085:15)
    at ensureEvaluate (http://localhost:60000/node_modules/systemjs/dist/system.src.js?1525789356291:993:15)
    at http://localhost:60000/node_modules/systemjs/dist/system.src.js?1525789356291:1011:22
    at Object.eval (http://localhost:60000/app/app.module.js:20:34)
    at eval (http://localhost:60000/app/app.module.js:45:4)
    at eval (http://localhost:60000/app/app.module.js:46:3) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues**

I also tried adding the whole code from the documentation of the angular-auth-oidc-client but still not working.
I tried adding the AuthModule to another Module for example Home Module or About but it;s not working i followed some discussion from other issues and tried to fix it but it's not working i added 
this to project.config.ts at additionalPackages:
const additionalPackages: ExtendPackages[] = [
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      },
      {
        name: 'angular-auth-oidc-client',
        // Path to the package's bundle
        path: 'node_modules/angular-auth-oidc-client/bundles/angular-auth-oidc-client.umd.js'
      }
    ];
but still not working i can't find any solutions ! Can somebody help me with this error. 

The behavior will be AutoLogin redirecting to IdentityServer and back. I already implemented this to another project where i don't use angular seed from @mgechev and it works perfectly fine but when i try to implement the same code from the other project into this project it's not working. 

"author": "Minko Gechev <mgechev>",
  "license": "MIT",
  "engines": {
    "node": ">=6.9.0",
    "npm": ">=3.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.2.9",
    "@angular/language-service": "^5.2.9",

**Comment by mgechev** [comment]
Sorry, but I cannot read through the issue. Please, use the specified template. Also, in case of support requests, please, use gitter or any other medium.

If you're just getting started with Angular and you don't need custom/advanced build, consider Angular CLI.
