### ISSUE TITLE
Cannot run the seed with error with rxjs error loading.

### ISSUE THREAD

**Issue by hungnguyenhee** [mgechev/angular-seed#2277]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Current behavior**
Just follow the steps to install the seed. Npm start successfully but error on browser error and the site cannot run.
Error in console log: 
Unexpected token - Evaluating http://localhost:5555/rxjs
Cause: "http://localhost:5555/rxjs" is not found

**Expected behavior**
Web should run as normal

**Minimal reproduction of the problem with instructions**
Just follow the steps in How to Start.

**Please tell us about your environment:**
Windows 10, Node v6.11.4, NPM v3.10.10, Browser Chrome

* **Angular Seed Version:** `37e5cc1`

* **Node:** `node --version` =6.11.4

**Comment by vyakymenko** [comment]
@hungnguyenhee , please download new LTS [node.js](https://nodejs.org/dist/v8.11.2/node-v8.11.2-x64.msi) and install it on your PC.

**Comment by tolgaonbay** [comment]
@vyakymenko hi,

I have a similar problem. I can run it with `npm start` without any problem, but `npm run build.prod` produces the rxjs error as below. Node version is not the LTS, but the latest (10.3.0). Do we need to install LTS version?

**Environment** 
macOS High Sierra, Node 10.3.0, npm 6.1.0

**Error**
```
[23:12:21] Error on fetch for rxjs/operators.js at file:///Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js
        Loading dist/tmp/app/shared/name-list/name-list.service.js
        Loading dist/tmp/app/shared/shared.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js'
[23:12:21] 'build.prod' errored after 19 s
[23:12:21] Error in plugin "run-sequence(build.bundles.app)"
Message:
    Error on fetch for rxjs/operators.js at file:///Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js
        Loading dist/tmp/app/shared/name-list/name-list.service.js
        Loading dist/tmp/app/shared/shared.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        ENOENT: no such file or directory, open '/Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js'

Stack:
Error on fetch for rxjs/operators.js at file:///Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js
        Loading dist/tmp/app/shared/name-list/name-list.service.js
        Loading dist/tmp/app/shared/shared.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open '/Users/user/Workspace/ruby/sampleproject/client/node_modules/rxjs/operators.js'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 build.prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-05-31T20_12_30_209Z-debug.log
```

**Comment by alfirin** [comment]
Exactly same problem over here.
Everything is ok in dev and when I build in prod, it's not working as well.

**Comment by jt3po** [comment]
Any movement on this? I'm having the exact same issue as the original reporter. 

Steps to reproduce: 

Clone seed project.

npm install

npm run serve.dev

Console error : 

rror: Unexpected token <
  Evaluating http://localhost:5555/rxjs
  Evaluating http://localhost:5555/app/main.js
  Loading app/main
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)
    at instantiate.js:394
    at dynamicExecute (register-loader.js:665)
    at doEvaluate (register-loader.js:612)
    at ensureEvaluate (register-loader.js:520)
    at register-loader.js:538
    at doEvaluate (register-loader.js:610)
    at ensureEvaluate (register-loader.js:520)
    at register-loader.js:538 "Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues"
(anonymous) @ (index):60

OS: Windows 7
Node: 6.10.2
npm: 3.10.10

**Comment by vyakymenko** [comment]
Not yet, still busy with the main job, will create PR later. For now please use `$ npm run build.prod.rollup.aot`.

**Comment by jt3po** [comment]
I'm trying to run the dev server though. How does building the prod bundle help?

**Comment by vyakymenko** [comment]
@jt3po , to run development mode use`$ npm start` it will run automatically in development mode.

**Comment by jt3po** [comment]
Right and according to both my and the original reporter's steps to reproduce, this error occurs when running serve.dev

**Comment by vyakymenko** [comment]
@jt3po , this will be fixed later in this ticket: https://github.com/mgechev/angular-seed/issues/2288

**Comment by jt3po** [comment]
Updating to the latest node and npm solved the serve.dev issue.

If this project requires versions higher than what's advertised on the README:

"Note that this seed project requires node v4.x.x or higher and npm 2.14.7 but in order to be able to take advantage of the complete functionality we strongly recommend node >=v6.5.0 and npm >=3.10.3."

then the README should be updated.
