### ISSUE TITLE
error TS2307: Cannot find module 'vectormap-data/world.js'

### ISSUE THREAD

**Issue by praveen-nuovo** [mgechev/angular-seed#2278]
I am using devextreme maps, Here I have to integrate those into my angular-seed app.

But I am getting the error,

`error TS2307: Cannot find module 'vectormap-data/world.js'`
I made all configurations But still getting that error.

The things I want to be integrated in my App
[https://js.devexpress.com/Demos/WidgetsGallery/Demo/VectorMap/Overview/Angular/Light/](url)

in seed.config.ts ->
'devextreme': 'node_modules/devextreme',
'vectormap-data': 'node_modules/devextreme/dist/js/vectormap-data',
'devextreme-angular': 'node_modules/devextreme-angular',

Please help me on this.

Thank You

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by mgechev** [comment]
Btw, if you don't mind a more encapsulated build, you can try Angular CLI. It fulfills most requirements for traditional apps.
