### ISSUE TITLE
styles imported from node modules not works

### ISSUE THREAD

**Issue by MichaelSemchenko** [mgechev/angular-seed#2279]
**I'm submitting a bug report**

**Current behavior**
Impossible to import scss files from node modules.
When I try to import styles from one of the node modules I get follow error:
```
Error in plugin 'sass'
Message:
    src\client\css\main.scss
Error: File to import not found or unreadable: ~@progress/kendo-theme-default/scss/all.
        on line 46 of src/client/css/main.scss
>> @import "~@progress/kendo-theme-default/scss/all";

   ^
c:\dev\projects\logdep\node_modules\node-sass\lib\index.js:291
    var payload = assign(new Error(), JSON.parse(err));
                         ^
Error: src\client\css\main.scss
Error: File to import not found or unreadable: ~@progress/kendo-theme-default/scss/all.
        on line 46 of src/client/css/main.scss
>> @import "~@progress/kendo-theme-default/scss/all";
   ^
    at options.error (c:\dev\projects\logdep\node_modules\node-sass\lib\index.js:291:26)
```

**Expected behavior**
import from node modules works

**Minimal reproduction of the problem with instructions**
1. "npm install --save @ progress/kendo-theme-default" (without spacing after @)
2. "ENABLE_SCSS = true;" in project.config.ts
3. insert "@import "~@progress/kendo-theme-default/scss/all"; in entry scss file (according [official guide](https://www.telerik.com/kendo-angular-ui/components/styling/))

windows 10 64bit, npm 5.6.0

* **Node:** `node --version` = 8.9.4

**Comment by vyakymenko** [comment]
@MichaelSemchenko , you can use an [injection](https://github.com/mgechev/angular-seed/wiki/Add-external-scripts-and-styles) of particular CSS from `node_modules`. Or if you need to `import` SCSS file, please your full path to it and I recommend you to import it in `main.scss`, so it will be easier to manage your `UI` framework for the whole application.

**Comment by MichaelSemchenko** [comment]
@vyakymenko 
> you can use an injection of particular CSS from node_modules
I know about this option, but this is a wrong way. I need for importing sources. And in any case this is not a solution of issue with importing.

>  full path to it and I recommend you to import it in main.scss
That what I do now - I typed: "3: insert "@import "~/scss/all"; in entry scss file (according official guide)"
