### ISSUE TITLE
Remove build.prod and build.prod.aot

### ISSUE THREAD

**Issue by vyakymenko** [mgechev/angular-seed#2288]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Since we have a lot issues with `build.prod` or `build.prod.aot`, for [example](https://github.com/mgechev/angular-seed/issues/2277).

I think it's a time to remove `build.prod` and `build.prod.aot` since all developers use `build.prod.rollup.aot` and I think that only last task make sense, we also can rename it to `build.prod` and remove other options and drop a lot of dependencies and optimize tasks section.

**Expected behavior**
To avoid problems with supporting all 3 build tasks `build.prod`, `build.prod.aot` and `build.prod.rollup.aot` I propose to use only `build.prod.rollup.aot` and rename it to `build.prod`. Also, refactor a lot of dependencies and tasks.

P.S., In my opinion, there is no sense to provide for developers unoptimized build technics and confuse them. Let's provide maximum out of the box.

**Minimal reproduction of the problem with instructions**
For example `build.prod` is not working while `build.prod.rollup.aot` work like a charm. And there is no reason to work twice.

**What is the motivation / use case for changing the behavior?**
Knowledge sharing must be efficient, we need to share knowledge that provides the maximum for developers and one day someone will have an idea based on that knowing how to improve it more and more. We need to move on.

**Please tell us about your environment:**
All OS, All IDE.

**Comment by mgechev** [comment]
This makes sense. Temporary we can invoke rollup for all these tasks and print a warning message for some of them that they are deprecated.

**Comment by vyakymenko** [comment]
I hope that I'll have some time very soon to take a look at this issue.

**Comment by pvskasyrskiy** [comment]
@vyakymenko, @mgechev Guys please do not remove build.prod.aot build type in project. I have project which based on angular-seed but can not use build.prod.rollup.aot due issue with Ag-grid https://github.com/ag-grid/ag-grid-angular/issues/112
