### ISSUE TITLE
Failed at the angular-seed@1.0.0 start script

### ISSUE THREAD

**Issue by mohammad-tanzeel** [mgechev/angular-seed#2297]
After successful running the npm install, when I am trying to run by npm start.
getting the below error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@1.0.0 start script.

Can you please give the solution to run successfully?

Thanks
Mohd Tanzeel

**Comment by aamir1995** [comment]
Seems like environment issue from your end.
Please post your environment configuration.
Node version, Operating system, IDE, package manager, HTTP server,

**Comment by mohammad-tanzeel** [comment]
I am using the below environment.
node -v = v10.4.1
npm -v  = 6.1.0
Operating system = Ubuntu 16.04
IDE =  netbean
HTTP server =  Apache
