### ISSUE TITLE
Bootstrap stylesheets not loading on production build

### ISSUE THREAD

**Issue by ArminZol** [mgechev/angular-seed#2311]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

NPM_DEPENDENCIES do not load on production build (e.g. bootstrap) with this.ENABLE_SCSS set to true, and otherwise fails with error 

`Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but postcss-merge-rules uses 5.2.18. Perhaps this is the source of the error below`

**Expected behavior**

Bootstrap classes to work on production builds (prod.rollup.aot)

**Minimal reproduction of the problem with instructions**

1. Install bootstrap
`npm install bootstrap --save`
2. Add dependency to NPM_DEPENDENCIES in **project.config.ts**
`{src: 'bootstrap/dist/js/bootstrap.min.js', inject: 'libs'},`
`{src: 'bootstrap/dist/css/bootstrap.min.css', inject: true}`
3. Add alert to **home.component.html**
`<div class="alert alert-danger" role="alert">error</div>`
4. Test on development (should work fine)
`npm start`
5. Test on production
`npm run serve.prod.rollup.aot`
This should fail with error
`Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but postcss-merge-rules uses 5.2.18. Perhaps this is the source of the error below.`
`C:\git\angular-seed\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:37
    throw new BrowserslistError(name);`

If **this.ENABLE_SCSS** is set to true, it will compile, but the alert will not appear styled.

**What is the motivation / use case for changing the behavior?**

This affects anyone trying to use angular-seed with bootstrap stylesheets in a production build.
**Please tell us about your environment:**

Windows 10 with latest version of angular seed
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = v10.1.0

**Comment by mgechev** [comment]
For support requests, you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) to get a complete idea of how it works.
