### ISSUE TITLE
Error on fetch rxjs-compat during build.prod.aot task

### ISSUE THREAD

**Issue by danboone** [mgechev/angular-seed#2313]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
updated project to latest seed and  run build.prod.aot and get this error
 Error on fetch for rxjs-compat.js at file:///C:/TFS/TFSOnline/AngularSeed/node_modules/rxjs-compat.js
        Loading rxjs/Rx.js
        Loading @angular/core/bundles/core.umd.js
        Loading dist\tmp\app\main-prod.js
        ENOENT: no such file or directory, open 'C:\TFS\TFSOnline\AngularSeed\node_modules\rxjs-compat.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\TFS\TFSOnline\AngularSeed\node_modules\rxjs-compat.js'

**Expected behavior**
project to build prpperly

**Comment by mgechev** [comment]
For support requests, you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) to get a complete idea of how it works.
