### ISSUE TITLE
Remove SystemJS and use only Rollup

### ISSUE THREAD

**Issue by vyakymenko** [mgechev/angular-seed#2317]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
In the current implementation of `angular-seed` for a development build used `SystemJS`,
But for production build we using `Rollup`. I think we should remove `SystemJS` and migrate our `development` builds to `Rollup`. 

**Expected behavior**
Use `Rollup` instead of `SystemJS` for development builds, that will also optimize `angular-seed` and will remove a lot of unnecessary code and dependencies.

**Minimal reproduction of the problem with instructions**
Analyse `seed.config.ts` and `development` build tasks.

**What is the motivation / use case for changing the behavior?**
Passion in the performance and clean coding.

**Please tell us about your environment:**
All OS, all IDE.
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = All described versions in `README`.

**Comment by aelbore** [comment]
@vyakymenko i created a angular-seed fork from this repo but uses rollup, im still using systemjs for lazy loading module.
https://github.com/aelbore/ngx-seed

**Comment by wileymarques** [comment]
I use this project specially for lazy loading external modules using SystemJS.

Why not just give an option to not use it if you don't want, instead of removing completely?

**Comment by mgechev** [comment]
@wileymarques that's a useful feedback. If there are folks using SystemJS we won't drop it.
