### ISSUE TITLE
ActivatedRoute data is not present in AOT build

### ISSUE THREAD

**Issue by raizemm** [mgechev/angular-seed#2331]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Currently Angular's ActivatedRoute data is not present in the component in AOT build although it is present in JIT.

**Expected behavior**

ActivatedRoute data should be visible in both builds.

**Minimal reproduction of the problem with instructions**

1. Add data property to the HomeComponent path in home-routing.module.ts
2. npm run start -> try to console.log ActivatedRoute snapshot data (eg. {foo: 'bar'}) in HomeComponent, data should be present
3. npm run serve.prod ->  try to console.log ActivatedRoute snapshot data (eg. {foo: 'bar'}) in HomeComponent, data is not present and is undefined

Also during the **build.bundles.app.rollup.aot** there is a warning from rollup.
![image](https://user-images.githubusercontent.com/8191603/44628298-2691f900-a93d-11e8-8e88-c31003f498ad.png)

**What is the motivation / use case for changing the behavior?**

Route data should be present in both builds

**Please tell us about your environment:**

Operating system : Mac osx 10.13.6
IDE: WebStorm 2018.2.1
package manager: npm v5.6.0

* **Angular Seed Version:** `6abf152 `
Angular seed version 9314d596c88a29b8f30e3a6fcbfc5c480ec3849c

* **Node:** `node --version` = 8.11.3

**Comment by aamir1995** [comment]
Also when you remove the `data` property from the route, the error will be gone.

**Comment by raizemm** [comment]
@vyakymenko any help regarding this :(?

**Comment by AlekseiPinchuk** [comment]
Any updates for this?

**Comment by fireworkz** [comment]
It would be great to get an update on this - AOT performance benefits are great but right now cannot be used due to this issue!

**Comment by aamir1995** [comment]
@AlekseiPinchuk @lucadeangeli this seed is no longer under active maintenance, you should migrate to [Angular CLI](https://github.com/angular/angular-cli).

**Comment by fireworkz** [comment]
@aamir1995 thank you, my issue is in fact with Angular CLI, I will post on there
