### ISSUE TITLE
Transpiler Error from angular-seed latest version

### ISSUE THREAD

**Issue by chandu379** [mgechev/angular-seed#2352]
Iam getting this error with angular-seed latest version. Thanks in advance.

TypeError: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
    at transpile (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1539502346274:3738:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1539502346274:3516:14
    at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1539502346285:388:26)
    at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1539502346285:138:43)

**Comment by chandu379** [comment]
UPADTE:- I initially thought the error was due to the systemJs upgrade but then tried with the build before systemJS upgrade but didn't succeed there. Even that gives the same error

**Comment by slamkajs** [comment]
I am running into a similar error.  While trying to load a package's core.umd.js file 

The package I am trying to load has been added to the project.config.ts.  I have included another external dependency using a core.umd.js file with no problems.

The package I am working with is @agm/core (Angular Google Maps).

**Comment by chandu379** [comment]
May be it is the right time to think of migrating the project to cli as that is mature enough!!

**Comment by mgechev** [comment]
I'd encourage you to consider the CLI. I shifted focus to the Angular CLI and I don't have much bandwidth to make significant improvements in Angular seed.

**Comment by chandu379** [comment]
Thanks for your suggestion
