### ISSUE TITLE
App does not load with ngrok

### ISSUE THREAD

**Issue by Usama-Tahir** [mgechev/angular-seed#2456]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I use `ngrok` to serve the app on `https`, the app keeps on loading and does not render.

**Expected behavior**
The app should work fine using ngrok as well.

**Minimal reproduction of the problem with instructions**
1. Run the app locally using `npm run start` command.
2 The app will start running on port `5555`.
3. Run `./ngrok http -host-header=rewrite localhost:5555 `.
4. Open the `https` url provided by `ngrok`.
5. The app will keep on loading.

**What is the motivation / use case for changing the behavior?**
Certain libraries such stripe payment Request Button integrations require to run the app on `https`.

**Please tell us about your environment:**
OS: Ubuntu 20

* **Angular Seed Version:** `25ca32d9af0e9f2f3de01c39727b266a036df7fb`

* **Node:** `node --version` = 8.12

**Comment by TheDonDope** [comment]
Good day to you @Usama-Tahir 
The mgechev/angular-seed repository is no longer under active maintenance, as stated in the README.md.
So furthermore please consider migrating to @angular/cli as it is unlikely to receive support here.

Cheers
