### ISSUE TITLE
Cannot easily update computed config members in ProjectConfig

### ISSUE THREAD

**Issue by tvrtkos** [mgechev/angular-seed#823]
If you set APP_SRC inside ProjectConfig you don't get .css files injected into index.html.

I guess the reason is that properties like CSS_SRC and APP_ASSETS are calculated using old/default value of APP_SRC.

I can change APP_SRC inside SeedConfig as a workaround.

**Comment by mgechev** [comment]
Yes, this is an issue discussed before. I guess a way to handle is by using property accessors instead.

If you have some spare time, a PR is welcome!

**Comment by d3viant0ne** [comment]
@mgechev - I'm working on the manual_typings problem, I can roll this into that PR unless @tvrtkos wants to take this one.

If I don't see anything by the time I finish with the typings, i'll fix this in the PR for that

**Comment by Paladinium** [comment]
Same issue as #630 

@tvrtkos : you'll see the workaround there which is just overriding all dependent variables.

**Comment by ludohenin** [comment]
@d3viant0ne Are you working on that one, or can I take over ?

**Comment by mgechev** [comment]
Any updates here? I can take it as well.

**Comment by mgechev** [comment]
Duplicate of https://github.com/mgechev/angular-seed/issues/1429
