### ISSUE TITLE
build.prod doesnt work

### ISSUE THREAD

**Issue by hjc879227** [mgechev/angular-seed#997]
I've followed the #975 , 
**edit package.json devDependencies entry:
"systemjs-builder": "^0.15.14",
change to
"systemjs-builder": "0.15.14",**

but the same problem is shown.

`D:\GitWorkSpacePersonal\angular2-seed>gulp build.prod >>log.log
[10:14:24] 'build.bundles.app' errored after 2.81 s
[10:14:24] Error on fetch for dist/tmp/app/login/login.js at file:///D:/GitWorkS
pacePersonal/angular2-seed/dist/tmp/app/login/login.js
        Loading dist/tmp/app/app.component.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'D:\GitWorkSpacePersonal\
angular2-seed\dist\tmp\app\login\login.js'
    at Error (native)
[10:14:24] 'build.prod' errored after 36 s
[10:14:24] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    build.bundles.app callback`

`Message:
    ENOENT: no such file or directory, open 'D:\GitWorkSpacePersonal\angular2-seed\dist\tmp\app\login\app\login\login.html'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: D:\GitWorkSpacePersonal\angular2-seed\dist\tmp\app\login\app\login\login.html
    fileName: D:\GitWorkSpacePersonal\angular2-seed\dist\tmp\app\login\login.ts`

**login.ts**
`@Component({
	selector : 'login',
	templateUrl : 'app/login/login.html'
})
`
**I think it is wrong with  the Relative Paths in templateURL.**

and May be this is the real question asked by @lmessinger.

any ideas?

thanks very much

**Comment by zeeshanjan82** [comment]
I am also facing similar issue when using npm run build.prod
![error](https://cloud.githubusercontent.com/assets/8342604/16066679/08a53ffc-32d3-11e6-80d7-6fa711f068b8.png)

**Comment by hjc879227** [comment]
@zeeshanjan82 #975 has fixed your problem.you can take a look.

**Comment by zeeshanjan82** [comment]
thanks @hjc879227 actually I am using advanced seed project and am not sure if it is fixed there as well.

**Comment by mgechev** [comment]
https://github.com/mgechev/angular2-seed/issues/975 Is already in master. For your problem yiu have to set the property userRelativePaths to the plugin gulp-inline-ng2-template.

**Comment by zeeshanjan82** [comment]
@mgechev thanks for the information which file do I need to change?

**Comment by zeeshanjan82** [comment]
do I need to set it inside the build.js.prod.ts file, but I can already find the following code there: 
````js
const INLINE_OPTIONS = {
  base: TMP_DIR,
  useRelativePaths: true,
  removeLineBreaks: true
};
`````

**Comment by hjc879227** [comment]
@mgechev thanks ,I got the key.

**Comment by zeeshanjan82** [comment]
@mgechev I was able to fix the issue, your suggestion really helped.

**Comment by webia1** [comment]
But downgrade should not be the solution, why not fixing the "/"  "\" problem properly?

**Comment by mgechev** [comment]
Is this problem still reproducible?

**Comment by webia1** [comment]
I'm currently updating to Angular 2.0.2 and getting this error locally on windows.

**Comment by webia1** [comment]
that's the output:

```
[19:04:16] Loading tasks folder C:\dev\whateverapp\tools\tasks\seed
[19:04:16] Loading tasks folder C:\dev\whateverapp\tools\tasks\project
[19:04:16] Using gulpfile C:\dev\whateverapp\gulpfile.js
[19:04:16] Starting 'build.prod.war'...
[19:04:16] Starting 'clean.prod'...
[19:04:16] Deleted dist/tmp
[19:04:16] Deleted dist/prod
[19:04:16] Finished 'clean.prod' after 93 ms
[19:04:16] Starting 'build.assets.prod'...
[19:04:16] Finished 'build.assets.prod' after 319 ms
[19:04:16] Starting 'build.web-inf.xml'...
[19:04:16] Finished 'build.web-inf.xml' after 4.85 ms
[19:04:16] Starting 'build.html_css'...
[19:04:21] Finished 'build.html_css' after 5.23 s
[19:04:21] Starting 'copy.js.prod'...
[19:04:21] Finished 'copy.js.prod' after 91 ms
[19:04:21] Starting 'build.js.prod'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject(reporter)) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
[19:04:27] Finished 'build.js.prod' after 5.11 s
[19:04:27] Starting 'build.bundles'...
[19:04:31] Finished 'build.bundles' after 4.35 s
[19:04:31] Starting 'build.bundles.app'...
[19:04:32] 'build.bundles.app' errored after 750 ms
[19:04:32] Error on fetch for dist\tmp\app\main.js at file:///C:/dev/E2E_MAKLER/e2e-motor-makler-app/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\dev\whateverapp\node_modules\dist\tmp\app\main.js'
    at Error (native)
[19:04:32] 'build.prod.war' errored after 16 s
[19:04:32] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for dist\tmp\app\main.js at file:///C:/dev/E2E_MAKLER/e2e-motor-makler-app/node_modules/dist\tmp\app\main.js
        ENOENT: no such file or directory, open 'C:\dev\whateverapp\node_modules\dist\tmp\app\main.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\dev\whateverapp\node_modules\dist\tmp\app\main.js'
Stack:
Error on fetch for dist\tmp\app\main.js at file:///C:/dev/E2E_MAKLER/e2e-motor-makler-app/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\dev\whateverapp\node_modules\dist\tmp\app\main.js'
    at Error (native)
```

**Comment by webia1** [comment]
That's the problem:

`file:///C:/dev/whateverapp/node_modules/dist  <----->   \tmp\app\main.js`

**Comment by sasikumardr** [comment]
I also faced similar issue some days before. My problem was because of systemjs-builder package with higher version (compared to this seed project) which was not compatible with configuration in seed.config file.

Then https://github.com/mgechev/angular-seed/commit/bcbdcac5629d1890daa6860d1defb2fabca1065e commit brought necessary configuration that helped seed project to use latest version of systemjs-builder.    I suspect your case could also be same. Just sharing my thoughts 🤔

**Comment by mgechev** [comment]
@sasikumardr thanks for the comment. Yes, it's quite likely this to be the issue especially if you have overriden the `SYSTEM_BUILDER_CONFIG` in your `project.config.ts` file.

**Comment by mpx200** [comment]
same problem for me 

`[18:57:24] 'build.bundles.app' errored after 868 ms
[18:57:24] Error on fetch for dist\tmp\app\main.js at file:///C:/dev/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\dev\node_modules\dist\tmp\app\main.js'
    at Error (native)
[18:57:24] 'build.prod' errored after 30 s
[18:57:24] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for dist\tmp\app\main.js at file:///C:/dev/node_modules/dist\tmp\app\main.js
        ENOENT: no such file or directory, open 'C:\dev\node_modules\dist\tmp\app\main.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\dev\node_modules\dist\tmp\app\main.js'
Stack:
Error on fetch for dist\tmp\app\main.js at file:///C:/dev/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\dev\node_modules\dist\tmp\app\main.js'
    at Error (native)
`
  "systemjs-builder": "0.15.14",

**Comment by mgechev** [comment]
@mpx200 there were some changes in systemjs-builder which broke our build so we had to adjust to them. Please update to the latest builder version (take a look at package.json) and make sure you're following the same configuration as the seed (back slashes vs forward slashes is **very** important).

**Comment by andfs** [comment]
I'm with systemjs-builder 0.15.14 and facing the same problem.

```
Error on fetch for dist\tmp\app\main.js at file:///C:/Anderson/Projetos/portal/portal-client/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\Anderson\Projetos\portal\portal-client\node_modules\dist\tmp\app\main.js'
```

Some news about this issue?

**Comment by mpx200** [comment]
i just updated to newest seed and now it works normally
